### ISSUE TITLE
my-sql

### ISSUE THREAD

**Issue by phframe2** [Gozargah/Marzban#1000]
با سلام برای استفاده از mysql به این مشکل میخورم

![image](https://github.com/Gozargah/Marzban/assets/170531178/0ca6dfef-a184-4ed0-b71b-f631456a4f7e)

**Comment by pasargadweb** [comment]
پسورد mysql داخل فال .env اشتباهه

**Comment by ImanEjt** [comment]
گواهی ssl پنل رو چک کنید که مشکلی نداشته باشه.

**Comment by mayburs** [comment]
منم این مشکل رو دارم.
به راه حل خاصی رسیدین؟

**Comment by mayburs** [comment]
مشکل من حل شد
باید دقیقا همانطوری که داخل داکیومنت مرزبان گفته پیش برین تا تغییرات اعمال بشه
قبل دستور sqlite هم با دستور apt install sqlite3 -y، sqlite را نصب کنید.

لینک داکیومنت مرزبان: https://gozargah.github.io/marzban/fa/examples/mysql
