### ISSUE TITLE
Auto-updating Feature

### ISSUE THREAD

**Issue by rezazoom** [Gozargah/Marzban#1001]
Right now, updating Marzban requires small scripting talents and SSH enabled and following a manual.

Including a built-in update checker and auto-updating feature for seamless maintenance will be great.

Consider creating a section for Update checker and installer, it may contain an option to set for update channel which currently can be 'dev' and 'stable'.

Reverting back an update and switching to another version can be on your roadmap if possible.

**Comment by M03ED** [comment]
Using auto update can cause problem 
Mostly people wait until midnight to update there marzban 
Without a manual update people can be confused with change's 
In dev version this can make some problem like what happened when someone change sub link generate function
I don't see any point to make a auto update script

**Comment by rezazoom** [comment]
Hello,

I believe there was a misunderstanding regarding my previous message. When I mentioned Auto Update, I did not mean that the system should update itself at a specified time automatically. Instead, I meant that the update process should be integrated into the panel rather than being done via the CLI.

The idea is that the panel should automatically check for new versions, and if updates are available, it should notify the system administrator. The administrator can then implement the update with a single click from the management panel. This is somewhat similar to how content management systems like WordPress handle updates, if you are familiar with that.

**Comment by rezazoom** [comment]
@M03ED I have previously discussed this with Gozarman in a discussion, and he agreed with the suggestion, which you can see here: [Discussion about Marzban Next version](https://github.com/Gozargah/Marzban/discussions/985#discussioncomment-9459333).

**Comment by fodhelper** [comment]
Auto Update is nothing but troubles, especially for dockerized projects!
newbie users love auto update and will dislike my message, but they will regret and cry when auto update make troubles for them and their customers start calling them, then they will spam here and telegram groups lol

**Comment by M03ED** [comment]
i don't think this be good idea and there is some more important things to implement, if you are interest in this you can implement it your self and we will check it.
