### ISSUE TITLE
فعال کردن  حالت دولوپر

### ISSUE THREAD

**Issue by Mrkalier** [Gozargah/Marzban#1002]
من تمامی مراحل حالت دولوپر رو  میرم ولی کانفیگام بصورت کاستوم کانفیگ اضافه نمیشن

**Comment by hamedefatian** [comment]
تو بخش هاست مقدار فرگمنت رو مشخص کردید؟

**Comment by sirvan32** [comment]
این مشکل برای من هم وجود داره. مقدار فرگمنت رو هم مشخص میکنم ولی به صورت کاستوم کانفیگ در نمیاد

**Comment by hamedefatian** [comment]
تو فایل .env
این رو بنویسید
 USE_CUSTOM_JSON_FOR_V2RAYN=True
 USE_CUSTOM_JSON_FOR_V2RAYNG=True

اگر از قبل داشتید فقط کافیه # رو بردارید
دست آخر فایل رو ذخیره و مرزبان ری استارت کنید
