### ISSUE TITLE
فعال کردن مسیر سرتیفیکیت برای لینک اشتراک

### ISSUE THREAD

**Issue by Pezhman5252** [Gozargah/Marzban#1003]
لینک اشترام رو در فایل .env تغییر بدم دیگه جایی نیست که مسیر فایل های سرتیفیکیت برای دامنه جدید رو وارد کنم، فقط ssl برای لینک اشتراک پنل مادر فعال میشه

**Comment by M03ED** [comment]
میتونید 2 ssl رو ترکیب کنید و با از wildcard استفاده کنید
