### ISSUE TITLE
اعمال نشدن تغییرات جزئی اینباند روی هاست

### ISSUE THREAD

**Issue by Pezhman5252** [Gozargah/Marzban#1007]
وقتی روی تنظیمات اینباند تغییرات جزئی داشته باشم مثلا پورت اینباند رو تغییر بدیم، این تغییرات روی مقادیر پیشفرض هاست نمیشینه و همچنان همان مقدار قبلی نمایش داده میشه، تا زمانی که خودم یک بار از مرزبان بیام بیرون و دوباره واردش بشم تا تغییرات اعمال بشه.

**Comment by M03ED** [comment]
این موارد در کش مرورگر ذخیره میشن و برای تغییر نیاز به رفرش کردن صفحه دارید ، مقادیر در سمت سرور تغییر می کنند
