### ISSUE TITLE
کوتاه کردن لینک سابسکریپشن

### ISSUE THREAD

**Issue by Pezhman5252** [Gozargah/Marzban#1008]
لطفا در صورت امکال لینک سابسکربشن رو کمی کوتاه تر کنید تا امکان کپی کردن لینک برای کاربر راحتتر باشه. مثلا برای هر کاربر یک uuid4 اختصاصی فقط برای لینک سابسکریپشن تولید بشه که کوتاه تر از حالت فعلی هست.
حالت فعلی:
https://sub.XXX.com/subset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNaXRyYSIsImFjY2VzcyI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTcxNjYxNDE1M30.T2xx3eFoWaIiZsgrZ4q6Hg7RyVh1OxDk3uaMoiZJuUk

حالت پیشنهادی:
https://sub.XXX.com/subset/cb8b6214-1b69-4759-a872-0ac0ff06e353

**Comment by M03ED** [comment]
این مورد قبلا انجام شده

#904
