### ISSUE TITLE
استفاده یکی از اینبادها و یا کانفیگها از وارپ

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#1010]
سلام و احترام
چطور میتونم استفاده از وارپ را برای تمام سایتها فقط محدود به یکی از کانفیگها کنم؟
سپاس

**Comment by Ilaprgg2** [comment]
`"routing": { 
"rules": [
{
        "inboundTag": [
          "Your Inbound"
        ],
        "outboundTag": "warp",
        "type": "field"
    }
]`
