### ISSUE TITLE
اضافه شدن قابلیت Direct 

### ISSUE THREAD

**Issue by chitoz1300** [Gozargah/Marzban#1012]
<div dir="rtl">
سلام عرض ادب وقتتون بخیر ، لطفا قابلیت Direct ip / Domain رو به برنامه V2rayNG بصورت کاستوم کانفیگ اضافه بفرمایید

</br>
</br>
  <p align="center" ><img  src="https://github.com/Gozargah/Marzban/assets/87599806/8ddc2019-4297-4eb1-9cff-7027ef874f61"></p>

**Comment by M03ED** [comment]
همه این موارد به وسیله تمپلیت قابل انجام هست
