### ISSUE TITLE
نمایش مصرف کل (داخل پنل) بر اساس مصرف کاربران ادمین

### ISSUE THREAD

**Issue by m0x61h0x64i** [Gozargah/Marzban#1015]
من خودم پایتون کار نکردم اگر شما یکم همکاری کنید میتونیم پیاده سازیش کنیم (بدون تغییر کد در فرانت اند میشه انجامش داد)
 
ایده اصلی این هستش که وقتی ادمین sudo نیست بیایم و ترافیک مصرف شده کاربران همون ادمین رو نمایش بدیم
چرا؟ چون ادمینی که sudo نیست نیاز به اطلاعاتی که مربوط به کل هست نداره و چون ادمین غیر sudo هست برای کنترل مصرف اون ادمین توسط ادمین sudo این کار اطلاعات با ارزشی رو به ادمین sudo میده. 
 
اما ادمین sudo توی پنل خودش بهتره که همون مصرف کل همه کاربران رو داشته باشه و بهتره که این کار فقط برای ادمین غیر sudo اضافه بشه. نظر شما چیه؟
 
برای اینکار من چک کردم کاربری که مصرف داشته و پاک میشه ترافیک مصرف شدش موقع حذف ذخیره نمیشه که اول باید این فیکس شه.
 
راه حل:
تیبل UserUsageResetLogs فایل models باید دوتا ستون زیر اضافه بشه
```
admin_id = Column(Integer, ForeignKey("admins.id"))
used_traffic_at_delete = Column(BigInteger, nullable=False)
```
بعد موقع حذف کاربر در تابع remove_user فایل crud باید ستون های used_traffic_at_delete و admin_id اپدیت بشه
```
db.update(UserUsageResetLogs).(used_traffic_at_delete = dbuser.used_traffic, admin_id = dbuser.admin_id)
```
یه همچین کدی هست درستش رو نمیدونم چجوریه
بعد موقعی که کاربر ریست میشه used_traffic ذخیره میشه اما admin_id ست نمیشه که باید گذاشته بشه به شکل زیر:
در فایل crud تابع reset_user_data_usage این کد :
```
UserUsageResetLogs(
        user=dbuser,
        used_traffic_at_reset=dbuser.used_traffic,
    )
```
تغییر کند به:
```
UserUsageResetLogs(
        user=dbuser,
        used_traffic_at_reset=dbuser.used_traffic,
        admin_id=dbuser.admin_id
    )
```
 
حالا که این اتفاق میافته مصرف هر کاربر به طور کامل در تیبل UserUsageResetLogs قابل دریافت هست (زمانی که ریست میشه مصرفش ذخیره میشه زمانی هم که حذف میشه مصرفش ذخیره میشه) اگر کاربر پاک شه فقط user_id نال میشه ولی هنوز سر جاش هست و از طریق admin_id میشه مصرف اون کاربر رو برای ادمین به دست اورد
 

برای اینکه مقدار مصرفی کاربران ادمین غیر sudo رو به ادمین نشون بدیم:
توی فایل crud یه متد میخایم که کوئری بزنه و مقدار مصرفی رو بهمون بگه:
```
def get_admin_users_usages(admin_id) {
    usages = 0
    for user_usage in db.query(UserUsageResetLogs).filter(User.admin_id == admin_id):
        usages += User.used_traffic_at_reset
        usages += User.used_traffic_at_delete
        
    return usages
}
```
یه همچین چیزی. درستش نمیدونم توی پایتون به چه شکله.

و برای نمایش توی پنل:
 فایل system ای پی ای زیر
@app.get("/api/system"
باید یه شرط اضافه بشه زیر
```
system = crud.get_system_usage(db)
```
به این شکل:
```
if (!admin.is_sudo) {
        total_admin_users_usages = crud.get_admin_users_usages(admin_id)
        system.uplink = total_admin_users_usages / 2
        system.downlink = total_admin_users_usages / 2
    }
```
حالا درستش توی پایتون نمیدونم به چه شکله. این میاد اگر ادمین sudo نبود uplink و downlink که جمع این دو داخل پنل نمایش داده میشه رو با مقدار جمع اوری شده توسط متد کوئری get_admin_users_usages جایگزاری میکنه

**Comment by M03ED** [comment]
#935

**Comment by m0x61h0x64i** [comment]
سلام عزیز.
یسری اقدامات اوی اون pull request انجام شده بود چیز زیادی متوجه نشدم. الان من با اخرین نسخه dev توی پنل ادمین غیر sudo مصرف کاربرای ادمین رو نمیتونم وسط صفجه ببینم (که مصرف سیستم رو نمایش میده) عکس:

![image](https://github.com/Gozargah/Marzban/assets/109550653/d7679906-605a-48f6-928e-1c2e1c4cbf3b)

 و همچنین با ادمین غیر sudo نمیتونم مصرف نود هارو ببینم. عکس:
  
![image](https://github.com/Gozargah/Marzban/assets/109550653/f7170c47-923c-4c7e-b7a2-0ba23629ffa1)


حالا فکر میکنم منظور شما این بود که عکس دوم داخل اون pull request میخواسته فیکس بشه درسته؟ حالا اینکه شد یا نشد نمیدونم چون برای منکه اپدیت کردم تست کردم عکس دادم اینطوری بود. (نسخه dev هستم
چیزی که من ایده دادم درواقع برای عکس اول هست که توی پنل ادمین غیر sudo مصرف کاربرای ادمین رو اونجا نمایش بده (اگر دقت کنید کاربرای ادمین 0 هست ولی مصرف 74 TB که منطقی نیست.

@M03ED

**Comment by erfjab** [comment]
درود و وقت بخیر، فعلا درگیر اولویت های دیگه ای هستیم، آینده بهش برمیگردم، لیبل انهولد اضافه میکنم.
