### ISSUE TITLE
دار tls کار نکردن کانکشنها 

### ISSUE THREAD

**Issue by Aronablade** [Gozargah/Marzban#1017]
با سلام ، وقتی تو تنظیمات host یه کانفیگ میسازم و tls رو انتخاب میکنم ، کانکشن وصل نمیشه . روی دامین و روی پنل tls رو فعال کردم ، sni هم میدم ولی کار نمیکنه . جایی رو باید تغییر بدم ؟

و اینکه چرا روی پنل محدودیت اتصال نمیذارین ، اینم باشه واقعا تکمیله . خیلی بهتر از پنل های دیگه هستش

**Comment by Ilaprgg2** [comment]
اینباند رو بفرستید تا ببینیم

**Comment by Aronablade** [comment]
{
  "inbounds" : [
    {
      "listen" : "127.0.0.1",
      "port" : 1080,
      "protocol" : "socks",
      "settings" : {
        "auth" : "noauth",
        "udp" : true
      },
      "sniffing" : {
        "destOverride" : [
          "http",
          "tls",
          "quic",
          "fakedns"
        ],
        "enabled" : false,
        "routeOnly" : true
      },
      "tag" : "socks"
    }
  ],
  "outbounds" : [
    {
      "protocol" : "vmess",
      "settings" : {
        "vnext" : [
          {
            "address" : "m1.vesta6.xyz",
            "port" : 8081,
            "users" : [
              {
                "id" : "bb346d07-32f2-4f48-bcb0-5ab2c6b819a5",
                "security" : "auto"
              }
            ]
          }
        ]
      },
      "streamSettings" : {
        "network" : "tcp",
        "security" : "tls",
        "tcpSettings" : {
          "header" : {
            "request" : {
              "headers" : {
                "Host" : [
                  "google.com"
                ]
              },
              "path" : [
                "\/"
              ]
            },
            "type" : "http"
          }
        },
        "tlsSettings" : {
          "alpn" : [
            "h2",
            "http\/1.1"
          ],
          "fingerprint" : "random",
          "serverName" : "m1.vesta6.xyz"
        }
      },
      "tag" : "proxy"
    },
    {
      "protocol" : "freedom",
      "tag" : "direct"
    },
    {
      "protocol" : "blackhole",
      "tag" : "block"
    }
  ]
}

**Comment by Ilaprgg2** [comment]
اینکه کانفیگ کلاینت هست. کانفیگ مرزبان رو بفرستید

**Comment by M03ED** [comment]
چون شما داکیومنت رو نخوندید ، هاست صرفا اطلاعات ارسالی به سمت کاربر رو تغییر میده و کاربرد دیگه ای نداره
لطفا قبل از هر کاری داکیومنت رو مطالعه کنید
https://gozargah.github.io/marzban/fa/examples/xray-tls-inbound
