### ISSUE TITLE
ناقص بودن اطلاعات موجود در لینک کانفیگ shadowsocks

### ISSUE THREAD

**Issue by omid-sadeghi** [Gozargah/Marzban#1022]
وقتی یک کانفیگ‌ shadowsocks را از داخل پنل با دکمه‌ Copy Config یا از سابسکریپشن کپی می‌کنیم، اطلاعات کامل کانفیگ از جمله tls، sni، path، fingerprint در لینک کپی شده وجود نداره و فقط نوع رمزنگاری، رمز، دامنه، پورت و نام کانفیگ هست.

اگر از طریق دکمه‌ی Copy Config لینک را بگیرم، مرزبان حتی پورتی که در host setting وارد شده نیز مورد توجه قرار نمیده و همان پورت داخل core settings را میاره.

این باعث میشه که وقتی کانفیگ tls دار به کاربر میدیم یا اینکه برای فالبک از path یا sni استفاده می‌کنیم، خود کاربر مجبور باشه اینا رو دستی وارد کنه.

این مشکل برای کانفیگ‌های vmess و vless و trojan وجود ندارد و به خوبی کار می‌کنن.

لینک‌های shadowsocks به صورت زیر هستن:
`ss://YWVzLTEyOC1nY206ZFNTWXVGSnJoSEdxcGNiaEZETE1QUQ==example.com:443#remark`
که قسمت اول نوع رمزنگاری و رمز رو در مبنای 64 میده و بعدش دامنه و پورت و نام کانفیگ. هر چند که من path و tls و fingerprintدر قسمت host setting تعیین کردم ولی توی لینکا یا سابسکریپشن بهم نمیده.

البته نمی‌دونم این مشکل پنل محسوب میشه یا اینکه کلا امکان اضافه کردن path و ... در لینک shadowsocks وجود نداره.

**Comment by omid-sadeghi** [comment]
نه این ربطی نداره. اولا شما لینک اوتباند رو دادی. اما اینجا اینباند مورد نظر هست
[https://xtls.github.io/en/config/inbounds/shadowsocks.html](https://xtls.github.io/en/config/inbounds/shadowsocks.html)

بعد این تنظیماتی که من گفتم در قسمت streamSettings هست. چون streamSettings بین اینبادهای مختلف مشترک هست، جدا بحث شده.
https://xtls.github.io/en/config/transport.html#streamsettingsobject

وگرنه اگر vmess و vless و trojan هم توی قسمت اینباندها نگاه کنید، حرفی از sni یا path گفته نشده. این تنظیمات مورد نظر من برای لایه‎‌ی پایین‌تر هست.

مثلا این کانفیگ اینباند من هست که البته با فالبک بهش وصل میشم. توی path من یه مقدار دارم. و اگر path  رو درست وارد کنم، بهش وصل میشم و کار میکنه. منتها لینکهای shadowsocks داخلش path نیست و باید دستی وارد کنم.
```
{
      "tag": "161___sst",
      "listen": "127.0.0.1",
      "port": 2161,
      "protocol": "shadowsocks",
      "settings": {
        "clients": []
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
          "acceptProxyProtocol": true,
          "header": {
            "type": "http",
            "request": {
              "path": [
                "/61-delete-stubborn-stitch"
              ]
            }
          }
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
```

**Comment by M03ED** [comment]
چیزی که شما دنبالشید احتمالا shadowsocks 2022 هست که در مرزبان پشتیبانی نمیشه

**Comment by omid-sadeghi** [comment]
ممنون از پاسخگویی. فک میکنم کلا shadowsocks داخل URI خودش همچین چیزایی (path، sni، fingerprint) رو پشتیبانی نمیکنه. طبق لینک زیر میگم که سایت خود پروژه هست:

https://shadowsocks.org/doc/sip002.html

ضمنا خودم بصورت دستی path رو به URI اضافه کردم اما وقتی لینک رو وارد کلاینت v2ray میکنم، تأثیری نداره.
