### ISSUE TITLE
استفاده از دیتابیس خارج از سرور اصلی 

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#1025]
سلام و احترام
یک سرور و یا داکر از قبل ساحته شده برای mysql وجود دارد 
- چطور میتونم بدون ساخت داکر جدید برای sql و phpmyadmin  در فایل .env آن را ادرس دهی کنم؟
- در فایل docker-compose.yml به جای استفاده از 
depends_on:
 mysql
      میباست از چه کدی استفاده کنم تا از طریق دیتابیس بیرونی پنل سازماندهی شود؟

**Comment by M03ED** [comment]
#758
