### ISSUE TITLE
پروکسی ساکس و http در مرزببان 

### ISSUE THREAD

**Issue by t-51** [Gozargah/Marzban#1026]
سلام وقت بخیر
ببخشید برام سوال هست که مرزبان از پروکسی های ساکس و http پشتیبانی میکنه یانه و اگر میکمه کانفیگ چطگری وارد کنیم؟

**Comment by M03ED** [comment]
دقیقا طبق چیزی که تو داکیومنت ایکس ری هست
https://xtls.github.io/en/config/inbounds/http.html
