### ISSUE TITLE
ماکس رو در سینگ باکس غیرفعال کنید لطفا

### ISSUE THREAD

**Issue by plasticgholam** [Gozargah/Marzban#1027]
در اپدیت اخیر در مرزبان dev با تمپلت یا بدون تمپلت سینگ باکس در هر حالت اگه ماکس در پنل فعال باشه دیگه اون کانفیگ در سینگ باکس کار نمینه (چون ماکس در سینگ باکس فعال میشه که نباید بشه) تا قبل از این، اینطور نبود و ماکس در سینگ باکس فعال نمیشد

**Comment by M03ED** [comment]
#1006
