### ISSUE TITLE
marzban restart problem

### ISSUE THREAD

**Issue by mayburs** [Gozargah/Marzban#1028]
سلام
کسی می دونه این مشکل برای چیه؟
وقتی می خوام restart کنم پنلو به این مشکل می خورم.
از این لوپ دیگه بیرون نمیاد.
root@vserver:~# marzban logs
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

**Comment by M03ED** [comment]
مسیر فایل های سرتیفیکیت تون اشتباهه
