### ISSUE TITLE
marzban socket

### ISSUE THREAD

**Issue by sirvan32** [Gozargah/Marzban#1032]
Uvicorn running on unix socket /var/lib/marzban/marzban.socket

بعد از حذف شدن این فایل دیگه پنل بالا نمیاد و هر کاری میکنم نمی تونم وارد پنل بشم. سرور رو ریبولد کردم باز این فایل ایجاد نشد و همچنان پنل لود نمیشه. لطفا راهنمایی کنید

**Comment by sirvan32** [comment]
برای کسایی که شاید این مشکل واسشون پیش بیاد: تو این روش اگه marzban.socket رو حذف کنید دیگه caddy نمیتونه به سرتیفیکیت دسترسی داشته باشه و باید از روش های دیگه واسه فعالسازی ssl استفاده کنید که Uvicorn گزینه ی خوبیه
https://gozargah.github.io/marzban/fa/examples/marzban-ssl#%D9%81%D8%B9%D8%A7%D9%84%E2%80%8C%D8%B3%D8%A7%D8%B2%DB%8C-ssl-%D8%A8%D8%A7-uvicorn

**Comment by M03ED** [comment]
استفاده از `haproxy` هم خوبه ، من خودم از این روش استفاده می کنم
