### ISSUE TITLE
DEFAULT_VLESS_FLOW

### ISSUE THREAD

**Issue by DigneZzZ** [Gozargah/Marzban#1035]
Hello!
What about the VLESS - flow default option?
DEFAULT_VLESS_FLOW = "xtls-rprx-vision"

Which will allow each connection to be assigned a flow, regardless of how it was created, in Telegram through a bot or through an API, or through a dashboard

**Comment by iamtheted** [comment]
Hi @DigneZzZ 
You can add a trigger that enables Flow in case you have forgotten, it sets the flow when it inserts the user's info into database.

Enable trigger

```
DELIMITER //
CREATE TRIGGER DEFAULT_FLOW
BEFORE INSERT ON proxies
FOR EACH ROW
BEGIN
    IF NEW.type = 'VLESS' AND JSON_UNQUOTE(JSON_EXTRACT(NEW.settings, '$.flow')) = '' THEN
        SET NEW.settings = JSON_SET(NEW.settings, '$.flow', 'xtls-rprx-vision');
    END IF;
END;
//
DELIMITER ;
```

Disable trigger: 

```
DROP TRIGGER DEFAULT_FLOW;
```

Thanks to Kiya6955 for the triggers 💙
