### ISSUE TITLE
Update xray version

### ISSUE THREAD

**Issue by harukodi** [Gozargah/Marzban#1041]
Add the new xray version. Xray version 1.8.13

**Comment by M03ED** [comment]
https://gozargah.github.io/marzban/fa/examples/change-xray-version

**Comment by M03ED** [comment]
before you open issue check documentation

**Comment by harukodi** [comment]
Yeah my bad sorry for that! Now i see the documentation is not in English do you guys need some write up for that?

**Comment by M03ED** [comment]
> Yeah my bad sorry for that! Now i see the documentation is not in English do you guys need some write up for that?

If someone can do it yeah we will appreciate it.

**Comment by harukodi** [comment]
Am on it but this is a way of installing marzban with docker-compose and not the script! I suppose the install script fetches the latest version right?

**Comment by M03ED** [comment]
> Am on it but this is a way of installing marzban with docker-compose and not the script! I suppose the install script fetches the latest version right?

There is no difference between docker and script, script will run marzban with help of docker.

**Comment by harukodi** [comment]
Does the script automatically fetch the new version of xray or do you need to install xray separately? As mentioned in the documentation?

How is xray fetched to run in the docker container is there a base version that is included with in the docker container? I dont know if you guys have changed the way you are fetching the xray

**Comment by harukodi** [comment]
I am not installing Marzban with the script am doing it the manual way.

Because it gives me more control and customization: By manually setting up the docker-compose.yml file, I can retain full control over the configuration. This allows me to tailor the setup precisely to my needs.
I will also understand every step of the setup process since am manually configuring it. This also helps me with a specific use case.

Am currently writing documentation for that way of installation of Marzban. When it's up you can take parts from that documentation that you think suits your documentation on your website  :)

**Comment by M03ED** [comment]
> Does the script automatically fetch the new version of xray or do you need to install xray separately? As mentioned in the documentation?
> 
> How is xray fetched to run in the docker container is there a base version that is included with in the docker container? I dont know if you guys have changed the way you are fetching the xray

Yes xray is included in image and it's latest version at time image built.
You can change it with env

**Comment by M03ED** [comment]
> I am not installing Marzban with the script am doing it the manual way.
> 
> Because it gives me more control and customization: By manually setting up the docker-compose.yml file, I can retain full control over the configuration. This allows me to tailor the setup precisely to my needs.
> I will also understand every step of the setup process since am manually configuring it. This also helps me with a specific use case.
> 
> Am currently writing documentation for that way of installation of Marzban. When it's up you can take parts from that documentation that you think suits your documentation on your website  :)

Manual setup tutorial already available in docs , try using Google translate, it can be helpful for start

**Comment by harukodi** [comment]
I see a documentation for the env under manual still not not for my use case am doing my own documentation. I can also write the one for your own xray core just for that part

**Comment by harukodi** [comment]
As promised, take parts of this documentation if you guys want to! :)

https://github.com/harukodi/IT-docu/blob/main/Docker-installations/Install%20marzban%20xray%20with%20docker-compose%20advanced.md
