### ISSUE TITLE
خطا در برقراری اتصال در زمان های رندوم

### ISSUE THREAD

**Issue by ThePishro** [Gozargah/Marzban#1049]
بعضی مواقع بیشتر صبح ها به هیچکدوم از کانفیگ ها نمیشه متصل شد و مشکل با ریستارت کردن مرزبان حل میشه ولی خیلی اذیت کنندست
برای رفع مشکل یک سری از دوستان پیشنهاد دادن که دیتابیس رو به mysql تغییر بدم که اینکارو انجام دادم ولی مشکل برطرف نشد
شک به این داشتم که میتونه از وارپ باشه سر همین برای یک مدت محدود وارپ رو برداشتم ولی بازم این اتفاق افتاد
داخل لاگ هم زیاد اطلاعات بدرد بخوری نصیبم نشده که بتونم مشکل رو برطرف کنم و قسمت های اخر لاگ که اخرین بار این مشکل پیش اومد رو کپی کردم که پایین دارید مشاهده میکنید اگر کمک کنید این مشکل برطرف شه خیلی ممنون میشم

marzban-1     | INFO:     172.68.194.142:30872 - "GET /sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrZXl2YW4iLCJhY2Nlc3MiOiJzdWJzY3JpcHRpb24iLCJpYXQiOjE3MTYzODM1ODh9.29zYSJcPk0w7N0Uzx83SSK4FHLRWtKmcRwcuimccT4I HTTP/1.1" 200 OK
marzban-1     | INFO:     206.168.34.116:60416 - "GET / HTTP/1.1" 200 OK
marzban-1     | INFO:     206.168.34.116:59368 - "GET / HTTP/1.1" 200 OK
mysql-1       | 2024-06-15 15:05:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.0-1.el9 started.
marzban-1     | WARNING:  Invalid HTTP request received.
marzban-1     | INFO:     206.168.34.116:48760 - "GET /favicon.ico HTTP/1.1" 404 Not Found
marzban-1     | INFO:     172.68.194.143:47870 - "GET /sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrZXl2YW4iLCJhY2Nlc3MiOiJzdWJzY3JpcHRpb24iLCJpYXQiOjE3MTYzODM1ODh9.29zYSJcPk0w7N0Uzx83SSK4FHLRWtKmcRwcuimccT4I HTTP/1.1" 200 OK
marzban-1     | INFO:     87.236.176.126:35355 - "GET / HTTP/1.1" 200 OK
mysql-1       | 2024-06-15 15:05:50+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
phpmyadmin-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
mysql-1       | 2024-06-15 15:05:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.0-1.el9 started.
mysql-1       | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
mysql-1       | 2024-06-15T15:05:51.524518Z 0 [System] [MY-015015] [Server] MySQL Server - start.
mysql-1       | 2024-06-15T15:05:52.079295Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.4.0) starting as process 1
mysql-1       | 2024-06-15T15:05:52.095950Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql-1       | 2024-06-15T15:05:52.609489Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql-1       | 2024-06-15T15:05:53.043266Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql-1       | 2024-06-15T15:05:53.043332Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql-1       | 2024-06-15T15:05:53.054340Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql-1       | 2024-06-15T15:05:53.106723Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.4.0'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
mysql-1       | 2024-06-15T15:05:53.367243Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '127.0.0.1' port: 33060, socket: /var/run/mysqld/mysqlx.sock
phpmyadmin-1  | Syntax OK
phpmyadmin-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
phpmyadmin-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
phpmyadmin-1  | [Sat Jun 15 15:05:50.864825 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.8 configured -- resuming normal operations
phpmyadmin-1  | [Sat Jun 15 15:05:50.865260 2024] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
phpmyadmin-1  | 147.185.132.65 - - [15/Jun/2024:15:15:06 +0000] "GET / HTTP/1.1" 200 19975 "-" "Expanse, a Palo Alto Networks company, searches across the global IPv4 space multiple times per day to identify customers&#39; presences on the Internet. If you would like to be excluded from our scans, please send IP addresses/domains to: scaninfo@paloaltonetworks.com"

**Machine details (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
- Python version: 3.12.3

**Comment by mdjvd** [comment]
باید وقتی که این مشکل پیش میاد، قبل از ری استارت کردن لاگ ها رو چک کنید.

**Comment by nsa14** [comment]
سلام
برای ریستارت کردن اتوماتیک مرزبان میتونی از این اسکریپت اماده استفاده کنی
میاد طبق زمانی ک بهس میدی مثلا عدد ۳ یعنی هر ۳ ساعت یکباراتومات طبق تایم ریستارت میکنه مرزبان رو
