### ISSUE TITLE
قابلیت افزودن کاربر فقط روی یک نود خاص

### ISSUE THREAD

**Issue by Pezhman5252** [Gozargah/Marzban#1054]
با سلام و احترام،

من به عنوان یکی از کاربران پنل مرزبان، تقاضای افزودن قابلیت اتصال کاربران به هاست‌های خاص را در این پنل دارم.

در حال حاضر، هنگام ایجاد کاربر جدید، امکان تعیین هاست مورد نظر برای اتصال کاربر به آن وجود ندارد. این موضوع باعث می‌شود که کاربر به تمامی هاست‌های موجود در اینباند (مانند VMess TCP) دسترسی داشته باشد، در حالی که ممکن است من بخواهم دسترسی کاربر را به هاست‌های خاصی محدود کنم.

به عنوان مثال، من چند هاست با نام‌های "host Node 1"، "host Node 2" و "hostNode3" دارم که هر کدام از یک نود جداگانه ایجاد شده‌اند. می‌خواهم هنگام ایجاد کاربر جدید، بتوانم مشخص کنم که کاربر X فقط مجاز به مشاهده لینک‌های هاست "host Node 2" باشد.

متاسفانه، در نسخه فعلی API پنل مرزبان، امکان تعیین هاست‌های قابل مشاهده برای هر کاربر وجود ندارد و تمامی هاست‌های موجود در اینباند به طور پیش فرض برای کاربر جدید ساخته می‌شوند.

لذا تقاضا دارم امکان تعیین هاست‌های قابل مشاهده برای هر کاربر در هنگام ایجاد کاربر جدید به پنل مرزبان اضافه شود.

با تشکر

**Comment by erfjab** [comment]
درود و وقت بخیر ایده‌ی بسیار خوبی هست ولی در حال حاضر با اولویت های ما نمیخونه. من ایشو رو به حالت انهولد میزارم تا در آینده بهش برگردیم.
