### ISSUE TITLE
❤️❤️❤️ یه دونیت کوچولو، یه دنیا آپدیت خفن ❤️❤️❤️

### ISSUE THREAD

**Issue by Pezhman5252** [Gozargah/Marzban#1056]
یه پیشنهاد دوستانه!
سلام به رفقای گل و بلبل!

می‌دونم که خیلی از شما از پنل مرزبان برای استفاده شخصی‌تون استفاده می‌کنید و حرفی نیست. اما یه گروه دیگه هم هستن که با استفاده از این پنل، وی‌پی‌ان می‌فروشن و ازش کسب درآمد می‌کنن.

حالا یه حرفی دارم: به نظرتون منصفانه نیست که یه ذره از این درآمد به تیم فوق‌العاده مرزبان برسه؟

برنامه‌نویسی و پشتیبانی این پنل کار خیلی سختیه و این دوستان زحمت زیادی می‌کشن تا یه ابزار باحال و رایگان در اختیارمون بذارن.

پس چی بهتر از این که یه ذره از پولی که به واسطه زحمات این عزیزان به دست می‌آوریم، به خودشون برگردونیم؟

اینجوری انگیزه می‌گیرن که آپدیت‌های خفن‌تر و امکانات بهتری به پنل اضافه کنن.

راستش رو بخوای، یه صفحه دونیت هم گذاشتن که می‌تونید به راحتی از طریقش کمک کنید.

https://github.com/Gozargah/Marzban#donation

آدرس کیف پول‌ها هم توی صفحه هست.

TRON network (TRC20): **TX8kJoDcowQPBFTYHAJR36GyoUKP1Xwzkb**

ETH, BNB, MATIC network (ERC20, BEP20): **0xFdc9ad32454FA4fc4733270FCc12ddBFb68b83F7**

Bitcoin network: **bc1qpys2nefgsjjgae3g3gqy9crsv3h3rm96tlkz0v**

Dogecoin network: **DJAocBAu8y6LwhDKUktLAyzV8xyoFeHH6R**

TON network: **EQAVf-7hAXHlF-jmrKE44oBwN7HGQFVBLAtrOsev5K4qR4P8**

حمایت از برنامه‌نویس‌ها یه کار خیلی قشنگه و به نفع همه ماست.

پس معطل چی هستی؟ یه دستی به این عزیزان برسون تا با خیال راحت‌تر و انگیزه بیشتر، به کارشون ادامه بدن.

با تشکر فراوان از تیم بی‌نظیر مرزبان! ❤️❤️❤️

**Comment by iamtheted** [comment]
قلب پاکی دارین، خیلی خوبه که هنوزم آدمای خوب هستن 💙

**Comment by waxilu** [comment]
واقعا دمت گرم. همیشه و همجا از خایه مال ها بد گفتن ولی ایندفه کاملا بجا و درست بود 🙏🙏
