### ISSUE TITLE
Returning Null for admin_id When a User Is Created in Telegram Bot

### ISSUE THREAD

**Issue by amotlagh** [Gozargah/Marzban#1059]
ادمین سودو در `.env` آی‌دی عدی تلگرام را وارد کرده: `TELEGRAM_ADMIN_ID`
علاوه بر آن هنگام ایجاد ادمین هم آ‌ی‌دی تلگرام را وارد نموده. (در جدول `admins` برای یوزر سودو در `telegram_id` آی‌دی عددی تلگرام وجود داره)
حالا وقتی ادمین سودو  از طریق ربات اقدام به سایت یوزر میکنه؛ `admin_id` در جدول `users` مقدارش null هست:

![image](https://github.com/Gozargah/Marzban/assets/75310402/2c40c776-23e1-42c2-bfdd-c813a681b975)

![Screenshot from 2024-06-24 00-19-46](https://github.com/Gozargah/Marzban/assets/75310402/4c7040e7-37cf-4a0a-9fb3-bee7bedd8ade)

در `app/db/crud.py` فانکشن `get_admin_by_telegram_id` وجود داره ولی در` app/telegram/handlers/admin.py` در فانکشن `confirm_user_command` استفاده نشده:
 
![image](https://github.com/Gozargah/Marzban/assets/75310402/c64599fb-3ce3-4216-8789-3f811b9069e8)

**Comment by M03ED** [comment]
فیلد `telegram_id` در جدول ادمین در حال حاضر صرفا برای ارسال نوتفیکیشن استفاده میشه و نه چیز دیگه ای.
