### ISSUE TITLE
نحوه ایجاد وارپ شخصی سازی شده بروی نود و سرور اصلی

### ISSUE THREAD

**Issue by chitoz1300** [Gozargah/Marzban#1060]
سلام عرض ادب امکانش هست سرور نود بصورت کامل از روی وارپ عبور کنه و سرور اصلی فقط گوگل رو از وارپ عبور بده؟ 
کلا هم یدونه inbound vmess دارم

**Comment by M03ED** [comment]
اینگونه موارد مربوط به ایکس ری هست و باید داکیومنت ایکس ری رو مطالعه کنید 
https://xtls.github.io/en
تا جایی که من دیدم جنین کاری با یک اینباند ممکن نیست
