### ISSUE TITLE
Bug titleIssues with Trading & Banking Apps and Google Services

### ISSUE THREAD

**Issue by underdog-03** [Gozargah/Marzban#1068]
Hi @Gozargah
Thank you all for the great work you are doing.

I'm experiencing some issues when using Xray-core. Certain websites, services, and apps, such as `Google Analytics` and some `trading` and `banking` apps primarily from America or Europe, don't open when the VPN is on.
Interestingly, they work fine with other VPN services like ExpressVPN or NordVPN.

Is there any solution you can offer to resolve these problems?

Thank you in advance for your help.

**Comment by M03ED** [comment]
this problem its not about xray-core , this is depend on your ip address you use

**Comment by underdog-03** [comment]
@M03ED 
Thanks for your reply. Regarding your suggestions, I have tried Warp and Routing and specifically targeted the domains and IPs I wanted, forcing them to use IPv4. Unfortunately, it didn't work. I also forced all my traffic to go through Cloudflare Warp, but that didn't work either.

I made sure there are no DNS, WebRTC, or IP Address leaks, and I verified that the VPS IP is clean and doesn't have any blacklist history or bans. Despite all this, it still doesn't work!

For example, if you try to open [Google Analytics](https://analytics.google.com/), it still returns an `HTTP ERROR 503`. Some digital trading websites and international banks, mostly American and English, have the same problem. Somehow, they detect the VPN and proxy connections.

Any additional advice or solutions you could offer would be greatly appreciated.

**Comment by M03ED** [comment]
> @M03ED Thanks for your reply. Regarding your suggestions, I have tried Warp and Routing and specifically targeted the domains and IPs I wanted, forcing them to use IPv4. Unfortunately, it didn't work. I also forced all my traffic to go through Cloudflare Warp, but that didn't work either.
> 
> I made sure there are no DNS, WebRTC, or IP Address leaks, and I verified that the VPS IP is clean and doesn't have any blacklist history or bans. Despite all this, it still doesn't work!
> 
> For example, if you try to open [Google Analytics](https://analytics.google.com/), it still returns an `HTTP ERROR 503`. Some digital trading websites and international banks, mostly American and English, have the same problem. Somehow, they detect the VPN and proxy connections.
> 
> Any additional advice or solutions you could offer would be greatly appreciated.

mostly they are sensitive on using vps ip addresses, in situations like this you need a real person ip address, some people rent their ip monthly, you can search about this and find more, there is nothing more i can do
