### ISSUE TITLE
ALPN & fingerprint not set in custom configs

### ISSUE THREAD

**Issue by m0x61h0x64i** [Gozargah/Marzban#1069]
**Describe the bug**
ALPN & fingerprint not set in custom configs after applying changes to host settings and when i update subscription i can't see ALPN & fingerprint but they are alrdy set in database :
![image](https://github.com/Gozargah/Marzban/assets/109550653/4a4ffef3-ffb4-4291-808e-165ec0993593)

**To Reproduce**
1. create an inbound in latest marzban dev version
2. in host settings set apln and fingerprint and apply
3. update ur subscription
4. in config u cant see alpn and fingerprint (for me for ws no tls config)

**Expected behavior**
see alpn and fingerprint in custom config

**Additional context**
I dont use v2ray template
latest dev marzban version
Also using API to get v2ray-json i cant see alpn and fingerprint there too

**Comment by M03ED** [comment]
its ok , both alpn and fingerprint is applied on config 
but there is another problem for already reported in here #1034
output config:
```json
        "tlsSettings": {
          "serverName": "domain.com",
          "allowInsecure": false,
          "fingerprint": "randomized",
          "alpn": [
            "http/1.1"
          ],
```

**Comment by m0x61h0x64i** [comment]
> ```json
> "tlsSettings"
> ```

how about if u try a no tls config ?

**Comment by M03ED** [comment]
> > ```json
> > "tlsSettings"
> > ```
> 
> how about if u try a no tls config ?

do you have any documentation you can use them without tls ?

**Comment by m0x61h0x64i** [comment]
yes, ir-gfw says fingerprint must be specified for no tls configs, but for alpn no i dont

**Comment by M03ED** [comment]
> yes, ir-gfw says fingerprint must be specified for no tls configs, but for alpn no i dont

in v2rayn all of these fields is for tls 
you can use it when you enable tls
[sing-box docs](https://sing-box.sagernet.org/configuration/shared/tls/#outbound) says same thing 
![image](https://github.com/Gozargah/Marzban/assets/50927468/f01b69ea-91b0-48e9-906d-6970a70563e5)

**Comment by m0x61h0x64i** [comment]
okay I surrender
