### ISSUE TITLE
httpupgrade

### ISSUE THREAD

**Issue by morteza-rashidi** [Gozargah/Marzban#1070]
با سلام و خدا قوت
آیا پرتکول httpupgrade روی مرزبان فعال هست یا خیر؟ اگر هست چه ورژنی؟ و اگر هست اینباند مورد استفاده رو از کجا میتونم پیدا کنم

**Comment by M03ED** [comment]
سلام
روی ورژن dev قابل استفاده هست

**Comment by morteza-rashidi** [comment]
اینباند مورد استفاده رو هم بفرمایید از کجا می تونم پیدا کنم

**Comment by M03ED** [comment]
xtls.github.io/en/
