### ISSUE TITLE
dev branch: marzban update throws error

### ISSUE THREAD

**Issue by m0x61h0x64i** [Gozargah/Marzban#1075]
i just updated marzban and panel does not load 
logs:

![image](https://github.com/Gozargah/Marzban/assets/109550653/f2488165-2d90-43bc-a216-d56b54f49433)
![image](https://github.com/Gozargah/Marzban/assets/109550653/cd558cc9-6a5a-42a8-ab94-a36e45ec13be)
![image](https://github.com/Gozargah/Marzban/assets/109550653/11983db7-f226-47b8-9c92-7837dd64df90)
![image](https://github.com/Gozargah/Marzban/assets/109550653/1e338052-f350-45aa-8fb0-f50f815c68f3)

**Comment by m0x61h0x64i** [comment]
marzban restart does not help

**Comment by SaintShit** [comment]
Hi, there's a bug currently happening for some users. try this until it's fixed.
navigate to `/opt/marzban`

```
docker compose up -d marzban
docker compose exec marzban apt update
docker compose exec marzban apt install git
docker compose exec marzban git checkout c1b47d6
docker compose restart marzban
```

tell me if dashboard came up. it's a temporary way, we're fixing it.

**Comment by SaintShit** [comment]
a2ad3171eeebc8308027578eaedd956deff4caf8

**Comment by m0x61h0x64i** [comment]
I still get error:

![image](https://github.com/Gozargah/Marzban/assets/109550653/71312f37-429a-44d5-b0ba-2552663fd996)
![image](https://github.com/Gozargah/Marzban/assets/109550653/a85553fb-d966-4dd9-9530-8e01ee3641a4)

**Comment by SaintShit** [comment]
wait for this job to get completed ( around 3-4 minutes )
https://github.com/Gozargah/Marzban/actions/runs/9778769406/job/26996350437
then update your marzban, it'll be fixed.
let me know

**Comment by m0x61h0x64i** [comment]
> [a2ad317](https://github.com/Gozargah/Marzban/commit/a2ad3171eeebc8308027578eaedd956deff4caf8)

gives error:

![image](https://github.com/Gozargah/Marzban/assets/109550653/a33b888f-93ae-454f-be0e-dbf7d9b7de0d)
![image](https://github.com/Gozargah/Marzban/assets/109550653/6baa9b0d-19bb-43f9-be45-d37b5b6ce0f1)
![image](https://github.com/Gozargah/Marzban/assets/109550653/7dbdf010-25dd-4de7-b8ca-1e18eb7a3a9c)
![image](https://github.com/Gozargah/Marzban/assets/109550653/39f67e57-3221-4077-a383-dedc76876354)

also tried marzban restart

**Comment by SaintShit** [comment]
@m0x61h0x64i jobs done, do update

**Comment by m0x61h0x64i** [comment]
> wait for this job to get completed ( around 3-4 minutes ) https://github.com/Gozargah/Marzban/actions/runs/9778769406/job/26996350437 then update your marzban, it'll be fixed. let me know

yes fixed, thanks

**Comment by SaintShit** [comment]
happy to hear that
