### ISSUE TITLE
refactor subscription link handling.

### ISSUE THREAD

**Issue by EryX0** [Gozargah/Marzban#1091]
**The problem.**
Not being able to create users with predefined subscription link or edit their subscription link, also another problem is **_subscription_url_** changes when a user's username gets edited (because its generated everytime UserResponse is accessed.)

**Solution [(discussed in Marzneshin group)](https://t.me/marzneshins/9501)**
the solution i have in mind is to decouple **_subscription_url_** from the **_UserResponse class_**, and add a user attribute called **_"subscription_id"_** when creating the user, and if **_subscription_id_** wasn't passed through api, we can have a default value to generate a subscription_id based on username and a hash (current approach) but again, only when creating the user, and adding this to the subscription_id attribute for the user class.

we also have to decouple subscriptions domain and subscription path from the subscription link we are giving to the user and store them in different variables and have them configurable inside panel settings, something like what 3x-ui has done.

**Comment by M03ED** [comment]
problem with your suggestion:
- jwt token cant be predefined or be edited, its gonna be generated every time and token it's different every time (as you mentioned)
- why you should change user's username ? its only factor for authentication
- adding unnecessary row to database is not a good job
- here is not marzneshin

> we also have to decouple subscriptions domain and subscription path from the subscription link we are giving to the user and store them in different variables and have them configurable inside panel settings, something like what 3x-ui has done.

this one maybe added in future but for now i don't think so

**Comment by EryX0** [comment]
> * here is not marzneshin

my bad, sorry.
i was super sleepy when i was writing this issue,
this issue was intended for Marzneshin and not Marzban, i mistakenly wrote the issue here, closing it now.
