### ISSUE TITLE
*.domain.com پشت CDN برای نود ها کار نمیکند

### ISSUE THREAD

**Issue by CIAHAT** [Gozargah/Marzban#1092]
سلام
وقتی از *.domain.com بعنوان SNI و Host تو کانفیگ VLESS WS TLS استفاده میکنم، برای سرور مرکزی کاملا اوکیه و جواب میده.
اما وقتی تو کلودفلیر، آیپی پشت دامنه رو میبرم روی سرور نود، دیگه کار نمیکنه.
هر دامنه ای بجز *.domain.com برای نود کار میکنه و تست شده

تنظیمات هاست مرزبان رو هم ادیت میکنم همه جزئیات رعایت میشه. مثلا وقتی تنظیمات Xray Core و هاست مرزبان رو برای *.domain.com تنظیم کردم و پشت کلودفلیر، آیپی سرور مرکزی رو دادم، همه چیز اوکیه و درست کار میکنه. بدون دست زدن به هیچ چیزی، وقتی آیپی رو میذارم برای نود، دیگه کار نمیکنه
شرایط مشابهی رو تصور کنید که دقیقا همین کار ها رو انجام میدم ولی بجای *.domain.com، یک دامنه تکی هست. در اونصورت هم پشت سرور مرکزی کار میکنه هم پشت آیپی سرور نود.

**Comment by M03ED** [comment]
استفاده از ساب دامنه رندوم نیازمند استفاده از سرتیفیکیت وایلد کارت هست و به سرتیفیکیت های عادی که برای تک دامنه هستن نمیشه این کار رو انجام داد

**Comment by CIAHAT** [comment]
> استفاده از ساب دامنه رندوم نیازمند استفاده از سرتیفیکیت وایلد کارت هست و به سرتیفیکیت های عادی که برای تک دامنه هستن نمیشه این کار رو انجام داد

سرتیفیکیت وایلد کارت خود کلودفلیر هست. تو توضیحات هم نوشتم همون دامنه همون تمظیمات همون سرتیفیکیت، وقتی به آیپی سرور مرکزی اشاره میکنه، درست کار میکنه کاملا.
اما وقتی به آیپی سرور نود اشاره میکنه کار نمیکنه. و فقط هم سابدامین رندوم اینطوریه. یعنی همون دامنه و تنظیمات، اگر تک سابدامین به آیپی نود اشاره کنه، درست کار میکنه
نسخه xray 1.8.10 مرکزی و نود

**Comment by M03ED** [comment]
این مشکل قبلا هم مشاهده شده و با استفاده از سرتیفیکیت های غیر از Cloudflare مشکل رفع شده

**Comment by CIAHAT** [comment]
> این مشکل قبلا هم مشاهده شده و با استفاده از سرتیفیکیت های غیر از Cloudflare مشکل رفع شده

با سرتیفیکیت Lets encrypt هم تست کردم مشکل مشابهی وجود داره. شما از چه سرتی استفاده کردید که حل شد براتون؟

**Comment by M03ED** [comment]
> > این مشکل قبلا هم مشاهده شده و با استفاده از سرتیفیکیت های غیر از Cloudflare مشکل رفع شده
> 
> با سرتیفیکیت Lets encrypt هم تست کردم مشکل مشابهی وجود داره. شما از چه سرتی استفاده کردید که حل شد براتون؟

Lets encrypt

**Comment by CIAHAT** [comment]
> > > این مشکل قبلا هم مشاهده شده و با استفاده از سرتیفیکیت های غیر از Cloudflare مشکل رفع شده
> > 
> > 
> > با سرتیفیکیت Lets encrypt هم تست کردم مشکل مشابهی وجود داره. شما از چه سرتی استفاده کردید که حل شد براتون؟
> 
> Lets encrypt

عجیبه. چون با این سرت هم دقیقا مشکل قبلی برام پیش اومد. اگر امکان دستوراتی که براش استفاده کردید رو بذارید اینجا.

**Comment by CIAHAT** [comment]
امروز متوجه شدم برای xray core نسخه 1.8.9 به بعد تا خود همین 1.8.19، برای سرور اصلی هم دامنه های *.domain.com به مشکل میخورن.
ارور 404 Not found handshake میگیرن.
پروتکلی که استفاده میشه: VLESS+WS+TLS
مشکل هم دقیقا همین دامنه های *.domain هستند. چون وقتی سابدامنه سینگل میذارم اوکی میشه.
سرتیفیکیت Lets encrypt هستش.

احتمالی که میدم اینه که ناسازگاری بخاطر نسخه xray core باشه. تا وقتی سرور مرکزی نسخه 1.8.9 بود و نود ها بالاتر بودن، مشکل برای نود ها بود. الان که سرور مرکزی رو اپدیت کرم، خودش هم به همون مشکل دچار شده.

**Comment by M03ED** [comment]
> عجیبه. چون با این سرت هم دقیقا مشکل قبلی برام پیش اومد. اگر امکان دستوراتی که براش استفاده کردید رو بذارید اینجا.


```shell
apt install socat certbot
curl https://get.acme.sh | sh
~/.acme.sh/acme.sh --set-default-ca --server letsencrypt
mkdir /var/lib/marzban/certs/
export CF_Key="xxx"
export CF_Email="yyy"
~/.acme.sh/acme.sh --issue -d domain.xxx -d '*.domain.xxx' --dns dns_cf --key-file /var/lib/marzban/certs/key.pem --fullchain-file /var/lib/marzban/certs/fullchain.pem
```

**Comment by M03ED** [comment]
> امروز متوجه شدم برای xray core نسخه 1.8.9 به بعد تا خود همین 1.8.19، برای سرور اصلی هم دامنه های *.domain.com به مشکل میخورن. ارور 404 Not found handshake میگیرن. پروتکلی که استفاده میشه: VLESS+WS+TLS مشکل هم دقیقا همین دامنه های *.domain هستند. چون وقتی سابدامنه سینگل میذارم اوکی میشه. سرتیفیکیت Lets encrypt هستش.
> 
> احتمالی که میدم اینه که ناسازگاری بخاطر نسخه xray core باشه. تا وقتی سرور مرکزی نسخه 1.8.9 بود و نود ها بالاتر بودن، مشکل برای نود ها بود. الان که سرور مرکزی رو اپدیت کرم، خودش هم به همون مشکل دچار شده.
> 
> پ.ن: با سرت کلودفلیر هم مشکل مشابهی وجود داره

من از ورژن 1.8.16 استفاده می کنم و مشکلی وجود نداره

**Comment by CIAHAT** [comment]
> > عجیبه. چون با این سرت هم دقیقا مشکل قبلی برام پیش اومد. اگر امکان دستوراتی که براش استفاده کردید رو بذارید اینجا.
> 
> ```shell
> apt install socat certbot
> curl https://get.acme.sh | sh
> ~/.acme.sh/acme.sh --set-default-ca --server letsencrypt
> mkdir /var/lib/marzban/certs/
> export CF_Key="xxx"
> export CF_Email="yyy"
> ~/.acme.sh/acme.sh --issue -d domain.xxx -d '*.domain.xxx' --dns dns_cf --key-file /var/lib/marzban/certs/key.pem --fullchain-file /var/lib/marzban/certs/fullchain.pem
> ```

مشکل نود برطرف شد با این دستور. تشکر

**Comment by M03ED** [comment]
https://gozargah.github.io/marzban/fa/examples/wild-card-ssl

**Comment by aqilahmadi** [comment]
سلام من هم همین مشکل رودارم دقیقا، ایا راه حلی پیدا کردین؟
