### ISSUE TITLE
اضافه کردن ستون به دیتابیس

### ISSUE THREAD

**Issue by morteza-rashidi** [Gozargah/Marzban#1094]
برای اضافه کردن ستون به دیتابیس باید چکاری انجام بدیم؟
من بصورت دستی به جدول admins ی ستون بنام name اضافه کردم
آیا با آپدیت مرزبان وجود این ستون میتونه باعث ایجاد مشکل بشه ؟

**Comment by M03ED** [comment]
#1099

**Comment by M03ED** [comment]
ممکنه به وجود بیاد و یا نیاد ، بستگی به تغییر شما و تغییرات آینده مرزبان داره

**Comment by morteza-rashidi** [comment]
کلا راه استانداردی وجود داره ؟

**Comment by M03ED** [comment]
خیر
