### ISSUE TITLE
DEV: tls: invalid nextprotos value in Hiddify client

### ISSUE THREAD

**Issue by DigneZzZ** [Gozargah/Marzban#1097]
If you update from older latest version to newest dev bench, you v got this bug in Hiddify client
` tls: invalid nextprotos value`

![image](https://github.com/Gozargah/Marzban/assets/50312583/5f41066e-7c0d-4ae9-9a74-d1155176d44d)

We have two ways to fix it:
1. Insert `/clash-meta` into the subscription link when you add it to the Hiddify client.
2. Server-side solution - you need to set up the ALPN in your configs:
<img width="380" alt="image" src="https://github.com/Gozargah/Marzban/assets/50312583/bac94706-47a8-4d1e-a6c1-e46c302db49e">

The ALPN solution fixed it, but will there be a permanent fix?

**Comment by M03ED** [comment]
i know where is problem i try to fix it today or tomorrow
