### ISSUE TITLE
"Accept-Encoding" in tcp request header

### ISSUE THREAD

**Issue by plasticgholam** [Gozargah/Marzban#1098]
in v2ray customized config in "tcpSettings" in request header when "Accept-Encoding" set to both "gzip, deflate" encodings, then in some operators like MCI there would be a problem. only either of them should be there, but I deleted this line and the problem solved:

https://github.com/Gozargah/Marzban/blob/6dc0d38a0e58dcd60a413f0fe5af6597f6960fa4/app/subscription/v2ray.py#L516C1-L516C95

**Comment by nasiriscript** [comment]
It looks like any changes to the default Xray TCP headers will do the work, whether we change the default values of the headers or remove existing headers.

**Comment by nasiriscript** [comment]
@M03ED

**Comment by plasticgholam** [comment]
I figured It all related to the user-agent in v2ray and requsted headers
if you remove this line for user-agent for example and it will do the job but idk the consequences

https://github.com/Gozargah/Marzban/blob/6dc0d38a0e58dcd60a413f0fe5af6597f6960fa4/app/subscription/v2ray.py#L529

**Comment by plasticgholam** [comment]
I also only edited this line like this and works well too, jest needed ", "

            tcpSettings["header"]["request"]["headers"]["Accept-Encoding"] = ["gzip**"**, **"**deflate"]

**Comment by plasticgholam** [comment]
now I figured any customized change in request header values will solve the problem (e.g. method, version, encoding,..) the default values detected by MCI and got blocked
