### ISSUE TITLE
مشکل ساب در کلاینت‌ها با هسته سینگ باکس

### ISSUE THREAD

**Issue by DrAmirB** [Gozargah/Marzban#1101]
سلام وقت بخیر من بعد از اینکه نسخه dev رو امروز اپدیت کردم متوجه شدم بعد از اینکه لینکهای ساب اپدیت میشن دیگه کانفیگهایی که قبلا بدون مشکل در نرم افزارهایی که هسته سینگ باکس استفاده میکنن (مثل کارینگ، هیدیفای و نکوباکس) کار میکردن از کار میوفتن
تنها کانفیگای tcp+http متصل باقی میمونن و ریلیتی و cdn تماما از کار میوفتن

پ.ن: تا موقعی که لینک سابها اپدیت نشده باشن کانفیگا کار میکنن بدون مشکل. اما به محض اپدیت ساب تمام کانفیگا از کار میوفتن.

چند سرور تستی دیگه هم ساختم همه همین مشکل داشتن

**Comment by plasticgholam** [comment]
اره منم به این مشکل برخورده باید در هاست ستینگز alpn بزاری برای ws و httpupgrade و reality تا دوباره کار کنند
