### ISSUE TITLE
Templates for create user button

### ISSUE THREAD

**Issue by govfvck** [Gozargah/Marzban#111]
**Is your feature request related to a problem? Please describe.**
It's very good to have some templates for user creation. for example, the admin could create a template with 30Gb of data usage, 1 month for the duration, and vless as the enabled proxy. anytime the admin clicks on this template, they would only enter the username and everything else would be filled automatically for that user.

**Describe the solution you'd like**
have a `templates` table to save these templates; users could add, remove, and edit these templates.  
it would also need to be implemented in the front-end panel!

**Comment by SaintShit** [comment]
The front-end part might have lots of work. how about inbounds? can a template have a custom inbound (rather than protocol)?
