### ISSUE TITLE
تغییر مکرر لینک ساب 

### ISSUE THREAD

**Issue by Non-believer** [Gozargah/Marzban#1113]
سلام وقت بخیر در آپدیت جدید من وقتی یوزر جدید می‌سازم و لینک سابش رو میگیرم اگه برای بار دوم بخوام اون لینک رو از پنل بردارم پنل در کنار لینکی که قبلا داده یه لینک جدید میده  به طوری که انگار میشه برای یک کاربر بینهایت لینک ساب متفاوت داشت خواستم بدونم این ویژگی امنیتی جدید پنله یا صرفا یک باگه که دیتابیس رو الکی الکی پر میکنه؟

**Comment by M03ED** [comment]
این نه جدیده و نه مشکل ، لینک ساب همیشه همین طور بوده ، در هر بار رفرش یک لینک جدید ساخته میشه و قبلی ها هم همچنان فعال هستن

**Comment by M03ED** [comment]
ربطی به دیتابیس هم نداره
