### ISSUE TITLE
عدم نمایش یوزر ها بعد از بروزرسانی

### ISSUE THREAD

**Issue by Dnt3e** [Gozargah/Marzban#1114]
![photo_2024-07-16_02-32-57](https://github.com/user-attachments/assets/2058e915-5137-488b-8459-514bbb186cc4)

>  File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
> marzban-1     |     raise errorclass(errno, errval)
> marzban-1     | sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'users.auto_delete_in_days' in 'field list'")
> marzban-1     | [SQL: SELECT users.id AS users_id, users.username AS users_username, users.status AS users_status, users.used_traffic AS users_used_traffic, users.data_limit AS users_data_limit, users.data_limit_reset_strategy AS users_data_limit_reset_strategy, users.expire AS users_expire, users.admin_id AS users_admin_id, users.sub_revoked_at AS users_sub_revoked_at, users.sub_updated_at AS users_sub_updated_at, users.sub_last_user_agent AS users_sub_last_user_agent, users.created_at AS users_created_at, users.note AS users_note, users.online_at AS users_online_at, users.on_hold_expire_duration AS users_on_hold_expire_duration, users.on_hold_timeout AS users_on_hold_timeout, users.auto_delete_in_days AS users_auto_delete_in_days, users.edit_at AS users_edit_at, users.last_status_change AS users_last_status_change, admins_1.id AS admins_1_id, admins_1.username AS admins_1_username, admins_1.hashed_password AS admins_1_hashed_password, admins_1.created_at AS admins_1_created_at, admins_1.is_sudo AS admins_1_is_sudo, admins_1.password_reset_at AS admins_1_password_reset_at, admins_1.telegram_id AS admins_1_telegram_id, admins_1.discord_webhook AS admins_1_discord_webhook
> marzban-1     | FROM users LEFT OUTER JOIN admins AS admins_1 ON admins_1.id = users.admin_id
> marzban-1     | WHERE users.status = %(status_1)s]
> marzban-1     | [parameters: {'status_1': 'active'}]
> marzban-1     | (Background on this error at: https://sqlalche.me/e/14/e3q8)

وقت بخیر
بعد از اپدیت پنل به ورژن جدید با خطای تصویر پیوست شده مواجه شدم ورژن mysql 9 هست و لازم به ذکر هست بعد از دانگرید به ورژن 0.4.9 مشکل برطرف میشه دوستان اگر کسی راه حلی داره ممنون میشم راهنمایی کنه

**Comment by M03ED** [comment]
```shell
cd /opt/marzban
docker compose exec marzban bash
alembic upgrade head
```
