### ISSUE TITLE
alpn custom config

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#1116]
درود alpn رو در پنل تعین میکنم ولی با کاستوم کانفیگ منتقل نمی شود
کانفیگ reality و vless ws tls رو تست کردم

**Comment by M03ED** [comment]
ریلیتی اصلا از alpn پشتیبانی نمیکنه و برای ws tls هم همین الان تست کردم ، ارسال میشه و درست هست

**Comment by realartin** [comment]
حله
