### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by m0x61h0x64i** [Gozargah/Marzban#1122]
چند روز پیش دوتا سایت myip رو گذاشتم توی وارپ. بعد از وارپ برداشتمشون ولی هنوزم که میرم توشون هر چند ثانیه که میرم توشون بعضا میبینم ایپیم وارپه!

اومدم اوتباند وارپو پاک کردم بازم همینجوریه!

یعنی واقعا چطور؟!

یه سرور پنل مرزبان و یه سرور نود مرزبان

**Comment by xmohammad1** [comment]
مرزبان رو ریستارت کنید ببینید مشکل حل میشه؟

**Comment by m0x61h0x64i** [comment]
> مرزبان رو ریستارت کنید ببینید مشکل حل میشه؟

نشد

**Comment by m0x61h0x64i** [comment]
فقط میدونم از مرزبان نیست
