### ISSUE TITLE
Allow inscure on vmess configs

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#1126]
سلام وقت بخیر
تو host وقتی allow inscure برای یه کانفیگ روشن میکنی اگه vless باشه سمت کلاینت فعال میشه ولی برای vmess سمت کلاینت فعال نمیشه , هم داخل برنامه v2rayng تست کردم

**Comment by M03ED** [comment]
این محدودیتی هست که از سمت v2rayn اعمال شده و ربطی به مرزبان نداره ، برای اینکه محدودیت رو دور بزنید میتونید از کاستوم کانفیگ استفاده کنید
