### ISSUE TITLE
 بهم ریختن ترتیب کانفیگا در حالت کاستوم

### ISSUE THREAD

**Issue by dvltak** [Gozargah/Marzban#1127]
بعد از اپدیت مرزبان به نسخه 0.5.1 و 0.5.2 ترتیب کانفیگادر حالت کاستوم از اینباند اخر به اول شده

**Comment by SaintShit** [comment]
توی چه برنامه‌ای؟ اگر توی برنامه Streisand مشکل دارین، مشکل از سمت خود برنامه هست.

**Comment by dvltak** [comment]
نه داخل v2rayng وsingbox و v2box چک کردم داخل جروه مرزبان هم دو سه نفر مثل من این مشکل رو داشتن

**Comment by dvltak** [comment]
> توی چه برنامه‌ای؟ اگر توی برنامه Streisand مشکل دارین، مشکل از سمت خود برنامه هست.
نه داخل v2rayng وsingbox و v2box چک کردم داخل جروه مرزبان هم دو سه نفر مثل من این مشکل رو داشتن

**Comment by ImMohammad20000** [comment]
باگ از برنامه ها هست

**Comment by mamad4** [comment]
این مشکل بهم خوردن ترتیب کانفیگا در حالت کاستوم برای منم هست
ولی در نسخه 1.8.27 v2rayng این مشکل وجود نداره و ترتیبش درسته
