### ISSUE TITLE
httpupgrade 

### ISSUE THREAD

**Issue by esodrevo** [Gozargah/Marzban#1129]
سلام و خسته نباشید خدمت تیم مرزبان،  اول تشکر کنم بخاطر اپدیت بزرگ و عالی اخیر ،
من با ترنزپورت httpupgrade به مشکل میخورم و مجبور میشم روزی سه چهار بار ریست کنم xray رو تا کانفیگ دوباره کار کنه،
و ارور هایی که توی لاگ xray هستن به این شکله
![Screenshot_20240717_175330_Chrome](https://github.com/user-attachments/assets/1876826f-e066-46f9-b2b3-d5c5166aabbd)

**Comment by M03ED** [comment]
لطفا این مورد رو ریپو خود xray مطرح کنید چون این مورد مربوط به ایکس ری هست و نه مرزبان

**Comment by esodrevo** [comment]
چشم ممنون

**Comment by esodrevo** [comment]
> لطفا این مورد رو ریپو خود xray مطرح کنید چون این مورد مربوط به ایکس ری هست و نه مرزبان

فقط ببخشید یه سوال ؛ کامندی هست که بشه بصورت cli اکس ری رو ریستارت کرد و کرون تنظیم کرد براش؟ لااقل فعلا کارم راه بیفته، یا تنها دسترسی از پنله؟

**Comment by M03ED** [comment]
> فقط ببخشید یه سوال ؛ کامندی هست که بشه بصورت cli اکس ری رو ریستارت کرد و کرون تنظیم کرد براش؟ لااقل فعلا کارم راه بیفته، یا تنها دسترسی از پنله؟

خیر کامندی نیست ، میتونید براش اسکریپت بنویسید و اون رو ران کنید
