### ISSUE TITLE
Subscription link file type

### ISSUE THREAD

**Issue by papampi** [Gozargah/Marzban#113]
Please make the subscription link file type as txt so it can be opened in web and be compatible with cloudflare workers too.

**Comment by SaintShit** [comment]
it already has `text/plain` media type and `content-disposition` header set and would work fine.

**Comment by papampi** [comment]
But when try to open the subscription link with browser it does not open and browser ask to save it.
I want to use it in [@vfarid](https://gist.github.com/vfarid/7a725ccba10da1fc21f55037873727f6#file-clash-sub-worker-js) sub worker but marzban subscription link not working with it.

**Comment by papampi** [comment]
Already asked @vfarid  [here](https://gist.github.com/vfarid/7a725ccba10da1fc21f55037873727f6?permalink_comment_id=4509380#gistcomment-4509380) but got no answer from him.
