### ISSUE TITLE
sort subscription from host

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#1132]
سلام و خسته نباشید به دوستان گل دولپر
یه مشکلی که خیلی وقته هست اینکه که داخل سابسکریپشن بر حسب اینباند هایی که داخل host هست نمی چینه کانفیگارو
من میخوام تو سابسکریپشن کلا بر حسب اینباند های داخل host بچینم
یعنی مثلا یه اینباید vless دارم اون اول باشه بعد یه اینباند vmess دارم اون دوم باشه بعد یه اینباند vless دیگه دارم اون بره سوم ...

**Comment by M03ED** [comment]
اینباند ها بر اساس ترتیب کانفیگ ایکس ری هستند

**Comment by xmohammad1** [comment]
> اینباند ها بر اساس ترتیب کانفیگ ایکس ری هستند

متاسفانه ترتیب بندیش برای من کلا بهم خورده و به تربیت اینباند های داخل xray نیستش مثلا یه تروجان میزارم کانفیگ سوم ولی به عنوان اخری نشون میده

**Comment by xmohammad1** [comment]
> 
> پنل ذاتا براساس اینباندهای xray می‌فرسته.

برای من اینطوری نیست 🥹
همه vless هارو کنار هم میزاره همه vmess هارو هم همینطور
یا مثلا trojan اضافه میکنم میره اخر
چطوری میشه ترتیب بندیشو درست کرد؟

**Comment by xmohammad1** [comment]
درسته ضاهرا این حق با شماس من دیشب تست میکردم این مورد وجود داشت ولی ضاهرا الان اوکی هست 🤷‍♂️
