### ISSUE TITLE
مشکل در فرگمنت

### ISSUE THREAD

**Issue by bestkilleriranlod** [Gozargah/Marzban#1134]
درود
چرا برای کانفیگ های shadowsocks نمیشه فرگمنت زد ، هر چی میزنیم هیچ فرگمنتی روشون اعمال نمیشه در حالیکه دستی از داخل خود نرم افزار میزنم مشکلی نداره و کار میکنه
لطفا این قابلیت فرگمنت رو برای همه مدل کانفیگ ها در نظر بگیرید

**Comment by M03ED** [comment]
شدوساکس از این مورد پشتیبانی نمی کنه به همین دلیل روش اعمال نمیشه ، اعمال دستی از طریق نرم افزار هم تغییری روی شدوساکس ایجاد نمی کنه و اتصال بدون فرگمنت باقی میمونه

**Comment by bestkilleriranlod** [comment]
طبق تست من ای پی های شادوساکس روی همراه اول بطور کامل فیلتر نمیشن و اتفاقی مشابه اختلال شدید توشون میوفته که با نرم افزار Streisand فرگمنت براش تعریف کردم و بطور کامل اختلال برطرف شد

**Comment by M03ED** [comment]
اون چیزی که شما دنبالش هستید shadowsocks2022 هست که در مرزبان دردسترس نیست
