### ISSUE TITLE
Option to disable Login Notify Msg

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#1140]
Hello
Please add option to disable Login Notify Msg
as many third-party scripts/bots uses User & Password instead of Cookie and logins many times
and some people don't need login notify messages

**Comment by erfjab** [comment]
> Hello
> Please add option to disable Login Notify Msg
> as many third-party scripts/bots uses User & Password instead of Cookie and logins many times
> and some people don't need login notify messages

![IMG_20240719_145714_002.jpg](https://github.com/user-attachments/assets/4aecdd78-5c78-415e-9425-d9c7ea387732)

Of course, it is optional.

**Comment by fodhelper** [comment]
No, check this https://github.com/Gozargah/Marzban/commit/2d120a5f9c0e91faea7a2c1718940bead1ef5085

**Comment by erfjab** [comment]
> No, check this https://github.com/Gozargah/Marzban/commit/2d120a5f9c0e91faea7a2c1718940bead1ef5085

Saw. Wait for the outcome of the issue.
