### ISSUE TITLE
حذف نشدن نود بعد از آپدیت به ۰.۵.۲

### ISSUE THREAD

**Issue by Mrclocks** [Gozargah/Marzban#1147]
اوبونتو ۲۲
نسخه پنل ۰.۵.۲
نسخه نود ۰.۳.۳

بعد از آپدیت کردن به نسخه آخر دیگه نمیتونم نود های قبلی رو پاک کنم ارور میدهد .

![IMG_1853](https://github.com/user-attachments/assets/d6341601-268d-4f96-b6e8-5a916ec3684a)

**Comment by erfjab** [comment]
درود و وقت بخیر کلاک عزیز
لطفا از لاگ هاتون هنگام این درخواست شات بفرستید.
شاید بتونم راهنمایی تون کنم.

**Comment by Mrclocks** [comment]
> درود و وقت بخیر کلاک عزیز لطفا از لاگ هاتون هنگام این درخواست شات بفرستید. شاید بتونم راهنمایی تون کنم.

سلام عرفان عزیز ❤️
بفرمایید : 
![IMG_1855](https://github.com/user-attachments/assets/91710b70-9cc2-4dec-abb8-37634c370dc5)

**Comment by erfjab** [comment]
> > درود و وقت بخیر کلاک عزیز لطفا از لاگ هاتون هنگام این درخواست شات بفرستید. شاید بتونم راهنمایی تون کنم.
> 
> سلام عرفان عزیز ❤️
> بفرمایید : 
> ![IMG_1855](https://github.com/user-attachments/assets/91710b70-9cc2-4dec-abb8-37634c370dc5)
> 

دیتابیس‌تون sqlite هست؟

**Comment by erfjab** [comment]
> > درود و وقت بخیر کلاک عزیز لطفا از لاگ هاتون هنگام این درخواست شات بفرستید. شاید بتونم راهنمایی تون کنم.
> 
> سلام عرفان عزیز ❤️
> بفرمایید : 
> ![IMG_1855](https://github.com/user-attachments/assets/91710b70-9cc2-4dec-abb8-37634c370dc5)
> 

کلاک جان بهتره شات رو حذف کنی، آیپی ات مشخصه 😶

**Comment by Mrclocks** [comment]
> > > درود و وقت بخیر کلاک عزیز لطفا از لاگ هاتون هنگام این درخواست شات بفرستید. شاید بتونم راهنمایی تون کنم.
> > 
> > 
> > سلام عرفان عزیز ❤️
> > بفرمایید :
> > ![IMG_1855](https://private-user-images.githubusercontent.com/140599540/350530506-91710b70-9cc2-4dec-abb8-37634c370dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjA4OTEsIm5iZiI6MTcyMTQyMDU5MSwicGF0aCI6Ii8xNDA1OTk1NDAvMzUwNTMwNTA2LTkxNzEwYjcwLTljYzItNGRlYy1hYmI4LTM3NjM0YzM3MGRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQyMDIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDg5OWFlYTJmNGIwMTU2ZGExMzU0MGQ5MzQwYjdiMmJjYjM1N2E3MWZmNTI1OGVkMzg4ZDcyMGY1MzlmMTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cxOFe2nlGTUc75Q9POfQu4m_O7AK7ZT-HVkRbG_-S7Y)
> 
> دیتابیس‌تون sqlite هست؟

بلی

**Comment by erfjab** [comment]
> > > > درود و وقت بخیر کلاک عزیز لطفا از لاگ هاتون هنگام این درخواست شات بفرستید. شاید بتونم راهنمایی تون کنم.
> > > 
> > > 
> > > سلام عرفان عزیز ❤️
> > > بفرمایید :
> > > ![IMG_1855](https://private-user-images.githubusercontent.com/140599540/350530506-91710b70-9cc2-4dec-abb8-37634c370dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjA4OTEsIm5iZiI6MTcyMTQyMDU5MSwicGF0aCI6Ii8xNDA1OTk1NDAvMzUwNTMwNTA2LTkxNzEwYjcwLTljYzItNGRlYy1hYmI4LTM3NjM0YzM3MGRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQyMDIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDg5OWFlYTJmNGIwMTU2ZGExMzU0MGQ5MzQwYjdiMmJjYjM1N2E3MWZmNTI1OGVkMzg4ZDcyMGY1MzlmMTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cxOFe2nlGTUc75Q9POfQu4m_O7AK7ZT-HVkRbG_-S7Y)
> > 
> > دیتابیس‌تون sqlite هست؟
> 
> بلی

ارورها اینو میگه که دیتابیس خراب شده. بکاپ دارید؟

**Comment by Mrclocks** [comment]
> > > > > درود و وقت بخیر کلاک عزیز لطفا از لاگ هاتون هنگام این درخواست شات بفرستید. شاید بتونم راهنمایی تون کنم.
> > > > 
> > > > 
> > > > سلام عرفان عزیز ❤️
> > > > بفرمایید :
> > > > ![IMG_1855](https://private-user-images.githubusercontent.com/140599540/350530506-91710b70-9cc2-4dec-abb8-37634c370dc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjA4OTEsIm5iZiI6MTcyMTQyMDU5MSwicGF0aCI6Ii8xNDA1OTk1NDAvMzUwNTMwNTA2LTkxNzEwYjcwLTljYzItNGRlYy1hYmI4LTM3NjM0YzM3MGRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQyMDIzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDg5OWFlYTJmNGIwMTU2ZGExMzU0MGQ5MzQwYjdiMmJjYjM1N2E3MWZmNTI1OGVkMzg4ZDcyMGY1MzlmMTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cxOFe2nlGTUc75Q9POfQu4m_O7AK7ZT-HVkRbG_-S7Y)
> > > 
> > > 
> > > دیتابیس‌تون sqlite هست؟
> > 
> > 
> > بلی
> 
> ارورها اینو میگه که دیتابیس خراب شده. بکاپ دارید؟

بله مشکل از دیتابیس بود ، دیتابیس از بکاپ برگردوندم درست شد ، ممنون ازت
