### ISSUE TITLE
Feature : Number of online users

### ISSUE THREAD

**Issue by ayoubghasemi72** [Gozargah/Marzban#116]
hi.

Please add the "connected device number" and "number of online users".

Thanks.

**Comment by govfvck** [comment]
Hi.

currently, there is no way(as long as I know) to count "number of online users" or "connected device number".

the only thing you could do, is maybe to [(1)](https://unix.stackexchange.com/a/36170) count connected ip's to a certain port or [(2)](https://serverfault.com/a/421313) open connections to a certain port.
