### ISSUE TITLE
✘ marzban-node Error toomanyrequests: You have rea...

### ISSUE THREAD

**Issue by meysamamarlou** [Gozargah/Marzban#1160]
سلام روی ابونتو داکر نصب کردم ولی مرحله آخر 
docker compose up -d
انجام نمیشه و این پیام رو دارم
✘ marzban-node Error toomanyrequests: You have rea...                     2.5s
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by M03ED** [comment]
به نظر میرسه بیش از حد به داکر ریکوئست زدید 
ایمیج داکر تون رو به `ghcr.io/gozargah/marzban:dev` تغییر بدید و دوباره تست کنید
