### ISSUE TITLE
دارک مود 

### ISSUE THREAD

**Issue by soheylshorg** [Gozargah/Marzban#1167]
در نسخه اپدیت ورژن 0.6.0 در قسمت دارک مود هنگام تنظیم کاربر برخی نوشته ها به درستی نشان داده نمیشن و به صورت لایت مود و نوشته ها دیده نمیشن با تشکر از دست اندر کاران مرزبان

**Comment by soheylshorg** [comment]
![Screenshot 2024-07-22 210051](https://github.com/user-attachments/assets/fd527deb-dccc-48fd-a8d7-b280d658056f)

**Comment by vahidyeganeh1373** [comment]
منم دیروز آپدیت کردم دقیقا همین مشکلو دارم لطفا برطرف کنید

**Comment by erfjab** [comment]
> منم دیروز آپدیت کردم دقیقا همین مشکلو دارم لطفا برطرف کنید

مشکل با pr عرفان عزیز حل شده، بعد بررسی نهایی مرج خواهد شد.

**Comment by MR-MKZ** [comment]
> منم دیروز آپدیت کردم دقیقا همین مشکلو دارم لطفا برطرف کنید

I fixed this bro just @SaintShit or @gozarman should check it.
