### ISSUE TITLE
Domain Park

### ISSUE THREAD

**Issue by ali-system** [Gozargah/Marzban#117]
با سلام من میخوام چندیین دامنه رو به پنلم اضافه کنم
مشکل در سرتیکیفکیت های جدید که باید گرفته بشه
و به انجینیکس اضافه بشه  از طرفی میترسم دست کاری کنم همه چیز بپره
میشه راهنمایی کنید

**Comment by govfvck** [comment]
سلام دقیقا مشکلتون کجاست؟
اگه میخواید چند دامنه اضافه کنید، کافیه اون ها رو به شکل زیر به کانفیگ nginxاتون اضافه کنید:

`server_name example.com example2.com example3.com`

و برا گرفتن سرتیفیکیت هم از `certbot` استفاده کنید:
`certbot certonly --nginx`

که میاد کانفیگ nginxاتون رو میخونه و برای دامنه‌ها درخواست سرتیفیکیت میکنه. (دقت کنید که اگر چندتا دامنه هم داشته باشید، certbot فقط یک فایل بهتون میده که همون فایل سرتیفیکیت برای تمام دامنه‌ها هست و نیازی نیست برای تک به تک اونها اضافش کنید)

**Comment by naghiloo** [comment]
این مشکل رو منم دارم و میخوام به هرکاربر دامنه ای خاص رو اختصاص بدم. راهی هست؟ چون کاربران من پشت cdn هستن و محدودیت حجمی هست و مجبورم چندین دامنه داشته باشم
