### ISSUE TITLE
old subscription link does not work in Singbox app

### ISSUE THREAD

**Issue by radin-mg** [Gozargah/Marzban#1176]
hi
thank you for developing marzban
after updating to the new version of Marzban, the old subscription link does not work in the singbox app

![photo_2024-07-23_00-30-08](https://github.com/user-attachments/assets/f6755572-9ab7-43dc-b45e-cf318cb34d25)

**Comment by M03ED** [comment]
Do you use host to send data to users?

**Comment by radin-mg** [comment]
no, i dont use it
new subscription link is working in singbox, but old subscription link does not work
this problem does not exist in other apps, only in singbox

**Comment by radin-mg** [comment]
> Do you use host to send data to users?

no, i dont use it
new subscription link is working in singbox, but old subscription link does not work
this problem does not exist in other apps, only in singbox
