### ISSUE TITLE
Marzban doesn't include Host for HTTPUpgrade

### ISSUE THREAD

**Issue by Kiya6955** [Gozargah/Marzban#1177]
Hi 
When I set `Host` for HTTPUpgrade inbounds no matter it's TLS or noTLS, marzban doesn't include host in configs and it leaves it empty so I have to set host manually in host settings.

**Comment by iamtheted** [comment]
We conducted a test together, it's true.

**Comment by M03ED** [comment]
i test it right now and output is correct
```json
    "splithttpSettings": {
            "headers": {},
            "path": "/",
            "host": "xray.com",
            "maxUploadSize": 1000000,
            "maxConcurrentUploads": 10
        }
```

**Comment by M03ED** [comment]
> We are talking about HTTPUpgrade.

oh sorry
but i can't find the problem, output is correct 
```json
"streamSettings": {
                    "network": "httpupgrade",
                    "security": "none",
                    "httpupgradeSettings": {
                        "headers": {},
                        "path": "/",
                        "host": "xray.com"
                    }
                }
```

**Comment by M03ED** [comment]
> I think you set host manually in host settings. ![image](https://private-user-

nope its empty

**Comment by M03ED** [comment]
> I think i found the problem When we use
> 
> ```
>           "headers": {
>             "Host": "example.com"
>           }
> ```
> 
> instead of
> 
> ```
> "Host": "example.com"
> ```
> 
> this problem happened shouldn't it work this way too? I thought host is a part of headers section.

host can be part of headers but marzban will not catch it, because using host in headers is no common and mostly used in outbounds not inbounds

**Comment by OxJ4ck** [comment]
> Yes but most of Marzban users generate inbound with [MarzbanInboundGenerator](https://azavaxhuman.github.io/MarzbanInboundGenerator/) and this inbound generator set host in header for web socket and marzban doesnt have this bug in web socket.

شما باید از [داکیومنت پروژه xray](https://xtls.github.io/config/transports/httpupgrade.html) استفاده کنید.
در ws هم بعد از ورژن 1.8.10 (فک کنم) قسمت هاست از بخش header جدا شده.

**Comment by M03ED** [comment]
> Yes but most of Marzban users generate inbound with [MarzbanInboundGenerator](https://azavaxhuman.github.io/MarzbanInboundGenerator/) and this inbound generator set host in header for web socket and marzban doesnt have this bug in web socket.

That's just a third party project.
Marzban always recommend using official docs.
