### ISSUE TITLE
مشکل  در پنل پس از اپدیت مرزبان به نسخه [v0.6.0]

### ISSUE THREAD

**Issue by mamdali96** [Gozargah/Marzban#1178]
پس از اپدیت از نسخه [v0.5.2] به نسخه [v0.6.0] با دو مورد باگ و مشکل رو  به رو شدم به شرح زیر
البته قبل از اون سیستم عامل و شرایطی که در اون مرزبان اجرا میشه رو بازگو میکنم
ابونتو 22
دیتاسنتر OVH
DNS : Google و Quad
همه اپدیت ها و پیش نیاز ها به درستی نصب شده
دیتابیس Sqlite
نوع پنل تک پورت 443 وب سوکت
نسخه ایکس ری v1.8.19
مشکل | باگ شماره 1 :
پس از اپدیت امکان ورود به پنل چه با دامنه چه با ای پی به صورت مستقیم اصلا امکلن پذیر نبود و پس از بررسی لوگ متوجه شدم حین کلیک کردن بر روی دکمه لاگین این ارور به نمایش در میاد (به علت موارد امنیتی ای پی ها جایگذاری شدن) البته باید بگم اتصال اکانت ها مختل  نشده بودند

marzban-1  | INFO:      - "POST /api/admin/token HTTP/1.1" 500 Internal Server Error
marzban-1  | ERROR:    Exception in ASGI application
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marzban-1  |     return await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
marzban-1  |     await super().__call__(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
marzban-1  |     await self.app(scope, receive, _send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
marzban-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
marzban-1  |     await self.app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marzban-1  |     raise e
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
marzban-1  |     await route.handle(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
marzban-1  |     response = await func(request)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
marzban-1  |     raw_response = await run_endpoint_function(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
marzban-1  |     return await run_in_threadpool(dependant.call, **values)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
marzban-1  |     return await get_asynclib().run_sync_in_worker_thread(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marzban-1  |     return await future
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
marzban-1  |     result = context.run(func, *args)
marzban-1  |   File "/code/app/views/admin.py", line 42, in admin_token
marzban-1  |     client_ip = get_client_ip(request)
marzban-1  |   File "/code/app/views/admin.py", line 33, in get_client_ip
marzban-1  |     return request.client.host
marzban-1  | AttributeError: 'NoneType' object has no attribute 'host'
nginx-1    | 192.168.1.1 - - [23/Jul/2024:14:21:58 +0000] "POST /api/admin/token HTTP/2.0" 500 21 "https://100.168.1.1/dashboard/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
marzban-1  | INFO:      - "POST /api/admin/token HTTP/1.1" 500 Internal Server Error
marzban-1  | ERROR:    Exception in ASGI application
marzban-1  | Traceback (most recent call last):
nginx-1    | 192.168.1.1  - - [23/Jul/2024:14:21:59 +0000] "POST /api/admin/token HTTP/2.0" 500 21 "https://100.168.1.1/dashboard/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marzban-1  |     return await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
marzban-1  |     await super().__call__(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
marzban-1  |     await self.app(scope, receive, _send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
marzban-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
marzban-1  |     await self.app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marzban-1  |     raise e
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
marzban-1  |     await route.handle(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
marzban-1  |     response = await func(request)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
marzban-1  |     raw_response = await run_endpoint_function(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
marzban-1  |     return await run_in_threadpool(dependant.call, **values)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
marzban-1  |     return await get_asynclib().run_sync_in_worker_thread(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marzban-1  |     return await future
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
marzban-1  |     result = context.run(func, *args)
marzban-1  |   File "/code/app/views/admin.py", line 42, in admin_token
marzban-1  |     client_ip = get_client_ip(request)
marzban-1  |   File "/code/app/views/admin.py", line 33, in get_client_ip
marzban-1  |     return request.client.host
marzban-1  | AttributeError: 'NoneType' object has no attribute 'host'

مشکل | باگ شماره 2 : پس از اپدیت به نسخه [v0.6.0] از نسخه [v0.5.2] اگه اکانتی لیمیت حجم یا اکسپایر شده باشه حتی با ریست کردن حجم و یا تغییر تاریخ دکمه ادیت کار نمیکنه ، به علت اینکه دکمه استاتوس بر روی حالت غیرفعال مانده (قبلا سویچ میکرد وقتی تاریخ یا حجم رو تغییر میدادید) و باید به صورت دستی دکمه استاتوس رو از حالت غیرفعال به حالت فعال سویچ کنی تا دکمه ادیت فعال و قابل کلیک بشه و سیو بشه عملیاتی که داشتید انجام میدادید

در حال حاضر مشکل | باگ شماره 1 رو با بازگشت به نسخه قبل یعنی  [v0.5.2] تونستم رفع و حل کنم 
 ولی مشکل | باگ شماره 2 همچنان پابرجاست
(حتی انیمشن دکمه فعال/غیرفعال درگوشی به درستی کار نمیکنه)
 حتی در پنل های دیگه که هنوز در نسخه  هستند [v0.6.0]
"ممنون از تمامی دست اندرکاران پروژه مرزبان به امید فردای بهتر"

**Comment by sarboy1371** [comment]
> پس از اپدیت از نسخه [v0.5.2] به نسخه [v0.6.0] با دو مورد باگ و مشکل رو به رو شدم به شرح زیر البته قبل از اون سیستم عامل و شرایطی که در اون مرزبان اجرا میشه رو بازگو میکنم ابونتو 22 دیتاسنتر OVH DNS : Google و Quad همه اپدیت ها و پیش نیاز ها به درستی نصب شده دیتابیس Sqlite نوع پنل تک پورت 443 وب سوکت نسخه ایکس ری v1.8.19 مشکل | باگ شماره 1 : پس از اپدیت امکان ورود به پنل چه با دامنه چه با ای پی به صورت مستقیم اصلا امکلن پذیر نبود و پس از بررسی لوگ متوجه شدم حین کلیک کردن بر روی دکمه لاگین این ارور به نمایش در میاد (به علت موارد امنیتی ای پی ها جایگذاری شدن) البته باید بگم اتصال اکانت ها مختل نشده بودند
> 
> marzban-1 | INFO: - "POST /api/admin/token HTTP/1.1" 500 Internal Server Error marzban-1 | ERROR: Exception in ASGI application marzban-1 | Traceback (most recent call last): marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi marzban-1 | result = await app( # type: ignore[func-returns-value] marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in **call** marzban-1 | return await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in **call** marzban-1 | await super().**call**(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in **call** marzban-1 | await self.middleware_stack(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** marzban-1 | await self.app(scope, receive, _send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in **call** marzban-1 | await self.simple_response(scope, receive, send, request_headers=headers) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** marzban-1 | await self.app(scope, receive, sender) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in **call** marzban-1 | raise e marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in **call** marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in **call** marzban-1 | await route.handle(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app marzban-1 | response = await func(request) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app marzban-1 | raw_response = await run_endpoint_function( marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function marzban-1 | return await run_in_threadpool(dependant.call, **values) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool marzban-1 | return await anyio.to_thread.run_sync(func, *args) marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync marzban-1 | return await get_asynclib().run_sync_in_worker_thread( marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread marzban-1 | return await future marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run marzban-1 | result = context.run(func, *args) marzban-1 | File "/code/app/views/admin.py", line 42, in admin_token marzban-1 | client_ip = get_client_ip(request) marzban-1 | File "/code/app/views/admin.py", line 33, in get_client_ip marzban-1 | return request.client.host marzban-1 | AttributeError: 'NoneType' object has no attribute 'host' nginx-1 | 192.168.1.1 - - [23/Jul/2024:14:21:58 +0000] "POST /api/admin/token HTTP/2.0" 500 21 "https://100.168.1.1/dashboard/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-" marzban-1 | INFO: - "POST /api/admin/token HTTP/1.1" 500 Internal Server Error marzban-1 | ERROR: Exception in ASGI application marzban-1 | Traceback (most recent call last): nginx-1 | 192.168.1.1 - - [23/Jul/2024:14:21:59 +0000] "POST /api/admin/token HTTP/2.0" 500 21 "https://100.168.1.1/dashboard/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-" marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi marzban-1 | result = await app( # type: ignore[func-returns-value] marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in **call** marzban-1 | return await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in **call** marzban-1 | await super().**call**(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in **call** marzban-1 | await self.middleware_stack(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** marzban-1 | await self.app(scope, receive, _send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in **call** marzban-1 | await self.simple_response(scope, receive, send, request_headers=headers) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** marzban-1 | await self.app(scope, receive, sender) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in **call** marzban-1 | raise e marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in **call** marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in **call** marzban-1 | await route.handle(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app marzban-1 | response = await func(request) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app marzban-1 | raw_response = await run_endpoint_function( marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function marzban-1 | return await run_in_threadpool(dependant.call, **values) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool marzban-1 | return await anyio.to_thread.run_sync(func, *args) marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync marzban-1 | return await get_asynclib().run_sync_in_worker_thread( marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread marzban-1 | return await future marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run marzban-1 | result = context.run(func, *args) marzban-1 | File "/code/app/views/admin.py", line 42, in admin_token marzban-1 | client_ip = get_client_ip(request) marzban-1 | File "/code/app/views/admin.py", line 33, in get_client_ip marzban-1 | return request.client.host marzban-1 | AttributeError: 'NoneType' object has no attribute 'host'
> 
> مشکل | باگ شماره 2 : پس از اپدیت به نسخه [v0.6.0] از نسخه [v0.5.2] اگه اکانتی لیمیت حجم یا اکسپایر شده باشه حتی با ریست کردن حجم و یا تغییر تاریخ دکمه ادیت کار نمیکنه ، به علت اینکه دکمه استاتوس بر روی حالت غیرفعال مانده (قبلا سویچ میکرد وقتی تاریخ یا حجم رو تغییر میدادید) و باید به صورت دستی دکمه استاتوس رو از حالت غیرفعال به حالت فعال سویچ کنی تا دکمه ادیت فعال و قابل کلیک بشه و سیو بشه عملیاتی که داشتید انجام میدادید
> 
> در حال حاضر مشکل | باگ شماره 1 رو با بازگشت به نسخه قبل یعنی [v0.5.2] تونستم رفع و حل کنم ولی مشکل | باگ شماره 2 همچنان پابرجاست (حتی انیمشن دکمه فعال/غیرفعال درگوشی به درستی کار نمیکنه) حتی در پنل های دیگه که هنوز در نسخه هستند [v0.6.0] "ممنون از تمامی دست اندرکاران پروژه مرزبان به امید فردای بهتر"

منم دقیقا همین دو مشکل رو دارم

**Comment by mamdali96** [comment]
> > پس از اپدیت از نسخه [v0.5.2] به نسخه [v0.6.0] با دو مورد باگ و مشکل رو به رو شدم به شرح زیر البته قبل از اون سیستم عامل و شرایطی که در اون مرزبان اجرا میشه رو بازگو میکنم ابونتو 22 دیتاسنتر OVH DNS : Google و Quad همه اپدیت ها و پیش نیاز ها به درستی نصب شده دیتابیس Sqlite نوع پنل تک پورت 443 وب سوکت نسخه ایکس ری v1.8.19 مشکل | باگ شماره 1 : پس از اپدیت امکان ورود به پنل چه با دامنه چه با ای پی به صورت مستقیم اصلا امکلن پذیر نبود و پس از بررسی لوگ متوجه شدم حین کلیک کردن بر روی دکمه لاگین این ارور به نمایش در میاد (به علت موارد امنیتی ای پی ها جایگذاری شدن) البته باید بگم اتصال اکانت ها مختل نشده بودند
> > marzban-1 | INFO: - "POST /api/admin/token HTTP/1.1" 500 Internal Server Error marzban-1 | ERROR: Exception in ASGI application marzban-1 | Traceback (most recent call last): marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi marzban-1 | result = await app( # type: ignore[func-returns-value] marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in **call** marzban-1 | return await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in **call** marzban-1 | await super().**call**(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in **call** marzban-1 | await self.middleware_stack(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** marzban-1 | await self.app(scope, receive, _send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in **call** marzban-1 | await self.simple_response(scope, receive, send, request_headers=headers) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** marzban-1 | await self.app(scope, receive, sender) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in **call** marzban-1 | raise e marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in **call** marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in **call** marzban-1 | await route.handle(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app marzban-1 | response = await func(request) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app marzban-1 | raw_response = await run_endpoint_function( marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function marzban-1 | return await run_in_threadpool(dependant.call, **values) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool marzban-1 | return await anyio.to_thread.run_sync(func, *args) marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync marzban-1 | return await get_asynclib().run_sync_in_worker_thread( marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread marzban-1 | return await future marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run marzban-1 | result = context.run(func, *args) marzban-1 | File "/code/app/views/admin.py", line 42, in admin_token marzban-1 | client_ip = get_client_ip(request) marzban-1 | File "/code/app/views/admin.py", line 33, in get_client_ip marzban-1 | return request.client.host marzban-1 | AttributeError: 'NoneType' object has no attribute 'host' nginx-1 | 192.168.1.1 - - [23/Jul/2024:14:21:58 +0000] "POST /api/admin/token HTTP/2.0" 500 21 "https://100.168.1.1/dashboard/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-" marzban-1 | INFO: - "POST /api/admin/token HTTP/1.1" 500 Internal Server Error marzban-1 | ERROR: Exception in ASGI application marzban-1 | Traceback (most recent call last): nginx-1 | 192.168.1.1 - - [23/Jul/2024:14:21:59 +0000] "POST /api/admin/token HTTP/2.0" 500 21 "https://100.168.1.1/dashboard/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-" marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi marzban-1 | result = await app( # type: ignore[func-returns-value] marzban-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in **call** marzban-1 | return await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in **call** marzban-1 | await super().**call**(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in **call** marzban-1 | await self.middleware_stack(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in **call** marzban-1 | await self.app(scope, receive, _send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in **call** marzban-1 | await self.simple_response(scope, receive, send, request_headers=headers) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in **call** marzban-1 | raise exc marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in **call** marzban-1 | await self.app(scope, receive, sender) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in **call** marzban-1 | raise e marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in **call** marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in **call** marzban-1 | await route.handle(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle marzban-1 | await self.app(scope, receive, send) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app marzban-1 | response = await func(request) marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app marzban-1 | raw_response = await run_endpoint_function( marzban-1 | File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function marzban-1 | return await run_in_threadpool(dependant.call, **values) marzban-1 | File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool marzban-1 | return await anyio.to_thread.run_sync(func, *args) marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync marzban-1 | return await get_asynclib().run_sync_in_worker_thread( marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread marzban-1 | return await future marzban-1 | File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run marzban-1 | result = context.run(func, *args) marzban-1 | File "/code/app/views/admin.py", line 42, in admin_token marzban-1 | client_ip = get_client_ip(request) marzban-1 | File "/code/app/views/admin.py", line 33, in get_client_ip marzban-1 | return request.client.host marzban-1 | AttributeError: 'NoneType' object has no attribute 'host'
> > مشکل | باگ شماره 2 : پس از اپدیت به نسخه [v0.6.0] از نسخه [v0.5.2] اگه اکانتی لیمیت حجم یا اکسپایر شده باشه حتی با ریست کردن حجم و یا تغییر تاریخ دکمه ادیت کار نمیکنه ، به علت اینکه دکمه استاتوس بر روی حالت غیرفعال مانده (قبلا سویچ میکرد وقتی تاریخ یا حجم رو تغییر میدادید) و باید به صورت دستی دکمه استاتوس رو از حالت غیرفعال به حالت فعال سویچ کنی تا دکمه ادیت فعال و قابل کلیک بشه و سیو بشه عملیاتی که داشتید انجام میدادید
> > در حال حاضر مشکل | باگ شماره 1 رو با بازگشت به نسخه قبل یعنی [v0.5.2] تونستم رفع و حل کنم ولی مشکل | باگ شماره 2 همچنان پابرجاست (حتی انیمشن دکمه فعال/غیرفعال درگوشی به درستی کار نمیکنه) حتی در پنل های دیگه که هنوز در نسخه هستند [v0.6.0] "ممنون از تمامی دست اندرکاران پروژه مرزبان به امید فردای بهتر"
> 
> چطوری دانگرید کنم به 5.2.منم دقیقا همین دو مشکل رو دارم

قابلیت و اموزش دانگرید به تازگی در کانال مرزبان نامه قرار داده شده " البته نیاز هستش که از اول بازسازی انجام بدی و بعد جا به جای دیتا"
یا میتونی از Docker Compose در پوشه ENV در قسمتی که یاد داشت شده Latest نسخه مورد نظر خود رو وارد کنی به صورت
v0.5.2

**Comment by echo-333** [comment]
منم تازه آپدیت کردم و دقیقا همین مشکلات رو دارم، شما موفق شدی حلش کنی؟

**Comment by echo-333** [comment]
دقیقا برای منم همین مشکلی پیش اومده

**Comment by janahnovin** [comment]
من هم همین مشکل دارم مجبور به دانگرید شدم

**Comment by erfjab** [comment]
درود و وقت بخیر دوستان عزیز.
این باگ در نسخه‌ی dev حل شده و به زودی ریلیز خواهد شد.
باگ شماره‌ی دو هم باگ نیس عزیز.
ایشو به خاطر فیکس شدن بسته میشه.

**Comment by echo-333** [comment]
دوست عزیز بعد از آپدیت دیروز همچنین این مشکل لاگین نکردن پا برجا هستش، و این ارور در لاگ دیده میشه
![IMG_8723](https://github.com/user-attachments/assets/d0d75004-1b2c-4fb8-a0ae-af9b01584dec)
