### ISSUE TITLE
Marzban doesn't include Host for Trojan Web socket

### ISSUE THREAD

**Issue by Kiya6955** [Gozargah/Marzban#1179]
Hi
When I set `Host` outside of header for Trojan Web socket inbounds no matter it's TLS or noTLS, marzban doesn't include host in configs and it leaves it empty so I have to set host manually in host settings.
Server inbound :
```
{
      "tag": "TROJAN WS Header NoTLs",
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "trojan",
      "settings": {
        "clients": []
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/",
          "host": "cloudflare.com"
        },
```
Generated Client inbound :
```
...
                "streamSettings": {
                    "network": "ws",
                    "security": "none",
                    "wsSettings": {
                        "headers": {},
                        "path": "/"
                    }
                }
...
```

**Comment by M03ED** [comment]
i check this and i didn't found any explanation for this, you can use hosts settings for now.
i will check it again in future.

**Comment by M03ED** [comment]
Fixed.

**Comment by Vahidf153** [comment]
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E01.1080p.WEB-DL.x264-ZarFilm.mkv?md5=jNu1pfmYCH_Kkjg4r-kpcw&u=893798&expires=1729901719
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E02.1080p.WEB-DL.x264-ZarFilm.mkv?md5=QigbHgDdEWHSZZJMzDDtNA&u=893798&expires=1729901719
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E03.1080p.WEB-DL.x264-ZarFilm.mkv?md5=PmVRSWMPK1ivCJcy6nc9Mg&u=893798&expires=1729901719
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E04.1080p.WEB-DL.x264-ZarFilm.mkv?md5=BTFBl9IcUoEtOow2VgymLg&u=893798&expires=1729901719
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E05.1080p.WEB-DL.x264-ZarFilm.mkv?md5=aN_DVeqwmhi9WRNQZrgN_g&u=893798&expires=1729901719
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E06.1080p.WEB-DL.x264-ZarFilm.mkv?md5=COI1jxQkCdFAvucBtUu0jQ&u=893798&expires=1729901719
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E07.1080p.WEB-DL.x264-ZarFilm.mkv?md5=i4h-UV0ZkjxgB96GIgFlcw&u=893798&expires=1729901719
https://dl1.linkro.info/Series3/Planet.Earth.III.2023/S01/1080p/Planet.Earth.III.S01E08.1080p.WEB-DL.x264-ZarFilm.mkv?md5=5rBFoxNUuwrBvywMoInqgw&u=893798&expires=1729901719
