### ISSUE TITLE
Example xray_config.json file for other transmissions ( grpc , kcp , tcp ,...)

### ISSUE THREAD

**Issue by Mrx-403** [Gozargah/Marzban#118]
سلام . از اونجایی که باید transmission  های مختلف برای inbound ها از فایل xray_config.json  تنظیم بشن و این کار برا مبتدی ها سخته لطفا یه فایل نمونه با تنظیمات برای این transmission  ها ارائه کنید تا کاربرا بتونن با مراجعه به اون تنظیمات رو انجام بدن . در حال حاضر فقط تنطیمات مربوط به ws تو این فایل به صورت دیفالت هست . 
ممنون .

**Comment by Elhwm** [comment]
@Mrx-403 نه

**Comment by Elhwm** [comment]
@Elhwm ثبت شد😂
