### ISSUE TITLE
The subscription link is not added to Singbox App

### ISSUE THREAD

**Issue by XuVix** [Gozargah/Marzban#1180]
In App

![Screenshot_20240724-013102_sing-box~2](https://github.com/user-attachments/assets/c4b6c4a5-b6e3-4061-92e0-99e6bf8e0af0)

In marzban Log

![Screenshot_20240724-013834_Termius~2](https://github.com/user-attachments/assets/84ad1ebe-1162-4684-adbc-2d58d89c914f)

![Screenshot_20240724-013808_Termius~2](https://github.com/user-attachments/assets/0f6d0bfc-0a7a-4718-8de2-a23dee9e5fea)

In browser add "/sing-box" 

![Screenshot_20240724-104645_Chrome~2](https://github.com/user-attachments/assets/e8ec8f18-386f-404f-97f4-7f382a43e76e)

**Comment by ImMohammad20000** [comment]
are you change default sing-box template?

**Comment by XuVix** [comment]
> are you change default sing-box template?

I also tested without a template

**Comment by XuVix** [comment]
https://github.com/Gozargah/Marzban/issues/1178

Something similar to this problem, but my problem is on Singbox sub

**Comment by M03ED** [comment]
> https://github.com/Gozargah/Marzban/issues/1178
> 
> Something similar to this problem, but my problem is on Singbox sub

These are different and your template is incorrect.
