### ISSUE TITLE
کانفیگ خالی (null)

### ISSUE THREAD

**Issue by soheylshorg** [Gozargah/Marzban#1183]
سلام !!

در اپدیت های اخیر در کانفیگ های داخل ساب کانفیگ خالی وجود داره با علامت null که روی بعضی کلاینت ها باعث آزار میشه و گاها کاربر به مشکل اتصال میخوره 

با تشکر از زحمات شما مدیران محترم مرزبان نامه

**Comment by ImMohammad20000** [comment]
سلام کدوم کلاینت و چه تایپ کانفیگی همچین مشکلی داره؟

**Comment by erfjab** [comment]
> داخل ساب یه کانفیگ null میاد بعضی کاربران که بلد نیستن کانفیگ انتخاب کنن با خطای اتصال مواجه میشن فقط همین چون داخل ساب یه کانفیگ null وجود داره همین 


بهتر در کلاینت های hiddify streisand v2rayNG V2rayN تست کنید و یه گزارشی بدید که نسبت به اون فیکس کنیم.

**Comment by RezaKardoost** [comment]
منم دقیقا بعد از آپدیت از 0.5.2 به 0.6.0  همین مشکل رو داشتم که مجبور شدم دوباره برگردم به 0.5.2
وقتی داخل پنل copy configs میزدم، علاوه بر کانفیگ هایی که خودم تعریف کرده بودم، اون  اخر یه مقدار بولین False هم بود.

باز اگر برای فیکس کردنش بهه اطلاعات بیشتری نیازه، دوباره به 0.6.0 اپدیت کنم

**Comment by M03ED** [comment]
Duplicate of #1166
