### ISSUE TITLE
problem with permanent report_login in v0.6.0

### ISSUE THREAD

**Issue by develfishere** [Gozargah/Marzban#1184]
Hello Marzban Team,

Thank you very much for keeping Marzban updated.

Recently, I updated my panel to version 0.6.0 and, upon reviewing the source code, I noticed that the login notification in the internal Telegram bot has been forcibly enabled without an option to disable it. This has caused issues for me and others who use external Telegram bots to manage accounts. These bots log into the panel every 30 seconds or less, resulting in a high volume of messages from Marzban's notification bot throughout the day.

I also observed that the environment variable to disable login notifications existed prior to version 0.6.0 but has been removed in recent commits. Could you please consider reinstating this option?

Thank you very much for your contribution.

**Comment by M03ED** [comment]
> Recently, I updated my panel to version 0.6.0 and, upon reviewing the source code, I noticed that the login notification in the internal Telegram bot has been forcibly enabled without an option to disable it. This has caused issues for me and others who use external Telegram bots to manage accounts. These bots log into the panel every 30 seconds or less, resulting in a high volume of messages from Marzban's notification bot throughout the day.

That's the worst code design you can do as a developer, there is a thing called token , you can just use that and when it is expired get a new one, also you can set the token expire to unlimited.

**Comment by mhmdh94** [comment]
> > Recently, I updated my panel to version 0.6.0 and, upon reviewing the source code, I noticed that the login notification in the internal Telegram bot has been forcibly enabled without an option to disable it. This has caused issues for me and others who use external Telegram bots to manage accounts. These bots log into the panel every 30 seconds or less, resulting in a high volume of messages from Marzban's notification bot throughout the day.
> 
> That's the worst code design you can do as a developer, there is a thing called token , you can just use that and when it is expired get a new one, also you can set the token expire to unlimited.

We have other notifications that matter to us in the logger channel, but since some management robots need to login multiple times for every action, it is spammed by them in the channel. perhaps we could have variables in the env to disable the whole thing  or just for some admins as exceptions ?
also, I didn't get how that token thing is related to these notification spams? could you elaborate ?

**Comment by M03ED** [comment]
Every time you login , you get a new token , that's what marzban uses for authentication
You can do everything with a single token.

**Comment by develfishere** [comment]
> > Recently, I updated my panel to version 0.6.0 and, upon reviewing the source code, I noticed that the login notification in the internal Telegram bot has been forcibly enabled without an option to disable it. This has caused issues for me and others who use external Telegram bots to manage accounts. These bots log into the panel every 30 seconds or less, resulting in a high volume of messages from Marzban's notification bot throughout the day.
> 
> That's the worst code design you can do as a developer, there is a thing called token , you can just use that and when it is expired get a new one, also you can set the token expire to unlimited.

Yes you are right.
