### ISSUE TITLE
تعداد کاربران انلاین،اپلود و دانلود لحظه ای سرور و تعداد کانکشن

### ISSUE THREAD

**Issue by Elhwm** [Gozargah/Marzban#119]
سلام و خسته نباشید به دولوپر عزیز،امکانش هست که مثله ایکس یوای تعداد کانکشن و کاربران و انلاین،وضعیت cpu و اپلود و دانلود لحظه ای سرور رو اضافه کنید؟ممنون

**Comment by shuvvan** [comment]
آیا کسی در این پروژه پاسخگوی سوالات هست؟!

**Comment by SaintShit** [comment]
@shuvvan درباره کاربر های آنلاین: https://github.com/Gozargah/Marzban/issues/116

باقی اضافه میشه
