### ISSUE TITLE
random_user_agent is enabled for all hosts

### ISSUE THREAD

**Issue by mdjvd** [Gozargah/Marzban#1198]
Hello,
With recent commits to dev branch (PRs merged from yesterday to today), I have encountered a new problem, which is that random_user_agent will be forcefully enabled for all hosts (except for Reality configs).
I have random_user_agent enabled for one host, But once I disable it for that host, the problem will be fixed.
I still don't know which commit created this issue, but I'll let you know once I find it.

**Comment by erfjab** [comment]
This problem of hosting clutter has been fixed, dear Javad, I will contact you from Telegram to check other cases.

**Comment by plasticgholam** [comment]
this bug is fixed in the regular configs with this pr but still persists in the customized ones! like in v2rayng customized configs :/

**Comment by M03ED** [comment]
Fixed
