### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by mahdiismailpuri** [Gozargah/Marzban#1200]
The client whose status was changed to limited mode, after increasing the data limit and changing its status to active mode, xray still rejected its connection. After re-editing the user with the same previous list [edit user], the problem was solved

This problem only happened once and I reproduced it

V 0.6.0 dev

**Comment by erfjab** [comment]
Did you make this change with the Marzban Front or the Marzban official bot?

**Comment by erfjab** [comment]
> You can edit disabled users with telegram bot for now. I have the same issue.

The user's inbound editing has a front-end bug that will be fixed soon.

**Comment by mahdiismailpuri** [comment]
The first change was made by the bot through the API But edit the user to fix the problem through the front

**Comment by erfjab** [comment]
> The first change was made by the bot through the API But edit the user to fix the problem through the front

So your bot has a problem.

**Comment by mahdiismailpuri** [comment]
> > The first change was made by the bot through the API But edit the user to fix the problem through the front
> 
> So your bot has a problem.

no After increasing the data, the user status limit was active in the panel But it prevented the user from connecting The bot has been working through the API for a long time, and this issue arose from the new DEV update

**Comment by erfjab** [comment]
> > > The first change was made by the bot through the API But edit the user to fix the problem through the front
> > 
> > So your bot has a problem.
> 
> no After increasing the data, the user status limit was active in the panel But it prevented the user from connecting The bot has been working through the API for a long time, and this issue arose from the new DEV update

Well, I'll check his commits and let you know the result.
Added to Tasks ✅

**Comment by sons-of-liberty** [comment]
I have the same issue. I think it happened after i added a new inbound and disabled it for all users. Though it doesnt happen for all users.
