### ISSUE TITLE
host headers and paths got messed up

### ISSUE THREAD

**Issue by plasticgholam** [Gozargah/Marzban#1201]
now in the same protocol inbounds with several hosts, all of the headers and paths got duplicated from the last config in the host settings.
it is really messy now!

**Comment by erfjab** [comment]
> now in the same protocol inbounds with several hosts, all of the headers and paths got duplicated from the last config in the host settings.
> it is really messy now!  

Pr #1197
Duplicate #1198

**Comment by fodhelper** [comment]
Switch from 'dev' to 'release', wait for fix

**Comment by plasticgholam** [comment]
> Switch from 'dev' to 'release', wait for fix

your post is unrelated to the solution or the bug!

**Comment by plasticgholam** [comment]
erfen pull request would only fixed it in the regular configs not in the cutomized ones.

https://github.com/Gozargah/Marzban/pull/1197

**Comment by plasticgholam** [comment]
this bug is fixed in the regular configs with this pr https://github.com/Gozargah/Marzban/pull/1197 but still persists in the customized ones! linke in v2rayng customized configs

**Comment by M03ED** [comment]
Fixed
