### ISSUE TITLE
ارور EOF بعد از ساخت اکانت با API روی بعضی از اینباندها

### ISSUE THREAD

**Issue by automa-gen** [Gozargah/Marzban#1205]
این مشکل رو با استفاده از صفحه OpenAPI مرزبان روی نسخه 0.6.0 تست کردیم و مشخص شد باگ هست. تو نسخه 0.5 یا 0.6 به وجود اومده. اگر یه ریکوئست POST به این شکل بزنم برای ایجاد یوزر جدید:

{ "username": "user1234", "proxies": { "vmess": {}, "vless": {} }, "inbounds": { "vmess": [ "VMess Websocket" ], "vless": [ "Legacy", "de+usd" ] }, "expire": 0, "data_limit": 0, "status": "active", "note": "Test1234" }

کانفیگهای ویلس همه EOF میزنن ولی ویمسها وصل میشن.
اما اگر ریکوئست POST برای ایجاد یوزر رو اینجوری بزنم که همه اینباندها انتخاب بشن:

{ "username": "user1234", "proxies": { "vmess": {}, "vless": {} }, "inbounds": { "vmess": [ ], "vless": [ ] }, "expire": 0, "data_limit": 0, "status": "active", "note": "Test1234" }

این بار دقیقا همون کانفیگها میان توی ساب ولی همه کار میکنن و پینگ میدن.

**Comment by waxilu** [comment]
`"proxies":{"vless":"","vmess":""},"inbounds":{"vless":["Legacy", "de+usd"],{"vmess":["VMess Websocket"]}`

**Comment by automa-gen** [comment]
> `"proxies":{"vless":"","vmess":""},"inbounds":{"vless":["Legacy", "de+usd"],{"vmess":["VMess Websocket"]}`

نمونه دیفالت روی OpenAPI مرزبان به این شکله:

```
{
  "username": "user1234",
  "proxies": {
    "vmess": {
      "id": "35e4e39c-7d5c-4f4b-8b71-558e4f37ff53"
    },
    "vless": {}
  },
  "inbounds": {
    "vmess": [
      "VMess TCP",
      "VMess Websocket"
    ],
    "vless": [
      "VLESS TCP REALITY",
      "VLESS GRPC REALITY"
    ]
  },
  "expire": 0,
  "data_limit": 0,
  "data_limit_reset_strategy": "no_reset",
  "status": "active",
  "note": "",
  "on_hold_timeout": "2023-11-03T20:30:00",
  "on_hold_expire_duration": 0
}
```

یعنی تغییر کرده؟

**Comment by automa-gen** [comment]
مشکل پیدا شد. باگ از مرزبان نبود. مشکل اینجا بود که کاربر کانفیگ مربوط به اینباند رو زیر مجموعه اینباند دیگه قرار داده بود توی قسمت Host settings. بعد موقع ساخت یوزر اینباندی که کانفیگی نداشت ولی برای کانفیگهای دیگه لازم نبود رو انتخاب نمیکرد.
