### ISSUE TITLE
quic inbound 

### ISSUE THREAD

**Issue by P3YM4N3** [Gozargah/Marzban#1212]
Hello, I place this inbound sample inside the Core and there is no problem. But there is a point: if I manually enter the config, there is no problem, but it does not enter the client along with the Subscription. I would appreciate it if you could check this. Thank you

v0.6.0

  {
     "tag": "Quic",
     "listen": "0.0.0.0",
     "port": 8880,
     "protocol": "vless",
      "settings": {
      "clients": [],
     "decryption": "none"
    },
     "streamSettings": {
       "network": "quic",
        "quicSettings": {
          "header": {
           "type": "wireguard"
         },
      "key": "B4dt632ZJd",
      "security": "chacha20-poly1305"
     },
    "security": "none"
   },
       "sniffing": {
       "enabled": true,
      "destOverride": [
         "http",
         "tls",
        "quic"
       ]
    }
 }

**Comment by M03ED** [comment]
This should be ok on the dev branch.

**Comment by P3YM4N3** [comment]
Thank you for your response. However, I did not get any results on the dev image either, and the subscription does not enter into the client

> This should be ok on the dev branch.

**Comment by M03ED** [comment]
Dev branch updated last night, do you test that ?

**Comment by P3YM4N3** [comment]
> Dev branch updated last night, do you test that ?

I am testing it now and will let you know the result.

**Comment by P3YM4N3** [comment]
> > Dev branch updated last night, do you test that ?
> 
> I am testing it now and will let you know the result.

I tested it, the issue still persists.

**Comment by M03ED** [comment]
> > > Dev branch updated last night, do you test that ?
> > 
> > 
> > I am testing it now and will let you know the result.
> 
> I tested it, the issue still persists.

can you send marzban output and correct output ?

**Comment by P3YM4N3** [comment]
> > > > Dev branch updated last night, do you test that ?
> > > 
> > > 
> > > I am testing it now and will let you know the result.
> > 
> > 
> > I tested it, the issue still persists.
> 
> can you send marzban output and correct output ?

Before updating to the new dev version, the issue was that if I added this inbound, the whole subscription would face problems and I would get a failure.But after updating to the latest dev version that you mentioned was released last night, this failure issue with the subscription link has been resolved. However, the QUIC configuration along with the subscription is not being applied to the program.Is there anything else I should do? I will report the results back to you.What did you mean by Marzban output?

**Comment by M03ED** [comment]
> Before updating to the new dev version, the issue was that if I added this inbound, the whole subscription would face problems and I would get a failure.But after updating to the latest dev version that you mentioned was released last night, this failure issue with the subscription link has been resolved. However, the QUIC configuration along with the subscription is not being applied to the program.Is there anything else I should do? I will report the results back to you.What did you mean by Marzban output?

i test it local now and output looks correct
```json
            {
                "protocol": "vless",
                "settings": {
                    "vnext": [
                        {
                            "address": "11.1.1.1",
                            "port": 8880,
                            "users": [
                                {
                                    "id": "73879356-2f1c-4f52-b723-8d1bc5ea0419",
                                    "security": "auto",
                                    "encryption": "none",
                                    "email": "https://gozargah.github.io/marzban/",
                                    "alterId": 0,
                                    "flow": ""
                                }
                            ]
                        }
                    ]
                },
                "streamSettings": {
                    "network": "quic",
                    "quicSettings": {
                        "security": "chacha20-poly1305",
                        "header": {
                            "type": "wireguard"
                        },
                        "key": "B4dt632ZJd"
                    }
                }
            }
            ```

**Comment by P3YM4N3** [comment]
> > Before updating to the new dev version, the issue was that if I added this inbound, the whole subscription would face problems and I would get a failure.But after updating to the latest dev version that you mentioned was released last night, this failure issue with the subscription link has been resolved. However, the QUIC configuration along with the subscription is not being applied to the program.Is there anything else I should do? I will report the results back to you.What did you mean by Marzban output?
> 
> i test it local now and output looks correct
> 
> ```json
>             {
>                 "protocol": "vless",
>                 "settings": {
>                     "vnext": [
>                         {
>                             "address": "11.1.1.1",
>                             "port": 8880,
>                             "users": [
>                                 {
>                                     "id": "73879356-2f1c-4f52-b723-8d1bc5ea0419",
>                                     "security": "auto",
>                                     "encryption": "none",
>                                     "email": "https://gozargah.github.io/marzban/",
>                                     "alterId": 0,
>                                     "flow": ""
>                                 }
>                             ]
>                         }
>                     ]
>                 },
>                 "streamSettings": {
>                     "network": "quic",
>                     "quicSettings": {
>                         "security": "chacha20-poly1305",
>                         "header": {
>                             "type": "wireguard"
>                         },
>                         "key": "B4dt632ZJd"
>                     }
>                 }
>             }
> ```

That's right, it's not a problem But with the subscription link It does not enter the client

**Comment by M03ED** [comment]
its ok for me and i get output right in client

**Comment by M03ED** [comment]
i test this and there is no problem , we get configs correct and there is no problem in dev version for quic , if you have any other problem provide fore spacefic detail
