### ISSUE TITLE
ضریب اینباند (inbound coefficient)

### ISSUE THREAD

**Issue by MrR4di0k4l** [Gozargah/Marzban#1213]
اضافه کردن ضریب برای یک اینباند که بتونی یه ضریبی تعیین کنی که ترافیک رو بسته به اون ضریب حساب کنه
مثلا شاید از نود مرزبان واسه تونل استفاده نکنی و تونل ریورس بزنی  بین دو سرور  یا کلا بخوای یه اینباند حتی بدون تونل بیشتر ترافیکش حساب بشه در کل چیز جالب و خوبی هست ممنون میشم PR کنید.

Adding a coefficient for an inbound so that you can set a coefficient that will calculate the traffic depending on that coefficient
For example, maybe you don't use Marzban node for the tunnel and make a reverse tunnel between two servers, or you want an inbound even without a tunnel, most of the traffic will be counted. In general, it's an interesting and good thing. Thank you for PR.

**Comment by M03ED** [comment]
چنین چیزی در ساختار فعلی ایکس ری ممکن نیست

**Comment by MrR4di0k4l** [comment]
خوب ساختار ضریب نود چطوریه که میشه ضریب گذاشت ؟

**Comment by erfjab** [comment]
>  خوب ساختار ضریب نود چطوریه که میشه ضریب گذاشت ؟
>  اگر بخوایم تانل ریویس بزنیم میشه با نود اوکی کرد که از ضریب اون استفاده کنیم؟
>  راهکاری میشه پیشنهاد بدید

درود و وقت بخیر، از طریق api ها و یا از طریق فرانت نسخه‌ی 6 مرزبان میتونید ضریب نود بزارید که هر مصرفی از کانفیگ های اون نود رو ضرب در عددی که مشخص میکنید حساب میکنه. مثلا 1.5 2.3 5.0... چیز خاصی نیست. راحته.

**Comment by MrR4di0k4l** [comment]
نه منظورم متوجه نشدید با نود میشه تانل ریورس زد که از این قابلیت استفاده کرد ؟

**Comment by erfjab** [comment]
> نه منظورم متوجه نشدید با نود میشه تانل ریورس زد که از این قابلیت استفاده کرد ؟

چرا نشه.

**Comment by MrR4di0k4l** [comment]
میشه بیشتر راهنمایی کنید یا رفرنسی بدید 
مثلا تانل رتهول روی دو سرور ایران و خارج رانه چطور این کار کنیم؟

**Comment by M03ED** [comment]
> میشه بیشتر راهنمایی کنید یا رفرنسی بدید 
> مثلا تانل رتهول روی دو سرور ایران و خارج رانه چطور این کار کنیم؟

این مورد اصلا هیچ ربطی به نوع تانل و غیره نداره ، فقط روی مرزبان اعمال میشه

**Comment by erfjab** [comment]
> میشه بیشتر راهنمایی کنید یا رفرنسی بدید 
> مثلا تانل رتهول روی دو سرور ایران و خارج رانه چطور این کار کنیم؟

عزیز دل شما به نود ضریب میدید، حالا رو اون نود رتهول بزنید، ریلیتی بزنید، هرچی بزنید بهتون گفتم که دیتای مصرفی اون نود با ضریبی که مشخص کردید محاسبه میشه. قضیه رو خیلی گنگ نکنید. مرزبان رو به نسخه‌ی 6 آپدیت کنید تو فرانت می‌بینید.

**Comment by MrR4di0k4l** [comment]
ممنون تست میکنم
