### ISSUE TITLE
Custom Volume for each Inbound

### ISSUE THREAD

**Issue by amirhr098** [Gozargah/Marzban#1215]
یک مشکلی که من خودم دارم این هست که برای بعضی از کاربرها میخوام سرویس تانل قرار بدم اما به دلیل گرون بودن، میخوام حجم کمی بهشون بدم که فقط در مواقعی که اختلال زیاد هست متصل بشن.
در حال حاضر برای هر یوزر امکان تعیین محدودیت حجم به صورت کلی هست و این حجم هم مجموعه استفاده کاربر از همه ایننباند ها هست. اگه بشه یک ویژگی‌ای اضافه کرد که برای یک اینباند خاص، حجم متفاوتی تعیین کرد خیلی خوب میشه. این حجم هم میتونی روی حجم کلی اون کاربر محاسبه بشه یا نشه که خب اینم میتونی یه گزینه جدا باشه که بشه انتخاب کرد.
خیلی ممنون بابت این همه زحمتی که کشیدید واقعا.

**Comment by M03ED** [comment]
به جای این کار میتونید ضریب مصرف یک نود خاص رو بالاتر ببرید و از اون برای تانل استفاده کنید ، نیاز به انجام چنین تغییرات پیچیده ای نیست.

**Comment by erfjab** [comment]
درود و وقت بخیر، قابلیت خوبی هست و در حاضر طبق حرف موسد عزیز ما راه حل ضریب نود را داریم ،راه حل external config داریم که شما میتوانید در مواقع قطعی یک کانفیگ موقت تانل به ساب کاربران وارد کنید. اما بازم من برای راه حل های بهتر فکری خواهم کرد. در حال حاضر اولویت های دیگری داریم، آینده روش کار خواهم کرد.

**Comment by erfjab** [comment]
خودم رو تگ کردم، بعدا بتونم پیداش کنم.
