### ISSUE TITLE
مشکل اتصال اپراتور همراه اول

### ISSUE THREAD

**Issue by MatinSenPai** [Gozargah/Marzban#1216]
دوستان من زمانی که پینگ میگیرم با CMD، کاملا هم آیپی هم دامنه اوکیه ولی نه پنل واسم با همراه اول بالا میاد، نه سرورها واسم کار میکنه. با آیپی مستقیم هم پنل بالا نمیاد روی همراه اول.
خیلی اوکی میتونم ssh بزنم بهش با اینترنت همراه اول، 
اما پنل X-UI رو هم که نصب کردم همین شکلی بود
راهی هست واسه‌ی این قضیه که این محدودیت همراه اول رو دور بزنیم؟

**Comment by M03ED** [comment]
اینگونه موارد به مرزبان ربطی نداره ، لطفاً از باز کردن issue برای این گونه موارد خوددداری کنید ، برای این موارد میتونید گروه تلگرام استفاده کنید.
