### ISSUE TITLE
Usage Ratio

### ISSUE THREAD

**Issue by Sajjad-Asad** [Gozargah/Marzban#1217]
سلام و عرض خسته نباشید.

خیلی خوب میشه اگه Usage Ratio رو از Node Settings به Host Settings انتقال بدید تا بشه برای هر کانفیگی ضریب خاص خودش رو گذاشت

این کار باعث میشه بتونیم روی یک نود چندین کانفیگ با ضرب های مختلف داشته باشیم

ممنون از همه زحمات شما❤️

**Comment by erfjab** [comment]
> سلام و عرض خسته نباشید.
> 
> خیلی خوب میشه اگه Usage Ratio رو از Node Settings به Host Settings انتقال بدید تا بشه برای هر کانفیگی ضریب خاص خودش رو گذاشت
> 
> این کار باعث میشه بتونیم روی یک نود چندین کانفیگ با ضرب های مختلف داشته باشیم
> 
> ممنون از همه زحمات شما❤️

درود و وقت بخیر، ساختار حاضر ایکس ری همچین امکانی نداره،بجاش میتوانید از ضریب نود استفاده کنید. اگر در آینده ایکس ری شرایطی برای این قابلیت در اختیار مون گذاشت حتما اضافه خواهیم کرد.
