### ISSUE TITLE
Telebot Template

### ISSUE THREAD

**Issue by mhmdh94** [Gozargah/Marzban#1228]
after update to 0.6.0, also on dev version, we can not create users from templates that were working on previous builds.

this is the error I get in logs
![image](https://github.com/user-attachments/assets/b23e13a4-7cbf-42a6-add0-d1b5ac887f46)

and these are the templates that were working fine before.
![image](https://github.com/user-attachments/assets/8398d7b3-bf14-4b9f-99d3-581b03443f87)

**Comment by erfjab** [comment]
We are refactoring the Telegram bot, but we will check and fix this bug. Thanks for your report.

**Comment by mhmdh94** [comment]
@erfjab 
another issue is that we don't get a notification in logger channel when we create a user from the bot.
works for deleting a user but not creating one.

**Comment by erfjab** [comment]
> @erfjab 
> another issue is that we don't get a notification in logger channel when we create a user from the bot.
> works for deleting a user but not creating one.

was added to my tasks. ✅
