### ISSUE TITLE
showing each none sudo Admin its used traffic

### ISSUE THREAD

**Issue by iyf577ge6** [Gozargah/Marzban#1229]
Greetings 

it would be great that each none sudo admin will be able to see its users traffic spent instead of all Admins in the main panel.

thanks

**Comment by erfjab** [comment]
Those statistics are based on the system and have nothing to do with the admins.

**Comment by erfjab** [comment]
But we can add it in the future.

**Comment by iyf577ge6** [comment]
thanks
