### ISSUE TITLE
کاستوم کانفیگ 

### ISSUE THREAD

**Issue by Nima786** [Gozargah/Marzban#1236]
سلام، امروز مرزبان رو ست کردم که کاستوم کانفیگ‌ بزنم و فرگمنت رو برای کانفیگ های CDN فعال کنم، بدون مشکل انجام شد ولی بعدش متوجه شدم کانفیگهای مستقیم vless tcp no header دیگه کار نمیکنن، بعد از کلی جستجو متوجه شدم، موقع تبدیل کانفیگ ها به کاستوم ، کانفیگهای مستقیم که هدر نداشتن و بهتره بگم type اونها none بود، در کاستوم کانفیگ ها این type خود بخود تبدیل شده به http و به همین دلیل دیگه کانفیگ ها کار نمیکنن، و راه حلش هم این بود که توی تنظیمات کور اینباند برم type رو از none به http تغییر بدم که با کانفیگ های کاستوم مچ بشن.
لطفاً این مورد رو بررسی بفرمایید که چرا این تغییر خود بخود بوجود میاد توی کاستوم کانفیگ ها.
ممنون

**Comment by M03ED** [comment]
duplicate #1222
