### ISSUE TITLE
scam notification 

### ISSUE THREAD

**Issue by esodrevo** [Gozargah/Marzban#1239]
سلام خسته نباشید ، ربات تلگرامی خود مرزبان بصورت مداوم و پشت سر هم داره پیام لاگ این میفرسته، با ای پی سرور پنل ، هیچ اسکریپت جانبی هم ندارم رو سرور ، پنلمم به اخرین نسخه dev اپدیت هست.
![IMG_20240811_181709_933](https://github.com/user-attachments/assets/2cc4f16a-f181-4c03-922a-e481ffb4260a)

**Comment by erfjab** [comment]
درود و وقت بخیر
این مورد باگ نداره، لطفا از وجود اسکریپت و یا باتی مطمئن شوید و خاموش کنید.

**Comment by esodrevo** [comment]
تنها اسکریپت اضافه ، بکاپ ac-lover , و ربات هولدربات شماست، هروقتی اینجوری قفلی داره پیام میفرسته اخرش مرزبان رو ریستارت میکنم

**Comment by M03ED** [comment]
> تنها اسکریپت اضافه ، بکاپ ac-lover , و ربات هولدربات شماست، هروقتی اینجوری قفلی داره پیام میفرسته اخرش مرزبان رو ریستارت میکنم

دلیل همون هولدر بات هست

**Comment by erfjab** [comment]
> تنها اسکریپت اضافه ، بکاپ ac-lover , و ربات هولدربات شماست، هروقتی اینجوری قفلی داره پیام میفرسته اخرش مرزبان رو ریستارت میکنم

خب عزیز پس اسکریپت جانبی دارید. 😄
در #1185 راجب این مسئله گفته بودم، حتی برای اینکه استفاده نشه سورس هولدربات رو از دسترس خارج کرده بودم. مانیتورینگ نود و نوتیس رو خاموش کنید مشکل‌تون حل میشه.

**Comment by esodrevo** [comment]
بله خیلی ممنون مطالعه کردم🤍 دمتون گرم
