### ISSUE TITLE
اضافه کردن ریست ترافیک مصرفی کاربر

### ISSUE THREAD

**Issue by alirezaraz21** [Gozargah/Marzban#124]
سلام

اول اینکه تشکر میکنم بابت پنل بینظیرتون
 دوم اگر بتونید امکان ریست کرد ترافیک رو هم از داخل پنل و هم از طریق API اضافه کنید خیلی خوب میشه و اینکه ربات تلگرام رو من هرکار کردم نتونستم استفاده کنم به گمونم باید پیش نیاز های ربات رو بگید که نصب کنیم 

امیدوارم پیامم دیده بشه و جوابی بدید بهش 😁😁

**Comment by MuhammadAshouri** [comment]
@alirezaraz21 ریست ترافیک که هستش

**Comment by alirezaraz21** [comment]
> @MuhammadAshouri  میشه راهنمایی کنید کجاست چون من پیدا نکردم نه داخل پنل و نه API

**Comment by MuhammadAshouri** [comment]
@alirezaraz21 توی API:
/api/user/{username}/reset
توی پنل هم روی یوزر که بزنی کنار آیکون دلیت نوشته reset usage

**Comment by alirezaraz21** [comment]
> @alirezaraz21 توی API: /api/user/{username}/reset توی پنل هم روی یوزر که بزنی کنار آیکون دلیت نوشته reset usage

والا من همچین لینکی رو توی داکیومنت ندیدم برای ریست توسط api 
و قسمت ریست از داخل پنل هم که گفتید میاد کاربر رو کامل پاک میکنه من اینو نمیخوام میخوام که ترافیکی که استفاده کرده مجدد صفر بشه

**Comment by MuhammadAshouri** [comment]
هردو رو پیوست میکنم بررسی کنید
![marzban-panel](https://user-images.githubusercontent.com/38324227/227635564-e619ef4f-9f98-4a93-80e6-ae5467989911.png)
![marzban-api](https://user-images.githubusercontent.com/38324227/227635592-0d5b2eac-df4a-40d1-8e48-d62dd3402f9e.jpg)

**Comment by SaintShit** [comment]
@alirezaraz21 این قابلیت از ورژن ۰.۲.۰ اضافه شده. پنل خودتون رو آپدیت کنید. برای راهنمایی میتونید توی گروه تلگرام عضو شید.
