### ISSUE TITLE
اینباند cdn کلود فلر

### ISSUE THREAD

**Issue by Mo3tafakhodsetan** [Gozargah/Marzban#1240]
سلام عزیزان
کسی اینباند برای استفاده cdn کلود فلر آماده داره بفرسته همینجا ؟
httpupgrade

**Comment by M03ED** [comment]
بخش issue برای اینگونه موارد نیست

**Comment by erfjab** [comment]
> سلام عزیزان
> کسی اینباند برای استفاده cdn کلود فلر آماده داره بفرسته همینجا ؟
> httpupgrade 
> 

درود و وقت بخیر
موسد درست میگه اینجا، جای این موارد نیست.
ولی میتوانید از طریق داکیومنت رسمی مرزبان و این پروژه dds اینباند رو بسازید.
https://gozargah.github.io/marzban/fa/docs/xray-inbounds

https://azavaxhuman.github.io/MarzbanInboundGenerator/v2/
