### ISSUE TITLE
multi sni & host

### ISSUE THREAD

**Issue by sirvan32** [Gozargah/Marzban#1241]
میخوام چند تا دامین به هاست و sni اضافه کنم که هر بار مرزبان رندوم یکی از هاست ها و sni ها رو جایگزین کنه که به این صورت عمل میکنم؛
 host;
x.com,y.com,z.com

sni;
x.com,y.com,z.com

ولی کانفیگ در صورتی عمل میکند که دامین x همزمان در کانفیگ هم هاست باشد هم sni. ولی مرزبان هر بار رندوم یکی‌از دامنه ها را در کانفیگ قرار میده که باعث میشه کانفیگ عمل نکنه.
امکانش هست که به صورت رندوم دامین x هاست رو با دامین ایکس sni و دامین y رو هم به ترتیب با y ست کنه؟

**Comment by erfjab** [comment]
> میخوام چند تا دامین به هاست و sni اضافه کنم که هر بار مرزبان رندوم یکی از هاست ها و sni ها رو جایگزین کنه که به این صورت عمل میکنم؛
>  host;
> x.com,y.com,z.com
> 
> sni;
> x.com,y.com,z.com
> 
> ولی کانفیگ در صورتی عمل میکند که دامین x همزمان در کانفیگ هم هاست باشد هم sni. ولی مرزبان هر بار رندوم یکی‌از دامنه ها را در کانفیگ قرار میده که باعث میشه کانفیگ عمل نکنه.
> امکانش هست که به صورت رندوم دامین x هاست رو با دامین ایکس sni و دامین y رو هم به ترتیب با y ست کنه؟

درود، یه pr برای این مورد زده شده عزیز. به زودی بررسی میشه، اوکی نبود خودم اضافه میکنم.

**Comment by erfjab** [comment]
ایشو رو میبندم چون تکراریه.
