### ISSUE TITLE
شخصی سازی مصرف هر کانفیگ 

### ISSUE THREAD

**Issue by mobohes** [Gozargah/Marzban#1244]
در حال حاظر پنل قابلیت اینو داره که مصرف هر کاربر رو روی حجم دلخواهمون به صورت روزانه یا بیشتر تنظیم کنیم تا مصرف کاربر ریست بشه، این قابلیت در حال حاظر خوبه اما روی تمام کانفیگ ها اعمال میشه

شما تصور کنید من از این ۱۰ گیگ حجم روزانه ای که به کاربرم اختصاص دادم، میخوام ۸ گیگشو بین چند تا کانفیگ تقسیم کنم و ۲ گیگش رو هم بین مثلا یک کانفیگ، یعنی بتونم همین ۱۰ گیگ روزانه رو تعین کنم که برای کدوم کانفیگ ها استفاده بشه

مثلا من دو مدل کانفیگ دارم: x و y
مجوعا ۱۰ گیگ برای مصرف کلی کانفیگ ها تعریف کردم
حالا بیام تو تب پایین تعیین کنم که این ۱۰ گیگ چطوری بین کانفیگ ها تقسیم بشه
مثلا نهایت ۸ گیگ کانفیگ x بتونه مصرف بشه و ۲ گیگ کانفیگ y 
کاربر این وسط ممکنه کانفیگ ۲ گیگش زود تموم بشه و کانفیگ های مربوطش قطع بشن ولی خب طبیعیه که بره سراغ بقیه کانفیگ ها که حجم روزانه بیشتری دارند و از اونا استفاده کنه

اینطوری فروشنده ها میتونن حجم ۱۰ گیگ روزانه کاربر رو بهتر مدیریت کنن
و عمده مصرف همین ۱۰ گیگ رو بیشتر به یک کانفیگ یا چندین کانفیگ اختصاص بدن

در مورد نحوه نمایشش هم میتونن کاربران تو قسمت نام کانفیگشون نشون بدن که از ۲ گیگ مثلا چقدر استفاده شده ( یعنی بتونن روی خود کانفیگ خورده مصرفشونو ببینن یا یک یا چند  کانفیگ غیر فعال تعبیه کنن و داخل اون بنویسن از ۲ گیگ کانفیگ x انقدر مصرف داشته و داخل کانفیگ دیگر هم اون یکی رو نوشته بشه که از مثلا ۸ گیگ چقدر مصرف شده ، مجموع اینا هم داخل لینک ساب نمایش داده بشه

در کل این به نظرم یکی از انقلابی ترین آپدیت های پنل مرزبان میتونه باشه، امیدوارم کامل توضیح داده باشم، با تشکر از تمام زحماتتون❤

**Comment by erfjab** [comment]
درود و وقت بخیر
با ساختار فعلی ایکس ری همچین چیزی امکان پذیر نیست.

**Comment by mobohes** [comment]
> درود و وقت بخیر با ساختار فعلی ایکس ری همچین چیزی امکان پذیر نیست.

عزیز چرا امکان پذیر نباشه؟
میشه نهایت دو تا uuid برای یک لینک اختصال داد و برای هر کدوم حجم مصرفی روزانه تعیین کنیم و مجموع اینها داخل لینک نمایش داده بشه درست مثل چیزی که گفتم
پس نهایتا با تعدد uuid امکان پذیره

**Comment by erfjab** [comment]
> > درود و وقت بخیر با ساختار فعلی ایکس ری همچین چیزی امکان پذیر نیست.
> 
> عزیز چرا امکان پذیر نباشه؟
> میشه نهایت دو تا uuid برای یک لینک اختصال داد و برای هر کدوم حجم مصرفی روزانه تعیین کنیم و مجموع اینها داخل لینک نمایش داده بشه درست مثل چیزی که گفتم
> پس نهایتا با تعدد uuid امکان پذیره
> 

میشه اول بگید کدوم مشکل کامیونیتی مرزبان رو حل می‌کنه؟

**Comment by mobohes** [comment]
> > > درود و وقت بخیر با ساختار فعلی ایکس ری همچین چیزی امکان پذیر نیست.
> > 
> > 
> > عزیز چرا امکان پذیر نباشه؟
> > میشه نهایت دو تا uuid برای یک لینک اختصال داد و برای هر کدوم حجم مصرفی روزانه تعیین کنیم و مجموع اینها داخل لینک نمایش داده بشه درست مثل چیزی که گفتم
> > پس نهایتا با تعدد uuid امکان پذیره
> 
> میشه اول بگید کدوم مشکل کامیونیتی مرزبان رو حل می‌کنه؟

عزیز اگر کسی هم تو کانفیگاش مستقیم گذاشته باشه هم تانل
میتونه حجم کمتری از مصرف روزانه هر کاربرو به تانل ها اختصاص بده تا هم مصرف کانفیگ های تانل از سمت کاربر کمتر بشه و هم به این شکل قیمت تموم شده برای فروشنده خیلی پایین تر بیاد
طبیعتا وقتی همچین لیمیتی پیاده نشه
ممکنه اکثر کاربرا فقط از کانفیگ های تانل استفاده کنن و فروشنده هم مجبور قیمت سرویس رو بالاتر بزاره تا اگر همه با تانلا متصل بودن براش ضرر نداشته باشه، ولی وقتی این قابلیت وجود داشته باشه، فروشنده دستش تو پایین آوردن قیمت باز تره

حتی تصور کنید فقط یک فروشنده کانفیگ های تانل داره با چندین لوکیشن مختلف
ممکن هست بعضی از این سرورا ترافیک های محدودی داشته باشن یا هزینه هر ترا ترافیکش براشون خیلی گرون تر باشه
وقتی این قابلیت باشه میتونن مثلا از 10 گیگ حجم روزانه فقط 5 گیگشو به سرور آلمان اختصاص بدن و باقیشو به سرور های دیگه که uuid متفاوتی دارند

**Comment by erfjab** [comment]
خب ضریب نود مشکلات شمارو برطرف میکنه.

**Comment by mobohes** [comment]
> خب ضریب نود مشکلات شمارو برطرف میکنه.

بله حق با شماست ، ممنون از پیشنهادتون من ضریب نود رو اصلا در خاطر نداشتم
البته اینکه من گفتم هم شیوه جالبی بود ولی خب مهم اینه که الان از طریق راه حل شما راحت تر قابل اجراس
با تشکر از پاسخ گویی شما❤

**Comment by mobohes** [comment]
> خب ضریب نود مشکلات شمارو برطرف میکنه.

عزیز الان متوجه شدم که این ضریب نود یک محدودیتی داره اونم اینکه همه کانفیگ های روی اون نود این ضریب اعمال میشه که خب ممکنه من بخوام با یک نودم یک کانفیگ مستقیم بسازم و یک کانفیگ تانل و فقط بخوام کانفیگ تانل رو محدود کنم
برای محدود کردن تعدادی از کانفیگ های نود (نه همشون) فکر میکنم راهکاری که من دادم خیلی عالی باشه، در صورتی که خودتون راهکار دیگه ای دارید خوشحال میشم بهم بگید🙏

**Comment by erfjab** [comment]
تیم الان درگیر مسئله های دیگه هست عزیز، نمیتونیم اون تغییرات مدنظر شما که مربوط به اکثر کامیونیتی مرزبان هم نیست در اولویت قرار دهیم.

**Comment by mobohes** [comment]
> > خب ضریب نود مشکلات شمارو برطرف میکنه.
> 
> عزیز الان متوجه شدم که این ضریب نود یک محدودیتی داره اونم اینکه همه کانفیگ های روی اون نود این ضریب براش اعمال میشه که خب ممکنه من بخوام با یک نودم یک کانفیگ مستقیم بسازم و یک کانفیگ تانل و فقط بخوام کانفیگ تانل رو محدود کنم برای محدود کردن تعدادی از کانفیگ های نود (نه همشون) فکر میکنم راهکاری که من دادم خیلی عالی باشه، در صورتی که خودتون راهکار دیگر و بهتری دارید خوشحال میشم بهم بگید🙏

یک ایده دیگر هم دارم برای رفع این موضوع اونم تعدد نود ها از یک سرور هست
یعنی از یک سرور بیشتر از یک نود به پنل مستر اختصاص بدیم و تعین کنیم هر نود وظیفه محاسبه کدوم کانفیگ هارو داشته باشه و اینطوری میتونم ضریب دلخواهمونو بهش بدیم تا فقط کانفیگ های مشخص شده برای اون نود را محاسبه کنه، فکر میکنم این پیشنهاد بهتر از پیشنهاد اولم باشه
امیدوارم خوب توضیح داده یاشم که منظورم چیه
(به طور خلاصه منظورم محدود کردن نود در محاسبه فقط بعضی از کانفیگ هاست نه همه کانفیگ های مربوط به اون نود)

**Comment by erfjab** [comment]
نحوه‌ی محاسبه حجم نود متفاوته و اینجوری که شما می‌فرمایید ساختار ایکس ری اجازه نمیده عزیز.

**Comment by mobohes** [comment]
> تیم الان درگیر مسئله های دیگه هست عزیز، نمیتونیم اون تغییرات مدنظر شما که مربوط به اکثر کامیونیتی مرزبان هم نیست در اولویت قرار دهیم.

الویت بندی این پیشنهاد با شما هست ، اما من فکر میکنم پیشنهاد من به درد تمام کامیونیتی مرزبان میخوره، در صورت پیاده نشدن همچین امکانی هر فرد مجبور هست برای شخصی سازی مصرف کانفیگش یک سرور مجزا تهیه کنه و فقط مثلا کانفیگ تانلشو به اون اختصاص بده تا بتونه براش ضریب تعیین کنه
قطعا برای هر فردی مفید هست این ایده که بتونه فقط با یک سرورش هم کانفیگ تانل برای مشتری بسازه هم تانل و بتونه فقط کانفیگ های مربوط به تانل رو مضرب مصرف ۲ یا بالاتر براش در تظر بگیره تا ترافیک مصرفی تانلش هم بهتر مدیریت بشه

**Comment by erfjab** [comment]
عزیز عرض کردم خدمتتون که، ساختار فعلی ایکس ری به ما همچین اجازه ای نمیده و گرنه ضریب بندی اینباند هارو اضافه میکردیم. تا وقتی ایکس اضافه نکنه، امکان پذیر نیست.

**Comment by mobohes** [comment]
> عزیز عرض کردم خدمتتون که، ساختار فعلی ایکس ری به ما همچین اجازه ای نمیده و گرنه ضریب بندی اینباند هارو اضافه میکردیم. تا وقتی ایکس اضافه نکنه، امکان پذیر نیست.

متوجه شدم بزرگوار متشکرم از پاسختون و امیدوارم xray این ویژگی رو به زودی اضافه بکنه🤝
موفق باشید❤
