### ISSUE TITLE
حداکثر تعداد کاربران همزمان مجاز روی سرور نود

### ISSUE THREAD

**Issue by Pezhman5252** [Gozargah/Marzban#1245]
با سلام و احترام
لطفا این قابلیت رو فعال کنید که بشه حداکثر تعداد کاربران همزمان مجاز روی سرور نود را کنترل کرد، مثلا من 5 تا نود دارم و میخوام روی هر نود 200 کاربر بیشتر فعال نباشن و اگر به میزان مجاز ظرفیت رسید دیگه نتونم روی اون نود یوزر جدید بسازم یا اتصال جدید بدم، این کار باعث میشه که امکان مدیرت اتصال کاربران روی هر نود رو برای جلوگیری از شلوغ شدن نود ها انجام داد.

**Comment by erfjab** [comment]
درود و وقت بخیر
اضافه کردن این پیچیدگی به ساختار نودها کار درستی نیست، شما می‌توانید خودتون دستی اینباندی که مربوط به نودتون هست رو فقط برای کاربران دلخواه تون فعال کنیذ.

**Comment by Pezhman5252** [comment]
من از طریق API دارم کاربران رو میسازم و از این طریق نمیشه کنترلی روی تعداد کاربران روی هر نود داشت، آیا راهکاری برای این موضوع نیست؟

**Comment by erfjab** [comment]
> من از طریق API دارم کاربران رو میسازم

خب چه عالی، همونجا میتونید خیلی راحت و سریع لیمیتی مشخص کنید.
فقط کافیه اینباندهایی که مربوط به نودهاتون هست رو به کاربرای کمتری بدید.

**Comment by Pezhman5252** [comment]
منظور شما اینه که بابت هر اینباند که روی نود میسازم یک شمارنده داشته باشم و بررسی کنم که اگر ظرفیت اینباندهایی که روی این نود هست مثلا بیشتر از 100 شد بره روی یک نود دیگه اینباند هارو بسازه، درسته؟؟
 مشکل اینجاست که کاربر تو تنظیمات کانکشن وی پی ان خودش میتونه به هر اینباندی که خود کاربر بخواد دسترسی داشته باشه، فقط کافیه لینک اینباندرو قرار بده، آیا نمیشه وقتی من یک کاربر رو مجاب کردم که فقط از همین اینباند استفاده کنه نتونه به اینباند دیگه متصل بشه؟؟

**Comment by erfjab** [comment]
>  مشکل اینجاست که کاربر تو تنظیمات کانکشن وی پی ان خودش میتونه به هر اینباندی که خود کاربر بخواد دسترسی داشته باشه، فقط کافیه لینک اینباندرو قرار بده، 

کاربر از کجا میخواد لینک اون اینباند رو پیدا کنه؟

**Comment by Pezhman5252** [comment]
سناریو من اینه که هر بار کاربر بخواد اکانتشو تمدید کنه تو سیستم چک میکنه اگر ظرفیت یک نود آزاد شده باشه به نود دیگه انتقال پیدا میکنه میکنه.
 اگر کاربر تنظیمات سرویسش رو چک کنه میتونه متوجه تغییر در آدرس سرور بشه.
 اگر این امکان وجود داشت که بشه مدیریت دقیق تری روی نودهای فعال داشت خیلی خوب بود، اینکه از طریق api خود مرزبان بشه روی نودهای فعال محدودیت اتصال قرار داد و مشخص کرد هر نود امکان اتصال به چند اینباند رو داشته باشه. همچنین اتصال به اینباند هایی برقرار بشه که نود اصلی روش تنظیم شده، نه اینمه کاربر درصورت تغییر آدرس سرور بتونه به هر نودی که خودش خواست متصل بشه. ممنون از شما
