### ISSUE TITLE
Marzban can`t load SSL certificates not from /var/lib/marzban/certs/

### ISSUE THREAD

**Issue by Skrepysh** [Gozargah/Marzban#1246]
**Describe the bug**
If in .env I specify the path to the SSL certificate file and this file is located not in /var/lib/marzban/certs/, then marzban does not start. A screenshot of the logs is attached.

**To Reproduce**
1. Run sudo marzban down
2. Copy .pem SSL-cert files (fullchain.pem and key.pem) from /var/lib/marzban/certs to any other place.
3.  Specify path to the new SSL-cert files location in /opt/marzban/.env
4. Run sudo marzban up
5. See that marzban cannot start up.

**Expected behavior**
Marzban must start no matter where the SSL certificate files are located.

**Screenshots**
![WindowsTerminal_3Fk7HxQxPF](https://github.com/user-attachments/assets/f97ea4a2-5ba1-4435-bab9-c1d60ce74442)

**Machine details:**
 - OS: Ubuntu Server 24.04
- Python version: 3.12.3
- Nodejs version: 20.16.0
- Browser: Chrome 127.0.6533.120

**Additional context**
No

**Comment by M03ED** [comment]
because docker don't have access to that directory , add access to the directory or move ssl file to `/var/lib/marzban/certs/`
