### ISSUE TITLE
Update user api request BUG 

### ISSUE THREAD

**Issue by voono** [Gozargah/Marzban#1249]
I have multiple Marzban panels and i manage them with my own personal bot based on Marzban API.
In the largest one with over 600 users, when you update a disabled user to make it enable, the changes will be made with no problem and are visible in the panel but the user can not connect to any node (including Master) until i restart the core via panel. 

the data i send for update user api request:
```
      "expire": expire,
      "data_limit": data_limit,
      "status": "active"
```

- OS: ubuntu 20
- i have tried both ARM and x64 VPS (Hetzner)
- it happens in the last 2 or 3 Marzban updates.

**Comment by erfjab** [comment]
We are refactoring the Marzban APIs. We will check.

**Comment by M03ED** [comment]
> I have multiple Marzban panels and i manage them with my own personal bot based on Marzban API. In the largest one with over 600 users, when you update a disabled user to make it enable, the changes will be made with no problem and are visible in the panel but the user can not connect to any node (including Master) until i restart the core via panel.
> 
> the data i send for update user api request:
> 
> ```
>       "expire": expire,
>       "data_limit": data_limit,
>       "status": "active"
> ```
> 
> * OS: ubuntu 20
> * i have tried both ARM and x64 VPS (Hetzner)
> * it happens in the last 2 or 3 Marzban updates.

this happen every time or only when you send request with your bot?

**Comment by voono** [comment]
> > I have multiple Marzban panels and i manage them with my own personal bot based on Marzban API. In the largest one with over 600 users, when you update a disabled user to make it enable, the changes will be made with no problem and are visible in the panel but the user can not connect to any node (including Master) until i restart the core via panel.
> > the data i send for update user api request:
> > ```
> >       "expire": expire,
> >       "data_limit": data_limit,
> >       "status": "active"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * OS: ubuntu 20
> > * i have tried both ARM and x64 VPS (Hetzner)
> > * it happens in the last 2 or 3 Marzban updates.
> 
> this happen every time or only when you send request with your bot?

Every time i use my "own bot" that i created using the Marzban api, i did not try the official Marzban bot.
it happens when i use the api, the front-end panel works well.
i also sent the update request data sample i use, in the message above.

**Comment by ImMohammad20000** [comment]
Do you use library's for api request?
something like marzpy?

**Comment by ImMohammad20000** [comment]
Do you use dev version ?

**Comment by voono** [comment]
> Do you use library's for api request? something like marzpy?

no im not using any library beside python request.
`requests.put(url, json=data, headers=headers)`

and im not using dev version

**Comment by sons-of-liberty** [comment]
> I have multiple Marzban panels and i manage them with my own personal bot based on Marzban API. In the largest one with over 600 users, when you update a disabled user to make it enable, the changes will be made with no problem and are visible in the panel but the user can not connect to any node (including Master) until i restart the core via panel.
> 
> the data i send for update user api request:
> 
> ```
>       "expire": expire,
>       "data_limit": data_limit,
>       "status": "active"
> ```
> 
> * OS: ubuntu 20
> * i have tried both ARM and x64 VPS (Hetzner)
> * it happens in the last 2 or 3 Marzban updates.

پیدا کردم دلیلشو. 
توی کدت باید قسمت ریست ترافیک رو بیاری قبل از قسمت modify user.
