### ISSUE TITLE
چند عدد پیشنهاد

### ISSUE THREAD

**Issue by nasiriscript** [Gozargah/Marzban#125]
سلام، ممنون بابت این پنل زیبا یه چندتا پیشنهاد داشتم اگر وقت کردید و دیدید مناسبه اضافه کنید و گرنه که هیچی:
1- امکان تغییر مسیر پنل از /dashboard به موارد دیگر
2- امکان تغییر uuid کانفیگ
3- امکان تغییر path کانفیگ
4- امکان ست کردن آیپی کلادفلر و دریافت کانفیگ با توجه به اون
با تشکر.

**Comment by SaintShit** [comment]
@nasiriscript مورد سوم و چهارم در حال حاضر امکان پذیره.
مورد ۳ از فایل xray_config.json
مورد ۴ از داخل داشبورد بخش hosts settings
