### ISSUE TITLE
باگ پروتکل httpguard

### ISSUE THREAD

**Issue by afraz5** [Gozargah/Marzban#1250]
سلام وقتی با اینباند جنریتور کاستوم کانفیگ میزنم و به مرزبان اضافه میکنم موقع ساخت یوزر لینک ساب کانفیگو کامل نمیارهکلا ناقص کانفیگو بالا میاره مثه اینکه با پروتکل httpguard مشکل داره
![photo_2024-08-18_16-48-25](https://github.com/user-attachments/assets/72793743-20b7-44f9-b4a4-69e46eb9946e)

**Comment by M03ED** [comment]
the tool you are using it's not official, use xray docs
https://xtls.github.io/en/
