### ISSUE TITLE
stream settings for tcp

### ISSUE THREAD

**Issue by iyf577ge6** [Gozargah/Marzban#1253]
greetings 

there is a bug in the DEV version for TCP transmissions. (custom configs version 6)

with creating an inbound in x-ray core like this:

{
  "tag": "VLESS + TCP",
  "listen": "0.0.0.0",
  "port": 8080,
  "protocol": "vless",
  "settings": {
      "clients": [],
      "decryption": "none"
    },
  "streamSettings": {
    "network": "tcp",
    "tcpSettings": { },
    "security": "none"
  },
  "sniffing": {
    "enabled": true,
    "destOverride": ["http", "tls"]
  }
}

that contains no header and path in the x-ray core configuration will not be startable 

![photo_2024-08-19_14-40-00](https://github.com/user-attachments/assets/104c3c19-7f62-4510-8872-ffdebab87d84)

when we downgrade to the latest version the result would be different:

![photo_2024-08-19_14-40-16](https://github.com/user-attachments/assets/36836678-70da-4884-bd2d-89f87a1fd8cf)

and configs start normally

thanks.

**Comment by M03ED** [comment]
this is already reported #1222
and its waiting to be accepted #1224
