### ISSUE TITLE
pg migrations

### ISSUE THREAD

**Issue by kanewi11** [Gozargah/Marzban#1256]
```
marzban  | INFO  [alembic.runtime.migration] Running upgrade 31f92220c0d0 -> 305943d779c4, add h3 to alpn enum
...
marzban  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) default for column "alpn" cannot be cast automatically to type temp_alpn
marzban  | 
marzban  | [SQL: ALTER TABLE hosts ALTER COLUMN alpn TYPE temp_alpn USING alpn::text::temp_alpn]
```
**v 0.6.0**

**Comment by Kaidstor** [comment]
want psql too..

**Comment by M03ED** [comment]
@lastbyte32

**Comment by CRaFT4ik** [comment]
Add PostgreSQL support please.
I looked at different options, and I had to give up Marzban for now because I don't want to deploy another database instance.

**Comment by engAmirEng** [comment]
> postgresql is not in the marzban plan to be supported. Recently one of the users edited some of the old migration files to be synced with postgresql. You can do it yourself and make a pr for it if you're interested, but at this point I can't help you with this because I have no experience with postgresql.

This statement is odd, you are using a powerful ORM(sqlalchemy) and not using any sqlite specific feature and yet fail to support postgresql the most common database in the world?
what is the good of having distributed Nodes when your database cannot scale??

**Comment by M03ED** [comment]
> This statement is odd, you are using a powerful ORM(sqlalchemy) and not using any sqlite specific feature and yet fail to support postgresql the most common database in the world?
> 
> if you only support sqlite then what is the good of having distributed Nodes when your database cannot scale??

If you're so interested, start it now and add postgresql support to marzban 
Pr Welcome. 👋

**Comment by engAmirEng** [comment]
@M03ED actually I finally decided to go with Marzban and I hope to start contributing to it as I'm using and adapting it to my needs
