### ISSUE TITLE
ست کردن دی ان اس از سمت سرور

### ISSUE THREAD

**Issue by Elhwm** [Gozargah/Marzban#126]
سلام و خسته نباشید به دولوپر محترم،ایا امکانش هست که از سمت سرور dns مدنظرمونو تنطیم کنیم تا در تمام کلاینت ها اعمال بشه؟ممنون میشم راهنمایی کنید،باتشکر.

**Comment by SaintShit** [comment]
سلام، لطفا سوالات رو در گروه تلگرام یا بخش discussion مطرح کنید. تنظیمات DNS کاملا مربوط به کلاینته مگر اینکه برنامه ای مثل کلش پشتیبانی کنه. برای برنامه کلش هم درحال حاضر امکان تغییر template وجود نداره ولی به زودی اضافه میشه.
