### ISSUE TITLE
اضافه کردن دو آپشن طلایی به اسکریپت

### ISSUE THREAD

**Issue by Golden-Source** [Gozargah/Marzban#1263]
درود ، 
ویژگی اول در خصوص کسانی هست که شرکت هستند و نیاز دارند که مدیریت کامل اشتراک های کارمند هاشون داشته باشند ، که قابلیت دسترسی به ای پی پرایویت به همراه استاتیک کردن ای پی ها موجب میشه که مرزبان برای پنل های شرکتی استفاده بشه .

ویژگی دوم قابلیتی باشه که امکانش باشه ما یک سری سایت تعریف کنیم و مرزبان از اون سایت ها اشتراکی کسر نکنه ، که اگر کسی شبکه پرایویت داشت یا سایت خودش بود یا قرارداد بسته بود با کسانی که سایت فیلم دارند امکان اینکه حجمی روی اشتراک مصرف نشه خیلی نیاز میشه.

**Comment by erfjab** [comment]
درود و وقت بخیر
راجب ویژگی اول که همون آیپی لیمیت هست، بهتره از اسکریپت های جانبی مثل آیپی لیمیت هوشمند استفاده‌ کنید.
راجب ویژگی دومم که ساختار xray به ما همچین اجازه ای نمیده.
