### ISSUE TITLE
`expire` Field not present in `subscription-userinfo` header

### ISSUE THREAD

**Issue by nulluser0** [Gozargah/Marzban#1265]
**Describe the bug**
The `expire` field is not present in `subscription-userinfo` headers for `sing-box` subscriptions in users with data limits.

**To Reproduce**
1. Create user with a data limit
2. Copy subscription URL of the user
3. Either using curl, panel docs page, or any other client, `GET (subscription url), accept application/json` with user agent set as `HiddifyNext` (or add `/sing-box`).
4. Check headers. The `expire` field is absent from `subscription-userinfo`.

**Expected behavior**
For users with data limits, there should be an `expire` field in `subscription-userinfo`. Lack of this means clients (like Hiddify Next) cannot show user their data usage.

**Screenshots**
N/A

**Machine details (please complete the following information):**
Client:
- OS: `Windows 11 23H2`
- Python version: `N/A`
- Nodejs version: `N/A`
- Browser: Firefox `129.0.2`

Server:
- OS: `Ubuntu-22.04-x86_64`
- Marzban version: `v0.6.0` on Docker
- X-Ray core version: `v1.8.23`

**Additional context**
N/A

**Comment by nulluser0** [comment]
Upon further exploration, I realized that the `expire` field is present only when expiration date and data limit are both set. When one or both are not, the `expire` field disappears.

Is this intended?

**Comment by M03ED** [comment]
this is fixed on dev branch, check dev version
