### ISSUE TITLE
مشکل کوئری حجم استفاده شده ادمین ها

### ISSUE THREAD

**Issue by ItsOrv** [Gozargah/Marzban#1267]
توی این کوئری که برای محاسبه حجم total هر ادمین استفاده میشه فکر کنم مشکل داره:
```
SELECT admins.username, (SUM(users.used_traffic) + IFNULL(SUM(user_usage_logs.used_traffic_at_reset), 0)) / 1073741824
FROM admins 
LEFT JOIN users ON users.admin_id = admins.id 
LEFT JOIN user_usage_logs ON user_usage_logs.user_id = users.id
Group By admins.username
```
مشکلش اینه حجم total یوزر هایی که نامحدود هستن یا لیمیتد شدن رو اشتباه نشون میده و فکر کنم اون حجم بعد اخرین ریست رو یبار دیگه هم باهاش جمع میکنه یا اون مقدار حجم هم توی used_traffic_at_reset هست هم توی used_traffic پس دوبار جمع میشه
سعی کردم با تغییر کوعری یبار این حجم دومی رو از کاربرایی که status اونا limited هست حساب نکنم  ولی اینجوری میاد کمتر از حجم استفاده شده واقعی نشون میده

**Comment by ItsOrv** [comment]
بعد اومدم با این کوئری تک تک یوزر های یه ادمین رو خروجی گرفتم مقایسه کنم:

SELECT 
    users.username, 
    (SUM(users.used_traffic) + IFNULL(SUM(user_usage_logs.used_traffic_at_reset), 0)) / 1073741824 AS total_traffic_in_gb 
FROM 
    users 
LEFT JOIN 
    user_usage_logs ON user_usage_logs.user_id = users.id 
JOIN 
    admins ON users.admin_id = admins.id 
WHERE 
    admins.username = 'pesarak' 
GROUP BY 
    users.username;
![IMG_20240826_174942_854](https://github.com/user-attachments/assets/6386b724-0b0f-4c27-abc3-025e5a99ae8a)

**Comment by M03ED** [comment]
کوئری ها وابسته به خودتون هستن و ربطی به مرزبان ندارن 
برای اسنفاده از کوئری نیاز به دانش فنی در زمینه sql دارید ، در صورتی که نیاز به کمک در این زمینه دارید میتونید از بخش discussions و یا گروه تلگرام مرزبان استفاده کنید
