### ISSUE TITLE
x-ui to marzban

### ISSUE THREAD

**Issue by mohsenzt** [Gozargah/Marzban#1269]
درود خدا قوت لطفا جهت انتقال از پنل x-ui به مرزبان 
امکان انتقال لینک ساب رو هم بزارین♥

**Comment by erfjab** [comment]
درود و وقت بخیر امکان انتقال لینک ساب نداریم. امکان انتقال کاربران اتوماتیک هم از طریق اسکریپت های جانبی امکان پذیره.

**Comment by erfjab** [comment]
https://github.com/ItsAML/X-Ui-to-Marzban

**Comment by mohsenzt** [comment]
امکانش نیست پچ ساب هر یوزر رو به صورت دستی تغییر بدم؟

**Comment by mohsenzt** [comment]
سیستم خواستی نداره دامنه:پورت/پچ و در نهایت توکن
دقیقا مثل مرزبان 
فقط نیاز هست بتونم توکن رو تغییر بدم

**Comment by erfjab** [comment]
چرا تو دو تا ایشوی متفاوت همان صحبت رو میکنیم؟ 😑
