### ISSUE TITLE
Custom config toggle

### ISSUE THREAD

**Issue by Ashaxer** [Gozargah/Marzban#1270]
Hi, There is an option in .env to enable "CUSTOM_CONFIG" for certain clients.
AFAIK these formats of configs are necessary for Fragment, random UA, MUX, and other client-side configuration settings, putting the "CUSTOM_CONFIG" in the .env file converts all of the configs to Custom Config and makes it harder for users to customize the config parameters and also it's still buggy (messes up with order of the configs).

It would be awesome if this option could only be enabled for certain hosts in Hosts Settings inside the Marzban panel.

**Comment by M03ED** [comment]
> (messes up with order of the configs

fix on dev version

> It would be awesome if this option could only be enabled for certain hosts in Hosts Settings inside the Marzban panel.

clients don't accept 2 type of config together, you can only send one config type
