### ISSUE TITLE
تغییر سابسکرایب

### ISSUE THREAD

**Issue by mohsenzt** [Gozargah/Marzban#1271]
درود اوقات بکام تشکر از اینکه وقت میزارین
ایا راهی هست پچ ساب دامنه هارو تغییر داد؟

**Comment by erfjab** [comment]
درود و وقت بخیر، میخوایید /sub رو عوض کنید؟
از قسمت Xray subscription path ممکنه آره
ولی ساب های قبلی از کار میفتن.

**Comment by mohsenzt** [comment]
سپاس عذر خواهی میکنم اشتباه نوشتم منظورم توکن ساب هست

**Comment by erfjab** [comment]
نه نمیتونید عزیز. چون با jwt جنریت میشه و هر بار متفاوته. ذاتا مهم اطلاعات توشه. تو گروهم همین پاسخ رو بهتون دادم.
