### ISSUE TITLE
Настройка уведомлений в телеграм-боте

### ISSUE THREAD

**Issue by qu1zzlyzz** [Gozargah/Marzban#1273]
Добавить в настройки MarzBan/телеграм-бота управление уведомлениями. Пользователь может выбрать какие типы уведомлений будут присылаться в лог-канал (вход в панель управления/создания пользователя и т.д)

**Comment by M03ED** [comment]
first of all try to use English in issues
and for what you ask is currently available in env file

**Comment by erfjab** [comment]
Added in the dev version. It will be released soon.
