### ISSUE TITLE
Marzban overrides SplitHTTP settings template

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#1277]
Why this values are hardcoded, and why they override my settings from template file
https://github.com/Gozargah/Marzban/blob/325d35d359d6abe15f18338d4dd364010b3b86f4/app/subscription/v2ray.py#L532

**Comment by M03ED** [comment]
These are default values that are provided by xray docs, these values should be set in xray core not in template, that's how it works.

**Comment by M03ED** [comment]
If we ignore the core and just apply the template users gonna face issue if they use 2 or more split http with different settings
