### ISSUE TITLE
support cert content in the core setting

### ISSUE THREAD

**Issue by Mmdd93** [Gozargah/Marzban#1280]
marzban supports certificate content for WebSockets but does not work with httpupgrades. Add httpupgrade cert content support too .make marzban easier to use cert content![Screenshot 2024-09-01 235817](https://github.com/user-attachments/assets/a12e70e1-9e85-4a85-9c56-7af0237cd4a5)

**Comment by M03ED** [comment]
this part of code is not specified for just ws or any other transport, if your inbound security be tls this will happen
