### ISSUE TITLE
حذف اینباد ها 

### ISSUE THREAD

**Issue by hossein2** [Gozargah/Marzban#1288]
سلام نمیدونم سوالی ک دارم میپرسم جاش همین قسمت یا خیر 
خواستم بدونم زمانی ک ما بیش از حد اینباند میسازیم و حذف میکنیم چطور میشه از تو دیتابیس هم چک کردو حذف کرد

**Comment by erfjab** [comment]
درود و وقت بخیر، منظورتون رو متوجه نشدم ولی بهتره سوالتون رو تو گروه مرزبان یا دیسکاشن ها بپرسید. ایشوهای برای باگ های و فیچر هستند. ممنون
