### ISSUE TITLE
can't set custom node to user subscription in api 

### ISSUE THREAD

**Issue by MaximCemencov** [Gozargah/Marzban#1295]
hi I want to create a functional for change the list of servers in users subscription but that I send a put request with something like {
  "links": [
    "vless://heremysubcription to server 1",
    "False"
  ]
}

than I got response {
  "proxies": {},
  "expire": 0,
  "data_limit": 0,
  "data_limit_reset_strategy": "no_reset",
  "inbounds": {},
  "note": "string",
  "sub_updated_at": "2024-09-03T13:48:06.648Z",
  "sub_last_user_agent": "string",
  "online_at": "2024-09-03T13:48:06.648Z",
  "on_hold_expire_duration": 0,
  "on_hold_timeout": "2024-09-03T13:48:06.648Z",
  "auto_delete_in_days": 0,
  "username": "string",
  "status": "active",
  "used_traffic": 0,
  "lifetime_used_traffic": 0,
  "created_at": "2024-09-03T13:48:06.648Z",
  "links": [ "vless://heremysubcription to server 1", "vless://heremysubcription to server 2", "False"],
  "subscription_url": "",
  "excluded_inbounds": {},
  "admin": {
    "username": "string",
    "is_sudo": true,
    "telegram_id": 0,
    "discord_webhook": "string"
  }
} I got 2 node and 1 main server but I can't modify than is than is it the lack of ability to change the list of servers or am I doing something wrong I try put in the put request full list that got by /api/user/{username} and change just the array of links pls help me 🙏

**Comment by erfjab** [comment]
Hello, is your problem with `False`?

**Comment by MaximCemencov** [comment]
No, the problem isn't with "False." The issue is that I'm unable to modify the list of server links for a user. Additionally, could you please explain why the "False" value always appears at the end of the "links" array?

**Comment by erfjab** [comment]
> Additionally, could you please explain why the "False" value always appears at the end of the "links" array?

Fixed in dev

**Comment by erfjab** [comment]
> No, the problem isn't with "False." The issue is that I'm unable to modify the list of server links for a user. 

Your links are generated based on these inbounds , to change the user links, you have to replace these inbounds.
