### ISSUE TITLE
خاموش کردن  پیش فرض اضافه شدن نود به هاست ها 

### ISSUE THREAD

**Issue by sirvan1133** [Gozargah/Marzban#1296]
اگر به صورت پیش فرض اضافه شدن نود به هاست ها غیر فعال بشه عالیه 
چون بعضی وقتا تعداد هاستا زیاده و میبینی اشتباه تیکشو غیر فعال نکردی 
و باید دونه دونه از هاست ها نود جدید رو پاک کنی 
![Screenshot 2024-09-03 174602](https://github.com/user-attachments/assets/3f127c9a-346b-48a7-93e4-a19b77643ffb)

**Comment by ImMohammad20000** [comment]
#1297
