### ISSUE TITLE
node_user_usages problem on the dashboard

### ISSUE THREAD

**Issue by mdjvd** [Gozargah/Marzban#1301]
Yesterday, I updated marzban (dev), and since then, node user usage on the dashboard has not shown any data from yesterday until today (older data is shown with no problem).
the records in the database are there and there is no problem there. and also user data usage is calculated with no problem.
I have restarted marzban, rebooted the server, logged out of the panel and logged in again, cleared the cache, and so on, but no luck.

![image](https://github.com/user-attachments/assets/cd13f0f0-19b2-42e1-ba55-4c8c3e74868a)
![image](https://github.com/user-attachments/assets/a7f3b7de-247c-4554-b3c6-52f5b2a5f039)
![image](https://github.com/user-attachments/assets/05df7d6f-2237-4ef3-875d-a24c58a2d149)

**Comment by M03ED** [comment]
Check the request and body and make sure it's right , and I think the problem happened after the API refactor, I will check it at night.

**Comment by M03ED** [comment]
this should be fixed with 68dab4cd1092c9e452e8bcca151c40b8ec0f6bad commit 
wait few minutes to and then update your marzban

**Comment by mdjvd** [comment]
yes, the issue with node_user_usages is now fixed. But now I have lost node_usages completely and here are the logs
![image](https://github.com/user-attachments/assets/cf1233a7-9047-4795-a952-a10bb4824c30)

**Comment by M03ED** [comment]
i think it should be fixed now

**Comment by mdjvd** [comment]
it's fixed.
Thank you.

**Comment by sirvan1133** [comment]
درست شد حاجی؟
