### ISSUE TITLE
Nodes Usage

### ISSUE THREAD

**Issue by sirvan1133** [Gozargah/Marzban#1303]
در نسخه dev بخش  Nodes Usage رو نشون نمیده 
![image](https://github.com/user-attachments/assets/55e451ea-9bbc-4897-8b1a-22d901c7aa03)

**Comment by sirvan1133** [comment]
![image](https://github.com/user-attachments/assets/118513de-7c9e-4371-afbc-78e6c819ada5)

this log

**Comment by arian24b** [comment]
I'm working on this issue.

**Comment by M03ED** [comment]
its fixed, wait few minutes and update your marzban

**Comment by sirvan1133** [comment]
> its fixed, wait few minutes and update your marzban

ok thanks
