### ISSUE TITLE
Setting up a time zone

### ISSUE THREAD

**Issue by CryZFix** [Gozargah/Marzban#1308]
Greetings. I looked at the previous topics on this issue and didn’t fully understand. Can we change the time zone or will it still lead to problems?

I have external monitoring services for log files of the container and it’s a little inconvenient to change the server time to utc

**Comment by M03ED** [comment]
You need a big change all over the code base ( both front-end and backend ) and it can become a big mess and I never suggest that , it's better to remain utc.
There is no need to change server time to utc.

**Comment by CryZFix** [comment]
> There is no need to change server time to utc.

There is a problem with setting up fail2ban, it refuses to work because of the time difference in the logs and the system.

**Comment by M03ED** [comment]
> > There is no need to change server time to utc.
> 
> There is a problem with setting up fail2ban, it refuses to work because of the time difference in the logs and the system.

You're using a third party project that has nothing to do with marzban.
You're the guy who should sync projects together.
And changing server time to utc is not a big deal, mostly people use servers outside of their country and timezone is different.
In this case even if you change marzban time, you need to change xray-core time too.
