### ISSUE TITLE
مشکل ران نشدن اسکریپت CLI

### ISSUE THREAD

**Issue by ManiXD** [Gozargah/Marzban#1310]
وقتی پروژه رو از کد ران میکنم با CLI به مشکل بر میخورم 
اروری که میده این هستش:
`root@root:~/Marzban# marzban-cli
Traceback (most recent call last):
  File "/usr/bin/marzban-cli", line 13, in <module>
    import cli.user
  File "/root/Marzban/cli/user.py", line 19, in <module>
    username: Optional[list[str]] = typer.Option(None, *utils.FLAGS["username"], help="Search by username(s)"),
TypeError: 'type' object is not subscriptable
`

**Comment by ImMohammad20000** [comment]
دستوری که میزنین چیه؟؟

**Comment by M03ED** [comment]
زمانی که issue باز می کنید و اطلاعاتی ازتون خوسته میشه پاسخگو باشید
