### ISSUE TITLE
درخواست راهنمایی برای رفع ارور های هسته

### ISSUE THREAD

**Issue by vahidyeganeh1373** [Gozargah/Marzban#1315]
سلام
من توی گروه چندبار سوال پرسیدم و غیر از من هم افراد زیادی بودن که جواب نگرفتن و کسی پاسخ نداد مجبور کنم این ایشو رو ایجاد کنم
چند هفته ای هست که هسته ارور های مختلف میده و کانفیگها قطع و وصل میشن 
یکی ارور :
2024/09/11 10:26:26 [Warning] [3693771235] common/mux: XUDP hit [141 19 160 85 59 95 232 98] > common/mux: conflict
2024/09/11 10:26:26 [Warning] [1958729533] common/mux: XUDP hit [141 19 160 85 59 95 232 98] > common/mux: conflict
2024/09/11 10:26:26 [Warning] [2262644332] common/mux: XUDP hit [141 19 160 85 59 95 232 98] > common/mux: conflict
2024/09/11 10:26:26 [Warning] [2574844489] common/mux: XUDP hit [141 19 160 85 59 95 232 98] > common/mux: conflict

2024/09/11 10:27:54 [Warning] [2566258898] common/mux: XUDP hit [141 19 160 85 59 95 232 98] > common/mux: conflict

2024/09/11 10:28:00 [Warning] [397500300] common/mux: XUDP hit [141 19 160 85 59 95 232 98] > common/mux: conflict

یکی هم این : 

connection ends > proxy/vless/inbound: failed to write A response payload > transport/internet/grpc/encoding: failed to send data over gRPC tunnel > rpc error: code = Canceled desc = context canceled

و اینم هست 
2024/09/11 08:36:05 [Warning] [2823116405] app/proxyman/inbound: connection ends > proxy/vless/inbound:

اگه کسی میتونه راهنمایی کنه

**Comment by M03ED** [comment]
ارور ها و مشکلات مربوط به ایکس ری هست و ربطی به مرزبان نداره.
