### ISSUE TITLE
تداخل گزارش لاگین و ربات مرزبان

### ISSUE THREAD

**Issue by vcoder-exe** [Gozargah/Marzban#1316]
وقتی که پنل از طریق API به یک ربات فروشگاهی متصله و ارتباط برقرار میکنه، ربات خود مرزبان لاگین گزارش میکنه ولی تعداد این گزارش ها توی این موقعیت خیلی زیاده و عملا دیگه با ربات خود مرزبان نمیشه کار کرد. اگر امکانی باشه که آیپی خود پنل مستر exclude بشه که تو گزارش ربات نیاد یا کلا بشه این قابلیت رو غ فعال کرد خیلی بهتره

![bug](https://github.com/user-attachments/assets/2ed87434-45f4-481c-b6dc-1cbaaed30ab3)

**Comment by M03ED** [comment]
این مشکل از سمت مرزبان نیست و به دلیل کد نویسی نادرست برخی ربات ها اتفاق می افته.
