### ISSUE TITLE
Errors in latest dev version

### ISSUE THREAD

**Issue by mhmdh94** [Gozargah/Marzban#1320]
When I try to search a user in the panel, if there are multiple instances only 10 of them will show and I get this error in logs.

![image](https://github.com/user-attachments/assets/07649ebc-e5d9-4d5d-8306-e22b05e304e6)

also  this error appears in the logs when some user ( I do not know which ) updates his subscription.

![image](https://github.com/user-attachments/assets/80d69c2a-bd34-4e1d-843b-246710cf2130)

**Comment by M03ED** [comment]
you probably use query on database and try to (enable , disable) proxy for all users , this cause some users become with 0 proxy type and its not acceptable in marzban models
you need to find these users and delete them from database
