### ISSUE TITLE
privateKey hardcoded unable to change privateKey

### ISSUE THREAD

**Issue by harukodi** [Gozargah/Marzban#1326]
{
            "tag": "VLESS TCP REALITY",
            "listen": "0.0.0.0",
            "port": 8443,
            "protocol": "vless",
            "settings": {
                "clients": [],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "tcpSettings": {},
                "security": "reality",
                "realitySettings": {
                    "show": false,
                    "dest": "discordapp.com:443",
                    "xver": 0,
                    "serverNames": [
                        "cdn.discordapp.com",
                        "discordapp.com"
                    ],
                    "privateKey": "MMX7m0Mj3faUstoEm5NBdegeXkHG6ZB78xzBv2n3ZUA",
                    "shortIds": [
                        "",
                        "6ba85179e30d4fc2"
                    ]
                }
            }
            
            
Why is the privateKey hardcoded? am i allowed to change this?

**Comment by M03ED** [comment]
reality can work without private key ? no 
so we need a default value for example and why you should not be able to change this ?

**Comment by M03ED** [comment]
and we don't call this as hard code

**Comment by harukodi** [comment]
But if you use the xray script you can generate your own privatekey/pubkey. Does this thing not give access to other people or? is this value perhaps changed within marzban after its started?

**Comment by M03ED** [comment]
just change it, generate new one and replace it
