### ISSUE TITLE
Change SplitHTTP Client Config (JSON Custom Config) Default Setting Parameters.

### ISSUE THREAD

**Issue by deepsm0ke** [Gozargah/Marzban#1327]
Hi. 
The default json custom config for SplitHTTP given to users needs to be changed ( Xray: 1.8.24 ).

Marzban Default SplitHTTP Settings :

"splithttpSettings": {
          "maxUploadSize": 1000000,
          "maxConcurrentUploads": 10 }

become like this :

"splithttpSettings": {
          "scMaxEachPostBytes": "1000000-2000000",
          "scMaxConcurrentPosts": "100-200",
          "scMinPostsIntervalMs": "10-50",
          "xPaddingBytes": "100-1000", }

https://xtls.github.io/en/config/transports/splithttp.html#splithttpobject

**Comment by M03ED** [comment]
yeah that's what we wanna do if you check pr's #1302
im waiting for a stable version
