### ISSUE TITLE
Warp WireGuard Node

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#1328]
**Warp** has been installed using **WireGuard** on both the node server and the server with the **Marzban panel**.

![image](https://github.com/user-attachments/assets/3647f336-273d-4c0d-a644-dc069e0967f2)

 The necessary code has also been added to the **core settings**, specifically in the first outbound section, as shown below:

```json
"outbounds": [
  {
    "tag": "direct",
    "protocol": "freedom",
    "streamSettings": {
      "sockopt": {
        "tcpFastOpen": true,
        "interface": "warp"
      }
    }
  }
]
```

However, this configuration does not seem to work on the node server, although it works fine on the local server configs. I would appreciate your guidance in resolving this issue.

**Comment by M03ED** [comment]
you need to add `network_mode: host` to your docker file, if you limit container ports this method won't work
