### ISSUE TITLE
باگ ربات تلگرامی

### ISSUE THREAD

**Issue by Tigervpnorg** [Gozargah/Marzban#1330]
ربات مدیریتی پنل مرزبان استارت میشه اطلاعات نمایش داده میشه همه چیز اکیه 
اما هیچ عملیاتی مثل Restart Xray/Create User و... کلا هیچ عملیاتی انجام نمیشه

https://github.com/user-attachments/assets/63557987-5ac6-433f-9015-112065fa447d

و اروری هم که داخل لاگ میده به صورت زیر هست

> marzban-1  | 2024-09-27 09:12:39,833 (__init__.py:1083 Thread-1 (infinity_polling)) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 4310"
> marzban-1  | 2024-09-27 09:12:39,833 (__init__.py:1085 Thread-1 (infinity_polling)) ERROR - TeleBot: "Exception traceback:
> marzban-1  | Traceback (most recent call last):
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 1074, in __threaded_polling
> marzban-1  |     self.worker_pool.raise_exceptions()
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 156, in raise_exceptions
> marzban-1  |     raise self.exception_info
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 100, in run
> marzban-1  |     task(*args, **kwargs)
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 6395, in _run_middlewares_and_handler
> marzban-1  |     result = handler['function'](message)
> marzban-1  |   File "/code/app/telegram/handlers/admin.py", line 1498, in confirm_user_command
> marzban-1  |     m = bot.edit_message_text(
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 3646, in edit_message_text
> marzban-1  |     result = apihelper.edit_message_text(self.token, text, chat_id, message_id, inline_message_id, parse_mode,
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/apihelper.py", line 1284, in edit_message_text
> marzban-1  |     return _make_request(token, method_url, params=payload, method='post')
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/apihelper.py", line 162, in _make_request
> marzban-1  |     json_result = _check_result(method_name, result)
> marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/apihelper.py", line 189, in _check_result
> marzban-1  |     raise ApiTelegramException(method_name, result, result_json)
> marzban-1  | telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 4310
> marzban-1  | "

**Comment by ImMohammad20000** [comment]
ظاهرا ip سرور بلاکه ip سرور رو عوض کنید

**Comment by M03ED** [comment]
سرور شما در ارتباط با سرور های تلگرام مشکل داره ، سرور تون رو تغییر بدید
