### ISSUE TITLE
dependency installation is a mess

### ISSUE THREAD

**Issue by darhelm** [Gozargah/Marzban#1332]
install the damn packages using poetry
it has to be a pain in the ass to install the packages on literally any other distro other than ubuntu 20 every damn time dude just install your goddamn packages with poetry 

add this in your dockerfile
```
# Use the official Python image as the base image
FROM python:3.11.8-slim

# Set environment variables for Python and Poetry
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV POETRY_HOME="/opt/poetry" \
    PATH="${PATH}:/opt/poetry/bin"


RUN apt-get update -yq \
    && apt-get install -y python3-dev build-essential autoconf automake libffi-dev libtool pkg-config git curl redis -yq
RUN pip3 install --upgrade pip
RUN pip3 install poetry

# Set the working directory
WORKDIR /app

# Copy only the requirements files to leverage Docker cache
COPY pyproject.toml poetry.lock* /app/

# Install project dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

# Copy the bitpin project files to the container
COPY . /app/
RUN pip3 install -e .
```

for the love of god use poetry and fix this dependency hell

**Comment by darhelm** [comment]
> Useless AI generated Dockerfile, Stop it.

sure buddy. fix your dependencies. i can't install it on other distros easily

**Comment by M03ED** [comment]
> > Useless AI generated Dockerfile, Stop it.
> 
> sure buddy. fix your dependencies. i can't install it on other distros easily

if you want to use docker just pull docker image and if you want to run it manually your on your own
