### ISSUE TITLE
question about UVICORN_ROOT_PATH

### ISSUE THREAD

**Issue by IMIEEET** [Gozargah/Marzban#1334]
im not a python dev but by looking at .env config file i noticed a config named "UVICORN_ROOT_PATH", i looked at uvicorn docs and they said it just root path
i could not find more details but isnt this the root path supposed to be a prefix to all URLs? 
for example default url is localhost:80/dashboard and with root-path="/random" -> localhost:80/random/dashboard. i might be mistaken but even after i set it to a string as by documentation it did nothing

**Comment by M03ED** [comment]
using root path will destroy frontend code unless you edit them too

**Comment by M03ED** [comment]
If you mean dashboard path, there is a pr open for it
But the API no
