### ISSUE TITLE
amnezia-wg pls add amnezia support

### ISSUE THREAD

**Issue by helpmebro911** [Gozargah/Marzban#1336]
https://github.com/Slava-Shchipunov/awg-openwrt
https://docs.amnezia.org/en/documentation/amnezia-wg/#working-principle
pls add amnezia support

**Comment by helpmebro911** [comment]
?

**Comment by M03ED** [comment]
> ?

Amnezia it's VPN service not a protocol

**Comment by helpmebro911** [comment]
> > ?
> 
> Amnezia it's VPN service not a protocol

protocol
Amnezia VPN = mod wiregurad protocol
