### ISSUE TITLE
Allow Insecure is not working as expected

### ISSUE THREAD

**Issue by amebrahimi** [Gozargah/Marzban#1338]
When I select Allow Insecure checkbox I expect in my subscription config Allow Insecure to become true but it's not in V2rayN in windows and V2rayng in android

![image](https://github.com/user-attachments/assets/ef2ee2a7-91e5-4755-9dd4-ceb891e25cc5)
![image](https://github.com/user-attachments/assets/d3bfbb4a-c2e0-4be5-b990-9c2e22606dc9)

**Comment by M03ED** [comment]
this is v2rayn limit, it won't accept allowinsecure parameter in links, you should use custom configs

**Comment by amebrahimi** [comment]
@M03ED thank you 
How should I enable custom configs?

**Comment by M03ED** [comment]
Env file
