### ISSUE TITLE
UDP through vless cannot be enabled for sing-box clients

### ISSUE THREAD

**Issue by tighnaridotme** [Gozargah/Marzban#1350]
**Describe the bug**
`"network": "tcp"` effectively prohibits any udp connections from being encoded and sent through a vless outbound in sing-box. This field has little to no use, so i believe it should not be present in the config at all. Another option could be adding a toggle for udp to the host settings in the dashboard.

**To Reproduce**
1. Enable a vless inbound
2. Configure a template for sing-box
3. Add the subscription to a sing-box client
4. Everything that runs over udp (like webrtc) is dead

**Comment by M03ED** [comment]
marzban do not force any `network` type in sing-box configuration 
its just depend on your xray-core configuration

**Comment by tighnaridotme** [comment]
Unfortunately, I couldn't manage to set it up the way it wouldn't force network: tcp

The following block is from my server config:
```
"inbounds": [
    {
      "tag": "hh",
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": "nginx:443",
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "security": "tls",
        "tlsSettings": {
          "rejectUnknownSni": true,
          "minVersion": "1.3",
          "certificates": [
            {
              "ocspStapling": 3600,
              "certificateFile": "/etc/ssl/cert/cert.pem",
              "keyFile": "/etc/ssl/cert/privkey.key"
            }
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
```

And here's a snippet of an actual sing-box config generated from the template:

```
{
            "type": "vless",
            "tag": "",
            "server": "",
            "server_port": 443,
            "flow": "xtls-rprx-vision",
            "network": "tcp",
            "tls": {
                "enabled": true,
                "server_name": "",
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                }
            },
            "multiplex": {
                "enabled": false,
                "protocol": "h2mux",
                "max_streams": 8
            },
            "uuid": ""
}
```
From the official sing-box documentation:

>network
>Enabled network
>
>One of tcp udp.
>
>Both is enabled by default.

Even if this value is set from the server configuration, I don't think there's any reason for it to be set at all.
Please correct me if I'm missing something!

**Comment by M03ED** [comment]
because your using a `tcp+tls` inbound
this is xray default network

**Comment by tighnaridotme** [comment]
Ok, thank you, understood. The gist remains the same though:
Even if this value is generated from the server configuration, I don't think there's any reason for it to be set at all.

Yes, the server expects only tcp connections. but it just makes no sense for the client. All udp packets get encoded with xudp by default and sent via tcp anyways, am I right?

The default value is the expected behavior, other values are for very specific use cases (when you really don't want to route any udp traffic through the proxy).

**Comment by M03ED** [comment]
you sure config work if we remove this ?
because sing-box doesn't support tcp
No TCP transport, plain HTTP is merged into the HTTP transport.
https://sing-box.sagernet.org/configuration/shared/v2ray-transport/

**Comment by tighnaridotme** [comment]
You're looking in the wrong direction. This field is not related to transport. To my understanding the only thing that it's doing is restricting the input to the outbound by its protocol (tcp or udp).
That's what the documentation says:
https://sing-box.sagernet.org/configuration/outbound/vless/#network

And of course everything works the way it should when you leave this value on default (which means udp traffic gets encoded by xudp and sent via tcp).

**Comment by L4zzur** [comment]
Forcibly deleting the "network" key from dist `config` is expected to fix this problem, but you need to do a more competent check.

**Comment by M03ED** [comment]
done
