### ISSUE TITLE
Dev update

### ISSUE THREAD

**Issue by mhmdh94** [Gozargah/Marzban#1351]
after updating to the latest dev version I get this error in logs and the panel does not come up.

![image](https://github.com/user-attachments/assets/c3996654-0019-4b15-9d96-51c77dd5278b)

**Comment by mhmdh94** [comment]
![image](https://github.com/user-attachments/assets/1cf3b522-1f68-4177-ad9b-aa2fc930c49d)
![image](https://github.com/user-attachments/assets/b3c98d6c-39d0-496b-8e3f-ff5c2ccc0166)

**Comment by mhmdh94** [comment]
It happens from  commits on Oct 2, 2024.

**Comment by M03ED** [comment]
@ImMohammad20000 
This is what happens when you use a string without a character limit

**Comment by M03ED** [comment]
wait few minutes and try new version

**Comment by mhmdh94** [comment]
tried the new version, the panel comes up but when I click the host settings I get this error
@M03ED 

![image](https://github.com/user-attachments/assets/a2fb1e18-f641-4296-b08c-792579cac64a)

**Comment by M03ED** [comment]
fixed.
