### ISSUE TITLE
no other protocols available

### ISSUE THREAD

**Issue by dsfsad3123** [Gozargah/Marzban#1355]
no other protocols available,
How can I generate a configuration so that other protocols appear, manual configuration gives a timeout, perhaps because I’m new to this, I can’t write a config that will work
![Без имени](https://github.com/user-attachments/assets/00a3a87e-aac0-4a51-972d-1fe293c10134)

**Comment by M03ED** [comment]
Just edit your core settings and stop asking this type of questions
