### ISSUE TITLE
Users migration strategy when node gets blocked by censor.

### ISSUE THREAD

**Issue by lk-geimfari** [Gozargah/Marzban#1364]
First of all, I would like to thank you for the work you’ve done on this project. It’s truly an important and valuable contribution to the fight against censorship.

Is there any recommended strategy for quickly and seamlessly migrating users if the node they are on gets blocked by a censor based on its IP address?

If there is no automated solution for this task at the moment, have you considered adding such functionality?

**Comment by M03ED** [comment]
How you wanna do this ? 
User configuration is a local data that won't be updated until they do it or the app has an automatic update option.
The only way that may help you is using a domain instead of IP address.
