### ISSUE TITLE
Admin panel isn’t working

### ISSUE THREAD

**Issue by Mr-X-01** [Gozargah/Marzban#1370]
I’ve been trying to install Marzban on a clean server after the latest update, but the admin panel isn’t working. I’ve reinstalled everything five times, following all the instructions carefully, but the issue persists. I still can’t access the admin panel despite multiple attempts.

**Comment by M03ED** [comment]
Read the log , there is a full guide for you

**Comment by RelaxStation** [comment]
@Mr-X-01 I have the same issue. is your problem fixed?
marzban update works correctly from the previous version but the admin panel hasn't working on the clean server with the 0.7 version for 2 weeks ago
nothing shows on [IPADDRESS]:8000 
@M03ED is there any new log for the latest version?

**Comment by M03ED** [comment]
> @Mr-X-01 I have the same issue. is your problem fixed? marzban update works correctly from the previous version but the admin panel hasn't working on the clean server with the 0.7 version for 2 weeks ago nothing shows on [IPADDRESS]:8000 , also checked firewalls and anything related @M03ED is there any new log for the latest version?

for the last time, read the god damn logs

**Comment by Mr-X-01** [comment]
> @Mr-X-01 I have the same issue. is your problem fixed?
> marzban update works correctly from the previous version but the admin panel hasn't working on the clean server with the 0.7 version for 2 weeks ago
> nothing shows on [IPADDRESS]:8000 , also checked firewalls and anything related
> @M03ED is there any new log for the latest version?
> 

Install ssl
