### ISSUE TITLE
Add option to allow binding to 0.0.0.0 w/o SSL

### ISSUE THREAD

**Issue by datew0** [Gozargah/Marzban#1375]
**Is your feature request related to a problem? Please describe.**
With latest update to v0.7.0 I got unavoidable warning:
```
IMPORTANT!
You're running Marzban without specifying UVICORN_SSL_CERTFILE and UVICORN_SSL_KEYFILE.
The application will only be accessible through localhost. This means that Marzban and subscription URLs will not be accessible externally.

If you need external access, please provide the SSL files to allow the server to bind to 0.0.0.0. Alternatively, you can run the server on localhost or a Unix socket and use a reverse proxy, such as Nginx or Caddy, to handle SSL termination and provide external access.

If you wish to continue without SSL, you can use SSH port forwarding to access the application from your machine. note that in this case, subscription functionality will not work. 

Use the following command:

ssh -L 8000:localhost:8000 user@server

Then, navigate to http://127.0.0.1:8000 on your computer.
```

I run Marzban in k8s cluster behind Nginx Ingress Controller terminating SSL. Do you really suggest running another Nginx container in the same pod just to listen on 0.0.0.0 and forward traffic to localhost for Marzban? Or sharing an absolutely unnecessary volume with unix socket between Marzban and Ingress controller? No comments about port-forwarding using SSH ... So, workarounds provided in warning message are inconvenient.

**Describe the solution you'd like**
I think that forcing SSL when listening on 0.0.0.0 is good security practice, especially for newbies. But, please, do not limit Marzban deployment scenarios to bare-metal only. It would be great if You provide special environment variable, which allows insecure listening on 0.0.0.0 without SSL.

Thanks!

**Comment by M03ED** [comment]
> I run Marzban in k8s cluster behind Nginx Ingress Controller terminating SSL

if your using nginx what is your problem ?

**Comment by datew0** [comment]
Nginx is running in separate pod and doesn`t share network namespace with Marzban pod. Nginx forwards traffic inside cluster to Marzban over HTTP

**Comment by ImMohammad20000** [comment]
> Nginx is running in separate pod and doesn`t share network namespace with Marzban pod. Nginx forwards traffic inside cluster to Marzban over HTTP

You can use socket file

UVICORN_UDS = /var/lib/marzban/marzban.socket

**Comment by M03ED** [comment]
Done?

**Comment by datew0** [comment]
> > Nginx is running in separate pod and doesn`t share network namespace with Marzban pod. Nginx forwards traffic inside cluster to Marzban over HTTP
> 
> You can use socket file
> 
> UVICORN_UDS = /var/lib/marzban/marzban.socket

For what? According your advice I need to place socket on shared volume between Nginx Ingress and Marzban pod. But sharing volume across namespaces is not supported in k8s.

**Comment by harukodi** [comment]
Nice update!

**Comment by M03ED** [comment]
> Nice update! moving on!
> 

If you have any complaint, you can sent it to @rprx

**Comment by harukodi** [comment]
You mean that the author of xray core made this SSL enforcement?

**Comment by M03ED** [comment]
> You mean that the author of xray core made this SSL enforcement? 

Yeap

**Comment by harukodi** [comment]
In what commit would that be could you give me a link to inspect this?

**Comment by M03ED** [comment]
https://github.com/XTLS/Xray-core/pull/3884

**Comment by RPRX** [comment]
宿主机的 IP 是 172.17.0.1？

**Comment by coyotle** [comment]
Same problem with Docker. After last update  marzban in docker container is unreacheable

**Comment by harukodi** [comment]
I would recommend moving to the Xray/Teddysun Docker container. It doesn't have a GUI, but the recent changes have made Marzban in Docker containers very unreliable.

**Comment by RPRX** [comment]
比如，如果在容器内看宿主机的 IP 是 172.17.0.1，那么可以仅监听这个地址，解决容器外无法访问的问题

**Comment by PoluektovArtur** [comment]
So, which solution for that problems?

I've tried to add self signed cert and put it into environment variables, but when i started docker compose i got error message, that my certs is self signed and it's not correct

**Comment by harukodi** [comment]
> So, which solution for that problems?
> 
> I've tried to add self signed cert and put it into environment variables, but when i started docker compose i got error message, that my certs is self signed and it's not correct

Have you tried to use cloudflares certs?

**Comment by harukodi** [comment]
> So, which solution for that problems?
> 
> I've tried to add self signed cert and put it into environment variables, but when i started docker compose i got error message, that my certs is self signed and it's not correct

![{BBB31104-0F88-4EAB-9F78-82F5B0F8D7F0}](https://github.com/user-attachments/assets/3a18810c-f88d-4f5c-9d7c-de80a43a7584)

**Comment by harukodi** [comment]
This may be a way to bypass that ssl verification, you can set the ssl expiry date to like 10 years or 15 years if you wish not to update it with acme every 3d month or so. Have not tested if this works but may be a fix for now

**Comment by PoluektovArtur** [comment]
> > Итак, какое же решение этой проблемы?
> > Я попытался добавить самоподписанный сертификат и поместить его в переменные среды, но когда я запустил Docker Compose, я получил сообщение об ошибке, что мой сертификат самоподписанный и это неправильно.
> 
> Вы пробовали использовать сертификаты Cloudflares?

no, thanks, i'll try it and return with feedback :)

**Comment by SaintShit** [comment]
Marzban container is running with `network_mode: host` by default, allowing it to share the host's network stack.
https://github.com/Gozargah/Marzban/blob/75bcdd98825b4d44a206e78871a9d3cd81af0dfb/docker-compose.yml#L6

If you have changed this configuration, you might need to use port mapping to expose the necessary ports for the Marzban container.

**Comment by SaintShit** [comment]
Also, you might use caddy, which is easy to set up and automatically manages SSL.

```
your-domain.com {
    reverse_proxy 127.0.0.1:PORT_OF_YOUR_PANEL
}
```

This will generate an SSL certificate for your-domain.com automatically.

**Comment by harukodi** [comment]
Why do I need to have my panel publicly facing the Internet tho? This allows others to try to sign in to the panel? Before this ssl validation the panel was not publicly facing and yes sure the subscriptions links did not work but i did have the option to just create a route for it using caddy

**Comment by PoluektovArtur** [comment]
> > Итак, какое же решение этой проблемы?
> > Я попытался добавить самоподписанный сертификат и поместить его в переменные среды, но когда я запустил Docker Compose, я получил сообщение об ошибке, что мой сертификат самоподписанный и это неправильно.
> 
> Вы пробовали использовать сертификаты Cloudflares?

This way is not for me, unfortunatly
I dont have domen, only IP address of my server. Cloudflares requires domen name

**Comment by M03ED** [comment]
> This way is not for me, unfortunatly I dont have domen, only IP address of my server. Cloudflares requires domen name

paying 1$ for 1 year, too expensive

**Comment by Platun0v** [comment]
I also faced problems after update. I use traefik as reverse proxy and it doesnt support unix sockets as a backend. So I had to configure ssl to use the service. I think it should be way for user to use 0.0.0.0 host without certs
