### ISSUE TITLE
اضافه کردن نمونه اینباند وایرگارد به داکیومنت مرزبان

### ISSUE THREAD

**Issue by farshadl** [Gozargah/Marzban#1376]
لطفا نمونه اینباند وایرگارد را به قسمت document مرزبان اضافه کنید

با تشکر

**Comment by M03ED** [comment]
وایرگارد در مرزبان پشتیبانی نمیشه ، میتونید خودتون به صورت دستی هر تعداد یوزر بخواهید اضافه کنید ولی مدیریتی بر جچم مصرفی اون ها وجود نداره
