### ISSUE TITLE
مشکل ERROR: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by k60380796** [Gozargah/Marzban#1380]
سلام
هر کاری میخام تو دیتابیس انجام بدم این ارور رو میده:
ERROR: FOREIGN KEY constraint failed

چیکارش کنم؟

**Comment by M03ED** [comment]
دلیلش اینه که شما نباید بدون دانش SQL دستی از دیتابیس چیزی رو تغییر بدید ، دلیل اینکه با این ارور مواجه می شید هم همین هست و یک سری موارد رو تو کوئری ها تون در نظر نمی گیرید
