### ISSUE TITLE
ClashMeta Bugs: Mux & HTTPUpgrade

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#1384]
Problem 1: Mux is disabled in mux template for clash meta (but enabled at host settings), mux will be enabled at clash meta config
Xray server does not support any mux except mux.cool, idk how clashmeta can still connect to my server using h2mux! maybe they have a fallback to disable mux if it's not supported by the server

Problem 2: HTTPUpgrade config does not work with ClashMeta, something must be wrong
I have tested with and without early data, none of them worked

**Comment by ImMohammad20000** [comment]
Pr would be welcome.

**Comment by mrkonaymyoaung** [comment]
same bug here
