### ISSUE TITLE
 مشکل قطعی در آپدیت جدید مرزبان Bug title

### ISSUE THREAD

**Issue by hayousef68** [Gozargah/Marzban#1387]
سلام . من چهادتا تا سرور دارم رو همشون مرزبان دارم .یکی از سرور هامو چند روز پیش آپدیت کردم وژن جدید مرزبان از روزی ک‌آپدیت کردم هر روز ساعت ۱۲ شب قطع میشه یکبار باید مرزبان رو ریستارت کنم اوکی بشه .اسکریپت مرزبان ریستارت خودکار رو هم‌گذاشتم روی ۲ ساعت بازم جواب نداد

**Comment by ImMohammad20000** [comment]
سلام
ورژن xray رو بیارید پایین روی 1.8.24 بزارید

**Comment by hayousef68** [comment]
> سلام ورژن xray رو بیارید پایین روی 1.8.24 بزارید

ببخشید از کدوم قسمت باید این کارو بکنم چون تا حالا انجام ندادم بلد نیستم

**Comment by ImMohammad20000** [comment]
> > سلام ورژن xray رو بیارید پایین روی 1.8.24 بزارید
> 
> ببخشید از کدوم قسمت باید این کارو بکنم چون تا حالا انجام ندادم بلد نیستم

https://gozargah.github.io/marzban/fa/examples/change-xray-version

**Comment by M03ED** [comment]
مشکل حل شد ؟

**Comment by hayousef68** [comment]
> مشکل حل شد ؟

دانگرید کردم به وژن ۶ اوکی شد

**Comment by M03ED** [comment]
پس مشکل شما از مرزبان نبوده و از xray هست
چون ورژن 6 از نسخه قدیمی تر xray استفاده می کنه
