### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by mrkonaymyoaung** [Gozargah/Marzban#1393]
**Describe the bug**
Marzban Login Dashboard is too loading and can't login.
![Screenshot 2024-10-22 233502](https://github.com/user-attachments/assets/1ba3d8f8-f9c6-4636-9e17-4b16b7c499fd)

**Comment by ImMohammad20000** [comment]
Send panel logs

**Comment by mrkonaymyoaung** [comment]
> Send panel logs

How I Show Panel Logs Sir?
Please Help Me

**Comment by ImMohammad20000** [comment]
marzban logs

**Comment by mrkonaymyoaung** [comment]
> marzban logs

![Screenshot 2024-10-23 001127](https://github.com/user-attachments/assets/3c0734cb-ec60-4f37-a3c4-29cdcb452fd4)
Here Sir

**Comment by ImMohammad20000** [comment]
You have to use ssl

**Comment by ImMohammad20000** [comment]
https://gozargah.github.io/marzban/fa/examples/issue-ssl-certificate

**Comment by mrkonaymyoaung** [comment]
> https://gozargah.github.io/marzban/fa/examples/issue-ssl-certificate

Thanks For Your Replying Brother, I Don't have any register domain. Can I Use SSL Without Domain. Plz Answer Brother

**Comment by ImMohammad20000** [comment]
Buy a domain

**Comment by mrkonaymyoaung** [comment]
> Buy a domain

![Screenshot_2024-10-23-01-25-11-012_com termux-edit](https://github.com/user-attachments/assets/42c213cb-968b-49d3-b9a0-22fc262f302f)
still nor working Sir 😔

**Comment by iamtheted** [comment]
> > Buy a domain
> 
> ![Screenshot_2024-10-23-01-25-11-012_com termux-edit](https://github.com/user-attachments/assets/42c213cb-968b-49d3-b9a0-22fc262f302f)
> still nor working Sir 😔 

You need to pay dollars so someone would teach you.

**Comment by mrkonaymyoaung** [comment]
> > > Buy a domain
> > 
> > 
> > ![Screenshot_2024-10-23-01-25-11-012_com termux-edit](https://private-user-images.githubusercontent.com/127788452/378983126-42c213cb-968b-49d3-b9a0-22fc262f302f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODQ4NTcsIm5iZiI6MTcyOTY4NDU1NywicGF0aCI6Ii8xMjc3ODg0NTIvMzc4OTgzMTI2LTQyYzIxM2NiLTk2OGItNDlkMy1iOWEwLTIyZmMyNjJmMzAyZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxMTU1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTkzNzU0MDNmZjdlNzQyYTJkNDg3MTcyN2MwNjMxZTQzNmZjMmYwNDllMDBkZGQxYzc3YjI0N2IxZDAzYmMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dldIacFe8UQi5fA_mCRjFiVmctLDmMvXLFwlMJ_EviU)
> > still nor working Sir 😔
> 
> You need to pay dollars so someone would teach you.

Thanks bro, I got it back.😃
