### ISSUE TITLE
Dashboard Page cannot load after Update 

### ISSUE THREAD

**Issue by mrkonaymyoaung** [Gozargah/Marzban#1394]
![Screenshot_2024-10-23-01-25-11-012_com termux-edit](https://github.com/user-attachments/assets/642b46e7-7bd2-4488-b89c-90d8af596bf5)
![Screenshot_2024-10-23-01-25-55-534_com android chrome](https://github.com/user-attachments/assets/b1021b73-4d4f-41c4-863b-71fb51671173)
Here is my marzban logs after ssl enable by using caddy but still it's not working to my dashboard access. please fix and help me sir

**Comment by amiredi** [comment]
آره درسته.من سرور جدید گرفتم مرزبان نصب میشه همه چی اوکیه ولی پنل بالا نمیاد کلا

**Comment by esodrevo** [comment]
نسخه اخر اگر سرت نگیرید پنل بالا نمیاد ، اپشن امنیتیه اضافه شده، ارتباط فقط بصورت https مجازه

**Comment by esodrevo** [comment]
> ![Screenshot_2024-10-23-01-25-11-012_com termux-edit](https://private-user-images.githubusercontent.com/127788452/378982154-642b46e7-7bd2-4488-b89c-90d8af596bf5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MzA2NDUsIm5iZiI6MTcyOTYzMDM0NSwicGF0aCI6Ii8xMjc3ODg0NTIvMzc4OTgyMTU0LTY0MmI0NmU3LTdiZDItNDQ4OC1iODljLTkwZDhhZjU5NmJmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQyMDUyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmZmMjk1NDhjZDI5MDJjMDBmMTkzNGMzYzRmNDJmYjQ2MmM0MTZhM2ZhNGVlMzhkNDg2OWVmZWFkMzVmYWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.klMflOBnLUGnnvc50wIwuiBNsTHb-wUqRCz3OqmLlj8) ![Screenshot_2024-10-23-01-25-55-534_com android chrome](https://private-user-images.githubusercontent.com/127788452/378982186-b1021b73-4d4f-41c4-863b-71fb51671173.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MzA2NDUsIm5iZiI6MTcyOTYzMDM0NSwicGF0aCI6Ii8xMjc3ODg0NTIvMzc4OTgyMTg2LWIxMDIxYjczLTRkNGYtNDFjNC04NjNiLTcxZmI1MTY3MTE3My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQyMDUyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2VlMzYxOGJkN2I3MDUyMWJjYTVkNDcwNzI5NTQxY2M3NWRkNzkwYmQ3ZjQxM2RlZmIxNzQ2YjhkMTkyMmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QBqiTu96glZ9_xszBi6d2xfp7D8utfsFbBvGv-zaM1U) Here is my marzban logs after ssl enable by using caddy but still it's not working to my dashboard access. please fix and help me sir

http connection is forbidden in 0.7.0,  thats why you have loading issue,  get certificate and use https connection

**Comment by M03ED** [comment]
> Here is my marzban logs after ssl enable by using caddy but still it's not working to my dashboard access. please fix and help me sir

how you get ssl without a domain ?

**Comment by siamakdals** [comment]
خب من ریدم تو این تغییرات که ی اپشن برا غیرفعال کردن ssl نذاشتن
کدوم احمقی اینو اضافه کرده
شاید یکی بخواد صرفا برا خودش نصب کنه و حوصله گرفتن ssl نداشته باشه

**Comment by M03ED** [comment]
> خب من ریدم تو این تغییرات که ی اپشن برا غیرفعال کردن ssl نذاشتن
> کدوم احمقی اینو اضافه کرده
> شاید یکی بخواد صرفا برا خودش نصب کنه و حوصله گرفتن ssl نداشته باشه

مرسی از اینکه پنل رو مفتی استفاده می کنید ، درآمد کسب می کنید و بعد توهین می کنید
اگر کسی بخواهد برای خودش ران کنی می‌تونه به راحتی و با ssh وصل بشه

**Comment by mrkonaymyoaung** [comment]
> > Here is my marzban logs after ssl enable by using caddy but still it's not working to my dashboard access. please fix and help me sir
> 
> how you get ssl without a domain ?

use caddy bro. you can read in marzban doc. use domain instead of your ip like http://192.168.1.1

**Comment by M03ED** [comment]
> use caddy bro. you can read in marzban doc. use domain instead of your ip like http://192.168.1.1

If you made a new version of tls that can work with ip instead of domain, yeah that's possible.

**Comment by siamakdals** [comment]
> > خب من ریدم تو این تغییرات که ی اپشن برا غیرفعال کردن ssl نذاشتن
> > کدوم احمقی اینو اضافه کرده
> > شاید یکی بخواد صرفا برا خودش نصب کنه و حوصله گرفتن ssl نداشته باشه
> 
> مرسی از اینکه پنل رو مفتی استفاده می کنید ، درآمد کسب می کنید و بعد توهین می کنید اگر کسی بخواهد برای خودش ران کنی می‌تونه به راحتی و با ssh وصل بشه

دوست عزیز من به درک
چیزی که اینقدر استفاده داره نباید تغییرات وحشتناکی مثل این یهویی ایجاد بشن
اونم بدون آموزش یا آموزش اشتباهی که کار نمیکنه
بهتره این تغییرات با تصمیم جمعی صورت بگیره  و اعمال شه
نه صرفا با نظر و سود یک نفر

**Comment by M03ED** [comment]
> دوست عزیز من به درک چیزی که اینقدر استفاده داره نباید تغییرات وحشتناکی مثل این یهویی ایجاد بشن اونم بدون آموزش یا آموزش اشتباهی که کار نمیکنه بهتره این تغییرات با تصمیم جمعی صورت بگیره و اعمال شه نه صرفا با نظر و سود یک نفر

حتما شما هم از اون دسته افرادی هستید که داکیومنت مرزبان رو هم نخونده و میگه که آموزش داده نشده ، چون اموزش دریافت SSL به 3 روش نوشته شده 
میتونم بپرسم این سودی که گفتید چی هست و اگر مالیه چقدره ؟ چون تا جایی که من میدونم دونیتی به مرزبان انجام نمیشه

**Comment by M03ED** [comment]
شما اگر فکر می کنسد سود این کار زیاده خودتون دست به کار شید ، یه پروژه بهتر ایجاد کنید و سود ها رو برای خودتون بردارید

**Comment by waxilu** [comment]
thanks for topic, I change my version to v0.6.0 and it solved.
That's stupid change from Marzban team!

**Comment by M03ED** [comment]
> thanks for topic, I change my version to v0.6.0 and it solved.
> That's stupid change from Marzban team!
> 

You're welcome , enjoy using http and not getting new features.
