### ISSUE TITLE
Issue with installing or updating version 7.0

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#1401]
I previously upgraded the central control panel to version 7, but the designated port for accessing the panel remained completely inactive. I also attempted a quick deployment on a fresh server instance, but again, the port didn’t open, and the panel was inaccessible.

I’ve also checked [this page](https://github.com/Gozargah/Marzban/issues/1400
), but the issue remains unresolved:

Are there any specific configurations or server-side adjustments required with this new panel version that I might have overlooked?

**Comment by M03ED** [comment]
if there is a issue that is not solved and you have same problem why you open new issue ? just use last one 
also i send a solution and he didn't respond after that

**Comment by yaramahmadi** [comment]
> if there is a issue that is not solved and you have same problem why you open new issue ? just use last one
> also i send a solution and he didn't respond after that

Thank you for your response.  

The previous issue was only related to the update from version 6 to 7, and that’s why I opened a new issue—my problem also involves a fresh installation of version 7.  

If opening a new issue was incorrect, I apologize.
