### ISSUE TITLE
غیر فعال کردن ارسال گزارش ورود در ربات تلگرام

### ISSUE THREAD

**Issue by amirhr098** [Gozargah/Marzban#1404]
سلام وقت بخیر. ربات تلگرام بعد از فعال شدن راهی برای غیر فعال کردن ارسال گزارش ورود نداره. من چون ربات فروش دارم و هر چند دقیقه لاگین میکنه، همش برای پیام ارسال میشه. راهی نیست بشه غیر فعالش کرد؟

**Comment by M03ED** [comment]
بات تلگرام تون رو فیکس کنید

**Comment by ImMohammad20000** [comment]
توی فایل .env اینو بزار

NOTIFY_LOGIN = false
