### ISSUE TITLE
Clash Config File Smux Option is WRONG

### ISSUE THREAD

**Issue by Mars160** [Gozargah/Marzban#1408]
**Describe the bug**
The Smux in Marzban is under tcp-opts
But as the docment shows, it should under the proxies.

**Screenshots**

![image](https://github.com/user-attachments/assets/4ea98560-111d-4795-a5d5-0110b1ca1d63)

![image](https://github.com/user-attachments/assets/d17fac65-0284-4cd7-bf97-6f35b617771f)

**Comment by ImMohammad20000** [comment]
Send document link

**Comment by Mars160** [comment]
https://wiki.metacubex.one/config/proxies/
