### ISSUE TITLE
Cannot bind to port 443, occupied by haproxy

### ISSUE THREAD

**Issue by ByteNode1** [Gozargah/Marzban#1411]
I've bought domain recentely, created client ssl from cloudflares for it, added ssl into .env file. What should I do next?
I tried to bind marzban to 443 port, then got this error. Occupied by haproxy
![image](https://github.com/user-attachments/assets/e92335f5-7530-4b4b-b021-0270eb24151d)
I've also binded it to default port and tried to access dashboard like `mydomain.com:8000/dashboard `
What am I doing wrong?

**Comment by ByteNode1** [comment]
> as you said port is already in use disable it or use another port , you should know cloudflare support few port for https, just use one of them

I tried to use 2096 port, which is one of other cloudflare's https ports, but marzban don't uses it
![image](https://github.com/user-attachments/assets/fcb379f1-516e-4e65-8a26-7fb99c1dadf8)

**Comment by M03ED** [comment]
i'm sure there is something wrong with your configuration
