### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by subzero911** [Gozargah/Marzban#1412]
**Describe the bug**
I can't connect to the control panel. I could do it before.

On Windows:

![image](https://github.com/user-attachments/assets/c6e2df8b-b4a6-4330-988f-95992380de30)

When I try connecting on Mac OS, login form appears (with an "unsafe" label in the address line), but when I enter login and password, the "enter" button doesn't work.

<img width="490" alt="image" src="https://github.com/user-attachments/assets/afade1d9-ce71-4dc5-b8c2-92921c2061cd">

**Machine details (please complete the following information):**
 - OS: Ubuntu Server 24.04 64bit
 - Python version: 3.12.3
- Nodejs version: not installed
- Browser: Chrome, Safari

**Comment by M03ED** [comment]
there is something called logs, you can check there

**Comment by subzero911** [comment]
> there is something called logs, you can check there

What exactly should I check?

**Comment by subzero911** [comment]
![image](https://github.com/user-attachments/assets/c285ac3a-f999-4fb7-b283-1c96fdcc724e)

Here are logs

**Comment by M03ED** [comment]
you don't have ssl, get ssl and set it up or use ssh tunnel, if your using ssh currently check logs when you press login and see what happen in server

**Comment by subzero911** [comment]
It asks for SSL certfile... but i don't want to buy a domain name.
I always entered the admin panel just by IP and port.

**Comment by M03ED** [comment]
> It asks for SSL certfile... but i don't want to buy a domain name. I always entered the admin panel just by IP and port.

its 1$ per year , if you can't afford it, just use ssh

**Comment by subzero911** [comment]
I checked the logs and nothing happened when I press login

**Comment by M03ED** [comment]
so what you see on your mac device is cashed data
