### ISSUE TITLE
Splithttp host header bug in custom configuration

### ISSUE THREAD

**Issue by mdjvd** [Gozargah/Marzban#1413]
If you have enabled v2ray custom config and use Splithttp network, the host header you set in host settings will not be included in the generated configuration. Adding the host header directly in the core configuration will not solve the problem either.
I have tested both TLS and non-TLS configurations; no difference.
There is no such issue on WS or HU networks.

**Comment by ImMohammad20000** [comment]
Send your configuration

**Comment by mdjvd** [comment]
Server configuration:
```json
    {
      "tag": "VLESS_SH",
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "splithttp",
        "splithttpSettings": {
          "path": "/sh"
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    },
```
I have set the host header in the host settings in the configuration above. And also enabled TLS from host settings. (It's the same story with non-TLS)

Client Config:
```json
 "outbounds" : [
    {
      "protocol" : "vless",
      "settings" : {
        "vnext" : [
          {
            "address" : "1.1.1.1",
            "port" : 443,
            "users" : [
              {
                "encryption" : "none",
                "id" : "2s9b4cf7-2g71-4dc9-a54b-e1x48b4aef64"
              }
            ]
          }
        ]
      },
      "streamSettings" : {
        "network" : "splithttp",
        "security" : "tls",
        "splithttpSettings" : {
          "headers" : {
            "Pragma" : "no-cache"
          },
          "path" : "/sh",
          "scMaxConcurrentPosts" : 100,
          "scMaxEachPostBytes" : 1000000,
          "scMinPostsIntervalMs" : 30,
          "xPaddingBytes" : "100-1000"
        },
        "tlsSettings" : {
          "allowInsecure" : false,
          "alpn" : [
            "h2"
          ],
          "serverName" : "my.domain.com"
        }
      },
      "tag" : "proxy"
    },
```


But also tried putting the host header in the server config, but no difference:
```json
      "streamSettings": {
        "network": "splithttp",
        "splithttpSettings": {
          "path": "/sh",
          "headers": {
            "host": "my.domain.com"
          }
        }
      },
```

**Comment by ImMohammad20000** [comment]
When you set host in hosts settings it not set custom config?

**Comment by mdjvd** [comment]
Both when host header is set in core configuration and when it is set in host settings, it will be ignored and not included in custom configuration.
This issue doesn't exist if you don't have custom configuration enabled.

**Comment by ImMohammad20000** [comment]
read the documents for splithttp : https://xtls.github.io/en/config/transports/splithttp.html

**Comment by mdjvd** [comment]
I don't understand how it is related to this issue.
Are you saying it's normal not to have a host header in custom configuration?

**Comment by ImMohammad20000** [comment]
Host not configure in headers it hase it own variable 
The other problem you have with headers i'll check it sone

**Comment by mdjvd** [comment]
Oh, I see. I also tried this according to the doc:
```json
        "splithttpSettings": {
          "path": "/sh",
          "host": "my.domain.com"
```
But again there is no host in the client config. 
Anyway, thanks.

**Comment by ImMohammad20000** [comment]
This problem is fixed in dev version
