### ISSUE TITLE
مشکل نصب مرزبان

### ISSUE THREAD

**Issue by mohamadm0meni** [Gozargah/Marzban#1419]
![image](https://github.com/user-attachments/assets/6e4d61c9-9b09-4bbc-8801-81609b46d3dd)

سرور هتزنر هست وقتی نصب میکنم و تمام میشود پنل بالا نمیاد تفاوتی که با بقیه دیدم داخل لاگ ها این بود 
marzban-1  | INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

برای من اینه 
ولی برای بقیه
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by mohamadm0meni** [comment]
![image](https://github.com/user-attachments/assets/5715dff8-5948-41fa-a6c0-45351e43924c)

**Comment by ImMohammad20000** [comment]
سلام باید ssl بگیرید

**Comment by mohamadm0meni** [comment]
> سلام باید ssl بگیرید

درست شد خیلی ممنونم
