### ISSUE TITLE
Add XMUX pattern to the Host Settings section or Template for that.

### ISSUE THREAD

**Issue by deepsm0ke** [Gozargah/Marzban#1421]
Hello to marzban team.

please add XMUX pattern to the host settings section or Template for that..
XMUX allows user to control SplitHTTP multiplexing behavior between h2 and h3 [Xray v24.9.19+] (Client-side ONLY !).
The parameters and default values are :

"xmux": {
    "maxConcurrency": 0,
    "maxConnections": 0,
    "cMaxReuseTimes": 0,
    "cMaxLifetimeMs": 0
}

And if your team choose add it to the host settings the correct pattern example can be as follows:
maxConcurrency,maxConnections,cMaxReuseTimes,cMaxLifetimeMs = 0,0,0,0 .

Thanks.

**Comment by M03ED** [comment]
you can set it in settings.json
