### ISSUE TITLE
Logs file address?

### ISSUE THREAD

**Issue by ehssanehs** [Gozargah/Marzban#1430]
سلام
داخل فایل کانفیگ رو به این صورت تنظیم کردم تا لاگها در فایل سیو شود.
`"log": {
    "loglevel": "info",
    "access": "access.log",
    "error": "error.log"
  },`
ولی فایل access.log رو پیدا نمی کنم.
میشه بدونم در چه آدرسی سیو میشه؟ و یا اینکه چطور دسترسی داشته باشم بهش
سپاس

**Comment by M03ED** [comment]
same address as your xray core file, if you don't know where is it use absolute path not relative
