### ISSUE TITLE
Error installing certificate (fullchain.cer / fullchain.pem)

### ISSUE THREAD

**Issue by hawshemi** [Gozargah/Marzban#144]
When the domain SSL is completed only the file `fullchain.cer` is created not `fullchain.pem`.

There is no `fullchain.pem` file in the directory.
I tried manually copying it in the `/var` directory with `cer` and `pem` formats but the dashboard won't open.

![cert-error](https://user-images.githubusercontent.com/16742123/228262027-113ff062-5f78-4378-af47-41e8b208d011.png)

**Comment by SaintShit** [comment]
![image](https://user-images.githubusercontent.com/118110306/228263659-8c651f32-4068-4638-8497-99866c9072a4.png)
