### ISSUE TITLE
Hysteria 2 External Config is not Appearing in Sing-Box

### ISSUE THREAD

**Issue by ByteMysticRogue** [Gozargah/Marzban#1454]
**Describe the bug**
I added the Hy2 External Config to the .env file. However, the configuration is not being decoded into the Singbox format as expected. But, it works fine with Streisand.

**Expected behavior**
Expected to see decode the hy2 config to singbox and extend the config list.

**Machine details (please complete the following information):**
I'm using the latest stable version of Marzban.

**Comment by M03ED** [comment]
the guy who add this feature couldn't use reverse engineering to make external config work for all clients (low skill).
because of this he just add it for v2ray links (not even json format) and it's not available for other clients.
this option may be removed in feuture.

**Comment by ByteMysticRogue** [comment]
but its useful to have this feature. maybe with some code refactoring.

**Comment by M03ED** [comment]
> but its useful to have this feature. maybe with some code refactoring.

there is nothing to refactor 
you need to write it from zero
