### ISSUE TITLE
Host switch doesn't display

### ISSUE THREAD

**Issue by rorosin** [Gozargah/Marzban#1459]
**Describe the bug**
No switch on any hosts of this server

**To Reproduce**
1. Go to Hosts dialog
2. Select any host

**Expected behavior**
I've excepted to see this switch :)

**Screenshots**
![image](https://github.com/user-attachments/assets/2d6995c6-6196-48a9-81e1-22f2de1266c2)

**Machine details:**
- Marzban v0.7.0
- OS Ubuntu 24.04
- Python v3.10.12
- Nodejs v21.7.3
- Browser Yandex for iOS

**Additional context**
-

**Comment by rorosin** [comment]
This is how it looks on other my servers.![image](https://github.com/user-attachments/assets/af25c877-6906-4e66-8003-3fcd58c7ee65)

**Comment by M03ED** [comment]
your using old version

**Comment by rorosin** [comment]
version is 0.7.0

I guess issue is with caching on browser's side, as on PC switch is there.
