### ISSUE TITLE
Update username column length to 36 characters

### ISSUE THREAD

**Issue by zapolnoch** [Gozargah/Marzban#1466]
The current length of the username column is set to [34 characters](https://github.com/Gozargah/Marzban/blob/master/app/db/models.py#L38):
`username = Column(String(34, collation='NOCASE'), unique=True, index=True)`

It would be better to increase this to 36 characters to accommodate UUIDs, which are 36 characters long.

`username = Column(String(36, collation='NOCASE'), unique=True, index=True)`

This ensures compatibility with UUIDs without truncation.

**Comment by M03ED** [comment]
Username is separated from uuid 
Also if you use uuid as username it can affect so much on search function and make it slow , search by uuid is one of things you should avoid as you can

**Comment by M03ED** [comment]
if you don't have any other question, close the issue
