### ISSUE TITLE
SplitHTTP removed from v2rayN v7.2.1+

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#1470]
![image](https://github.com/user-attachments/assets/c9de6832-ae1b-4e84-8860-9d683df3dfeb)
![image](https://github.com/user-attachments/assets/3cf81245-fd3f-4c50-83ac-9dfdb1c29483)

**Comment by ImMohammad20000** [comment]
We need to have that for backward compatiblity

**Comment by ImMohammad20000** [comment]
> Problem is that v2rayN 7.2.1+ can't connect to SplitHTTP configs because it's old transport name is completely removed

It's not our problem they should fix it in there app
