### ISSUE TITLE
multiple head revisions (dev)

### ISSUE THREAD

**Issue by mdjvd** [Gozargah/Marzban#1473]
I've Just updated to the last version of "dev" branch, and got this:

![image](https://github.com/user-attachments/assets/4169f469-2373-40a8-8499-04897a0d0453)
![image](https://github.com/user-attachments/assets/c61ce570-774d-49f5-9459-7750569e72bc)
![image](https://github.com/user-attachments/assets/3b71d971-4bfe-452f-99fe-e0e0e8aee09e)

Restarting marzban will not solve the problem. Merging the two branches into one would solve the issue in the first picture and changes in database tables are made, but the issue in second and third pictures are remaining. I don't know if merging those two were the right move but now I used my backup to go to the last version I was at.

**Comment by ImMohammad20000** [comment]
Send logs as test

**Comment by ImMohammad20000** [comment]
Wait a few minutes and update the panel

**Comment by mdjvd** [comment]
It's fixed now. Thank you :)
