### ISSUE TITLE
GET /api/user_template/{id} fails

### ISSUE THREAD

**Issue by vilsbole** [Gozargah/Marzban#1477]
Calling `/api/user_template/{id}` fails with the error: 
```
{"detail":{"template_id":"field required"}} 
```

Indeed `get_user_template` [expects](https://github.com/Gozargah/Marzban/blob/75bcdd98825b4d44a206e78871a9d3cd81af0dfb/app/dependencies.py#L58) a `template_id` argument, while the route [declares](https://github.com/Gozargah/Marzban/blob/75bcdd98825b4d44a206e78871a9d3cd81af0dfb/app/routers/user_template.py#L35) the path parameter as `id`. 

The change was introduced during the routes refactor: https://github.com/Gozargah/Marzban/commit/6918f7fa09e460a123578266920113037637e3c2#diff-ed802903465b7c70a1d639a86b8eeec5304f98e8631a634cf95951326b0b038eR36
Can I submit a PR to fix this ?

**Comment by M03ED** [comment]
oh shit, another bug created by a low skill guy
yes you can submit a pr

**Comment by M03ED** [comment]
> Erfjab submit a PR to fix this bugs but they closed that.
> #1426 

Yeah he was trying to destroy his perfect refactor.

**Comment by vilsbole** [comment]
Here it is: https://github.com/Gozargah/Marzban/pull/1483
