### ISSUE TITLE
Can`t install Marzban

### ISSUE THREAD

**Issue by yuhapl** [Gozargah/Marzban#1478]
**Describe the bug**
I cant install Marzban

**To Reproduce**
1. Wipe VM
2. apt update && apt upgrade -y && reboot
3. sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install

**Expected behavior**
I can't install it. I take the command from the main github branch

**Screenshots**
![image](https://github.com/user-attachments/assets/84ab65a1-03ae-4243-8bf2-2c77d6a4f29b)

**Machine details (please complete the following information):**
 - OS:  Ubuntu 24.04.1 LTS x86_64
- Python version: 3.12.3
- Nodejs version: i dont know

**Additional context**

**Comment by ImMohammad20000** [comment]
try this one 
sudo bash -c "$(curl -sL https://github.com/DigneZzZ/Marzban-scripts--n/blob/patch-1/marzban.sh)" @ install

**Comment by yuhapl** [comment]
Install Marzban with MySQL:

sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install --database mysql
Install Marzban with MariaDB:

sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install --database mariadb

if you need SQLite:

sudo bash -c "$(curl -sL https://github.com/DigneZzZ/Marzban-scripts-beta/raw/main/marzban.sh)" @ install
