### ISSUE TITLE
notifications bot

### ISSUE THREAD

**Issue by mohsenzt** [Gozargah/Marzban#1480]
درود اوقات به کام
چطور میتونم قبل از اتمام حجم یا تاریخ اعلان دریافت کنم
Customize all notifications
NOTIFY_STATUS_CHANGE = True
NOTIFY_USER_CREATED = false
NOTIFY_USER_UPDATED = false
NOTIFY_USER_DELETED = false
NOTIFY_USER_DATA_USED_RESET = false
NOTIFY_USER_SUB_REVOKED = True
NOTIFY_IF_DATA_USAGE_PERCENT_REACHED = True
NOTIFY_IF_DAYS_LEF_REACHED = True
NOTIFY_LOGIN = false
NOTIFY_DAYS_LEFT = 3
NOTIFY_REACHED_USAGE_PERCENT = 85
من از این موارد رو در فایل .env قرار دادم اما قبل از اتمام حجم و تاریخ ربات بهم اطلاع نمیده

**Comment by M03ED** [comment]
این موارد ربطی به ربات تلگرام ندارن و مربوط به وب هوک هست

**Comment by mohsenzt** [comment]
وقتی تغییرشون میدم تو اعلان های ربات تاثیر میزاره
