### ISSUE TITLE
minor updates

### ISSUE THREAD

**Issue by esodrevo** [Gozargah/Marzban#1481]
Hi, it would be great if Marzban could release minor updates more frequently and add new configurations, such as new transports, to the latest version more quickly. For example, the xhttp transport is currently available in the dev version, but it takes a long time to be added to the latest version.
Please apply xray configuration changes promptly. As for panel updates and future features, it's fine if they take some time.

**Comment by ImMohammad20000** [comment]
There is some bugs when there fixed we release a new version
