### ISSUE TITLE
Can`t install Marzban

### ISSUE THREAD

**Issue by yvnveligon** [Gozargah/Marzban#1482]
**I cant install Marzban**

`Error: bad expression, please check expression syntax`

pls, fix it
<img width="474" alt="Screenshot 2024-12-03 at 17 31 08" src="https://github.com/user-attachments/assets/49eee152-72ad-47c2-a021-fe902981fc18">

**Comment by ImMohammad20000** [comment]
test this command
```bash
sudo bash -c "$(curl -sL https://github.com/DigneZzZ/Marzban-scripts--n/blob/patch-1/marzban.sh)" @ install
```

**Comment by freeisok** [comment]
I also encountered the same problem, and tried the command just posted, but it prompted '-bash: /usr/bin/bash: Argument list too long'.

**Comment by ImMohammad20000** [comment]
re run the original command there is no problem now

**Comment by yvnveligon** [comment]
thanks boss
