### ISSUE TITLE
How i can add protocols?

### ISSUE THREAD

**Issue by ultraleks** [Gozargah/Marzban#1497]
Hi there!
I just install Marzban with easy-way

> sudo bash -c "$(curl -sL https://github.com/Gozargah/Marzban-scripts/raw/master/marzban.sh)" @ install

But after install i can just create user with Shadowsocks protocol. But i want to use VLESS protocol. 
There no information about adding protocols.
In older versions Marzban installed with all protocols and it correctly works with all of them.
![Снимок экрана 2024-12-07 191947](https://github.com/user-attachments/assets/1a2eea07-be10-4bef-9766-7b7e1d4b6324)

**Comment by M03ED** [comment]
Yes that's correct way.
