### ISSUE TITLE
Job "remove_expired_users", possible memory leak?

### ISSUE THREAD

**Issue by johnWinchester01** [Gozargah/Marzban#1499]
[error server logs.txt](https://github.com/user-attachments/files/18060482/error.server.logs.txt)
**Describe the bug**
I don't know what causes the error but my cpu and spikes when it hapens, possibly a memory leak? server logs are attached
Exception in ASGI application
Job "remove_expired_users

**Expected behavior**

**Screenshots**

**Machine details (please complete the following information):**
 - OS:ubunto 24
- version: latest

![f7rck750h](https://github.com/user-attachments/assets/b36bbb66-9a1d-471e-b5d7-66ea0c147f0a)

**Comment by ImMohammad20000** [comment]
do you have telegram bot running?

**Comment by ImMohammad20000** [comment]
its lock like you have telegram bot enable and panel can't access to telegram for some reason this is not a panel issue

**Comment by johnWinchester01** [comment]
> its lock like you have telegram bot enable and panel can't access to telegram for some reason this is not a panel issue

So how can i figure out what's the problem with telegram?

**Comment by ImMohammad20000** [comment]
> > its lock like you have telegram bot enable and panel can't access to telegram for some reason this is not a panel issue
> 
> So how can i figure out what's the problem with telegram? Should i change the bot?use proxy for connection?any settings i could tweak?

try change your token
