### ISSUE TITLE
مشکل در api

### ISSUE THREAD

**Issue by tbehzad76** [Gozargah/Marzban#15]
سلام وقت بخیر
امکانش هست ی نمونه اماده از api ساخت یوزر جدید برای php بزارین؟ یا با guzzle؟؟

**Comment by SaintShit** [comment]
@tbehzad76 سلام
بنده با php آشنایی ندارم. اما شما میتونید توی فایل env متغیر DOCS رو true قرار بدین و به مستندات API دسترسی پیدا کنید. 
همینطور اگر مستندات رو فعال کنید یک فایل openapi.json بهتون ارائه میده. برای زبان ها و ابزار های مختلف معمولا یک code generator با openapi هست که میتونید برای زبان مقصد خودتون پیدا کنید. 
من برای php سرچ کردم  و اینو دیدم:
https://lornajane.net/posts/2018/generating-php-library-code-from-openapi
