### ISSUE TITLE
Xhttp support 

### ISSUE THREAD

**Issue by chitoz1300** [Gozargah/Marzban#1509]
سلام عرض ادب لطف میکنید قابلیت Xhttp که به تازگی به هسته xray اضافه شده رو به مرزبان اضافه کنید دقیقا مثل زیر

مدل ساده بدون extra:

https://github.com/chika0801/Xray-examples/tree/main/VLESS-XHTTP-REALITY/steal_oneself

مدل پیچیده تر:

https://github.com/XTLS/Xray-core/pull/3955

    

 توضیحات کلاینت و اضافه کردن extra :

https://github.com/XTLS/Xray-core/pull/4000

امکان استفاده از cdn و ریلیتی بصورت همزمان فراهم میشه ، سپاس

**Comment by M03ED** [comment]
در حال حاضر ساپورت میشه
