### ISSUE TITLE
Update sub fail after latest update [ Dev Version ]

### ISSUE THREAD

**Issue by NotaNerd021** [Gozargah/Marzban#1515]
After updating marzban to the latest dev version sub update doesn't work
When I checked marzban logs I found this error

`marzban-1  | INFO:     172.71.164.25:40426 - "GET /sub/XXXRemovedUUIdExample123 HTTP/1.1" 500 Internal Server Error
marzban-1  | ERROR:    Exception in ASGI application
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
marzban-1  |     return await self.app(scope, receive, send)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
marzban-1  |     await super().__call__(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
marzban-1  |     await self.app(scope, receive, _send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
marzban-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
marzban-1  |     await route.handle(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
marzban-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
marzban-1  |     response = await f(request)
marzban-1  |                ^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
marzban-1  |     raw_response = await run_endpoint_function(
marzban-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
marzban-1  |     return await run_in_threadpool(dependant.call, **values)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
marzban-1  |     return await get_async_backend().run_sync_in_worker_thread(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
marzban-1  |     return await future
marzban-1  |            ^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
marzban-1  |     result = context.run(func, *args)
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/routers/subscription.py", line 56, in user_subscription
marzban-1  |     user: UserResponse = UserResponse.model_validate(dbuser)
marzban-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 627, in model_validate
marzban-1  |     return cls.__pydantic_validator__.validate_python(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  | pydantic_core._pydantic_core.ValidationError: 3 validation errors for UserResponse
marzban-1  | used_traffic
marzban-1  |   Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=149679331879.8035, input_type=float]
marzban-1  |     For further information visit https://errors.pydantic.dev/2.10/v/int_from_float
marzban-1  | lifetime_used_traffic
marzban-1  |   Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=149679331879.8035, input_type=float]
marzban-1  |     For further information visit https://errors.pydantic.dev/2.10/v/int_from_float
marzban-1  | admin.users_usage
marzban-1  |   Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=1707084.8, input_type=float]
marzban-1  |     For further information visit https://errors.pydantic.dev/2.10/v/int_from_float`

Every time someone update their sub it'll fail and I'll have similar error in my logs
Downgrading to latest version fixes the error

**Comment by ImMohammad20000** [comment]
log is not readable

**Comment by ImMohammad20000** [comment]
can you send ur database in telegram?

**Comment by ImMohammad20000** [comment]
i need to see ur database

**Comment by ImMohammad20000** [comment]
> > log is not readable
> 
> ```
> INFO:     172.71.xxx.xx:40426 - "GET /sub/XXXRemovedUUIdExample123 HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
>     raise exc
>   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
>     response = await f(request)
>                ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
>     raw_response = await run_endpoint_function(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
>     return await run_in_threadpool(dependant.call, **values)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
>     return await anyio.to_thread.run_sync(func, *args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
>     return await future
>            ^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
>     result = context.run(func, *args)
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/code/app/routers/subscription.py", line 56, in user_subscription
>     user: UserResponse = UserResponse.model_validate(dbuser)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 627, in model_validate
>     return cls.__pydantic_validator__.validate_python(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> pydantic_core._pydantic_core.ValidationError: 3 validation errors for UserResponse
> used_traffic
>   Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=149679331879.8035, input_type=float]
>     For further information visit https://errors.pydantic.dev/2.10/v/int_from_float
> lifetime_used_traffic
>   Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=149679331879.8035, input_type=float]
>     For further information visit https://errors.pydantic.dev/2.10/v/int_from_float
> admin.users_usage
>   Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=1707084.8, input_type=float]
>     For further information visit https://errors.pydantic.dev/2.10/v/int_from_float
> ```

you have the same error?

**Comment by NotaNerd021** [comment]
> i need to see ur database

Sure, what's ur telegram ID?

**Comment by ImMohammad20000** [comment]
> > i need to see ur database
> 
> Sure, what's ur telegram ID?

t.me/ImMohammad20000
