### ISSUE TITLE
عدم نمایش یوزرها در پنل مرزبان

### ISSUE THREAD

**Issue by aliamg1356** [Gozargah/Marzban#1521]
پنل مرزبان 0.7.0
پایگاه داده mysql
به یکباره یوزرهای من نمایش داده نمیشوند
یوزرها کار میکنند
اما نمایش داده نمیشوند
همه هم ظاهرا اوکی هست
یوزر جدید هم ساخته میشه نمایش داده نمیشه
تعداد یورزها روو صحیح نمایش میده
تو ربات مشکلی نیست فقط در پنل مشکل رو دارم
بکاپ هم ریستور کردم فایده نداشت
با تشکر

**Comment by LonUp** [comment]
در تنظیمات Host Settings برسی کنید عبارت یا کاراکتر غیر متعارفی استفاده نکرده باشید
از جمله {} 

ریستارت مرزبان بزنید و لاگ رو ارسال کنید

اخرین اعمال شما قبل از این باگ چی بوده ؟

**Comment by aliamg1356** [comment]
> در تنظیمات Host Settings برسی کنید عبارت یا کاراکتر غیر متعارفی استفاده نکرده باشید از جمله {}
> 
> ریستارت مرزبان بزنید و لاگ رو ارسال کنید
> 
> اخرین اعمال شما قبل از این باگ چی بوده ؟

ممنون از پاسختون
هیچ تغییری در این 2 روز انجام نداده بودم حتی پنل رو هم باز نکرده بودم.یوزر هم ایجاد نشده بود

بکاپ دو روز قبل رو برگردوندم درست شد

**Comment by LonUp** [comment]
وقتی دیتابیس ۲ روز پیش مشکل رو حل کرده . یعنی تغییری ایجاد شده . میتونید برای برسی دیتابیس رو برای دولوپر های مرزبان ارسال کنید . و حالا که مشکلتون حل شده میتونید این issue  رو ببندید
