### ISSUE TITLE
Independent Xray Node Configuration

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#1526]
In many scenarios, we have inbound configurations that are specific to a particular node, as well as outbound rules, routing, or custom policies that we want to apply exclusively to that node.

It would be highly beneficial to introduce an ENV variable for the node where we can specify the path to a custom Xray JSON configuration file. This would allow us to manually edit and fine-tune the configuration for that specific node without being dependent on the panel.

Such a feature is essential for greater flexibility and control over individual node configurations.

Thank you for your attention

**Comment by M03ED** [comment]
there is a issue for this and were trying to release this with new frontend
#702
