### ISSUE TITLE
Access to env vars in Jinja templates

### ISSUE THREAD

**Issue by kevlinsky** [Gozargah/Marzban#1532]
You've already added `env_override` function in app/templates/filter.py::31 project file, but not added to CUSTOM_FILTERS. Can you add in a new version env_override filter to CUSTOM_FILTERS for accepting env vars from Jinja templates?

**Comment by M03ED** [comment]
May I ask what is the use case of this ?

**Comment by kevlinsky** [comment]
> May I ask what is the use case of this ?

I'm using a custom subscription page template in my installation and I have dynamic link inside it which I want to configure by my .env file
