### ISSUE TITLE
inbounds dont generate in node

### ISSUE THREAD

**Issue by WhyMan1** [Gozargah/Marzban#1539]
در حالتی که ۵۰ تا اینباند dokomodoor داشتم روی دو تا نود نصف اینباندها فعال نمیشد روی هردو نود هم همینطور بود دقیقا

**Comment by WhyMan1** [comment]
@ImMohammad20000

**Comment by ImMohammad20000** [comment]
Gozargah/Marzban-node#62

**Comment by ImMohammad20000** [comment]
Test new node
