### ISSUE TITLE
Validation Error for `UserResponse` on `dev` Version due to Float-to-Int Conversion  

### ISSUE THREAD

**Issue by ZhuZhuZhuang10** [Gozargah/Marzban#1540]
**Description:**  

We encountered a validation error in the `UserResponse` model after switching to the `dev` version. The error occurs because the fields `used_traffic` and `lifetime_used_traffic` receive float values (e.g., `270257011.59999996`), while the model expects integers (`int`).  

### Error Details:
```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for UserResponse
used_traffic
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=270257011.59999996, input_type=float]
lifetime_used_traffic
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=270257011.59999996, input_type=float]
```

### Steps to Reproduce:
1. Switch to the `dev` version of the application.
2. Trigger an endpoint or function that uses the `UserResponse` model.
3. Observe the validation error.

### Expected Behavior:
The `UserResponse` model should handle the float-to-int conversion gracefully, or the API should return integer values directly.

### Actual Behavior:
The application raises a validation error due to the mismatch between the expected and actual data types.

### Suggested Fix:
- Convert float values to integers before validating with the `UserResponse` model.
- Alternatively, update the `UserResponse` model to accept float values if fractional data is expected.

Let me know if further details are required!

**Comment by M03ED** [comment]
can you send your database ? (don't export sensetive data
)

**Comment by ImMohammad20000** [comment]
Update and test

**Comment by ZhuZhuZhuang10** [comment]
Yes! It works, good job! Closing issue.
