### ISSUE TITLE
Support `2022-blake3-aes-128-gcm` and `2022-blake3-aes-256-gcm` for SS2022

### ISSUE THREAD

**Issue by yzy613** [Gozargah/Marzban#1545]
The 2022 new protocol format for Shadowsocks improves performance and includes complete replay protection, addressing the following security issues in the old protocol:

- The design of Shadowsocks AEAD encryption method has serious vulnerabilities, which cannot guarantee the reliability of communication content.  
- The false positive rate of the original TCP replay filter increases over time.  
- No UDP replay protection.  
- TCP behavior can be used for active probing.

**Comment by M03ED** [comment]
#329

**Comment by M03ED** [comment]
with next major update we have (in next few month) this will be added
