### ISSUE TITLE
وقتی inbounds رو حذف میکنم رکوردها تو دیتابیس  Mysql میمونه و پاک نمیشه.

### ISSUE THREAD

**Issue by crowlink** [Gozargah/Marzban#1547]
درود
وقتی inbounds رو حذف میکنم رکوردها تو دیتابیس  Mysql میمونه و پاک نمیشه.
بعد از چند بار اضافه و حذف سیستم کلا قاطی میکنه و وقتی رو تنظیمات هاست کلیک میکنم من رو میندازه بیرون.
راه حلی برای حذف inbounds استفاده نشده از دیتابیس هست؟
با تشکر

**Comment by ImMohammad20000** [comment]
why you need to delete the unused inbounds?

**Comment by iamtheted** [comment]
دیتای زیادی ندارن اینباند های قدیمی.
ولی کافیه تیک بغلشو بزنی و اون پایین delete رو بزنی تا پاک شه.
