### ISSUE TITLE
New features for Modify User in api

### ISSUE THREAD

**Issue by SirSobhan** [Gozargah/Marzban#16]
Hello..
After working with the api, I realized that it would be much better if it was possible to change 'used_traffic', and it would be great if it was possible to change the user's sub link or uuid randomly without sending a new value to the api.
Thanks

**Comment by SirSobhan** [comment]
Sorry, I was wrong about this and I think it would be better to have the ability to modify used traffic.  Because if we ourselves want to have some servers.  For example, if a user wants to change his server without paying, we have to create a new user on another server with the same user data.  In this way, the user's used traffic becomes zero.  But if it is possible to set used traffic, we can transfer the user between different servers that they want.  Sorry for commenting again, thanks.

**Comment by SaintShit** [comment]
To move users to another server, you just need to transfer your database there. reset user feature implemented on #23, take a look.

**Comment by SirSobhan** [comment]
> To move users to another server, you just need to transfer your database there. reset user feature implemented on #23, take a look.

As I said, the purpose of this work is not to transfer all users, just in case one of our users wants to choose another server, we cannot transfer the entire database to another server just for one user. And on the new server, it is not possible to enter the user's previous used_traffic.

**Comment by mrafieefard** [comment]
+1

**Comment by erfjab** [comment]
> +1

Come on :/

**Comment by mrafieefard** [comment]
> > +1
> 
> Come on :/

I'm moving from x-ui to marzban and I want to show user usege in marzban but seems its not possible so I fix it with traffic limit

**Comment by erfjab** [comment]
> > > +1
> > 
> > Come on :/
> 
> I'm moving from x-ui to marzban and I want to show user usege in marzban but seems its not possible so I fix it with traffic limit

Well, that's right.

**Comment by mrafieefard** [comment]
> > > > +1
> > > 
> > > 
> > > Come on :/
> > 
> > 
> > I'm moving from x-ui to marzban and I want to show user usege in marzban but seems its not possible so I fix it with traffic limit
> 
> Well, that's right.

I wrote webapp to show usage and more its messy if I show it from zero

**Comment by erfjab** [comment]
I didn't understand
