### ISSUE TITLE
افزودن نام کاننکشت تنظیم شده در ریماذک روی qr code

### ISSUE THREAD

**Issue by aliamg1356** [Gozargah/Marzban#162]
وقتی یوزر ساخته ضد و رو بارکد کلیک میکنیم همه بارکدها رو میاره که معلوم نیست مال کدوم کانکشنه و بهتر بود نام کانکشن رو هم روش نشون میداد و راحتت رو برای اسکن.

**Comment by aradesign** [comment]
کاش راهی باشه که بشه محاسباتی رو هم توی تنظیمات هاست روی متغیرها گذاشت!
مثلا ترافیک مصرفی رو ازکل کم کرد که باقی مونده بیاد!
یا اینکه یه متغییر برای این مورد اضافه بشه
