### ISSUE TITLE
بروزرسانی

### ISSUE THREAD

**Issue by shuvvan** [Gozargah/Marzban#166]
``سلام

لطفا بفرمایید ما که پنل رو نصب کردیم با داکر ، چطوری پنل رو بروزرسانی کنیم که اطلاعاتمون از دست نره؟
آیا پنل اتومات خودش بروزرسانی نمیشه؟

**Comment by shuvvan** [comment]
لطفا پاسخ بدید کار من الان چند روزه گیره !
پنل خوبی دارید ولی من الان پشیمونم نصب کردم چون پشتیبانی نداره واقعا گرفتارم الان

**Comment by SaintShit** [comment]
https://github.com/Gozargah/Marzban/blob/master/CONTRIBUTING.md#questions

[@Gozargah_Marzban](https://t.me/gozargah_marzban) / [GitHub Discussions](https://github.com/gozargah/marzban/discussions)

اینجا جای سوال پرسیدن نیست. 
جواب سوالتون توی [@Gozargah_news](https://t.me/Gozargah_news) هست

1. Backup your database

cp /var/lib/marzban/db.sqlite3 /var/lib/marzban/db.sqlite3.bak

2. Pull the latest image of Marzban

docker pull gozargah/marzban:latest

3. Restart the service 

cd marzban
docker compose down
docker compose up -d

همینطور میتونید از [`marzban.sh`](https://t.me/Gozargah_news/8) استفاده کنید
