### ISSUE TITLE
قابلیت uninstall

### ISSUE THREAD

**Issue by pouyaSanjari** [Gozargah/Marzban#168]
قابلیت uninstall خیلی مهمه برای پنل لطفا اضافه کنید

**Comment by GetPHP-IR** [comment]
این قابلیت لازم نیست.
اگه مستقیم با پایتون و venv اجرا کرده باشید که چیزی لازم نیست فقط فایل ها رو پاک کنید.
داکر هم که چیزی نمی خواد باز پاک کنی فایل ها رو می ره و اینکه سرویس مورد نظر رو stop و پاک کنی

**Comment by aliamg1356** [comment]
> این قابلیت لازم نیست. اگه مستقیم با پایتون و venv اجرا کرده باشید که چیزی لازم نیست فقط فایل ها رو پاک کنید. داکر هم که چیزی نمی خواد باز پاک کنی فایل ها رو می ره و اینکه سرویس مورد نظر رو stop و پاک کنی

با سلام و خسته نباشید  کاش آموزش نحوه آپدیت کردن رو هم میزاشتید
