### ISSUE TITLE
Parent panel for managing

### ISSUE THREAD

**Issue by meaqese** [Gozargah/Marzban#17]
Hi, Thank you for your work) I think it is necessary to implement (perhaps later) a parent panel for managing multiple servers, because in reality you will not go far with one server)

I suggested this idea in advance so that such a possibility would be taken into account when building the application architecture, and then it would not hurt to make such extensions

**Comment by SaintShit** [comment]
@meaqese Hi, you're absolutely right. this feature should be implemented with high priority
