### ISSUE TITLE
tls and none

### ISSUE THREAD

**Issue by s4I3h** [Gozargah/Marzban#176]
سلام وقتتون بخیر
عزیز الان وقتی که میخوای کانفیگ بسازی نمی تونی  تو بخش security از none استفاده کنی چون داخل سورس دیفالت tls تعریف شده و وقتی هم ادیت میکنی میزاری none دیگه نمیشه از tls استفاده کرد. خلاصه اینکه امکان استفاده از هر دو نیست مگر اینکه ی inbound دیگه تعریف کنی مثلا دو تا vmess  تو پنل بیاد ، یکی tls یکی هم none
امکانش هست تو اپدیت بعدی این اضافه بشه راحت تو پنل حالت security رو انتخاب کرد
در اخر خیلی ممنونم

**Comment by SaintShit** [comment]
سلام. اون بخش از اسمش هم پیداست، تنظیمات هاست هست. تنظیمات هاست هایی که منتعی میشه به اون اینباند توی سرور. شما ممکنه مثلا یک سرور ایران هم داشته باشی که تونل شده به سرور خارج شما، و مثلا درخواست های شما به اون سرور ایران بدون TLS میره، و شما روی سرور ایران خودتون درخواست رو به صورت TLS ارسال میکنید روی سرور خارجتون، اینجا میتونید none ست کنید تا لینک هایی که ساخته میشه برای اون هاست ( سرور ایران )، بدون TLS باشن. بخش هاست برای ساخت لینک هایی هست که به اون اینباند منتهی میشن. ممکنه چنتا لینک بخواین بدین، یا فقط یکی مستقیم. یا حتی ممکنه توی کانفیگ xray گواهینامه سه تا دامنه مختلف رو اضافه کنید و از توی تنظیمات هاست سه تا هاست با sni های متفاوت بسازید که هر سه روی همون اینباند میرن اما هرکدوم با دامنه متفاوت.

حالا کاری که شما میخواین بکنید راه حلش ساخت دوتا اینبانده. یک اینباند TLS و یک اینباند noTLS ( security: none ) میسازید. توی بخش هاست هم میتونید هر اینباند رو جداگونه تنظیم کنید. مثلا اگر یک ورکر دارین که درخواست هارو به صورت TLS میگیره و بدون TLS میفرسته روی سرور شما، شما میتونید روی اینباند noTLS که ساختید یک هاست برای اون ورکر با security TLS اضافه کنید و sni و host رو دامنه اون ورکر قرار بدین. لینکی که مرزبان برای اون هاست ( ورکر ) میسازه TLS خواهد شد در صورتی که اینباندی که در نهایت بهش میرسه درخواست ها noTLS هست. کاری هم که ورکر انجام میده، اینه که درخواست های TLS رو دریافت میکنه، TLS Termination رو انجام میده و به صورت Plain ( noTLS ) به اینباند شما میفرسته.

**Comment by s4I3h** [comment]
یک دنیا ممنونم❤
