### ISSUE TITLE
Bad Gateway After installing from docker

### ISSUE THREAD

**Issue by Shjpr9** [Gozargah/Marzban#18]
After installing the web app from docker, the panel won't be available on port 8880.
I tried on multiport management panel and get the "Bad Gateway" error!
Thanks

**Comment by SaintShit** [comment]
Hi, what address are you going to? try add a / at the end (`/dashboard/`) and see if panel load up.
if not, I need further information, please include your server logs here. also mention that you're tryna fetch dashboard over a CDN?

**Comment by Shjpr9** [comment]
> Hi, what address are you going to? try add a / at the end (`/dashboard/`) and see if panel load up. if not, I need further information, please include your server logs here. also mention that you're tryna fetch dashboard over a CDN?

It fixed after adding a `/` after dashboard. But it seems the vpn does not work properly

**Comment by SaintShit** [comment]
VPN problems can be related to many things, so plz give more info along with your logs. like how are your tls settings and how are your dns records? are they proxied?

**Comment by Shjpr9** [comment]
Yes, and it may not work in hard filtering situations. I didn't use tls settings for testing and I tried to connect with direct ip

**Comment by SaintShit** [comment]
@Shjpr9 Any update on your problem, is it fixed?

**Comment by artan-riseup** [comment]
Hi there . Tnx for your app develpo . I think for editing env and x-ray._config.json is not exact and full detail . Totally in first point u need update your code chain . Add grpc . Add utls . Alpn . Sni and many other things . خوشحالم که امثال شما مشغول کپی برداری نیستند و تولید ویدیوی مانیتایز نمیکند ک

**Comment by Shjpr9** [comment]
@SaintShit yes, after placing server behind cloudflare and using clean ips, it worked on every isp. Thank you very much ❤️

**Comment by artan-riseup** [comment]
سلام . گله قشنگم من تو کامنت ها هنوز تست نگرفته بودم .‌‌با تمام اپراتورها .
پشت کلاد . ای پی تمیز دامنه نو . وی پی اس . اسپانیا با ۴ هسته سی پی یو و ۲
گ رم . تو وای فای زیره ۸۰۰ نداد پینگ کشتم خودمو . تو ایرانسل هم با تاخیر
چند ثانیه بی بالای ۱۲۰۰ پینگ . خدایی این تخصص و عشق و همراه ب اشتراک بزار
با دیگران و ی کاره عمقی و قابل ارتقا و محشر بیرون بدید . الان خودمون
تنهاییم عملا غیر قابل استفادست گله قشنگم 💕
