### ISSUE TITLE
Port setting

### ISSUE THREAD

**Issue by AC-Lover** [Gozargah/Marzban#182]
Hello
I only set the port for this case, but the whole `TROJAN_WS_INBOUND ` sets port 443
please check it

![image](https://user-images.githubusercontent.com/49290111/231857512-e4b54a39-1a62-42a2-a365-ff7a0199fbd4.png)

**Comment by AC-Lover** [comment]
> which version did you install?

Single Port Proxy - dev
last version

**Comment by SaintShit** [comment]
https://github.com/Gozargah/Marzban/releases/tag/v0.2.6
