### ISSUE TITLE
About {SERVER_IP} Variable

### ISSUE THREAD

**Issue by Sooshka-X** [Gozargah/Marzban#185]
سلام
لطفا" در صورتی که امکان داره ، در کنار این متغییر، متغییری برای domain قرار بدین که از URL استفاده بشه و کاملا" پشت Cloudflare قرار بگیره.
اینطوری وقتی که Subscription ساخته میشه  همه سرویسها فقط با IP هستن و در صورتی که بخوایم IP سرور مشخص نباشه و از CDN استفاده کنیم عملا" بی فایده میشه.
تشکر از زحماتتون

**Comment by OxJ4ck** [comment]
سلام میتونید تو قسمت host setting پنل دامنه خودتون رو قرار بدین.

**Comment by Sooshka-X** [comment]
سلام ممنون میشم راهنمائی کنید که کدوم قسمت رو باید URL سایت رو ثبت کنم.
من میخوام وقتی سرورها اضافه میشن به کلاینت IP اصلی سرور نمایش داده نشه.
با این حالتی که این متغییر در قسمت Address هست، IP Server رو نمایش میده و عملا" به خود سرور اشاره میکنه، اینطوری اصلا" از CDN استفاده نمیشه.

**Comment by OxJ4ck** [comment]
وارد پنل که میشین منوی همبرگری بالا سمت راست رو بزنید بعد Hosts Settings رو انتخاب کنید، یه منو بالا میاد که تگ inbound هاتون توش هست رو هر کدوم کلیک کنید تنظیمات مربوط به اون inbound باز میشه.
- بخش Remark اسم کانفیگ هست که هر اسمی میتونید بذارین و همچنین چندتا متغیر هم داره با زدن دکمه i کنارش میتونید متغیر هارو ببنیدید. ( این متغیر ها شامل نام کاربری، حجم مصرف شده کاربر، حجم کامل کاربر، تعداد روز باقیمانده از اشتراک کاربر، پروتکل و ترنزمیشن هستن) برای مثال
`VPN [{USERNAME} {DATA_USAGE}/{DATA_LIMIT}]`
- بخش Address دامنه رو قرار میدین اگر از آیپی تمیز کلودفلر استفاده میکنید اینجا قرار بدین.
- عدد روبروی Address پورت هست که اگر پورت دیگه ای استفاده میکنید که اونجا قرار میدین اگر نه که دست بهش نزنید.
- بخش SNI برای tls هستش اگر برای دامنتون سرتیفیکیت گرفتین اینجا قرارش میدین. اگر برای همه ساب دامین ها سرتیفیکیت گرفتین که میتونید اینجا از * استفاده کنید، خود مرزبان براتون ساب دامین رندم میسازه برای مثال
`*.example.com`
`site*.example,com`
`my.example.com`
- بخش Host هم دوباره دامنتونو قرار میدین.

اگر بازم خواستین برای این inbound دامنه دیگه ای اضافه کنید (برای مثال آیپی تمیز همراه اول، ایرانسل و ...) دکمه Add host رو بزنید و دوباره همین هارو پر کنید

**Comment by Sooshka-X** [comment]
ممنون از توضیحاتتون
آیا متغییری برای قسمت آدرس نداره که URL رو از خود سرور بگیره؟

**Comment by OxJ4ck** [comment]
نه چون جایی ذخیره نمیشه.
اما اگر tls بگیرین و توی فایل xray_config.json وارد کنید، خود مرزبان sni و host رو بر اساس اون پر می‌کنه.

**Comment by Sooshka-X** [comment]
ممنونم از راهنمائیتون.
بله tls دارم، پس لازم نیست توی هر قسمت از Hosts Settings ، دستی host و sni رو وارد کنیم؟
یه راهنمائی میفرمائید که کدوم حالت نصب بشه بهتره؟
من حالت single-port-proxy رو نصب کردم.
پورت 8443 برای سرویسها.
443 باشه بهتر میشه؟

**Comment by OxJ4ck** [comment]
تفاوت چندانی نداره و سلیقه ای. من خودم از fully single port استفاده میکنم چون همه چی رو پورت ۴۴۳ هستش. یه سایت فیک هم بالا آوردم.
نسخه multi port راحت تر میتونید فایل xray_config.json رو ویرایش کنید.
اینجور سوالات رو هم تو [گروه تلگرامی ](https://t.me/gozargah_marzban)  بپرسید زودتر به نتیجه میرسین.

**Comment by Sooshka-X** [comment]
ممنونم از راهنمائیتون
نمیدونستم گروه تلگرامی هست.

**Comment by aliamg1356** [comment]
> نه چون جایی ذخیره نمیشه. اما اگر tls بگیرین و توی فایل xray_config.json وارد کنید، خود مرزبان sni و host رو بر اساس اون پر می‌کنه.
اگر tls داشته باشیم بله sni رو خودش پر میکنه ولی هاست رو نه و باید در تنظیمات گذاشته بشه

**Comment by Sooshka-X** [comment]
> 

ممنونم.
اگر راه حلی برای همه اپراتورها باشه خیلی خوبه.
در گروه هم سوال پرسیدم اما پاسخی دریافت نکردم.
