### ISSUE TITLE
نحوه آپدیت

### ISSUE THREAD

**Issue by aliamg1356** [Gozargah/Marzban#189]
با سلام و خسته نباشید.
در گیت هاب اصلا صحبتی در مورد آپدیت چیزی ننوشتین
آیا برای نصب لازمه کانتینر و ایمیج ریمو بشه و ایمیج جدید نصب بشه یا راه کار دیگری داره؟
اگر آپدیت بشه به هر صورتی فایل دیتا بیس قبلی قابل استفاده در نسخه های جدید خواهد بود؟

**Comment by rafiee** [comment]
مگه آپدیتی اومده اصلا ؟ حدود سه هفته است آپدیتی نیومده !

**Comment by OxJ4ck** [comment]
برای آپدیت مرزبان
اول از دیتابیس بکاپ بگیرین
```
cp /var/lib/marzban/db.sqlite3 /var/lib/marzban/db.sqlite3.bak
```
بعد برای گرفتن آخرین نسخه مرزبان دستور زیر رو بزنید.
```
docker pull gozargah/marzban:latest
```
حالا مرزبان رو ریسارت کنید.
```
cd marzban
docker compose down
docker compose up -d
```
