### ISSUE TITLE
عدم ارتباط با سرور پس از خاموش و روشن کردن سرور

### ISSUE THREAD

**Issue by rafiee** [Gozargah/Marzban#192]
**Describe the bug**
عدم ارتباط با سرور

**To Reproduce**
پنل مرزبان در سرور در حال کار بود. به خاطر ورود به سرور مجبور شدم پسورد رو ریست کنم و وارد بشم. بعد از ورود، دیگه پنل بالا نمیاد. ولی تمام کانفیگ ها کار می کنند.  در  کلودفلر با ارور Server is down و بعضی اوقات Web server is returning an unknown error  مواجه می شم. 
توضیحات تکمیلی:
در پوشه مرزبان ، پنل مرزبان نصب شده است.
در سرور پنل ثنایی نیز نصب شده است و بدون مشکل در حال کار کردن بودند.
بعد از آپدیت سرور و همچنین آپدیت ثنایی، دیگر پنل مرزبان بالا نمیاد. و با ارورهای 
Server is down
Web server is returning an unknown error
TLS handshake
مواجه می شم. همونطور که گفتم تمام کانفیگ ها همچنان بدون مشکل کار می کنند. پنل ثنایی نیز بون مشکل بالا میاد و کانفیگ ها کار می کنند. 
پنل مرزبان رو مجددا reinstall ( روی قبلی ) کردم. فالی کانفیگ رو ادیت کردم و همچنان پنل بالا نمی آید.
سرتیفیکیت از سایت کلودفلر origin server  گرفته شده است و بدون مشکل کار می کرد. با اینحال سرتیفیکیت دوباره آپدیت شد ولی همچنان پنل بالا نمی آید.
پنل از کلودفلر به ابرآروان منتقل شد و با ارور 502 در ابرآروان که سرور در دسترس نیست مواجه شدم.

**Expected behavior**

**Screenshots**

**Machine details (please complete the following information):**
 - OS: [e.g. ubuntu 20]
- Python version: [e.g 3.8]
- Nodejs version: [e.g 16.17]

**Additional context**

**Comment by rafiee** [comment]
تمام کانفیگ ها کار می کنند.  در  کلودفلر با ارور Server is down و بعضی اوقات Web server is returning an unknown error  مواجه می شم. 
توضیحات تکمیلی:
در پوشه مرزبان ، پنل مرزبان نصب شده است.
در سرور پنل ثنایی نیز نصب شده است و بدون مشکل در حال کار کردن بودند.
بعد از آپدیت سرور و همچنین آپدیت ثنایی، دیگر پنل مرزبان بالا نمیاد. و با ارورهای 
Server is down
Web server is returning an unknown error
TLS handshake
مواجه می شم. همونطور که گفتم تمام کانفیگ ها همچنان بدون مشکل کار می کنند. پنل ثنایی نیز بون مشکل بالا میاد و کانفیگ ها کار می کنند. 
پنل مرزبان رو مجددا reinstall ( روی قبلی ) کردم. فالی کانفیگ رو ادیت کردم و همچنان پنل بالا نمی آید.
سرتیفیکیت از سایت کلودفلر origin server  گرفته شده است و بدون مشکل کار می کرد. با اینحال سرتیفیکیت دوباره آپدیت شد ولی همچنان پنل بالا نمی آید.
پنل از کلودفلر به ابرآروان منتقل شد و با ارور 502 در ابرآروان که سرور در دسترس نیست مواجه شدم.

**Comment by rafiee** [comment]
پنل مرزبان در سرور در حال کار بود. به خاطر ورود به سرور مجبور شدم پسورد رو ریست کنم و وارد بشم. بعد از ورود، دیگه پنل بالا نمیاد. ولی تمام کانفیگ ها کار می کنند.  در  کلودفلر با ارور Server is down و بعضی اوقات Web server is returning an unknown error  مواجه می شم. 
توضیحات تکمیلی:
در پوشه مرزبان ، پنل مرزبان نصب شده است.
در سرور پنل ثنایی نیز نصب شده است و بدون مشکل در حال کار کردن بودند.
بعد از آپدیت سرور و همچنین آپدیت ثنایی، دیگر پنل مرزبان بالا نمیاد. و با ارورهای 
Server is down
Web server is returning an unknown error
TLS handshake
مواجه می شم. همونطور که گفتم تمام کانفیگ ها همچنان بدون مشکل کار می کنند. پنل ثنایی نیز بون مشکل بالا میاد و کانفیگ ها کار می کنند. 
پنل مرزبان رو مجددا reinstall ( روی قبلی ) کردم. فالی کانفیگ رو ادیت کردم و همچنان پنل بالا نمی آید.
سرتیفیکیت از سایت کلودفلر origin server  گرفته شده است و بدون مشکل کار می کرد. با اینحال سرتیفیکیت دوباره آپدیت شد ولی همچنان پنل بالا نمی آید.
پنل از کلودفلر به ابرآروان منتقل شد و با ارور 502 در ابرآروان که سرور در دسترس نیست مواجه شدم.

**Comment by shuvvan** [comment]
پس از خاموش و رشون کردن باید این دستورات رو هم بزنی بعد مرزبان میاد بالا

cd marzban
docker compose down
docker compose up -d

**Comment by aliamg1356** [comment]
> پس از خاموش و رشون کردن باید این دستورات رو هم بزنی بعد مرزبان میاد بالا
> 
> cd marzban docker compose down docker compose up -d

با فرمان زیر دیگه نیاز نیست بعد هر بار ریستارت دوباره کانتینیر مرزبان اجرا بشه  بعد از اجرای مرزبان این کد رو بزنین
docker update --restart unless-stopped $(docker ps -q)

**Comment by rafiee** [comment]
> پس از خاموش و رشون کردن باید این دستورات رو هم بزنی بعد مرزبان میاد بالا
> 
> cd marzban docker compose down docker compose up -d

ممنون از پاسخ شما
اینها رو هم میزدم بارها ، مرزبان با پیام موفقیت راه میوفتاد ولی بازهم پنل بالا نمیومد.
نکته عجیب اینه که همه کانفیگ ها بدون مشکل کار می کردند.
