### ISSUE TITLE
عدم نمایش اکانت ها 

### ISSUE THREAD

**Issue by M03ED** [Gozargah/Marzban#201]
سلام 
بنده از اخرین نسخه مرزبان استفاده میکنم و از دیروز با مشکل عجیبی مواجه شدم 
در پنل ادمین sudo یوزر ها نمایش داده نمیشه ولی تو بقیه ادمین ها یوزر ها کاملا درست نشون داده میشه 
![image](https://user-images.githubusercontent.com/50927468/233727061-c16cc0e1-c374-40f7-b425-9a29ccbc88e8.png)
سرور و مرزبان رو هم ری استارت کردم ولی درست نشد 
یوزر هایی هم که توسط sudo ساخته شده بود رو هم با api پاک کردم ولی باز هم مشکل رفع نشد

**Comment by SaintShit** [comment]
سلام، از نسخه `dev` استفاده میکنید؟
اگر نه، توی مرورگر f12 بزنید به تب network برید و از درخواست هایی که مرزبان بعد از ریفرش کردن میسازه عکس بدین.

**Comment by M03ED** [comment]
![image](https://user-images.githubusercontent.com/50927468/233729990-8f318ba7-ef2b-49ff-baef-bd8ee2568193.png)

**Comment by SaintShit** [comment]
خب ارور ندارین، روی درخواست آخر که با users? شروع میشه کلیک کنید، توی تب response, کاربری میبینید؟

**Comment by M03ED** [comment]
خیر 
از خود api هم که استفاده میکنم و get users رو استفاده میکنم هم همین مشکل رو داره 
![image](https://user-images.githubusercontent.com/50927468/233730981-63ea7248-1a74-4657-bf10-c77e213ebcf7.png)
![image](https://user-images.githubusercontent.com/50927468/233730992-4d2d4d33-1d1c-43eb-909f-dab529d111a1.png)

**Comment by SaintShit** [comment]
متوجه شدم. کاربر ها با همون اکانت سودو ساخته شدن؟ اکانت سودو رو توی دیتابیس انتقال دادین ( اگر از `dev` استفاده میکنید با marzban-cli امکانش هست ) یا اکانت سودو داخل env هست؟

**Comment by M03ED** [comment]
2 اکانت با سودو ساخته شده بودن که پاک شدن ، باقی با ادیمن های دیگه ساخته شدن ، دیتابیس رو دست نزدم 
اکانت سودو هم توی env ذخیره هست

**Comment by M03ED** [comment]
مشکل وارد مرحله جدیدی شد 
دیگه تعداد یوزر رو هم نشون نمیده 

![image](https://user-images.githubusercontent.com/50927468/234371291-ad809bb5-10d5-41ea-a6c1-7640413c723d.png)

**Comment by M03ED** [comment]
به طور اتفاقی متوجه شدم ادمینی هم نام به ادمین sudo ساختم و اینکار باعث این باگ شده ( پسورد ها متفاوت هستند ) ، تعداد یوزر نمایش داده میشه ولی اکانت های ادمین دوم نشون داده میشه.
در صورتی هم که با sudo اکانتی ساخته بشه نشون داده نمیشه.
