### ISSUE TITLE
اضافه کردن دکمه ان و اف کردن در تنظیمات هاست

### ISSUE THREAD

**Issue by ItsElw** [Gozargah/Marzban#202]
سلام وقت بخیر،اگر امکانش هست در قسمت تنظیمات هاست برای هر هاست تعریف شده یک دکمه تعبیه بشه تا زمانی که به اون هاست لازم نداریم اونو خاموش کنیم و بعد ها در صورت لزوم دوباره روشنش کنیم،اینجوری دیگه نیاز نیست که هاست مورد نظر و حذف کنیم و دوباره بعدا اونو اضافه کنیم،ممنون
![IMG_20230422_022613](https://user-images.githubusercontent.com/128150748/233740734-76405029-287b-4647-8855-9ffa4c153244.jpg)

**Comment by alireza1027** [comment]
اره خیلی لازمه

**Comment by farhadan** [comment]
فقط کافیه تو قسمت آدرس سرور اینباد مورد نظر بجای آی پی سرور یا دامنه  @ بزنید.
