### ISSUE TITLE
افزودن گزینه بستن سایتهای ایرانی

### ISSUE THREAD

**Issue by aliamg1356** [Gozargah/Marzban#203]
با سلام و خسته نباشید
اگر در نسخه بعدی بستن سایتهای ایرانی رو هم اضافه کنین عالی میشه/من با دستکاری فایل کانفیگ خواستم این مورد رو اضافه کنم ولی نشد و پنل بالا نیومد.
این مورد میتونه در دیرتر فیلتر شدن دامنه بسیار کمک کنه

**Comment by govfvck** [comment]
سلام.
این یه کاریه که باید خودتون در تنظیماتتون اضافه کنید و مرزبان هم بر خلاف خیلی از پنل ها با این فلسفه جلو میره که تنظیمات مربوط به xray رو خودتون انجام بدید.


میتونید [این آموزش](https://github.com/iranxray/hope/blob/main/routing.md) رو برای انجام این کار دنبال کنید.

**Comment by daniyousefifar** [comment]
درود،
برای انجام اینکار، اول دستورات زیر را بزنید :

`
cd /marzban
wget https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
wget https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat`

**Comment by daniyousefifar** [comment]
درود،
برای انجام اینکار اول دستورات زیر را اجرا کنید :


```bash
cd /marzban
wget https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/iran.dat
wget https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
```


سپس با ادیتور مدنظرتون فایل docker-compose.yml را باز می کنید و قطعه کد زیر را به قسمت volumes اضافه میکنید :


```
- ./iran.dat:/usr/local/share/xray/iran.dat
- ./dlc.dat:/usr/local/share/xray/dlc.dat
```

سپس با ادیتور مدنظرتون فایل xray_config.json را باز می کنید و قطعه کد زیر را به قسمت routing rules اضافه می کنید : 


```json
{
  "ip": [
    "geoip:ir"
  ],
  "outboundTag": "BLOCK",
  "type": "field"
},
{
  "domain": [
    "regexp:.*\\.ir$",
    "ext:iran.dat:ir",
    "ext:iran.dat:other",
    "geosite:category-ir-gov",
    "geosite:category-ir-news",
    "geosite:category-ir-bank",
    "geosite:category-ir-tech",
    "geosite:category-ir-travel",
    "geosite:category-ir-shopping",
    "geosite:category-ir-insurance",
    "geosite:category-ir-scholar",
    "snapp",
    "digikala",
    "tapsi",
    "blogfa",
    "sb24.com",
    "sheypoor.com",
    "tebyan.net",
    "beytoote.com",
    "telewebion.com",
    "Film2movie.ws",
    "Setare.com",
    "Filimo.com",
    "Torob.com",
    "Tgju.org",
    "Sarzamindownload.com",
    "downloadha.com",
    "P30download.com",
    "Sanjesh.org"
  ],
  "outboundTag": "BLOCK",
  "type": "field"
}
```

و در آخر با دستور زیر مزربان را ریستارت می کنیم : 
```bash
docker compose down && docker compose up -d
```

**:seedling: به امید آزادی**

**Comment by jaafar-c** [comment]
سلام دوست عزیز
قربان هر کاری کردم سایت های ایرانی بسته نمیشن
لطفا راهنمای ام کنید از سمت پنل اینم کانفیگ xray routing

  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "outboundTag": "blackhole",
        "ip": [
          "geoip:private"
        ],
        "domain": [
          "geosite:category-ir",
          "divar.ir"，
          "learnit.ir"
        ]
      },
      {
        "type": "field",
        "port": 53,
        "network": "tcp,udp",
        "outboundTag": "DNS-Internal"
      }
    ] 
}

**Comment by daniyousefifar** [comment]
سلام @jaafar-c 
دوست عزیز

1.  پیشنهاد میشه که رول IP ها و Domain ها جدا باشد.
2. مطمئن بشید که فایل های dat را دانلود کردید و در مسیر صحیح قرار داده اید.
3. مطمئن بشید که مقدار درست `outboundTag` را وارد می کنید.

باز اگر حل نشد می تونید از طریق آیدی `kingvision` در تلگرام با من در ارتباط باشید.

به امید فردایی بهتر...
