### ISSUE TITLE
مهاجرت از تک پورت به مولتی پورت

### ISSUE THREAD

**Issue by ItsElw** [Gozargah/Marzban#206]
سلام وقت بخیر،متاسفانه این روز ها ایرانسل به شدت روی پورت ۴۴۳ اختلال داره،تا حدی که ایپی تمیزی که روی بقیه پورتا کار میکنه روی پورت ۴۴۳ کار نمیکنه و یا به ندرت کار میکنه،بنابراین برای ایرانسل راهی جز استفاده از بقیه پورتای کلودفلر نمیمونه،ممنون میشم راهنمایی کنید که چطوری روی نسخه تک پورت از بقیه پورت ها بتونیم استفاده کنیم و یوزرها قطع نشن و فقط با اپدیت سابسکرایب بتونن وصل شن،باتشکر(داخل گروه این موضوعو مطرح کردم ولی انگار کسی راه حل قطعی نداره)

**Comment by OxJ4ck** [comment]
سلام
شما میتونید فایل xray_config.json رو ویرایش کنید و پورت رو از 443 به پورت دلخواهتون تغییر بدین.
فقط توجه کنید که اگر از CDN استفاده میکنید باید از پورت های مشخص شده استفاده کنید همچنین اگر از فایروال استفاده میکنید باید دسترسی به این پورت رو هم باز کنید.

**Comment by ach1992** [comment]
> سلام شما میتونید فایل xray_config.json رو ویرایش کنید و پورت رو از 443 به پورت دلخواهتون تغییر بدین. فقط توجه کنید که اگر از CDN استفاده میکنید باید از پورت های مشخص شده استفاده کنید همچنین اگر از فایروال استفاده میکنید باید دسترسی به این پورت رو هم باز کنید.

اینکه گفتید کار نمیکنه
اگر پورت تغییر بدیم لینک ساب از کار میفته و دیگه کار نمیکنه عملا بازم مولتی پورت نمیشه و فقط روی یک پورت دیگه هست و همه یوزرها هم از کار میفتند.

**Comment by OxJ4ck** [comment]
> > سلام شما میتونید فایل xray_config.json رو ویرایش کنید و پورت رو از 443 به پورت دلخواهتون تغییر بدین. فقط توجه کنید که اگر از CDN استفاده میکنید باید از پورت های مشخص شده استفاده کنید همچنین اگر از فایروال استفاده میکنید باید دسترسی به این پورت رو هم باز کنید.
> 
> اینکه گفتید کار نمیکنه اگر پورت تغییر بدیم لینک ساب از کار میفته و دیگه کار نمیکنه عملا بازم مولتی پورت نمیشه و فقط روی یک پورت دیگه هست و همه یوزرها هم از کار میفتند.

شما باید درخواست رو از پورت 443 به پورت دلخواهتون بفرستید برای مثال میتونید از nginx استفاده کنید و از کانفیگی مشابه زیر استفاده کنید
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name  marzban.example.com;

    ssl_certificate      /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/example.com/privkey.pem;

    location / {
        proxy_pass http://0.0.0.0:8880;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by shuvvan** [comment]
تشکر ولی این کد رو باید به کدوم قسمت اضافه کرد و یه توضیح هم بدید لطفا
