### ISSUE TITLE
Feature ip limit

### ISSUE THREAD

**Issue by farbodmahini** [Gozargah/Marzban#21]
Hello
First of all, thank you for your very effective and interesting project
As a suggestion, I will announce a few features to add in the future if possible:

1- Limiting the number of simultaneous users (IP) for each user
2- Telegram bot to monitor and announce the expiration and remind users of the expiration time
3- Server management panel such as V2board, SSpanel
4- Documentation and completion of API and its endpoints
5- Support for tunneling several servers
6- Ability to enter predetermined periods such as: daily, monthly instead of entering the date

**Comment by SaintShit** [comment]
Hi, thanks for your investigation

Telegram Bot has been implemeneted (#12) for admins, not for users currently, and it's dev branch
Also we're using FastApi which has it's built-in swagger documentation, you can access it by setting DOCS=True in your env. ([configuration](https://github.com/Gozargah/Marzban#configuration))
I don't have any idea on V2board, I put it aside to check it lately actually

We're thinking about implementing multi-server feature and will do it soon, but about IP limit, I think still there's no accurate way to make it yet. however I have got some ideas and I'm testing them rn.

the sixth feature you mentioned is on the way on pull request #20 🎉 thanks to @The-Daishogun

**Comment by OxJ4ck** [comment]
> Hi, thanks for your investigation
> 
> Telegram Bot has been implemeneted (#12) for admins, not for users currently, and it's on dev branch Also we're using FastApi which has it's built-in swagger documentation, you can access it by setting DOCS=True in your env. ([configuration](https://github.com/Gozargah/Marzban#configuration)) I don't have any idea on V2board, I put it aside to check it lately actually
> 
> We're thinking about implementing multi-server feature and will do it soon, but about IP limit, I think still there's no accurate way to make it. however I have got some ideas and I'm testing them rn.
> 
> the sixth feature you mentioned is on the way on pull request #20 🎉 thanks to @The-Daishogun

most of the management panel use [XrarR](https://github.com/XrayR-project/XrayR) as backend, you can use it. it's time saving for you and it's easier to migrate to Marzban from other panels.

**Comment by ayoubghasemi72** [comment]
hi
This IP restriction feature can be an important thing.
Please add this if possible.

thank you

**Comment by meaqese** [comment]
> hi This IP restriction feature can be an important thing. Please add this if possible.

The IP limit is impossible without modifying the xray core, as the author has already said, Marzban chooses a different way of development. And anyway, what will be the difference from the same x-ui if the authors of Marzban modify the xray core? What will be its uniqueness? 

As I said, and I will say, if you want a limit, use other panels, there are a lot of them. And the IP limit will not work on multiple servers. If you want a good system with an IP limit, use Marzban and write client applications with IP limits :)

**Comment by ayoubghasemi72** [comment]
> > hi This IP restriction feature can be an important thing. Please add this if possible.
> 
> The IP limit is impossible without modifying the xray core, as the author has already said, Marzban chooses a different way of development. And anyway, what will be the difference from the same x-ui if the authors of Marzban modify the xray core? What will be its uniqueness?
> 
> As I said, and I will say, if you want a limit, use other panels, there are a lot of them. And the IP limit will not work on multiple servers. If you want a good system with an IP limit, use Marzban and write client applications with IP limits :)

Definitely my choice was and still is Marzban
