### ISSUE TITLE
صفر شدن دیتا یوزیج پنل بعد از آپدیت

### ISSUE THREAD

**Issue by aliamg1356** [Gozargah/Marzban#215]
با سلام
بعد از آپدیت دیتا یوزیج تو پنل صفر شده و با وجود مصرف کاربران کانتر نمیندازه
در ضمن کاش افزوده شدم alpn و utls به صورت خودکار رو در این آپدیت اضافه کرده بودی

**Comment by aliamg1356** [comment]
و یک مشکل دیگه اینکه
در یکی از سرورها بعد مدنی کانتینر ngnixبالا نمیاد و متوقف میشه و هر بار هم میخوام استارت کنم استارت نمیشه و در لیست اجراییها دیده نمیشه

**Comment by shuvvan** [comment]
هاااا 
یعنی با داکر نصب نکنیم؟ احتمالش هست؟؟؟!! 
خوب الان خیلی دیره والا

**Comment by SaintShit** [comment]
> و یک مشکل دیگه اینکه در یکی از سرورها بعد مدنی کانتینر ngnixبالا نمیاد و متوقف میشه و هر بار هم میخوام استارت کنم استارت نمیشه و در لیست اجراییها دیده نمیشه

https://github.com/Gozargah/Marzban-examples/issues/16

**Comment by donatefi** [comment]
من هم امروز همین مشکل رو پیدا کردم و بعد از آپدیت Data Usage صفر شد. راه حلی نیست؟

**Comment by majiix** [comment]
من هم امروز همین مشکل رو پیدا کردم و بعد از آپدیت Data Usage صفر شد. راه حلی نیست؟

**Comment by s4I3h** [comment]
@donatefi کش مرورگر رو پاک کن
