### ISSUE TITLE
ارور 520 بعد از ریست کردن پنل

### ISSUE THREAD

**Issue by Amir7m8** [Gozargah/Marzban#219]
یکی از مشکلات پنل مرزبان به طور کلی اینه اگه بعد از چند وصت سرور تونو ریست کنید دیگه پنل مرزبان بالا نمیاد ولی کانفیگ ها کار می کنه 
کسی اگه راه حل میدونه راه نمایی کنه

**Comment by MuhammadAshouri** [comment]
@Amir7m8 docker compose down
rm -rf /var/lib/marzban/run
docker compose up

**Comment by Amir7m8** [comment]
ایول بلاخره کار کرد
