### ISSUE TITLE
اضافه کردن قابلیت اولویت دادن به اینباند ها در بخش هاست ستینگ

### ISSUE THREAD

**Issue by ItsElw** [Gozargah/Marzban#220]
سلام وقت بخیر،اگه داخل بخش هاست ستینگ قابلیتی اضافه بشه که بتونیم به اینباندهای فعال اولویت بدیم خیلی خوب میشه،مثلا کاری کنیم که بعد از اپدیت لینک سابسکریبشن اول کانفیگای vmess + ws نمایش داده بشن و ...

**Comment by gozarman** [comment]
Reorder hosts,
User needs to reorder the hosts using drag'n drop

**Comment by erfjab** [comment]
@MR-MKZ what do you think?

**Comment by MR-MKZ** [comment]
> @MR-MKZ what do you think?

I'm currently working on it.
