### ISSUE TITLE
نصب پنل یک پورت در هیتزنر  درست وصل میشود اما بعد از نصب در دیجیتال اوشین وی پی ان وضل نمی شود

### ISSUE THREAD

**Issue by sajadullahsafi** [Gozargah/Marzban#222]
سلام و عرز ادب
در اول تشکر خاص از سازنده این پنل که واقعا مشکلات مان را حل نموده است و بسیار یک پنل ساده و قدرمند را برایمان ساخته است.
. و از همه تقاضا من این است تا حد وس و توان کمک های خود را با مدیریت مرزیان اجرا کند. [لینک کمک](https://github.com/Gozargah/Marzban#donation)

دوهم
پنل یک پورت را طبق اموزش در هیتزنر نصب میکتم درست کار میکند اما وقتی که در سرور مجاری دیجیتل اوشین طبق اموزش نصب میکنم پنل نصب میشود وقتی مه کانفیگ میسازم وصل نمیشود
پورت 443 هم بار است در تظیمات کدام فرق نمیکند همه چیز یکسان است 
ای پی هم تمیز فقظ مشکل در وصل شدن با سرور دارد . در تست سرعت تایم اوت میدهد

![Screenshot_20230428-030120_v2rayNG.jpg](https://user-images.githubusercontent.com/1274394/235012521-e5112b04-4fe0-4527-a2b2-d84f3cf98f0c.jpg)

نمایش ایرور نصب پنل در دیجیتال اوشین

**Comment by SaintShit** [comment]
سلام
مشکلات از این قبیل قالبا مربوط به فیلترینگ و آیپی سرور مقصد هست. از اونجایی که مرزبان هیچ دستی در رسیدگی به درخواست های مربوط به پروکسی نداره و تماما توسط خود xray پردازش میشه.
