### ISSUE TITLE
عدم بسته شدن تورنت

### ISSUE THREAD

**Issue by M03ED** [Gozargah/Marzban#224]
با سلام.
بنده در تلاشم تورنت رو با فایل xray_config بلاک کنم ولی متاسفانه کد کار نمیکنه 
کد به صورت زیر هست 
"outbounds": [
        {
            "protocol": "blackhole",
            "settings": {},
            "tag": "blackhole"
        }
    ],
"routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "outboundTag": "blackhole",
                "protocol": [
                    "bittorrent"
                ]
            }
        ]
    }

**Comment by SaintShit** [comment]
سلام
این نمونه ها توی مخزن نمونه های خود xray یعنی https://github.com/XTLS/Xray-examples/ موجود بوده میتونین بررسی کنید
اگر براتون کار نمیکنه حتما xray قادر به تشخیص اینکه ترافیک torrent هست نبوده، میتونید پورت های پیشفرض تورنت رو هم برای محکم کاری ببندید.
