### ISSUE TITLE
ریست تنظیمات

### ISSUE THREAD

**Issue by shuvvan** [Gozargah/Marzban#225]
عرض ادب 

بفرمایید چطور میتونم کانفیگا و اینبوندها و تنظیماتی که اعمال کردم رو ریسیت کنم؟ لطفا راهنمایی کنید حیلی ضروریه

**Comment by SaintShit** [comment]
سلام اگر منظورتون از تنظیمات، متغیر های محیطی توی فایل env هست، کافیه پاکشون کنید. برای کانفیگ ها هم، تغییراتی که دادین رو برگردونین به کانفیگ پیشفرضی که در marzban-examples هست. اگر از marzban.sh استفاده میکنید، وقتی دستور 
```
marzban.sh install
```
نصب جدید جایگزین مرزبان قبلی میشه کامل و همه چی به تنظیمات پیشفرض برمیگرده، ولی کاربر ها همچنان باقی میمونن.
