### ISSUE TITLE
ساب تصادفی 

### ISSUE THREAD

**Issue by sirvan1133** [Gozargah/Marzban#232]
امکان داره یه گزینه به نام ساب تصادفی اظافه بشه 
یعنی برای هر کاربر یه ساب تصادفی در قسمت هاست و اس ان آی درست کنه ؟ 
اگر این اظافه بشه هیچ وقت نمیشه ساب دامنه رو فیلتر رد

**Comment by sirvan1133** [comment]
ترو خدا جواب بدین 
 این ایده مهمه 
برای مثال دامنه اینه 
example.com 
ما در بخش adress یا sni یا host 
اینو بنویسیم 
{RANDOM_SUB}.example.com 
در بخش راندوم ساب خودش برای هر کاربر یه کاراکتر دلخواه غیر تکراری تعیین کنه
اگر بیشتر اطلاعات میخواهین میتونم بیشتر توضیح بدم 
که چطور کار میکنه

**Comment by M03ED** [comment]
این قابلیت همین الان تو مرزبان وجود داره 
میتونید با زدن 
*.example.com
به جای servername و یا حتی برای لینک اینکار رو انجام بدید

**Comment by sirvan1133** [comment]
پس چرا آموزشش نبوده :(

**Comment by hadi7000** [comment]
تو بخش Host Setting نوشته که میتونی از * برای رندوم ساب استفاده کنی

**Comment by sirvan1133** [comment]
حله سپاس

**Comment by SaintShit** [comment]
@sirvan1133 یکی براش بنویسه که با وجود اینم فیلتر میشه دیگه

**Comment by hrprogrammer** [comment]
فعلا این مورد رو نداره و روشی هم که دوستمون گفتن آدرس رو شما باید خودت دستی رو کانفیگ دلخواه بزنی ساب دامین رو ولی منظور دوستمون فکر کنم این بود اتوماتیک باشه، اگه میشد اون پارامترهایی که تو remark میزنیم تو قسمت های دیگه هم بزنیم اوکی میشد

**Comment by SaintShit** [comment]
حالتی که @M03ED بهش اشاره کرد این کارو براتون انجام میده. بهش میگن wildcard dns. گواهینامه ssl برای
` *.domain.com‍‍‍‍`
دامنتون بگیرید، همین رو ست کنید و مرزبان جای * کاراکتر های رندوم میزاره.

**Comment by sirvan1133** [comment]
> حالتی که @M03ED بهش اشاره کرد این کارو براتون انجام میده. بهش میگن wildcard dns. گواهینامه ssl برای
> 
> ```
> *.domain.com‍‍‍‍
> ```
> 
> دامنتون بگیرید، همین رو ست کنید و مرزبان جای * کاراکتر های رندوم میزاره.

برای فیلتر نشدن دامنه تاثیری داره ؟

**Comment by shuvvan** [comment]
**میشه بیشتر توضیح بدید** 

- [ ] - من از کجا ssl بگیرم برای دامنه 

- [ ] - بعد الان من در کلادفلر برای `*.mydomain.me` ‌آیپی تانلم رو تنظیم کردم و در قسمت سرورآدرس اینو ست کردم ولی هر بار بروزرسانی میکنم کانفیگارو هیچی تغییر نمی کنه و `*.mydomain.me` نشون میده ! باید کار خاصی تنظیم خاصی انجام بدم؟

**Comment by shuvvan** [comment]
> **میشه بیشتر توضیح بدید**
> 
لطفا پاسخ این موارد رو بفرمایید خیلی ضروریه
