### ISSUE TITLE
Flow Select

### ISSUE THREAD

**Issue by M03ED** [Gozargah/Marzban#248]
Hi guys.
Can you move flow select from edit user to host settings ?
When it's in edit user we need to enable it manually for each user but if be in host settings it's gonna be applied for all users at once.

**Comment by OxJ4ck** [comment]
afaik flow is client setting, so you need to change it for every client (user).

**Comment by M03ED** [comment]
Surely they can add option make it enable for all clients.
If I try to add flow to client line in xray config file marzban can't be run.

**Comment by OxJ4ck** [comment]
چون دیدم تو Discussions فارسی حرف زدی، فارسی میگم، این نظر منه شاید برنامه نویس های مرزبان نظر دیگه ای داشته باشن، شما وقتی برای همه کاربر ها flow رو فغال کنی برای جاهایی ک نخوایی استفاده کنی باز باید دستی غیرفعال کنی چون طبق چیزی که میدونم flow روی tcp و mKCP و domainsocket میشه استفاده کرد پس یه چیز جامع نیست که برای همه فعال بشه.

**Comment by M03ED** [comment]
خب بله قطعا همین طوره
باید یه شرط واسش نوشته بشه که مثلا فقط زمانی که reality یا xtls روشنه گزینه شو نمایش بده 
ولی خب در کل میشه انجام داد 
![image](https://user-images.githubusercontent.com/50927468/236670156-f19e88f9-78b3-4b4c-a19b-ad4d1c4ab338.png)
درست مثل alpn که الان به صورت کلی میشه تغییر داد

**Comment by zhongfq** [comment]
> خب بله قطعا همین طوره باید یه شرط واسش نوشته بشه که مثلا فقط زمانی که reality یا xtls روشنه گزینه شو نمایش بده ولی خب در کل میشه انجام داد ![image](https://user-images.githubusercontent.com/50927468/236670156-f19e88f9-78b3-4b4c-a19b-ad4d1c4ab338.png) درست مثل alpn که الان به صورت کلی میشه تغییر داد

i add this setting in editing proxy panel https://github.com/Gozargah/Marzban/pull/327/commits/80dacd826addd874db133b2d1cec7019d5011ea4

**Comment by NaderAp** [comment]
کاملا موافقم. برای reality که دیفالت باید flow رو تغییر داد بهتره قابلیت تنظیم دیفالت flow قرار داده بشه
