### ISSUE TITLE
Docker container doesn't expose ports

### ISSUE THREAD

**Issue by Borderliner** [Gozargah/Marzban#25]
I've installed Marzban with docker images tutorial, everything runs butter-smooth except that I don't get to have ports like 8880 open. Do I need to setup a `reverse proxy`  or something? Also `netstat -nlp` shows nothing.

**Comment by SaintShit** [comment]
@Borderliner Hi, are you running multi-port? how about proxy ports? are they listening?

**Comment by Borderliner** [comment]
@SaintShit Yes I'm running the multi-port version. I'm using Caddy for server. Do I need to setup a reverse proxy or not?
```

```

**Comment by Borderliner** [comment]
I guess there were issues with my certificate. It's resolved now by following the tutorial exactly.
