### ISSUE TITLE
 اضافه کردن یه کاتنیگ برای همه یوزرها بدون نیاز به ادیت کردن تنظیمات کاتفیگ یوزر ها

### ISSUE THREAD

**Issue by ItsElw** [Gozargah/Marzban#257]
سلام وقت بخیر،اگر بشه که یک اپشنی تو پنل باشه که بتونیم یک کانفیگ و برای همه یوزرا بدون نیاز به ادیت اینبانداشون قرار بدیم،مثلا من به همه یوزرا تروجان دادم،حالا میخوام یه کاتفیگ ویلس ریلیتی برای همه اضافه بشه،برای این کار مجبورم که تک تک اینباند های همه یوزرهارو ادیت کنم و کاتفیگ vless tcp رو براشون فعال کنم،ولی اگر این امکان بلشه که نیازی نباشه همرو ادیت بزنم و کانفیگ براشون با اپدیت لینک سابسکریبشن اضافه بشه عالی میشه،با تشکر.

**Comment by ach1992** [comment]
اره این خیلی خوبه که مثلا بشه یکباره برای همه یوزرها یک کانفیگی رو قطع کرد یا یه کانفیگی رو فعال کرد.

**Comment by pbooyq** [comment]
@ach1992 اسکریپتش هست ولی خود مرزبان امکان نداره

**Comment by sirvan1133** [comment]
> @ach1992 اسکریپتش هست ولی خود مرزبان امکان نداره

میشه اسکریپتش  رو بگین ؟
