### ISSUE TITLE
[BUG] [Dev] Adding unnecessary inbound config is mandatory

### ISSUE THREAD

**Issue by Musixal** [Gozargah/Marzban#259]
سلام
برای ذخیره قسمت hosts باید حتما یک کانفیگ وجود داشته باشه. مثلا در اینجا حتما باید یک کانفیگ تروجان وارد کنم که تغییرات اعمال بشه. در صورتی که نیازی به این inbound ندارم.

<img width="467" alt="Screenshot 2023-05-09 at 23 58 49" src="https://github.com/Gozargah/Marzban/assets/124933548/7952452d-f7db-4d9a-b29b-e682fc2ed0cd">

**Comment by s4I3h** [comment]
@Musixal خب از فایل
nano xray_config.json
کامند کنیدش یا پاک

**Comment by Musixal** [comment]
منطقی نیست. شاید بعدا بخوام کانفیگ تروجان اد کنم. توی نسخه dev این مشکل وجود داره.

**Comment by s4I3h** [comment]
@Musixal خب کامند کن
بعد خواستی باز ادیت کن
یکم فقط کار داره

**Comment by Musixal** [comment]
باگ frontend رو باید توی frontend رفع کرد

**Comment by SaintShit** [comment]
@Musixal این مشکل نیست، validation هست. که اینباندی بدون هاست نمونه.

**Comment by Musixal** [comment]
جالبه توی نسخه ی stable چنین مشکلی نبود. الان مجبور شدم کامل پروتکل ویمس و تروجان رو از کانفیگ حذف کنم. یوزر فرندلی نیست.

**Comment by SaintShit** [comment]
9912fc9945825ac609b03e88070cb2ed44a9d3f9
