### ISSUE TITLE
مشکل EOF در نسخه ی DEV

### ISSUE THREAD

**Issue by sirvan1133** [Gozargah/Marzban#272]
من در حالت ریلیتی خطای EOF دارم 
یعنی هر تغییری در فایل JASON بدم خطای EOF پیدا میکنه 
و باید فلو رو غیر فعال و فعال کنم تا درست بشه 
و این برای هر کاربر باید انجام بشه که درست بشه

**Comment by SaintShit** [comment]
@sirvan1133 مشکل قبلا رفع شده
آخرین نسخه dev رو pull کنید

**Comment by sirvan1133** [comment]
> @sirvan1133 مشکل قبلا رفع شده آخرین نسخه dev رو pull کنید
چطور pull  کنیم ؟

**Comment by pbooyq** [comment]
@sirvan1133 docker compose down
docker compose pull
docker compose up -d

**Comment by sirvan1133** [comment]
یوزرا پاک نمیشن ؟

**Comment by pbooyq** [comment]
@sirvan1133 خیر

**Comment by sirvan1133** [comment]
> @sirvan1133 docker compose down docker compose pull docker compose up -d

یوزرا پاک نمیشن ؟

**Comment by sirvan1133** [comment]
> @sirvan1133 خیر

سپاس

**Comment by sirvan1133** [comment]
> @sirvan1133 docker compose down docker compose pull docker compose up -d
وقتی این دستور رو میزنم 
docker compose down
این ارور رو میده 
no configuration file provided: not found

**Comment by sirvan1133** [comment]
حل شد یادم نبود برم پوشه مرزبان

**Comment by sirvan1133** [comment]
> @sirvan1133 مشکل قبلا رفع شده آخرین نسخه dev رو pull کنید

میشه در  نسخه ی dev از مرزبان نود به عنوان vless + ws +tls 
استفاده کرد ؟ 
اگه آره ، گوهینامه SSL را در کدام سرور بگیریم ؟
