### ISSUE TITLE
Add two features

### ISSUE THREAD

**Issue by AC-Lover** [Gozargah/Marzban#273]
- Please add the feature of limiting the node for the user or in general
- And add the feature of disabling or activating the host for the user, as well as the feature of adding the host separately to the user

**Comment by zhongfq** [comment]
@AC-Lover hello, recently i implement some feature relative with this https://github.com/zhongfq/marzban/tree/dev-sub, but it still in progress.

feature of these:

- rules manage
- proxy manage
- proxy group manage
- proxy for user manage
- setting for clash or others

![image](https://github.com/Gozargah/Marzban/assets/2108342/6bedea97-305e-412b-b2d3-6e70271ad9ed)
![image](https://github.com/Gozargah/Marzban/assets/2108342/1af234e1-e051-483d-8f0a-309bf7b3521b)
![image](https://github.com/Gozargah/Marzban/assets/2108342/500beb9d-f378-4e56-8cc0-357b70ffceaf)
![image](https://github.com/Gozargah/Marzban/assets/2108342/0262798c-d6ac-46d2-b123-da816c7a5e88)

**Comment by reloadlife** [comment]
@zhongfq Oh, that is cooool

**Comment by zhongfq** [comment]
@AC-Lover hello, can you test it https://github.com/zhongfq/marzban/tree/dev-sub

1. alembic upgrade head
2. add proxy
3. set domain and add proxy tag to user
4. copy the subscription url to use

**Comment by zhongfq** [comment]
> @zhongfq Oh, that is cooool

https://github.com/Gozargah/Marzban/pull/327

it is available for test now

**Comment by zhongfq** [comment]
> @zhongfq Oh, that is cooool

you can try my fork, it already done, https://github.com/zhongfq/marzban

**Comment by zhongfq** [comment]
> > > @zhongfq Oh, that is cooool
> > 
> > 
> > you can try my fork, it is very easy to manage different proxies for each people with different subscription url prefix, it already done, https://github.com/zhongfq/marzban
> 
> Can I contact you on Telegram?

I have no Telegram, you can contact me with gmail
