### ISSUE TITLE
variable for SNI

### ISSUE THREAD

**Issue by Kiya6955** [Gozargah/Marzban#274]
درود
اگه variable باشه برا SNI مثل Remark که یوزر نیمارو به عنوان ساب اد کنیم و هر یوزر یدونه ساب داشته باشه که فیلتر نشه

**Comment by OxJ4ck** [comment]
سلام میتونید از * استفاده کنید، مرزبان بصورت رندم سابدامین میسازه براتون.

**Comment by amiraliq-1** [comment]
@OxJ4ck البته باید تو کلودفلر رکورد با ساب * بزنه تا به مشکل نخورن

**Comment by Kiya6955** [comment]
.

**Comment by amiraliq-1** [comment]
@Kiya6955 شنیدن کی بود مانند دیدن
