### ISSUE TITLE
کار نکردن vless tcp header 

### ISSUE THREAD

**Issue by solidwar** [Gozargah/Marzban#277]
![image](https://github.com/Gozargah/Marzban/assets/130087244/c76c8889-f50b-4a3a-84e8-0eb59703d472)

![image](https://github.com/Gozargah/Marzban/assets/130087244/5a13cc34-bd35-4d09-8d17-5b5e3aa7bd9e)
 تک پورت 443  مرزبان رو نصب کردم. این باره سومه که پنل روی آیپی های مختلف تست کردم دقیقا همین آیپی رو روی  پنل دیگه مثل اسدی 
و ثنایی و حالا هرکسی دیگه جز کافکا نصب کنم جواب میگیرم

![image](https://github.com/Gozargah/Marzban/assets/130087244/93e38ac6-9fcf-4258-a4e5-df02c4d46ceb)
![image](https://github.com/Gozargah/Marzban/assets/130087244/3c53a52f-16e8-4c2f-9941-6bc013b46bcb)
بصورت دستی متغیر هایی که در ویمس بود و در ویلس نبود جایگزینی کردم اما هنوزم مشکل داره

**Comment by OxJ4ck** [comment]
احیانا مشکل از path تون نیست؟

**Comment by solidwar** [comment]
> احیانا مشکل از path تون نیست؟

خیر. عرض کردم که

**Comment by OxJ4ck** [comment]
> خیر. عرض کردم که

اخه هر اینباند path مربوط به خودشو داره و شما نمیتونی path مربوط به vmess رو به vless بدین، چون هر دو کانفیگتون از پورت 443 استفاده میکنه این path خیلی مهمه.
اگر فایل json رو بفرستید شاید زودتر به نتیجه برسید.
