### ISSUE TITLE
ram usage with node

### ISSUE THREAD

**Issue by danial-barati** [Gozargah/Marzban#279]
بالا رفتن عجیب رم بدون توقف  . کانفیگ vmess + ws  با پورت 443 . بعد از اضافه کردن نود به سرور برای استفاده 2 سرور به عنوان cdn  , رم سرور مادر طی یک روز به 1 گیگ میرسه و متوقف نمیشه بالاتر هم میره . باید هی reboot کنم و بعد از 24 ساعت دوباره بالا میره

**Comment by dangodly** [comment]
سرعت سرور مادر هم به حداقل ترین حالت ممکن میرسه
