### ISSUE TITLE
عدم نمایش درست صفحات بعد از انتقال بکاپ

### ISSUE THREAD

**Issue by younex65** [Gozargah/Marzban#280]
من فایلهای مورد نیاز بکاپ رو از سرور قبل به سرور جدید انتقال دادم همه چی اوکیه ولی صفحه 2 برام نمایش داده نمیشه تو قسمت سرچ اسم یوزر رو سرچ میکنم میاره ولی رو شماره صفحه کلیک میکنم چیزی نمیاره

**Comment by mobinalipour** [comment]
منم همین مشکل رو دارم
