### ISSUE TITLE
ری استارت شدن پشت سر هم ایکس ری با بستن سایت های ایرانی در فایل جیسون

### ISSUE THREAD

**Issue by Elhwm** [Gozargah/Marzban#282]
سلام وقت بخیر،در نسخه دو وقتی طبق اموزش داخل گیت هاب سایتای ایرانیو بلاک میکنیم،دیگه پنل بالا نمیاد و ایکس ری پشت سر هم ری استارت میشه

**Comment by iERROR-XD** [comment]
@Elhwm میتونید این کارو با یه اسکریپت دیگه انجام بدین و تغییراتی تو فایل ایکس ری ایجاد نکنید

**Comment by Elhwm** [comment]
> @Elhwm میتونید این کارو با یه اسکریپت دیگه انجام بدین و تغییراتی تو فایل ایکس ری ایجاد نکنید

میشه اسکریپتو بفرستید؟

**Comment by iERROR-XD** [comment]
@Elhwm bash <(curl -s https://raw.githubusercontent.com/elemen3/wepn/master/wepn.sh)

**Comment by SaintShit** [comment]
سلام، دلیل ریست شدن مداوم رو میتونید از قسمت لاگ های core بررسی کنید
