### ISSUE TITLE
Result expired error

### ISSUE THREAD

**Issue by AC-Lover** [Gozargah/Marzban#283]
Hello @zhongfq 
This error is constantly being spammed in the logs on the central server (Not Node).
I think it is related to the parts that you edited
This error has disrupted my entire panel!
Tell me if you need more information
Please check and fix, I need this error to be fixed very urgently

![image](https://github.com/Gozargah/Marzban/assets/49290111/3952e91a-e761-4dd2-aa22-9e5089d3a131)

![image](https://github.com/Gozargah/Marzban/assets/49290111/a58cec26-5373-4389-b49e-584d77ab28b9)

**Comment by zhongfq** [comment]
@AC-Lover i already redesign the usage for user and node https://github.com/Gozargah/Marzban/pull/263, it record usage for user and node per hour per record, but it not merged.

**Comment by AC-Lover** [comment]
> @AC-Lover i already redesign the usage for user and node #263, it record usage for user and node per hour per record, but it not merged.

It was merged and I updated it and it is still not fixed 😔

**Comment by pbooyq** [comment]
@AC-Lover چی؟

**Comment by zhongfq** [comment]
@AC-Lover https://github.com/Gozargah/Marzban/commit/d05e32da79667e32c4c18d8c56c94123b8c7d057

**Comment by zhongfq** [comment]
> > @AC-Lover i already redesign the usage for user and node #263, it record usage for user and node per hour per record, but it not merged.
> 
> It was merged and I updated it and it is still not fixed 😔

show the log again

**Comment by AC-Lover** [comment]
> > > @AC-Lover i already redesign the usage for user and node #263, it record usage for user and node per hour per record, but it not merged.
> > 
> > 
> > It was merged and I updated it and it is still not fixed pensive
> 
> show the log again

https://pastebin.com/SG8GAGqi

**Comment by SaintShit** [comment]
I'm trying to fix it, it seems that the connection.ping() gets timed out

**Comment by zhongfq** [comment]
I think it should try several times, because lost ping packet is very common

**Comment by SaintShit** [comment]
> I think it should try several times, because lost ping packet is very common

I got his server to check, it doesn't get any response at all, from three different nodes, that's weird. all calls lead to timeout. I also checked the firewall on both servers, everything seems fine, they can ping each other too. I'm still investigating it

**Comment by zhongfq** [comment]
> 

the ping api is thread safe? the ping can be call multi times at once and don’t affect others?

**Comment by AC-Lover** [comment]
**This bug was fixed in an update, thank you all**

**Comment by zhongfq** [comment]
> This bug was fixed in an update, thank you all

how was fixed?

**Comment by alisystemit** [comment]
@zhongfq Yes

**Comment by SaintShit** [comment]
> > This bug was fixed in an update, thank you all
> 
> how was fixed?

This was due to a change I made. It got stuck on start when the log level was "error" and above ( because Xray didn't print 'Xray * started' ). 
https://github.com/Gozargah/Marzban-node/commit/e6a2346ddacb3f0a49ddd8482bd5d369301c4885

Now I need to implement something to fetch node logs, to catch Xray errors.
