### ISSUE TITLE
Sending random sni with no reason to user 

### ISSUE THREAD

**Issue by M03ED** [Gozargah/Marzban#290]
hi 
in last dev version i recieve random sni with no reason , sometimes happen some times not

![image](https://github.com/Gozargah/Marzban/assets/50927468/6b41e638-e23c-431b-9406-1f09655527c1)

i didnt use any *.domain.com in sni or address and xray config.

i test it with v2ray and v2rayng.

**Comment by SaintShit** [comment]
what you set? you can replace your domain with `example.com` and send it here

**Comment by M03ED** [comment]
Sni : Domain.com
Name server in xray config : domain.com

**Comment by M03ED** [comment]
I apologize, if sni in host settings be empty this happen.

**Comment by SaintShit** [comment]
are you sure you don't have any serverName set in you're xray config?

**Comment by M03ED** [comment]
I have servername in xray config yes but when I don't fill sni in host settings it send random subdomain to user
![IMG_20230528_143733.jpg](https://github.com/Gozargah/Marzban/assets/50927468/a19e376b-995e-447b-a81b-2e3a058691bf)

**Comment by SaintShit** [comment]
by default, the serverName in config will be used, unless u define something else in hosts settings, would you remove serverName from your json config and test it out?

**Comment by M03ED** [comment]
I didn't test that but when I fill sni in host settings problem gonna be solved.
If you want access to my server I can send it to test it.

**Comment by SaintShit** [comment]
@M03ED please send your configuration for this inbound if you can ( with including serverName )

**Comment by M03ED** [comment]
i sent it to your telegram

**Comment by M03ED** [comment]
Looks like this is new feature that read SSL certificate and detect domain automatic.
You don't have to add servername in json file.
As I have wildcard certificate marzban make random sni and send it to client.
I close issue.
