### ISSUE TITLE
Error opening external geosite file

### ISSUE THREAD

**Issue by GawrAme** [Gozargah/Marzban#298]
it keep showing error 

Xray 1.8.1 (Xray, Penetrates Everything.) Custom (go1.20.3 linux/amd64)

A unified platform for anti-censorship.
2023/05/31 14:08:47 [Info] infra/conf/serial: Reading config: stdin:
Failed to start: main: failed to load config files: [stdin:] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: ext:geositeindo.dat:rule-indo > infra/conf: failed to load external sites: rule-indo from geositeindo.dat > infra/conf: failed to load file: geositeindo.dat > infra/conf: failed to open file: geositeindo.dat > open /usr/local/share/xray/geositeindo.dat: no such file or directory

![image](https://github.com/Gozargah/Marzban/assets/97426017/a60f5c5e-d534-48dd-b896-aabc34be5aae)

i already put the dat file in the right folder, with xray standart settings it can run, but with marzban panel can't.
is i missing some step here?

![image](https://github.com/Gozargah/Marzban/assets/97426017/402d36db-ff9a-49a5-b1f8-95f384c5e3a5)

**Comment by SaintShit** [comment]
You put it on your machine, Marzban's service only have access to `/var/lib/marzban` directory.
you can make define a custom assets directory and put the files there
for example:
```
# create the directory
mkdir -p /var/lib/marzban/assets/
# download default .dat files
wget -O /var/lib/marzban/assets/geoip.dat https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
wget -O /var/lib/marzban/assets/geosite.dat https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
```
and add your custom files to `/var/lib/marzban/assets/` as well

then just set this in your environment ( put it in `/opt/marzban/.env `)
```
XRAY_ASSETS_PATH = "/var/lib/marzban/assets/"
```

**Comment by GawrAme** [comment]
Thank you for reply!

I'll give it a try.

Another case, is possible to change the Core of Xray? I want to rollback to version 1.7.2 if that possible.

**Comment by SaintShit** [comment]
see [configuration](https://github.com/Gozargah/Marzban#configuration)

you have to download xray somewhere in /var/lib/marzban and set `XRAY_EXECUTABLE_PATH` variable
