### ISSUE TITLE
Node Connection

### ISSUE THREAD

**Issue by M03ED** [Gozargah/Marzban#303]
hi
i have problem with node on specific server 
i try to add node on server but i get this error

![image](https://github.com/Gozargah/Marzban/assets/50927468/059849ef-e2d9-4695-8eef-139ed58733bd)

then i try to add this node to another server but it connected fast and easy 
then i run another marzban on same vps with problem and thats work fine too
then i replace my main database with second marzban and i didn't get any error
i tried few node but for all them this happen i dont know why

**Comment by lvlrf** [comment]
![image](https://github.com/Gozargah/Marzban/assets/26125186/f488c1b3-f4ad-4e9c-8be8-4ac097b7a314)
i hvae same issue

installed fresh marzban, also update my node from docker,
in the left Marzban Log, and other side my node logs
i try to change port and ect. but dosnt work

**Comment by M03ED** [comment]
my problem was because iran.dat file 

solved with this works

mkdir -p /usr/local/share/xray/

transfer files to this folder
add this line to docker compose

volumes:
  - /usr/local/share/xray/:/usr/local/share/xray/

**Comment by SaintShit** [comment]
> ![image](https://user-images.githubusercontent.com/26125186/242756736-f488c1b3-f4ad-4e9c-8be8-4ac097b7a314.png) i hvae same issue
> 
> installed fresh marzban, also update my node from docker, in the left Marzban Log, and other side my node logs i try to change port and ect. but dosnt work

You would check the debug logs of your node to detect what's the problem, we're planning to make the errors more clear.
you can enable DEBUG logs by setting DEBUG environment variable to your docker compose file

**Comment by lvlrf** [comment]
> > ![image](https://user-images.githubusercontent.com/26125186/242756736-f488c1b3-f4ad-4e9c-8be8-4ac097b7a314.png) i hvae same issue
> > installed fresh marzban, also update my node from docker, in the left Marzban Log, and other side my node logs i try to change port and ect. but dosnt work
> 
> You would check the debug logs of your node to detect what's the problem, we're planning to make the errors more clear. you can enable DEBUG logs by setting DEBUG environment variable to your docker compose file

here you are, this is my node logs

![image](https://github.com/Gozargah/Marzban/assets/26125186/f47246c8-3e43-4736-9c86-88675621fab1)
