### ISSUE TITLE
All Configs Disconnect

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#305]
سلام مرزبان عشقم خوبی؟
همه کانفیگا یهو قطع میشن و مجدد با ریستارت کردن xray اوکی میشن 
و این اتفاق چندین بار در طول روز اتفاق میفته
ارور ها معمولا EOF و Closed on Pipe هستن 
چکار کنم درست شه؟ :(

**Comment by arashcg12** [comment]
اگر این مشکل رو حل کردین به منم اطلاع بدین
