### ISSUE TITLE
Jinja2 template not found

### ISSUE THREAD

**Issue by Iambabyninja** [Gozargah/Marzban#312]
Iam creating index.html file on      /var/lib/marzban/homepage/
Edit .env file and set variable
But if iam open home page, iam get server error
Jinja says it can't find the template, although it is 100% present in the directory and the path is explicitly specified in .env

![image](https://github.com/Gozargah/Marzban/assets/104270279/90fcbd48-e105-4191-922c-3678fa1485f9)

![image](https://github.com/Gozargah/Marzban/assets/104270279/08940d37-cf72-4d19-a1c0-9ecdc4d313c0)
![image](https://github.com/Gozargah/Marzban/assets/104270279/eb2c3984-425f-40b8-862e-b8a500d8079d)

**Comment by M03ED** [comment]
i have the same problem

**Comment by M03ED** [comment]
i tried subscription page template and it have same problem 
marzban-marzban-1  | ERROR:    Exception in ASGI application
marzban-marzban-1  | Traceback (most recent call last):
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marzban-marzban-1  |     return await self.app(scope, receive, send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
marzban-marzban-1  |     await super().__call__(scope, receive, send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
marzban-marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
marzban-marzban-1  |     raise exc
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
marzban-marzban-1  |     await self.app(scope, receive, _send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
marzban-marzban-1  |     await self.app(scope, receive, send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
marzban-marzban-1  |     raise exc
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
marzban-marzban-1  |     await self.app(scope, receive, sender)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marzban-marzban-1  |     raise e
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marzban-marzban-1  |     await self.app(scope, receive, send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
marzban-marzban-1  |     await route.handle(scope, receive, send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
marzban-marzban-1  |     await self.app(scope, receive, send)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
marzban-marzban-1  |     response = await func(request)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
marzban-marzban-1  |     raw_response = await run_endpoint_function(
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
marzban-marzban-1  |     return await run_in_threadpool(dependant.call, **values)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
marzban-marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
marzban-marzban-1  |     return await get_asynclib().run_sync_in_worker_thread(
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marzban-marzban-1  |     return await future
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
marzban-marzban-1  |     result = context.run(func, *args)
marzban-marzban-1  |   File "/code/app/views/subscription.py", line 46, in user_subcription
marzban-marzban-1  |     render_template(
marzban-marzban-1  |   File "/code/app/templates/__init__.py", line 21, in render_template
marzban-marzban-1  |     return env.get_template(template).render(context or {})
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
marzban-marzban-1  |     return self._load_template(name, globals)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
marzban-marzban-1  |     template = self.loader.load(self, name, self.make_globals(globals))
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
marzban-marzban-1  |     source, filename, uptodate = self.get_source(environment, name)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_sourcemarzban-marzban-1  |     raise TemplateNotFound(template)
marzban-marzban-1  | jinja2.exceptions.TemplateNotFound: /var/lib/marzban/subscription/index.html

**Comment by kastov** [comment]
You need to uncomment templates dir first.
Example (!working!):
```
CUSTOM_TEMPLATES_DIRECTORY="/var/lib/marzban/templates/"
CLASH_SUBSCRIPTION_TEMPLATE="/clash/my_clash.yml"
# SUBSCRIPTION_PAGE_TEMPLATE="subscription/index.html"
# HOME_PAGE_TEMPLATE="home/index.html"
```

inside /templates/ you should have /clash/ folder for example.
