### ISSUE TITLE
VLESS WS

### ISSUE THREAD

**Issue by rm-killer** [Gozargah/Marzban#316]
PLz add VLESS WS.
This is the thing that just work for me.
PLz add it

**Comment by OxJ4ck** [comment]
you can use any protocol and transmission you want by edition xray_config.json

**Comment by rm-killer** [comment]
ohh tnx. didnt know.
BUt how can i add it both???
i  mean i want to see both in the dashboard for my user. not just change it but add it.

**Comment by zhongfq** [comment]
> ohh tnx. didn't know. BUt how can i add it both??? i mean i want to see both in the dashboard for my user. not just change it but add it. BTW im not familiar with environment variables. can you tell me how can i change this file with nano??? i can find the file with WinSCP directly in the file path they provided

https://github.com/Gozargah/Marzban/pull/327/files#diff-72cde22412067c6e97204c0b8fb105e477d0ac2e577f3943119ca6f91ed58f8a you can see xray_config.json changes, i add vless ws
