### ISSUE TITLE
Try to access to dashboard Using Domain 

### ISSUE THREAD

**Issue by rm-killer** [Gozargah/Marzban#317]
IM trying to logging with my domain name that are pointed to my ip address. it doesn't load. why?
DO i have to do anything before trying to logging with my domain??
im using Cloudflare dns and its not in proxy mode. 

Update:
I tied to access with another vpn and i did.
its weird. 
my domain name is not banned or filtered. i can ping it out with cmd. but still if i want to login in to the dashboard i need to use vpn.  every time i hard refresh my page it doesn't reload until i turn-on my vpn Any idea what can cause this issue???

**Comment by SaintShit** [comment]
your IP might be blocked in your region.
