### ISSUE TITLE
New inbounds are on for all users as default

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#324]
سلام به مرزبان دوس تداشتنی
امیدوارم حالت خوب باشه

میگم که من وقتی یه inbound جدید اضافه میکنم تو xray دیفالت برای همه یوزرا تیک میخوره. میشه یه آپشنی باشه که انتخاب کنیم برای همه یوزرا دیفالت تیک بخوره یا نخوره؟ (:

**Comment by farhadan** [comment]
تو قسمت آدرس هاست اینباد اضافه شده، @ بزنید تا برای همه غیر فعال بشه

**Comment by Habib1385** [comment]
@farhadan سلام 
هم این روش 
هم اینکه اگر نسخه dev باشید از طریق ربات تلگرام برا همه کاربر ها می تونید غیر فعال کنید
