### ISSUE TITLE
Major bug: the entire opt directory is deleted when uninstalling

### ISSUE THREAD

**Issue by WoChen5770** [Gozargah/Marzban#325]
**Describe the bug**
`
INSTALL_DIR="/opt"
uninstall_marzban() {
    if [ -d "$INSTALL_DIR" ]; then
        colorized_echo yellow "Removing directory: $INSTALL_DIR"
        rm -r "$INSTALL_DIR"
    fi
}
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Machine details (please complete the following information):**
 - OS: [e.g. ubuntu 20]
- Python version: [e.g 3.8]
- Nodejs version: [e.g 16.17]

**Additional context**

**Comment by SaintShit** [comment]
That's a BIG BIG problem, thanks for the report!
