### ISSUE TITLE
تک کاربره کردن

### ISSUE THREAD

**Issue by miladf17** [Gozargah/Marzban#331]
سلام وقتتون بخیر
پنل واقعا خیلی عالی هست دست تک تک سازنده هاش درد نکنه 
فقط یه سوالی داشتم اینه که چجوری میشه هر یوزر رو محدود کرد فقط یک کاربر بتونه وصل شه
منظورم اینه که تک آی پی بشه

**Comment by SaintShit** [comment]
سلام
درحال حاضر امکانش نیست، راه هایی که برای این کار وجود داره هیچکدومشون "بهترین راه" نیستند در نتیجه هنوز تصمیمی برای این قابلیت گرفته نشده.
ولی میتونید از اسکریپت هایی دوستان نوشتن استفاده کنید
https://github.com/houshmand-2005/V2IpLimit
