### ISSUE TITLE
Turn Node Off or On

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#336]
Hello my lovely Marzban
I hope you're all doing great!

Can you please add an option to turn the node off or on? 

Currently we should delete the node if we want to turn it off and if we want to add it again then we should get the ssl certificate, ip, port,.. 

Thank you so very much!

**Comment by M03ED** [comment]
Done in pr #548

**Comment by iamtheted** [comment]
> Done in pr #548

I really appreciate your time and effort making this happen 💙

**Comment by flyinthe-sky** [comment]
> Done in pr [#548](https://github.com/Gozargah/Marzban/pull/548)

Can you guide on how to use it?

**Comment by flyinthe-sky** [comment]
> Done in pr [#548](https://github.com/Gozargah/Marzban/pull/548)

Can you guide on how to do it?
