### ISSUE TITLE
نحوه محاسبه محدودیت ترافیک زمانی

### ISSUE THREAD

**Issue by morteza-rashidi** [Gozargah/Marzban#337]
سلام وقت بخیر
وقتی ترافیک رو بصورت دوره ای مثلا ماهیانه قرار میدیم این ترافیک چه زمانی ریست میشه؟
مثلا 30 روز پس از ایجاد اکانت یا ... ؟
ممنون میشم این مورد رو راهنمایی کنید

**Comment by SaintShit** [comment]
https://github.com/Gozargah/Marzban/blob/1821e2da5b0736c057c6384dc751325d23d53ae8/app/db/models.py#L57
اگر کاربر تاحالا ریست نداشته، از تاریخ ساختش محاسبه میشه و اگر داشته، از همون تاریخ
برای هر کاربر به نسبت تاریخ ریست خودش
