### ISSUE TITLE
مشکل حجم در کانفیگ های تانل شده دوکومودور

### ISSUE THREAD

**Issue by zaynbl** [Gozargah/Marzban#342]
سلام
من متوجه یه باگ شدم که وقتی از پنل اولم یه دوکومودور ساختم و توی پنل شما هم کانفیگ زدم بر اساس همون پورت و آدرس، کانفیگ هم راحت وصل میشه،ولی حجم از داخل پنل شما اصلا حساب نمیشه حتی یه کیلوبایت، در حالی که روی پنل xui اولم نگاه کردم روی دوکومودور که ساختم حجم داره حساب میشه...
لطفاً این مشکلوحل کنید که حجم اینجور کانفیگ ها حساب بشه

**Comment by SaintShit** [comment]
سلام
کانفیگتون رو ارسال کنید
مرزبان فقط اینباند های vmess, vless, trojan, shadowsocks رو مدیریت میکنه
dokodemodoor کاربر بهش اضافه نمیشه

**Comment by mohamadm0meni** [comment]
> سلام من متوجه یه باگ شدم که وقتی از پنل اولم یه دوکومودور ساختم و توی پنل شما هم کانفیگ زدم بر اساس همون پورت و آدرس، کانفیگ هم راحت وصل میشه،ولی حجم از داخل پنل شما اصلا حساب نمیشه حتی یه کیلوبایت، در حالی که روی پنل xui اولم نگاه کردم روی دوکومودور که ساختم حجم داره حساب میشه... لطفاً این مشکلوحل کنید که حجم اینجور کانفیگ ها حساب بشه

سرور ایران صنایی و خارج پنل مرزبان زدی منم همین کار کردم ولی روی ایرانسل کار نمیکنه چرا؟
