### ISSUE TITLE
مشکل کار نکردن دامنه روی کانفیگ ها

### ISSUE THREAD

**Issue by imaniy1994** [Gozargah/Marzban#346]
من برای دامنه سرتیفیکیت گرفتم و پروکسی رو روشن کردم و پنل رو با پورت 2096 بالا اوردم حالا مثالا میام تو قسمت HOST و برای TCP + Wmess و... دامنه رو به شکل زیر اضافه میکنم کانفیگ کار نمیکنه دیگه در صورتی که با ای پی کار میکنه.

https://s8.uupload.ir/files/screenshot_2023-06-16_232659_mccy.png

**Comment by SaintShit** [comment]
تنظیمات tls را روی inbound اعمال کردید؟

**Comment by iaghapour** [comment]
> تنظیمات tls را روی inbound اعمال کردید؟

امکانش وجود داره یه عکس بفرستید؟

**Comment by imaniy1994** [comment]
> تنظیمات tls را روی inbound اعمال کردید؟

امکانش هست یه عکس بفرستید؟

**Comment by M03ED** [comment]
ابتدا از xray config.json باید فعال کنید بعد از اینجا تغییر بدید

**Comment by ach1992** [comment]
> من برای دامنه سرتیفیکیت گرفتم و پروکسی رو روشن کردم و پنل رو با پورت 2096 بالا اوردم حالا مثالا میام تو قسمت HOST و برای TCP + Wmess و... دامنه رو به شکل زیر اضافه میکنم کانفیگ کار نمیکنه دیگه در صورتی که با ای پی کار میکنه.
> 
> https://s8.uupload.ir/files/screenshot_2023-06-16_232659_mccy.png

اگر از کلودفلر استفاده میکنید نباید ابر روشن باشه
دامنه ای هم که استفاده می کنید دقیقا باید همونی باشه که ssl گرفتید براش
