### ISSUE TITLE
Expiration Date Sorting

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#348]
سلام به مرزبان عزیز
امیدوارم حالت خوب باشه.

میگم توی پنل مرزبان یه آپشنی هست که میزنی روی Data Usage به ترتیب از کم مصرف تا پرمصرف رو نشون میده و یکبار دیگه بزنی روش برعکس میشه و از پرمصرف تا کم مصرف رو نشون میده.

میشه این آپشن رو به Status هم اضافه کنین که وقتی میزنیم روش نشون بده کی تاریخش نزدیک تره که تموم بشه؟

مرسی از همه زحماتتون 
عشقین

**Comment by MR-MKZ** [comment]
Done✅#1104

**Comment by iamtheted** [comment]
Thank you for the PR mate @MR-MKZ 
Can't believe we finally have this feature 😍
I'll close the issue then. ✅
