### ISSUE TITLE
custom v2ray profile

### ISSUE THREAD

**Issue by sharif221** [Gozargah/Marzban#35]
as I see there are only 4 default layouts that we can only check or uncheck from create user menu.
if we want to take it easy
You should add some variables to the env file to set the custom v2ray profile for example (vmess+tcp+http).
The problem may be is a single-port tcp connection.
however, I don't know much about connections and how we can separate two tcp inbounds

I think this is one of the lightest UI panels I have seen and there are a lot of places for improvements

I am at the beginning of the programming path and trying to learn and participate in this project.

**Comment by SaintShit** [comment]
Hi, The feature to select an inbound particularly is gonna be possible in the next version (4e4f75d396f3b219a107ff97f8bf7a36559b04c8). so that you can make two inbounds for vmess, for instance, (vmess+tcp+http) and (vmess+ws), and then select which one should be enabled for the user.
