### ISSUE TITLE
cannot create /etc/apt/sources.list.d/docker.list: Directory nonexistent

### ISSUE THREAD

**Issue by Navidmirzaei** [Gozargah/Marzban#351]
i have a problem with install on ubuntu 22

+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c install -m 0755 -d /etc/apt/keyrings
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu kinetic stable" > /etc/apt/sources.list.d/docker.list
sh: 1: cannot create /etc/apt/sources.list.d/docker.list: Directory nonexistent

**Comment by SaintShit** [comment]
`sudo mkdir /etc/apt/sources.list.d/`
