### ISSUE TITLE
Error api connect 500 internal server E 

### ISSUE THREAD

**Issue by ebikaargar** [Gozargah/Marzban#353]
ممنون از سرویس بی نظیرتون
![IMG_20230621_204710_080](https://github.com/Gozargah/Marzban/assets/125675747/1e78bc7c-9642-4766-ac8f-9ab97be0499f)

موقع اتصال به Api بخش یوزر ها با ارور
500 internal server E
مواجه میشم مشکل از چی میتونه باشه

**Comment by SaintShit** [comment]
سلام لطفا پخش های پایین تر ارور رو بفرستید

**Comment by ebikaargar** [comment]
> سلام لطفا پخش های پایین تر ارور رو بفرستید

سلام متشکر از شما اما مشکل حل شدش ( یه تعداد یوزر و با اسکریپت فرستاده بودیم سمت مرزبان به دلیل همخوانی نداشتن تاریخ بعضی از یوزر ها این مشکل پیش اومده بود )
