### ISSUE TITLE
MySQL Feature

### ISSUE THREAD

**Issue by RuofengX** [Gozargah/Marzban#358]
Using MySQL or other RDB rather than SQLite is more flexable in some scenery(like serverless).

I'm trying to use `SQLALCHEMY_DATABASE_URL` to set a mysql connector, however it returns in exception at startup(when creating table `nodes`) that mysql DO NOT support collation NOCASE(it seems like its a sqlite collation). I am trying to create table manually but it didn't work.

**Comment by RuofengX** [comment]
The SQL sentence which cause the exception(line 3):
```SQL
CREATE TABLE nodes (
        id INTEGER NOT NULL AUTO_INCREMENT, 
        name VARCHAR(256) COLLATE NOCASE, 
        address VARCHAR(256) NOT NULL, 
        port INTEGER NOT NULL, 
        api_port INTEGER NOT NULL, 
        certificate VARCHAR(2048) NOT NULL, 
        status ENUM('connected','connecting','error','disabled') NOT NULL, 
        last_status_change DATETIME, 
        message VARCHAR(1024), 
        created_at DATETIME, 
        uplink BIGINT, 
        downlink BIGINT, 
        PRIMARY KEY (id), 
        UNIQUE (name)
)
```

**Comment by SaintShit** [comment]
Hi, have you tried branch `dev`? it's already fixed on this branch, please try it and let me know if it's working or not

**Comment by SaintShit** [comment]
https://gozargah.github.io/marzban/examples/mysql

**Comment by alisystemit** [comment]
@SaintShit خیلی عالی 😊
