### ISSUE TITLE
Show Xray Version of Master Panel

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#375]
Hello Marzban 💙
I hope you're all doing great!

We can see the Xray version of nodes but not the master panel though, I was wondering if we could have that as well.
Maybe it could be down there beside Marzban version or wherever you think is right.

I appreciate your time
Thanks a lot!

**Comment by M03ED** [comment]
Are you sure about that ?
![IMG_20230709_212815.jpg](https://github.com/Gozargah/Marzban/assets/50927468/9a1f70bf-e03f-4992-95ea-697da11ba875)

**Comment by iamtheted** [comment]
Ohhh My bad! I didn't see that!
