### ISSUE TITLE
Tunnel

### ISSUE THREAD

**Issue by ezreza** [Gozargah/Marzban#380]
وقت بخیر
برای تانل از 
FakeTlsTunnel
 استفاده میکنم اما در مرزبان هر کاری میکنم انجام نمیشه
مشکل از کجا میتونه باشه؟ و اینکه راه دیگه ای هم وجود داره که توی پنل مرزبان انجام بدیم؟

**Comment by ramtiny** [comment]
برای منم دستورات تانل‌save نمیشه با یه ریبوت میپره
