### ISSUE TITLE
نشان ندادن ورژن پنل و کندی سرعت بعد از آپدیت جدید در نسخه dev دستی

### ISSUE THREAD

**Issue by Tili1420** [Gozargah/Marzban#381]
**Describe the bug**
هنگامی که مرزبان رو در روش دستی آپدیت میکنم ورژن همان ورژن قبلی و تغییری نمیکنه و سرعت پنل هم تغییری نمیکند. علت چیست؟ 

**To Reproduce**
1. Go to 'cd Marzban and run:  git pull
alembic upgrade head
pip install -r requirements.txt      and restart but don't change number of new version 
2' and restart
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

![20230711-11-16-40-AM](https://github.com/Gozargah/Marzban/assets/122120996/153f7202-df12-4ffa-b9d5-2227db5eecc9)

**Screenshots**
no change version:
![20230711-12-01-38-AM](https://github.com/Gozargah/Marzban/assets/122120996/874cf8dd-47cc-428b-85b6-8eac4b5bebef)
log xray:
![20230711-11-22-55-AM](https://github.com/Gozargah/Marzban/assets/122120996/4131ca59-3d70-4eee-9ab0-df97036c11f5)

**Machine details (please complete the following information):**
 - OS: [e.g. ubuntu 22]
- Python version: [e.g 3.8]
- Nodejs version: [e.g 16.17]
- Browser [e.g. chrome, safari, brave]

**Additional context**

**Comment by Tili1420** [comment]
مشکلم حل شد با تشکر از تیم مرزبان که هیچ راهنمایی نکردین

**Comment by iERROR-XD** [comment]
@Tili1420 =/

**Comment by SaintShit** [comment]
خواهش میکنم 🌹

**Comment by SaintShit** [comment]
> مشکلم حل شد با تشکر از تیم مرزبان که هیچ راهنمایی نکردین


خواهش میکنم rose

**Comment by iamtheted** [comment]
> مشکلم حل شد با تشکر از تیم مرزبان که هیچ راهنمایی نکردین

مگه مرزبان بدهکاره به ما آخه؟ بنده خدا پنل در اختیار ما گذاشته تا جایی هم که میتونسته کمک کرده حالا نمیتونه که صبح به صبح تک تک این پیاما رو چک کنه اینطوری که باید کار و زندگی و رها کنه. لطفا یکم لحن لطیف تری رو موقع صحبت کردن داشته باشین.

**Comment by Tili1420** [comment]
من چاکر شماها و تیم قدرتمند مرزبان هستم . اگه اونا نبودن ما به این مرتبه نمیرسیدیم. مرسی از همه زحمات بی دریغتون. شما مارو ترغیب کردید که مشکلات رو به کمک شما و هم در مواقع اضطراری حل کنیم البته دوباره بگم به لطف تیم مرزبان عزیز.
به هر حال من عذر میخوام بابت لحن تند... امیدوارم که هر روز بیشتر در راستای ارتقای اهداف و کارایی پنل و تکنولوژی پیش برید و عبور از فیلترینگ ساده تر و ساده تر بشه
باتشکر
