### ISSUE TITLE
افت ناگهانی سرعت

### ISSUE THREAD

**Issue by MajorTommy2023** [Gozargah/Marzban#382]
سلام . از مرزبان روی سرورم استفاده میکردم . سرعت اینترنت خود سرور به 2000 mb میرسه هر بار که تست میکنم . تا چند روز همه چیز خوب بود تا اینکه خیلی ناگهانی سرعت بسیار افت کرد . پینگ به مرزبان در v2ray به 3000 رسیده ( قبلا 300 بوده ) سرعت به شدت افت کرده به صورتی خیلی از کاربرا حتی نمیتونن متصل شن

کسی میتونه راهنمایی کنه مشکل میتونه از چی باشه و باید چیکار کرد ؟

**Comment by whereisafshin** [comment]
@MajorTommy2023 وقتی با اموزشای ایمان میای مرزبان بالا میاری و هیچی بلد نیستی از تکنیکای فیلترینگ 😔

**Comment by iamtheted** [comment]
سلام عزیزم
این باگ مرزبان نیست که Label باگ زدی ، افت سرعت مال ایپی ، SNI و خیلی فاکتورهای دیگس. وقتی آیپی کثیف باشه پنل هیچ کمکی نمیتونه بکنه.

**Comment by MajorTommy2023** [comment]
> سلام عزیزم این باگ مرزبان نیست که Label باگ زدی ، افت سرعت مال ایپی ، SNI و خیلی فاکتورهای دیگس. وقتی آیپی کثیف باشه پنل هیچ کمکی نمیتونه بکنه.

خیلی ممنون بابت راهنمایی . آی پی سرور موردی نداره به صورت کلی ، نه پکت لاس وجود داره نه پینگ بالا رفته و نه فیلترشده آی پی . کانفیگ های کلی سرور هم دست کاری نشدن اما یک شبه سرعت افت کرد . اگر امکان داره چند تا دیگه از فاکتور ها نام ببرید تا درموردشون بیشتر تحقیق کنم و داخل سرور هم بررسیشون کنم . ممنون

**Comment by MajorTommy2023** [comment]
> @MajorTommy2023 وقتی با اموزشای ایمان میای مرزبان بالا میاری و هیچی بلد نیستی از تکنیکای فیلترینگ 😔

 سلام دوست من ، مرزبان یه پروژه متن باز برای استفاده عمومی هست . اگر از این موضوع ناراحت هستید شاید بهتر باشه با توسعه دهندگانش درمیون بزارید .
