### ISSUE TITLE
Bug beta version

### ISSUE THREAD

**Issue by pvbooy** [Gozargah/Marzban#390]
Hello, in the beta version, when we click on the revoke subscription option, it gives a new link, but the previous link is not invalidated.  Please follow up on this matter.

**Comment by SaintShit** [comment]
I just today pushed fix on it and it's not yet fixed, be patient this is development branch not beta.

**Comment by pvbooy** [comment]
When will GitHub be placed?  There is no news yet

**Comment by pvbooy** [comment]
> I just today pushed a fix on it and it's not yet fixed, be patient this is development branch not beta.

When will this bug be fixed and placed on GitHub?  We are waiting for you :(
