### ISSUE TITLE
مدیریت چند کاربره ربات

### ISSUE THREAD

**Issue by ItsAML** [Gozargah/Marzban#393]
سلام خسته نباشید
برای مدیریت بهتر پنل از طریق ربات بنظرم بهتر میبود اگه میشد یه لیست از ایدی عددی هایی که میتونن ادمین ربات باشن میتونستیم قرار بدیم بتونن پنل رو مدیریت کنن

بطور مثال

TELEGRAM_USER_ID = ["ایدی عددی اول", "ایدی عددی دوم"]

درحال حاضر فقط یک ایدی عددی از طریق ربات میتونه مدیریت بشه اگه این امکان اضافه بشه خیلی بهتر میشه

**Comment by govfvck** [comment]
سلام
برناممون اینه که هر ادمین از طریق یوزر خودش در پنل بتونه با ربات کار کنه. سعی میکنیم بزودی این قابلیت رو اضافه کنیم.
