### ISSUE TITLE
نحوه نصب

### ISSUE THREAD

**Issue by shuvvan** [Gozargah/Marzban#40]
سلام و عرض ادب

بنده میخوام این پروژه رو نصب کنم ولی متاسفانه نمی تونم و نمی دونم از کجا باید شروع کرد ! لطفا یه آموزش جامع نصب برروی اوبونتو قرار بدید!
اگر فیلم باشه خیلی بهتره
چون اصلا از توضیحات شما سر در نیاوردم

**Comment by SaintShit** [comment]
[نصب به کمک Docker](https://github.com/Gozargah/Marzban/blob/master/README-fa.md#%D9%86%D8%B5%D8%A8-%D8%A8%D9%87-%DA%A9%D9%85%DA%A9-docker)

مستندات فارسی وجود داره مطالعه کنید. اگر کسی ویدیو بسازه ممنون میشیم خودمون پلنی برای اینکار نداریم.

**Comment by shuvvan** [comment]
والا اینم امتحان کردم نتونستم دوباره نصب میکنم ببینم چی میشه
