### ISSUE TITLE
Change data type

### ISSUE THREAD

**Issue by AC-Lover** [Gozargah/Marzban#406]
Hello
Please change the type of `data_limit` and expire_duration in `user_templates` table to **BIGINT** in MySQL, because it gives `Out of range value for column 'data_limit'` error

**Comment by govfvck** [comment]
hi.
this part of the code needs a full refactoring. I should have put it in the `user.py` and not a new file. I'll try to fix these and also this bug.

**Comment by M03ED** [comment]
Done in #615
