### ISSUE TITLE
Add SSH protocol

### ISSUE THREAD

**Issue by darklies** [Gozargah/Marzban#407]
لطفا پروتکل SSH هم به پنل اضافه کنید دیگه همه چیز تمام شه

**Comment by iamtheted** [comment]
سلام عزیز
استفاده از کانکشن SSH به عنوان VPN بسیار ناامنه راحت فیلتر میشه ، هرگز به مرزبان اضافه نخواهد شد /:

**Comment by darklies** [comment]
کی همچین حرفی زده ؟؟؟ 
جو چیه دوستان راه انداختین!

**Comment by iamtheted** [comment]
عزیز شما چند وقته ایران زندگی می‌کنید؟

**Comment by M03ED** [comment]
دوستان همینجا issue رو ببندید تموم بشه بره بنظرم بهتره.

**Comment by M03ED** [comment]
این مورد در برنامه تیم مرزبان نیست و در صورتی که نیاز دارید میتونید از پروژه های دیگه استفاده کنید
