### ISSUE TITLE
اتصال به تانل

### ISSUE THREAD

**Issue by ashkantoorani** [Gozargah/Marzban#41]
سلام این اسکریپت رو چطور میشه به تانل متصل کرد، آیا این اسکریپت با خودش xray-core رو نصب میکنه، اکر نصب میکنه چرا پوشه ها usr/local در قسمت داکیومنت خالیه
من فولدارها رو گشتم و چیزی پیدا نکردم
برای api به کجا و کدوم فولدر باید مراجعه کنم

**Comment by SaintShit** [comment]
سلام بله اجرا میکنه
برای فعال سازی API توی تنظیمات env متغیر
```bash
DOCS = True
```
کنید و به مسیر `/docs` توی مرورگرتون برین
در نسخه داکر xray-core دانلود میشه درون کانتینر
