### ISSUE TITLE
Set "Expiry Date" by days

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#413]
سلام
لطفا قابلیت این رو بزارید که جای وارد کردن date بیایم تعداد روز وارد کنیم برای اعتبار زمانی کاربر
این کاربردی تر هست تا اینکه بیایم از تو تقویم یه روزو انتخاب کنیم
با تشکر

**Comment by erfjab** [comment]
@SaintShit Done (om_hold) ✅
