### ISSUE TITLE
setting user agent by query string

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#421]

**Comment by SaintShit** [comment]
@mozilla-firefox سلام
مرزبان از نسخه v0.3.0 به بعد از clash meta پشتیبانی میکنه.

**Comment by SaintShit** [comment]
برای کلاینت دسکتاپ برنامه clash verge و کلاینت اندروید ClashMetaForAndroid پشتیبانی میشه.

**Comment by SaintShit** [comment]
@mozilla-firefox از Clash Verge که استفاده کنید و کور رو روی clash meta بزارید، کار میکنه

**Comment by oXIIIo** [comment]
@mozilla-firefox 
برای تمپلیت نمونه هم اگر دوست داشتی میتونی از [تمپلیت کلش متا ](https://github.com/oXIIIo/clash-meta-template)من که برای مرزبان نوشتم استفاده کنی.

**Comment by SaintShit** [comment]
> نظرتون چیه یه سری لینک باشه که فقط یه نوع خاصی از کانفیگ رو نشون بده بدون در نظر گرفتن یوزر اجنت؟ مثلا آخر لینک یه
> 
> `?force=clashmeta`
> 
> اضافه شه و وقتی این لینک حتی تو مرورگر باز شد بازم کانفیگ کلش متا رو نشون بده؟ @SaintShit

ایده خوبیه میشه اضافه کرد.
