### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by jamolsoltan** [Gozargah/Marzban#424]
یه امکان بتونین به api (خود مرزبان منظورمه) اضافه کنین که لیست پروتکل + زیر شاخاشو که توی Core Settings ست شده رو خروجی بده ، خروجی شامل اسم پروتکل(vmess,vless,trojan و... )، ترنزیشن(نوع انتقال ws,tcp,grpc و...) و امنیت شبکه رو خروجی بده ، این امکان خیلی به سمت توسعه دهنده های api مرزبان کمک میکنه امیداورم هرچه زودتر اضافه بشه

**Comment by oXIIIo** [comment]
سلام میتونید با

/api/core/config
کانفیگ json رو بگیرین و دیتایی که میخایین رو جدا کنید.
