### ISSUE TITLE
مجزا کردن ترافیک مصرفی،تنظیمات هاست و ...ادمین از پنل اصلی

### ISSUE THREAD

**Issue by ItsElw** [Gozargah/Marzban#428]
سلام وقت بخیر،اگه امکانش هست تو اپدیت بعدی ترافیک مصرفی کل پنل و ترافیک نود ها و یوزر های ادمین غیر سودو داخل پنل اصلی نمایش داده نشه و مجزا باشن،و اینکه بتونیم برای ادمین تنظیمات هاست متفاوتی تایین کنیم،ممنون

**Comment by l3lack-eyes** [comment]
@ItsElw چشم
