### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by M03ED** [Gozargah/Marzban#43]
سلام
من با پایتون تا حالا کار نکردم و نمیدونم این ارور موقع راه اندازی برای چیه 
لطفا اگه میشه راهنمایی کنید تا پنل رو راه اندازی کنم 
همه کتابخونه های لازم که تو فایل [requirements.txt] هستن رو نصب کردم 

![image](https://user-images.githubusercontent.com/50927468/221004917-9e4a05a0-5727-4152-9b8c-518afc5d4ab3.png)

و در اخر برای پیشنهاد اگر میشه اسکریپت رو ارتقا بدید که اتوماتیک فرایند نصب اتوماتیک رو انجام بده.

**Comment by SaintShit** [comment]
سلام، اگر توسعه دهنده نیستنید، نیازی به نصب به صورت دستی نیست. از داکر استفاده کنید.

[نصب به کمک Docker](https://github.com/Gozargah/Marzban/blob/master/README-fa.md#%D9%86%D8%B5%D8%A8-%D8%A8%D9%87-%DA%A9%D9%85%DA%A9-docker)

یکی از [کانفیگ](https://github.com/Gozargah/Marzban-examples) ها رو با توجه به نیازتون انتخاب کنید و دستورعملش رو مطالعه کنید. کمتر از ۵ دقیقه طول میکشه راه اندازی.

**Comment by M03ED** [comment]
ممنون از راهنمایی 
بنده مولتی پورت رو راه اندازی کردم و میخواستم بدونم پنل از xtls و grpc هم پشتیبانی داره یا نه ؟ 
و اینکه با کپی کردن و تغییر جزییات این قسمت از فایل xray_config.json میشه تعداد پروتکل ها رو بیشتر کرد ؟
![image](https://user-images.githubusercontent.com/50927468/221038740-2ff8c690-8121-433c-867c-b8bf34949b76.png)

**Comment by SaintShit** [comment]
@M03ED 
> ممنون از راهنمایی بنده مولتی پورت رو راه اندازی کردم و میخواستم بدونم پنل از xtls و grpc هم پشتیبانی داره یا نه ؟

سلام، grpc بله، xtls، خیر. کد هاش پیاده سازی شده اما نمیتونید برای هر کاربر مختص فعال کنید. اگر فعال هم بشه فقط vision فعال میشه، با توجه به داک های خود xray که بقیه دیگه کاربردی ندارند.

> و اینکه با کپی کردن و تغییر جزییات این قسمت از فایل xray_config.json میشه تعداد پروتکل ها رو بیشتر کرد ؟

بله هرچی اضافه و کم کنید مرزبان میتونه کاربر هاش رو مدیریت کنه.
