### ISSUE TITLE
Include Node statistics and system configurations in `/api/system`

### ISSUE THREAD

**Issue by govfvck** [Gozargah/Marzban#431]
As of newer versions of `Marzban` and the `MarzbanNode` feature, there is a need for Node server's statistics in the api. like number of cores, how much ram is used and etc.

I think it would be nice to add a `"nodes"` entry to the `/api/system` endpoint's response, this way i think it also wouldn't break backward compatibility.

```json
{
  "version": "string",
  "mem_total": 0,
  "mem_used": 0,
  "cpu_cores": 0,
  "cpu_usage": 0,
  "total_user": 0,
  "users_active": 0,
  "incoming_bandwidth": 0,
  "outgoing_bandwidth": 0,
  "incoming_bandwidth_speed": 0,
  "outgoing_bandwidth_speed": 0,
  "nodes": [
    {
      "id": 0,
      "node_version": "string",
      "mem_total": 0,
      "mem_used": 0,
      # and etc...
    }
  ]
}
```

Any thoughts on this? other solutions are welcomed.

**Comment by M03ED** [comment]
#789
