### ISSUE TITLE
Date Count

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#439]
Hello Marzban 💙

When I set 30 days for a users, It's 29 days in panel which means It counts the days from tomorrow not the day It's created at, Is this normal or It has to be 30 days?

**Comment by Newliex** [comment]
@iamtheted سوال منم هست

**Comment by govfvck** [comment]
Hi.
I think this is normal.
when you set it to 30 days, it actually counts it from 29 days and 24 hours. so it will be shorted out to 29.
