### ISSUE TITLE
Allow insecure 

### ISSUE THREAD

**Issue by alirezajj00** [Gozargah/Marzban#441]
سلام و خسته نباشید به بچه های مرزبان
اگر مقدور هست گزینه Allow insecure به هاست ستینگ اضافه کنید
تا لینک سابسکریپشن بتونه اون رو بخونه و روی گوشی های ایفون اعمال کنه
خیلی ممنون بابت زحمات شما❤️

**Comment by M03ED** [comment]
Added in pr #536
