### ISSUE TITLE
Marzban Offical Automatic Backup

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#443]
Hello Marzban 💙

As you know, backup is quite importand and I myself have been screwed because of it multiple times, lol. So, I think Marzban needs an official automatic backup in telegram bot but preferably in a second telegram bot aside from the management bot. 

I have seen 2 scripts for automatic backup but everybody must be aware of them so it would be helpful either to merge one of them to Marzban or creating a new one.

I understand things are easily said than done, adding all these features take a lot of time and effort so I want to take a moment and appreciate you all for all you've done for us. You're truly exceptional, don't you forget that.

With Sheer Love,
TED

**Comment by sons-of-liberty** [comment]
@iamtheted تد نمودی بسه

**Comment by iamtheted** [comment]
تموم شد سید همه رو ذکر کردم ، بوس.

**Comment by govfvck** [comment]
Hi. 
Acutally that's a very good idea to add automatic backup. I think It would be nice to add it into the [marzban.sh](https://github.com/Gozargah/Marzban-scripts/blob/master/marzban.sh) script.

I'll keep this in my mind and will try my best to come up with something for it.
