### ISSUE TITLE
Feature Request: API Route for Node System Stats

### ISSUE THREAD

**Issue by mromidi** [Gozargah/Marzban#444]
Firstly, I would like to extend my heartfelt gratitude for the effort and dedication put into maintaining and improving this repository. I'd love to see an API route that provides system stats (RAM, CPU, etc.) for each connected node to the master server. This feature would greatly improve monitoring and resource management. Thank you for considering it!

**Comment by Albatrossman** [comment]
I wanted to suggest a valuable enhancement to the existing API. Currently, when we retrieve the users list using _**api/users**_, we receive an array of configuration links without any clear association with their respective nodes.
I believe it would be immensely helpful if the API could also provide data in the following format:

```json
{
  "users": [
    {
      "proxies": {},
      "expire": 0,
      "data_limit": 0,
      "data_limit_reset_strategy": "no_reset",
      "inbounds": {},
      "username": "string",
      "status": "active",
      "used_traffic": 0,
      "lifetime_used_traffic": 0,
      "created_at": "2023-08-05T00:36:24.950Z",
      "links": [
          {
              "node": {
                  "name": "string",
                  "address": "string",
                  "port": 62050,
                  "api_port": 62051,
                  "certificate": "string",
                  "id": 0,
                  "xray_version": "string",
                  "status": "connected",
                  "message": "string"
           },
              "link": "configuration_url"
          }
      ],
      "subscription_url": "",
      "excluded_inbounds": {}
    }
  ],
  "total": 0
}
```

This would allow users to easily map each configuration url to its corresponding node, simplifying node management and configuration tracking.

**Comment by govfvck** [comment]
Hi  @mromidi 
There is already an open issue (#431) for this! please check the issues before opening a new one. please close this issue and comment your suggestions there.

**Comment by govfvck** [comment]
Hi @Albatrossman 
I don't think your comment is related to this issue, please take your suggestions to the appropriate issue or open a new one.
Thanks.
