### ISSUE TITLE
عدم مدیریت و حذف یوزر های منتقل شده از دیتابیس قدیمی

### ISSUE THREAD

**Issue by ashkanmafi2** [Gozargah/Marzban#445]
با درود و احترام خدمت تمامی دولوپر ها و سازندگان پروژه مرزبان ...
اول از همه مراتب تشکر و قدرددانی خود را خدمت شما سازندگان محترم اعلام می دارم .

ایرادی که با آن برخورد داشته ام و باعث مشکلات بسیار برای من شده است  :
 من از sqlite به mysql تغییر دیتابیس دادم و الان 
 
۱- نمیتونم یوزرهای قدیمی رو حذف کنم (یوزرهایی که از sqlite به mysql منتقل شدن
۲-  و همینطور مدیریت کاربری اشتراکشون رو انجام بدم ... ( کم و زیاد کردن اینباند های اختصاص یافته به کاربر یا حذف و ریست توکن اشتراک آنها )

این مسئله رو چطور میتونم حل کنم ؟

ممنون و سپاسگزارم

**Comment by govfvck** [comment]
سلام و درود
وقتی میخواید کارهایی که گفتید رو انجام بدید با ارور خاصی مواجه میشید؟ امکانش هست ارور ها رو قرار بدید
همیچنین سعی کنید لاگ‌های مرزبان رو درون یک سرویس pastebin قرار بدید و لینکش رو اینجا بزارید
و اینکه نوع سیستم عامل + ورژن + کدوم نسخه و کدوم ورژن مرزبان؟

**Comment by ashkanmafi2** [comment]
درود بر شما 
سپاس از پیگیری شما و همکاران ... 
ارور بنده این است که به هیچ وجه امکان تغییر منابع اختصاص داده شده به یوزر رو ندارم 
حتی امکان disable کردنش هم ندارم 
یعنی اگر بخوام یک هاست رو از لیست سابسکرایب کاربر کم یا اضافه کنم تایید نمیشه و ادیت آن بخش انجام نمیشه 
سیستم عامل اولونتو 22.04LTS  هست و اخرین ورژن مرزبان هم استفاده میکنم 
دیتابیس رو دقیقا مثل اموزش قرارداده شده در گیت هاب پروژه منتقل کردم ... ( با حدود 90 کاربر )
یک فیلم از مشکلی که دارم هم برای شما الان Attach میکنم که کامل در جریان قرار بگیرید 
سپاس فراوان از شما 
https://cdnshopturk.top/errormarzban.mp4

**Comment by govfvck** [comment]
سلام
لطف کنید لاگ‌های مرزبان رو هم قرار بدید.

**Comment by ashkanmafi2** [comment]
درود بر شما 
بنا بر دلایل امنیتی فایل لاگ پنل را از طریق تلگرام برای شخص شما ارسال کردم 

سپاس از شما

**Comment by govfvck** [comment]
درود
بعد از بررسی بیشتر متوجه شدم که مشکل از دوپلیکیت شدن تمام rowهای ‍‍`exclude_inbounds_association` در دیتابیس هست.
هنوز کاملا به نتیجه‌ای نرسیدم که چی باعث شده همچین اتفاقی بیوفته. @SaintShit نظر شما چیه؟

**Comment by govfvck** [comment]
راه حلی که برای حل مشکل انجام دادم رو اینجا شرح میدم. دقت کنید که عواقب احتمالی انجام این کار به عهده خودتون هست! حتما قبل از انجام هر کاری به صورت کامل از دیتابیستون بکاپ بگیرید.

مشکل از دوپلیکیت شدن تمام rowهای تیبل `exclude_inbounds_association`  بود. اگر میخواید چک کنید که این مشکل برای شما هم وجود داره میتونید از این کوئری استفاده کنید:

‍```sql
SELECT 
    inbound_tag, COUNT(inbound_tag),
    proxy_id, COUNT(proxy_id)
FROM
    exclude_inbounds_association
GROUP BY inbound_tag, proxy_id
HAVING (COUNT(inbound_tag) > 1) AND
(COUNT(proxy_id) > 1);
```

برای دیلیت کردن دوپلیکیت‌ها میتونید از هکی که من انجام دادم استفاده کنید:

ابتدا از تیبل `exclude_inbounds_association` یک کپی به صورت distinct میگیریم تا فقط دیتای غیرتکراری رو جدا کنیم. 

```sql
CREATE TABLE copy_exclude_inbounds_association SELECT DISTINCT proxy_id, inbound_tag FROM exclude_inbounds_association;
```

بعد از اون میایم تیبل اصلی رو دراپ میکنیم:

```sql
DROP TABLE exclude_inbounds_association;
```

و دوباره کار مرحله قبل تر رو انجام میدیم تا دیتا رو کپی کنیم توی تیبل قبلی:

```sql
CREATE TABLE exclude_inbounds_association SELECT DISTINCT proxy_id, inbound_tag FROM copy_exclude_inbounds_association;
```

حالا میتونید تیبل کپی رو حذف کنید. و اینکه نتیجه رو اینجا بگید شاید به این کمک کنه که مشکل اصلی رو پیدا کنیم.

**Comment by ashkanmafi2** [comment]
درود بر شما سپاس فراوان از وقتی که گزاشتید و مشکل را تا رفع آن پیگیری نمودید

**Comment by Tili1420** [comment]
با درود و سپاس فراوان از اساتید محترم
منم دقیقا همین مشکل رو دارم. این کوئری و اون دستورات رو باید کجا انجام بدم. میتونید بیشتر راهنمایی کنید لطفا؟

**Comment by Tili1420** [comment]
مرسی از راهنمایی هاتون و پیگیری مشکلات دوستان. مشکل من با کلی تحقیق و بررسی و آموزش و افزایش جزئی از علم حل شد😍
خیلی متشکر🙏🏻🌺
