### ISSUE TITLE
Tag System

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#446]
سلام
در حال حاضر برای هر یوزر میشه انتخاب کرد که به کدوم هاست ها دسترسی داشته باشه
اگر برای هر هاست بتونیم یه tag داشته باشیم خیلی بهتر میشه
مثلا من یه سری هاست دارم که ریلی ایران هستن، یه سری هم مستقیم خارج هستن
مستقیم ها رو بهشون تگ دیفالت میدم تا برای همه فعال باشن بصورت پیشفرض
برای ریلی ها تگ مجزا میزارم و وقتی کاربری اد میکنم که میخوام ریلی ها تو سابسکریپشن شون باشه تگ ریلی رو اضافه میکنم برای یوزر و تمام
این خیلی سریعتر و راحت تره تا انتخاب تکی هاست هایی که کاربر میتونه دسترسی داشته باشه یا نداشته باشه برای هر یوزر

اگر غیر از هاست، یه تعداد تگ دیگه هم باشه که به هر یوزر بشه داد هم خوب میشه، مثلا تگ کاربرایی که فامیل نزدیک هستن! یا نسیه خریداری کردن یا هرچی، بعدا بشه از این طریق همشونو فیلتر کرد تو پنل برای مانیتور کردن شون، یا بشه به همه اعضای یک تگ حجم یا زمان اضافی اد کرد یا همشو غیرفعال کرد

با تشکر

**Comment by Newliex** [comment]
بسه دیگه دلقک
