### ISSUE TITLE
🍆 OxJ4ck Kose nanat Akhe khayemal be to che madarjende

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#447]

**Comment by OxJ4ck** [comment]
سلام
تا جاییکه من دیدم تو کد ها access برای بخش های مختلفی استفاده میشه مثلا برای چک کردن ادمین و ...
پس حذف کردنش جالب نیست و در کل کوتاه شدن لینک سابسکریپشن هم تفاوت چندانی هم ایجاد نمیکنه چون در نهایت کاربر یک لینک رو کپی می‌کنه، حالا لینک کوتاه باشه یا طولانی برای کاربر مهم نیست

**Comment by OxJ4ck** [comment]
> برای تلگرام با محدودیت کلمات تاثیر داره، وسط متن میتونی راحت لینکو مستقیم بزاری جای Hyperlink کردن لینک به متن

برای من تفاوتی نداره چون برای راحتی کاربر در پیام جداگانه به صورت mono ارسال میکنم.

> توی خوانا بودن و بی اشتباه اسکن شدن qrcode که تعداد کل کلماتش محدود هست و هرچه تعداد کاراکتر بالاتر باشه درصد خطاش بیشتر میشه تاثیر داره

طبق چیزی ک سایت https://en.wikipedia.org/wiki/QR_code گفته qr code محدودیت 4,296 کاراکتری داره.




> الان حتی یه یوزر ساده هم با سرچ "/sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9" توی تلگرام و گوگل هرچی لینک ساب مرزبان هست میتونه استخراج کنه

لینک هایی هستن که کاربرها خودشون تو گروه های مشترکتون به اشتراک گذاشتن.

**Comment by OxJ4ck** [comment]
شما نظر شخص من رو پرسیدین من هم نظر خودمو دادم.
من توسعه دهنده مرزبان نیستم و ایشون تصمیم گیرنده هستن، من فقط میتونم نظر خودمو بگم.
