### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by vesnindev** [Gozargah/Marzban#449]
Hello. I install Marzban with docker and my installation stopped and not contine.How I can install this and what i do wrong?

`marzban-marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade  -> 94a5cc12c0d6, init user table
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 94a5cc12c0d6 -> 3cf36a5fde73, init system table
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 3cf36a5fde73 -> 9d5a518ae432, init jwt table
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 9d5a518ae432 -> 9b60be6cd0a2, add created_at field to users table
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 9b60be6cd0a2 -> 8e849e06f131, proxy table
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 8e849e06f131 -> 671621870b02, init admin
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 671621870b02 -> e91236993f1a, inbounds table & excluded_inbounds
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e91236993f1a -> b3378dc6de01, hosts
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 671621870b02 -> d02dcfbf1517, add UserUsageResetLogs Model and data_limit_strategy field to user
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade d02dcfbf1517, b3378dc6de01 -> ece13c4c6f65, empty message
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade ece13c4c6f65 -> b15eba6e5867, add host and sni columns to hosts table
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade b15eba6e5867 -> 51e941ed9018, deactive user status
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 51e941ed9018 -> e3f0e888a563, rename deactive status to disabled
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e3f0e888a563 -> 7cbe9d91ac11, ProxyHost: security added
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 7cbe9d91ac11 -> 5b84d88804a1, fix
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 5b84d88804a1 -> a0d3d400ea75, Admin: is_sudo field
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 5b84d88804a1 -> fad8b1997c3a, case insensitive username
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade fad8b1997c3a, a0d3d400ea75 -> e410e5f15c3f, merge fad8b1997c3a & a0d3d400ea75
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e410e5f15c3f -> 97dd9311ab93, add user templates
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 97dd9311ab93 -> 37692c1c9715, nodes
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 37692c1c9715 -> e4a86bc8ec7b, node_user_usages
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e4a86bc8ec7b -> 57fda18cd9e6, add xray version
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 57fda18cd9e6 -> c106bb40c861, alpn_fingerprint_hosts
marzban-marzban-1  | INFO  [alembic.runtime.migration] Running upgrade c106bb40c861 -> fc01b1520e72, add node usages
`

**Comment by M03ED** [comment]
this is not error , its just building database
