### ISSUE TITLE
Option to use different certificates

### ISSUE THREAD

**Issue by Moh3nGolshani** [Gozargah/Marzban#45]
Hi
Thanks for your great job,
It would be great to be able to use different certificates for different proxies, so we can use different certificates for direct and tunneled proxies.

**Comment by SaintShit** [comment]
Hi, you're currently able to do by editing xray config file. You can set any certificate you want, even multiple certificates, for each inbound.
see [TLSSettings](https://github.com/Gozargah/Marzban-examples/blob/master/multi-port/xray_config.json#L21)
