### ISSUE TITLE
marzban update

### ISSUE THREAD

**Issue by jsmohssen** [Gozargah/Marzban#458]
سلام ممنون میشم در این مورد راهنمایی بفرمایید
برای آپدیت کردن پنل به نسخه ی بروز اگر این دستور رو وارد کنیم marzban update توی سرور آیا ارتباط قطع خواهد شد یا عملیات بروزرسانی پنل انجام خواهد شد؟

**Comment by jsmohssen** [comment]
> @jsmohssen شما وقتی دستور اپدیت رو بزنید
> نسخه های جدید جایگزین میشن
> و شما باید یکبار marzban restart بزنید تا تغییرات اعمال بشه
> و تایم کوتاهی میبره

همینکار رو‌ کردم پنل بالا میاد کانفیگ ها هم مشکلی ندارن اما وقتی دیگه تو سرور دستور marzban restart میزنم خطا میگیرم

root@m2: ~# marzban restart
/us/local/bin/marzban: line 2: syntax error near unexpected token 'newline /us/local/bin/marzban: line 2:
<?xmi version="1.0" encoding="utf-8"?>

**Comment by OxJ4ck** [comment]
@jsmohssen 
فک کنم فایل اجرایی اسکریپت به مشکل خورده یه بار دیگه نصبش کنید.
میتونی خروجی این دستور هم بفرستی؟
```sh
cat /us/local/bin/marzban
```
