### ISSUE TITLE
مشکل در استفاده از IPV6 در ریالیتی

### ISSUE THREAD

**Issue by aminsh77** [Gozargah/Marzban#460]
وقت بخیر
موقعی که از ریالیتی استفاده میکنم درون پنل قسمت تنظیم آدرس کانفینگ ها دامنه یا آیپی ورژن ۴ بزارم مشکلی ندارم ولی وقتی آیپی ورژن ۶ رو بدون دامنه و مستقیم میزارم و سیو میکنم دیگه اون کانفینگ برای کاربر نمایش داده نمیشه و از کانفینگ های subscription حذف میشه هیچ خطایی هم تو پنل نمیده و سیو هم میشه

**Comment by nasiriscript** [comment]
این باگ نیست آیپی 6 رو باید داخل [ ] بزاری

**Comment by aminsh77** [comment]
> این باگ نیست آیپی 6 رو باید داخل [ ] بزاری
درست شد ولی توی کانفینگای کلاینت یه 20% کنار ipv6 میاد اینجور مشه 
2001:db8:3333:4444:5555:6666:1%20

**Comment by aminsh77** [comment]
> این باگ نیست آیپی 6 رو باید داخل [ ] بزاری

درست شد ولی توی کانفینگای کلاینت یه 20% کنار ipv6 میاد اینجور مشه 
2001:db8:3333:4444:5555:6666:1%20
