### ISSUE TITLE
🍆 Ty Erfjab, Kiret to kose nane TED o M03ED

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#461]
سلام
در حال حاضر وقتی سرچ میکنیم، فقط یوزر رو میتونیم وارد کنیم
لطفا قابلیت این بزارید که توی note کاربرا هم بتونیم جست و جو کنیم
و اگر بشه لینک کاربرو وارد کنیم و کاربرو برامون پیدا کنه هم میتونه کاربردی باشه
با تشکر

**Comment by erfjab** [comment]
@MR-MKZ what do you think?

**Comment by MR-MKZ** [comment]
I'll check it.

**Comment by erfjab** [comment]
This added.
