### ISSUE TITLE
عدم همخوانی مصرف نود ها با مصرف داده های صفحه اصلی

### ISSUE THREAD

**Issue by ashkanmafi2** [Gozargah/Marzban#462]
با درود و احترام 
به مسله ای برخوردم که در محاسبه مصرف دیتای نود ها یا همان سرورهای متصل به پنل اخلال برایمان ایجاد کرده است . 

در node usage  مصرف داده از تمامی سرورها دوبرابر سکشن node usage در صفحه اصلی پنل می باشد .. 

با استناد به کدام پارامتر میتوانیم مصرف واقعی نود ها را محاسبه کنیم ؟ 
البته توضیحی که لازم است داده شود این است که : 
1- من در پنل از تانل استفاده میکنم و حداقل نیمی از اینباند ها با ساب دامین سرورهای ایران ساخته شده اند ... ( حدود 10 اینباند از 22 اینباند کلی)
2- به دلیل تعدد سرور های استفاده شده ایرانی ؛ ساب دامین سرور های ایران مسلما متفاوت است .... 
3- حدود 12 اینباند بنده بصورت مستقیم و بدون تانلینگ در حال فعالیت هستند ... 

عکس های زیر تفاوت مقدار مصرف نود و دیتا رو مشخص میکند .. 

https://cdnshopturk.top/nodeusage.jpg   
https://cdnshopturk.top/datausage.jpg   

سپاس از شما

**Comment by ach1992** [comment]
سلام این مورد رو من 
https://github.com/Gozargah/Marzban/issues/408
اینجا گزارش کردم ولی خب کسی بهش توجه نکرد.

**Comment by KAJOOSH** [comment]
من هم همین مشکل رو مشاهده کردم ! 
حتی مصرف محاسبه شده برای کاربران کمتر از مصرف سرور محاسبه می شود.

**Comment by M03ED** [comment]
تو آپدیت امروز نسخه dev این مشکل حل شده ، اگر آپدیت انجام بدید مشکل تو رفع میشه.
