### ISSUE TITLE
مشکل ارور column count doesn't match value count at row 1

### ISSUE THREAD

**Issue by Hamedyar1375** [Gozargah/Marzban#467]
سلام بعد از زدن دستور 
docker compose exec mysql mysql -u root -p -h 127.0.0.1 marzban -e "SET FOREIGN_KEY_CHECKS = 0; SET NAMES utf8mb4; SOURCE dump.sql;"

رمزمو ازم می خواد وقتی وارد می کنم 

column count doesn't match value count at row 1
لطف راهنمایی کنید.

**Comment by farhadan** [comment]
یکی راهنمایی کنه چطور باید این مورد رو رفع کنیم
1136 (21S01) at line 48 in file: 'dump.sql': Column count doesn't match value count at row 1
