### ISSUE TITLE
کمک کنید دوستان -- به همراه اول و مخابرات متصل نمیشه

### ISSUE THREAD

**Issue by mohammadtwok** [Gozargah/Marzban#470]
سلام
دوستان تقریبا 10 روزی میشه که هر کانفیگی که از طریق مرزبان میسازم دیگه به همراه اول و مخابرات متصل نمیشه یا اگر هم میشه سرعت خوبی اصلا نداره
لطفا اگر کسی راهی داره کمکم کنه .. ممنونم

**Comment by iamtheted** [comment]
لطفا این issue رو ببندین و این قضیه رو توی گروه مطرح کنین.
این باگ نیست و به پنل ربط نداره.
