### ISSUE TITLE
مصرف سی پی یو بالا و استفاده  حجم غیرطبیعی

### ISSUE THREAD

**Issue by narouie13** [Gozargah/Marzban#474]
سلام 
یه مشکلی یه هفتست برام اتفاق افتاده اینه که یهو مصرف سی پی یو سرور رفت بالا و دقیقا باهاش مصرف پهنای باندم رفت بالا. سه بار سرور عوض کردم. وارپ و مسدود سازی سایتای ایرانی پاک کردم حتی ربات بکاپ گیریم پاک کردم. هیچ اینباند اضافه ای اضافه نکرد دیفالت تنظیمات ریالتی خود مرزبان ولی بازم بعد چندساعت همین اتفاق میوفته. مصرف دیتاش تقریبا هر نیم ساعت حدود ۱۰ گیگه!

**Comment by iamtheted** [comment]
سلام 
امیدوارم که حالتون خوب باشه
دیتابیستون SQLite هست یا MySQL؟ اگر MySQL باشه مصرف بالای رم عادیه.
هرچند که ذکر نکردید رم تا چه مقدار پر شده بود. میزان رم و میزانی که درگیر هست رو هم لطفا بگین.
