### ISSUE TITLE
تغییر ترتیب نمایش کانفینگ ها (الویت بندی برای نمایش)

### ISSUE THREAD

**Issue by aminsh77** [Gozargah/Marzban#475]
وقت بخیر
موقعی که از لینک subscription استفاده میکنم کانفینگ ها رو به این ترتیب نشون میده اول vless بعد shadowsocks بعد vmess بعد Trojan سوالم اینه چجور میشه این ترتیب رو به صورت دستی تغییر داد مثلاً vmess اول نمایش داده بشه

**Comment by iamirh7** [comment]
منم این مشکل رو دارم

**Comment by bobyturk** [comment]
سلام . هنوز راهی برای مرتب کردن نمایش کانفیگ ها پیدا نشده ؟
