### ISSUE TITLE
مشکل در استفاده از xtls-rprx-vision در vless

### ISSUE THREAD

**Issue by aminsh77** [Gozargah/Marzban#478]
وقتی flow رو روی مقدار xtls-rprx-vision برای کانفینگ های vless میزارم موردی که داره کانفینگ های vless tcp http دیگه کارنمیدن و request host پاک میشه از کانفینگ و راهی هم نداره یا من پیدا نکردم
 میخواستم بدونم راهی هست که از core setting این مقدار رو فقط برای یکسری ازکانفینگ ها تایین کرد؟

**Comment by Ilaprgg2** [comment]
من هم همین مشکل رو دارم.

**Comment by thenorthatlantic** [comment]
توی گروه پرسیدم اما جوابی نگرفتم.
از ادمین ها پرسیدم این باگ هنوز هست.

**Comment by Habib1385** [comment]
@thenorthatlantic پیام شما رو توی گروه دیدم و ریپلای کردم 
فکر کردم منظور شما فعال سازی دائمی xtls-rprx-vision هست 
که نسخه dev اضافه کرده بود مرزبان 
بعد گیت رو چک کردم متوجه حرف شما شدم که بعد از فعال سازی به مشکل می خوری 
اینو حقیقت نمی دونم چیه کار نکردم velss http

**Comment by M03ED** [comment]
سلام
نمونه کانفیگی که توی core setting استفاده می کنید رو همینجا ارسال کنید

**Comment by thenorthatlantic** [comment]
> سلام نمونه کانفیگی که توی core setting استفاده می کنید رو همینجا ارسال کنید

    {
      "tag": "VLESS TCP HTTP",
      "listen": "0.0.0.0",
      "port": 1234,
      "protocol": "vless",
      "settings": {
        "decryption": "none",
        "fallbacks": []
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tcpSettings": {
          "acceptProxyProtocol": false,
          "header": {
            "request": {
              "headers": {
                "Host": [
                  "chess.com"
                ]
              },
              "method": "GET",
              "path": [
                "/"
              ]
            },
            "response": {
              "headers": {},
              "reason": "OK",
              "status": "200",
              "version": "1.1"
            },
            "type": "http"
          }
        }
      }
    }
