### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by voicerecordist** [Gozargah/Marzban#480]
**i am getting this error during installation:**
> *Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?*

what is the problem?
OS: Ubuntu 20.04
CPU: Xeon

**Comment by SaintShit** [comment]
@voicerecordist You're docker service is not running. run

systemctl enable --now docker

and check it's status by,

systemctl status docker
