### ISSUE TITLE
زیاد شدن حجم دیتابیس

### ISSUE THREAD

**Issue by rgoogoonani** [Gozargah/Marzban#481]
سلام
وقتی قابلیت مرزبان نود رو روشن می کنم و چند تا سرور بهش اضافه می کنم که لینک سابسکریپشن بدم 
حجم دیتابیس مرزبان فضایی میره بالا 
راه حلی براش هست؟

**Comment by SaintShit** [comment]
@rgoogoonani سلام
به خاطر اطلاعات جزئی مصرف کاربر ها روی هر نود هست که توی دیتابیس ثبت میشه، موقتا میتونید با مقداردهی متغیر
DISABLE_RECORDING_NODE_USAGE = true
این قابلیت رو غیرفعال کنید

**Comment by rgoogoonani** [comment]
این کار توی کارکرد مدیریت حجم سابسکریپشن اختلال ایجاد نمی کنه ؟

**Comment by nimabark** [comment]
محدودیت کاربر نداره پنل مرزبان مصرف سیپیو به علت پخش شدن کانفینگ میره بالا

**Comment by nimabark** [comment]
حل کنید برادران
من تگ iplimit  رو اضاف کردم توی هسته xray تاثیری داره؟

**Comment by iamtheted** [comment]
من اومدم رو MySQL حجم دیتابیسم خیلی کم شده ، شاید سوییچ کنین رو این اوکی بشه.

**Comment by iamtheted** [comment]
> جناب اگر این DISABLE_RECORDING_NODE_USAGE برابر با true باشه مشکلی ایجاد نمیکنه توی محاسبه ی مصرف حجم کاربران؟ برای چی هست این فانکشن record_node_stats، صرفا برای دیباگ قابلیت نود هست؟ اگر اینطور هست چرا توی دیتابیس ذخیره میشه جای فایل لاگ همچنین میشد تعداد شو محدود کنید به 100 ریکورد آخر مثلا
> 
> @SaintShit

سلام 
این برای محاسبه ترافیک نود در قسمت Node Usage و همینطور فکر کنم Node Usage هر کاربر به صورت مجزا هست که نبودنش هم مشکل خاصی ایجاد نخواهد کرد و حجم دیتابیس شمارو پایین میاره.
