### ISSUE TITLE
مشکل دیسکانکت شدن نود ها و قطعی گسترده در سرویس کاربران

### ISSUE THREAD

**Issue by ashkanmafi2** [Gozargah/Marzban#482]
درود فراوان و خسته نباشید خدمت دولوپرهای عزیز

جدیدا مشکلی برخوردم اونم اینه که : نود ها دیسکانکت میشن و باید بصورت دستی بریم داخل پنل اونا رو مجدد ریستارت کنیم تا کانکشنشون با سرور اصلی برقرار بشه 
در واقع api error انگار دارن ..! 
حتی برای رفع این مشکل cronjob هم تعریف کردیم ولی باز هم افاقه نکرد ... 

راه حل برون رفت ازین مشکل چی هستش ؟ اطلاعی دارین ؟ 

اطلاعات پنل ( درصورت نیاز برای بررسی ): 
دیتابیس از sqlite یه mysql تغییر داده شده .. ( 80 یوزر  انتقال دادیم ) 
نود های فعال : 12 نود با پورت های متغیر ( منظور اینه که همگی با پورت پیش فرض 62050 متصل نیستن !) 
تعداد اینباند ها : 17 اینبایند ( 10 اینباند تانل می باشد ) 
تعداد یوزر ها : 95 یوزر... 

بدلیل قطعی نودها اکثر مواقع یوزر ها شاکی هستند و 80 درصد سرورهاشون گاها از کار میفته !

**Comment by SaintShit** [comment]
@ashkanmafi2 سلام، در صورت تمایل میتونید به نسخه dev آپدیت کنید، بخش کانکشن‌ نود ها بهبود پیدا کردن و برای تست روی این نسخه هست. اگر مشکل حل نشد همینجا مجدد پیام بدین تا بررسی کنیم.
(حتما قبل از آپدیت از دیتابیس بک آپ بگیرین )

**Comment by ashkanmafi2** [comment]
درود بر شما وقتتون بخیر 
بابت تاخیر در پاسخگویی از شما عذرخواهی میکنم
بنابر بررسی های صورت گرفته توسط همکار شما و سایر دوستان فعال در پروژه مرزبان ؛ نتیجه گرفتیم که قطعی نودها به دلیل عدم تنظیم فایل docker-compose.yml است 
با وارد کردن پورت های فعال در سرورهای نود و پاک کردن سایر پورت های غیرقابل استفاده ؛ این مشکل تا حد بسیار زیادی حل شده است 

services:
  node-ashkan:
    image: gozargah/marzban-node:latest
    restart: always

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node

    ports:
      - 60081:62050
      - 60082:62051
      - 22000:22000

با کامند فوق داکر پراکسی در نودسرور ها راه اندازی شده و پورت هایی که باید با xray تعریف شده در پنل(برای این نودسرور) فعالیت داشته باشند ؛ فعال میشوند و درخواست های اضافه ای به نود سرورها ارسال نمیشود !
سپاس از پیگیری شما و همکارانتان 
موفق و پیروز باشید

**Comment by DeAref** [comment]
سلام دوست عزیز. سوال مفیدی مطرح کردید. @ashkanmafi2 @SaintShit 
خواستم بپرسم ایا این مشکل براتون پیش اومده؟
[https://github.com/Gozargah/Marzban/issues/559](https://github.com/Gozargah/Marzban/issues/559)

من توی گروه هم چند نفر رو دیدم که این مشکل رو داشتند

**Comment by araadzandi** [comment]
درود به همگی 
من هم با این مشکل رو برو شدم بااین تفاوت که من از نود استفادهه نکردم و تک سرور هستم
