### ISSUE TITLE
Bug title ارسال نکردن پیام تغییر یا اضافه شدن یوزر توسط ادمین با ربات اصلی مرزبان

### ISSUE THREAD

**Issue by n0thiing** [Gozargah/Marzban#494]
رفتم رو نسخه دو بدون اطلاع
هرکاری میکنم ربات اکتیویتی ادمین هارو برام نمیفرسته
لطفاً حلش کنید

**Comment by iamtheted** [comment]
سلام فکر میکنم این مشکل رفع شده ، باید اپدیت کنید.
اگر مشکل رفع شد لطفا issue رو ببندین. 🌷
