### ISSUE TITLE
Node Notification

### ISSUE THREAD

**Issue by iamtheted** [Gozargah/Marzban#496]
Hi Marzban 💙

I believe It would be useful to add a feature in Telegram Bot to send a notification when a node is disconnected, most of the times I don't even know one of the nodes is down unless I check the node settings. 

Thanks a lot :)

**Comment by govfvck** [comment]
I think this is a good idea, I'll consider adding a telegram bot + webhook notification for this.

**Comment by erfjab** [comment]
I will add.
