### ISSUE TITLE
Incorrect public ip detection

### ISSUE THREAD

**Issue by Dliwk** [Gozargah/Marzban#497]
Marzban incorrectly detects external public ip when behind oracle virtual network.

`get_public_ip` is defined twice. First one should work while second one gives me oracle-internal 10.0.0.X instead of real public address.
https://github.com/Gozargah/Marzban/blob/c7762548c432f9791959be54ab386f3b45cafce0/app/utils/system.py#L96-L134

I'm guessing that was just an accident, see https://github.com/Gozargah/Marzban/commit/fedf77f698b344e5b54c3efc8ade736a35a38a8c

**Comment by BloodhoundAllfather** [comment]
Right. I tried to create a pull request, but it's already fixed on `dev` branch.

**Comment by Dliwk** [comment]
Ok; closing then.
