### ISSUE TITLE
مشکل قطع  و وصلی Node

### ISSUE THREAD

**Issue by powerboyhamed** [Gozargah/Marzban#499]
سلام و عرض ادب خدمت تیم مرزبان
من چند روزی هست پنل نصب کردم و بنظرم کاملترین پنل هست عالیه کارتون
تنها مشکل بنده اتصال نود ها هست، همه کارا بخوبی انجام می شه اما در سرور نود هسته Xray چند ثانیه یکبار ریست می شه آپدیت زدم و حتی سرور اصلی و سرور نود هم از ابتدا ریبیلد کردم و کانفیگ کردم اما مشکل حل نشد ممنون می شم راهنمایی کنید 
با تشکر

**Comment by powerboyhamed** [comment]
الان چک کردم خود پنل هم نصب کردم
همین مشکل روی خود پنل هم میاد هسته ریست می شه
marzban-marzban-1  | WARNING:  Restarting Xray core...
marzban-marzban-1  | WARNING:  Xray core 1.8.1 started

**Comment by powerboyhamed** [comment]
نه دوست عزیز

**Comment by iamtheted** [comment]
سلام 
اگر دیتابیس رو به MySQL تغییر بدین مشکل قطع و وصلی نود تا حد بسیار زیادی رفع خواهد شد.
لینک داکیومنت در خصوص تغییر دیتابیس رو این زیر براتون میگذارم. 
https://gozargah.github.io/marzban/examples/mysql

**Comment by powerboyhamed** [comment]
ممنون از شما دوست عزیز 
مشکل و پیدا کردم از دیتا سنتر بود

**Comment by iamtheted** [comment]
خواهش میکنم ، پس اگر ممکنه issue رو ببندین. 🌷

**Comment by powerboyhamed** [comment]
بله چشم حتما
