### ISSUE TITLE
Node Only Mode

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#502]
سلام
لطفا این آپشن بزارید که xray-core روی سرور اصلی اجرا نشه
فقط بشه نود وصل سرور اصلی کرد و از اونا استفاده کرد
با تشکر

**Comment by iamtheted** [comment]
سلام 
شما خیلی راحت از قسمت host settings میتونید ایپی سرور مستر رو پاک کرده و ایپی سرور نود رو جایگزین کنید تا کانفیگ ها فقط از نود باشن.

**Comment by iamtheted** [comment]
وقتی آیپی سرور مستر و نزاری تو host settings چطوری مستر میخواد درگیر xray core بشه؟

**Comment by RezaKardoost** [comment]
اره. بنظر منم کاش قابلیتی بود که بتونیم هسته x-ray core نود ها و حتی سرور اصلی رو خاموش و روشن کنیم.
