### ISSUE TITLE
Example of single port configuration!

### ISSUE THREAD

**Issue by dshleg** [Gozargah/Marzban#504]
Dear friends, inside readme i found information about "Multi-inbound on a single port (fallbacks support)" and in advanced section nginx configuration is present. can you provide example of single port configuration. i use dockerized marzban and nginx installed directly to OS for loadbalancing.

**Comment by lifeindarkside** [comment]
you can watch this video:
https://youtu.be/CX8bXLD69G0?si=d6ibOcQ9Tfk-SEQy
maybe you can't understand what he says, but you understand what he doo.

**Comment by M03ED** [comment]
https://gozargah.github.io/marzban/examples/all-on-one-port
