### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by Snyaify** [Gozargah/Marzban#509]
**Is your feature request related to a problem? Please describe.**
Is this possible to use Marzban in dual-stack mode? (ipv6 and ipv4)

**Describe the solution you'd like**
set UVICORN_HOST parameter to meet dual stack ip mode

**Comment by OxJ4ck** [comment]
when you set `UVICORN_HOST` to 0.0.0.0 it will accept traffic from all of the available network interfaces.
