### ISSUE TITLE
Is marzban can not use DoH server by Xray ?

### ISSUE THREAD

**Issue by GawrAme** [Gozargah/Marzban#517]
I tried using the Cloudflare DoH server as shown in the image below, but after a while I experienced an error.

My configuration
![error2](https://github.com/Gozargah/Marzban/assets/97426017/8800be52-daa5-4b6b-a8af-a54502496da4)

Error pict
![image](https://github.com/Gozargah/Marzban/assets/97426017/b0a58be7-4039-44fd-9924-c848e2886c16)

If I use a normal UDP server, for example 1.1.1.1, in this case it runs normally again.

Configuration pt. 2
![error4](https://github.com/Gozargah/Marzban/assets/97426017/85ea5fa7-5676-494c-8b31-dc30ad492369)

It can run perfectly normal
![error3](https://github.com/Gozargah/Marzban/assets/97426017/21090b3e-e248-4b8e-8b06-f1ab9456b6af)

Does marzban support DoH yet?
Thank you

**Comment by M03ED** [comment]
Fixed
