### ISSUE TITLE
make a choice to which nodes the user has access to

### ISSUE THREAD

**Issue by yremac** [Gozargah/Marzban#521]
how do you choose the protocols available to the user, only for nodes. for subscription subscriptions

**Comment by yunesxinus** [comment]
you can add a separate inbound for each node and select them in the client area.

you can also add node to existing inbounds from host settings which is not recommended

**Comment by yremac** [comment]
![изображение](https://github.com/Gozargah/Marzban/assets/113031864/f9c8e0df-29f0-46ac-9da1-0ec291eff1b5)
additional column with node selection

**Comment by M03ED** [comment]
I don't think marzban developer add this because you can separate nodes by using different inbound for each node

**Comment by yremac** [comment]
How to change this in a subscription for convenience

**Comment by yremac** [comment]
How to change this in a subscription for convenience
