### ISSUE TITLE
Clash Profile Issue

### ISSUE THREAD

**Issue by mmtech2012** [Gozargah/Marzban#524]
For clash profile, some mistakes exist.
the "cipher" field is missing and the value of "type" field is "shadowsocks" instead of "ss".

**To reproduce:**
1.setup panel normally and set clash profile template (dosent matter if default or custom)
2.add shadowsocks to xray core .json profile
3.create a user and copy sub link to some clash core apps (clash for windows or clash-verge )
4.see error like screenshot

**Expected behavior:**

All requierd field for any type of proxy properly filled.

**screenshots**
![Screenshot_2023-09-09_14-54-4](https://github.com/Gozargah/Marzban/assets/33870623/f452cff5-8973-4921-b103-d99e4b75d352)

![Screenshot_2023-09-09_14-55-3](https://github.com/Gozargah/Marzban/assets/33870623/cfd3e46f-15db-4730-acee-e55938632e5e)

**Machine details**
- OS : linux arch , android
- Clash clients : Clash for windows  , Clash-verge , Clash android , Clash meta android

**Comment by M03ED** [comment]
fixed in #536

**Comment by zhongfq** [comment]
you can try my fork, i add enhanced subscription for clash 
https://github.com/zhongfq/marzban
https://github.com/Gozargah/Marzban/pull/374
