### ISSUE TITLE
Revoke UUIDs

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#525]
سلام
در حال حاضر توی نسخه ی Dev میشه لینک سابسکریپشن رو Revoke کرد که خیلی خوب و کاربردی هست
لطفا یه آپشن برای Revoke کردن UUID ها هم بزارید (بدون اینکه لینک سابسکریپشن عوض شه)، برای اینکه کاربر ها رو مجبور به آپدیت سابسکریپشن کنیم کاربرد داره

برای زیبایی ظاهری میتونید جای Revoke Subscription بنویسید Revoke و بعد که موس میره روش گزینه ی Revoke Subscription Link و Revoke UUIDs ظاهر شن
با تشکر

**Comment by mozhutte** [comment]
سلام.
تا حالا امتحان کردی ببینی وقتی سه نقطه جلوی یه پروتکل رو بزنی و بیای پایین uuid رو پاک کنی و سیو کنی، چه اتفاقی میوفته؟
