### ISSUE TITLE
Charging Users Trough Bot | شارژ کردن یوزر ها از طریق ربات

### ISSUE THREAD

**Issue by ItsAML** [Gozargah/Marzban#531]
سلام و خسته نباشید خدمت برنامه نویسان عزیز،

موقع شارژ کردن یوزر از طریق تمپلیت های بات داخلی خود مرزبان شارژ به درستی اعمال نمیشه، داخل خود پنل و همچنین داخل ربات به درستی حجم و تاریخ رو نشون میده ولی عملا توی اتصال همون خطای EOF مربوط به اتمام حجم و یا تاریخ رو نشون میده و اتصالی برقرار نمیشه، خواستم بدونم روشی برای درست کردنش هست یا باید یه بخش از کد رو فیکس کنیم که اوکی بشه.

**Comment by hamedefatian** [comment]
منم بعضی اوقات این مشکل رو دارم 
اجبارا همونجا یک بار غیر قعال و مجدد فعال میکنم تا درست بشه
