### ISSUE TITLE
dokodemo-door Bug

### ISSUE THREAD

**Issue by amebrahimi** [Gozargah/Marzban#532]
Hi,
If you add a dokodemo-door config to the Core Settings, and you try to open the Host Settings menu it logs you out of the panel and if you log in it will log you out again until you put the URL in the address bar without /login.

**Comment by M03ED** [comment]
You can use this variable in env file and problem will be solved

XRAY_EXCLUDE_INBOUND_TAGS = "inbound tag" 

Close issue if you don't have any other problem

**Comment by amebrahimi** [comment]
yes thank you

**Comment by amebrahimi** [comment]
What is I want to exclude multiple tags?

**Comment by mozhutte** [comment]
just add a space between them:

XRAY_EXCLUDE_INBOUND_TAGS = "DOCO_1 DOCO_2 DOCO_3"

**Comment by amebrahimi** [comment]
Ok got it it's with space. But I think it would be more logical if the separator was comma
