### ISSUE TITLE
Bash script to automate Marzban-node install

### ISSUE THREAD

**Issue by AlirezaBaratian** [Gozargah/Marzban#539]
I wrote a simple bash script automating Marzban-node installation based on the docs. Should I fork this repo and submit a PR with the script or the Marzban-node?

**Comment by AlirezaBaratian** [comment]
چشم، ممنونم.

**Comment by Jaylennyy** [comment]
> I wrote a simple bash script automating Marzban-node installation based on the docs. Should I fork this repo and submit a PR with the script or the Marzban-node?

دوست عزیز کدتون قابل دسترس هست الان که بتونیم استفاده کنیم؟

**Comment by AlirezaBaratian** [comment]
بله روی https://github.com/Gozargah/Marzban-scripts یه PR زدم اونجا می‌تونید ببینید.
