### ISSUE TITLE
[Feature Request] Change Xray Policy Settings

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#541]
سلام
من میخواستم توی کانفیگم این پالیسی رو اضافه کنم (البته اعداد متفاوت)

https://github.com/chika0801/Xray-examples/blob/66d6638892b890cae868ef37bf38c2bba3e10da9/VLESS-XTLS-uTLS-REALITY/config_server.json#L66

سوالم اینه که آیا این مورد با مرزبان تداخل ایجاد خواهد کرد؟ با توجه این قسمت از کد های مرزبان

https://github.com/Gozargah/Marzban/blob/c7762548c432f9791959be54ab386f3b45cafce0/app/xray/config.py#L72

با تشکر

**Comment by OxJ4ck** [comment]
سلام policy تو مرزبان hard code شده و اگر مقدار دهی هم کنید اعمال نمیشه.
