### ISSUE TITLE
User Statistic

### ISSUE THREAD

**Issue by lifeindarkside** [Gozargah/Marzban#542]
**Is your feature request related to a problem? Please describe.**
I would like to have more user statistics available in the project. Specifically, I want to know the user's current connection status, the protocol and node they are connected to. Additionally, I would like to have access to the average speed of their session and the time their session ends.

**Describe the solution you'd like**
I would like to have a feature that provides the user's connection status, including the protocol and node they are currently connected to. It would also be helpful to display the average speed of their session and the time their session is expected to end.

**Describe alternatives you've considered**

**Additional context**

**Comment by lifeindarkside** [comment]
Tome zone is incorrect.
Maybee add parameter in docker, or .env file?

**Comment by lifeindarkside** [comment]
I create some solution with connect to MySQL db 
https://github.com/lifeindarkside/marzban_mysql_streamlit

**Comment by M03ED** [comment]
timezone its not incorrect
its based on utctime in marzban

**Comment by lifeindarkside** [comment]
But how i can change it?

**Comment by lifeindarkside** [comment]
> timezone its not incorrect
> its based on utctime in marzban

But how i can change it?

**Comment by M03ED** [comment]
you cant right now
chnaging timezome it can make some problem and bugs
i don't know what gonna happen specifically

**Comment by lifeindarkside** [comment]
> you cant right now
> chnaging timezome it can make some problem and bugs
> i don't know what gonna happen specifically

Ok i dont do it. I just fix this in sql request.

**Comment by lifeindarkside** [comment]
i create new repository for sqlite DB 
[https://github.com/lifeindarkside/marzban_sqlite_streamlit](https://github.com/lifeindarkside/marzban_sqlite_streamlit)
this version connect to marzban docker container.

**Comment by lifeindarkside** [comment]
Add english version for sqlite DB
https://github.com/lifeindarkside/marzban_sqlite_streamlit

**Comment by M03ED** [comment]
thanks for your good project
