### ISSUE TITLE
Adding User Ratio Control for Middle Node Connections

### ISSUE THREAD

**Issue by emahdij** [Gozargah/Marzban#543]
Feature Request:
In the Marzban panel, we currently have a Marzban node that connects to the center node. While this setup works well, it would greatly enhance the functionality of the panel if we could introduce a user ratio control for connections to expensive nodes.

Problem Statement:
In certain scenarios, we have expensive nodes that require more resources and are used for specific tasks. It is important to manage the allocation of users to these nodes efficiently. Currently, we do not have a built-in mechanism to control the ratio of users connecting to these expensive nodes, leading to potential resource allocation imbalances.

Proposed Solution:
I propose adding a feature that allows administrators to set a user ratio for connections to expensive nodes. This would provide better control over resource allocation and help ensure that these valuable resources are used effectively.

**Comment by M03ED** [comment]
this Feature its added in #548 pr and just need to be accepted
