### ISSUE TITLE
No Log

### ISSUE THREAD

**Issue by majiix** [Gozargah/Marzban#544]
قسمت لاگ پنل متصل نمیشه و چیزی نشون نمیده. پنل و اتصالات به خوبی کار میکنه ولی این قسمت نه. من از نسخه 0.2.6 به 0.3.2 آپدیت کردم با استفاده از دستور پایین. 
`docker pull gozargah/marzban:latest`
همه چی عالی آپدیت شد و کار میکنه جز این قسمت لاگ. چی رو باید تغییر بدم این مورد هم درست بشه؟

**Comment by M03ED** [comment]
سلام 
احتمالا با ادمین غیر sudo وارد پنل شدید

**Comment by majiix** [comment]
> سلام احتمالا با ادمین غیر sudo وارد پنل شدید

این مورد هم تست کردم جواب نداد. بین وضعیت Connecting و Closed می‌مونه.
![Screenshot 2023-09-15 192459](https://github.com/Gozargah/Marzban/assets/6815416/19a204d8-4a3f-4692-905c-f8aa97c6afad)

**Comment by arturinious** [comment]
The same problem with marzban-marzban-1  | INFO:     xx.xx.xx.xx:0 - "GET /api/core/logs?interval=1&token=eyJhbGciO... HTTP/1.0" 404 Not Found

**Comment by M03ED** [comment]
log is enable in you're xray core ?
it should be like this 
![image](https://github.com/Gozargah/Marzban/assets/50927468/87692932-8f22-451c-92c0-a521591e76c2)

**Comment by arturinious** [comment]
> log is enable in you're xray core ? it should be like this ![image](https://user-images.githubusercontent.com/50927468/272197639-87692932-8f22-451c-92c0-a521591e76c2.png)

Yes, of course. In Marzban logs all api requests are working, but GET /api/core/logs has 404 error.
"GET /api/system HTTP/1.0" 200 OK
"GET /api/core HTTP/1.0" 200 OK
"GET /api/core/config HTTP/1.0" 200 OK
"GET /api/core/logs?interval=1&token=eyJhbGciO......  HTTP/1.0"  404 Not Found

![Снимок экрана 2023-10-03 в 11 41 40](https://github.com/Gozargah/Marzban/assets/146424619/14705796-2109-4c19-b421-1b72c81b9f5e)

**Comment by arturinious** [comment]
Address http://IP:8000/dashboard works with no errors, but https://domain/dashboard has the error above. I think it's NGNIX config wrong file:

```
server {
	server_name www.domain.com;

	location /api {
		proxy_pass         https://127.0.0.1:8000;
		proxy_redirect     off;
		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Proto $scheme;
	}

	location /dashboard {
		proxy_pass         https://127.0.0.1:8000;
		proxy_redirect     off;
		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Proto $scheme;
	}

	location /sub {
		proxy_pass         https://127.0.0.1:8000;
		proxy_redirect     off;
		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Proto $scheme;
	}

	root /var/www/www.domain.com;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
		error_page 404 /404.html;
	}

	listen 443 ssl http2; # managed by Certbot
		ssl_certificate /etc/letsencrypt/live/www.domain.com/fullchain.pem; # managed by Certbot
		ssl_certificate_key /etc/letsencrypt/live/www.domain.com/privkey.pem; # managed by Certbot
		include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
		ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
	if ($host = www.domain.com) {
		return 301 https://$host$request_uri;
	} # managed by Certbot

	listen 80;
	server_name www.domain.com;
	return 404; # managed by Certbot
}
```

**Comment by arturinious** [comment]
I solved this problem with NGINX config:

location ~* /(sub|dashboard|api|docs|redoc|openapi.json) {
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
