### ISSUE TITLE
Proposal for Software Development Cycle Enhancement

### ISSUE THREAD

**Issue by linehman** [Gozargah/Marzban#547]
Dear Marzban team

I hope this message finds you well. I am a dedicated user of your software and have been closely following its development cycle. I would like to propose an enhancement to the current development process that I believe could benefit both the development team and the user community.

Current Situation:

Currently, the software development cycle consists of two channels, namely "Main" and "Dev." The "Dev" channel frequently receives new features and updates, often leading to potential bugs in this version. Unfortunately, the time gap between the "Dev" version and the "Main" release has been growing, which can be challenging for users seeking a balance between new features and stability.

Proposal:

I would like to suggest the introduction of an additional development channel between "Dev" and "Main," similar to the model used in the Firefox development cycle. This intermediate channel would serve as a bridge to address the following concerns:

    Frequent Updates and Bugs: The new channel can act as a buffer, allowing for more rigorous testing and bug-fixing before features are merged into the "Main" version. This would lead to a more stable "Dev" version.

    Reduced Time Gap: Users would have access to new features and improvements more frequently, bridging the gap between "Dev" and "Main" releases.

    Better User Experience: Users who seek the latest features but are wary of potential bugs in the "Dev" version would find this new channel a valuable middle ground.

Benefits:

    Improved software stability.
    Faster delivery of new features.
    Enhanced user experience.

Considerations:

I acknowledge that implementing this change may require adjustments to the existing development process and resource allocation. As an enthusiastic user of the software, my primary role is to provide feedback and advocate for improvements.

I understand that the development team has the expertise to evaluate the feasibility and potential impact of this proposal. I'm open to discussions and collaboration with the community to support the implementation of this enhancement.

Please feel free to reach out if you have any questions or require further input from the user community. Your consideration of this suggestion is greatly appreciated.

Thank you for your commitment to enhancing the software and fostering collaboration within the community.

Kind Regards

**Comment by M03ED** [comment]
this is good idea
