### ISSUE TITLE
jq: error (at <stdin>:1): Cannot index string with string "Service"Bug title

### ISSUE THREAD

**Issue by itmanpro** [Gozargah/Marzban#549]
**Describe the bug**
جالبه این خطا تابحال 9 بار داخل گروه تلگرامی هم پرسیده شده ولی دریغ از حتی یک جواب
وقتی روی سرور استتوس میگیرم این خطا رو میده
jq: error (at <stdin>:1): Cannot index string with string "Service"

و پنل مدیریتی لود نمیشه
سرور رو ریبوت کردم حذف کردم دوباره نصب کردم بازم مشکل همونه
سیستم عامل هم لینوکس اوبونتو 22.04 هست
در حالتهای فایروال بسته، فایروال فعال پورت 8000 باز هم تست کردم فرقی نکرد، هرچند بعید میدونم ربطی به پورت و شبکه داشته باشه
به نظر میرسه یه باگ در برنامه نویسی بک اندش هست
**To Reproduce**

**Expected behavior**

**Screenshots**

**Machine details (please complete the following information):**
 - OS: [e.g. ubuntu 20]
- Python version: [e.g 3.8]
- Nodejs version: [e.g 16.17]

**Additional context**

**Comment by zxwt42** [comment]
Facing the same issue on Debian 12. On :8000 I can see only the loading thing

**Comment by hamedhdd** [comment]
دوستان عزیزم دقت بفرمایید آدرس ورود به داشبورد به این صورته : 
http://domainnameorip:8000/dashboard/
به اون خطای JQuery توجه نکنید
