### ISSUE TITLE
کار نکردن لینک ساب روی ایفون

### ISSUE THREAD

**Issue by MHP370** [Gozargah/Marzban#552]
سلام 
لینک سابسکریپشن روی اپ های آیفون کار نمیکند

**Comment by Habib1385** [comment]
> سلام لینک سابسکریپشن روی اپ های آیفون کار نمیکند

سلام 
ssl فعال کنید

**Comment by M03ED** [comment]
از ssl استفاده کنید 
اگر مشکل تون حل شد issue رو ببندید ممنون

**Comment by MHP370** [comment]
مرسی 
اوکی شد
