### ISSUE TITLE
ترافیک غیرطبیعی نودها

### ISSUE THREAD

**Issue by TahaRJI** [Gozargah/Marzban#553]
ترافیک مصرفی نودها در قسمت nodes usage با اطلاعاتی که سرور و دیتا سنتر میده تطابق نداره
طبق تصویر در تاریخ مشخص شده ترافیک مصرفی‌ای که پنل از نود آلمان نشون میده 9.5 گیگه اما در همان تاریخ سرور 42.5 گیگ رو ثبت کرده (از vnstat استفاده کردم) و دیتاسنتر هم همین عدد رو نشون میده. این موضوع برای نود دیگر هم صدق میکنه. این درحالیه که جز تنظیمات لازم سرور نود و سایر تنظیماتی که تو داکیومنت مرزبان هست (مثل مسدود سازی سایت‌های ایرانی، وارپ و تغییر ورژن xray) تنظیمات دیگه‌ای روی سرور انجام نشده و برنامه‌ی دیگه‌ای هم نصب نیست.
![1](https://github.com/Gozargah/Marzban/assets/145503288/5429857e-ce07-4793-b0f9-28ed6d2443fe)
![2](https://github.com/Gozargah/Marzban/assets/145503288/ebe14464-a4f7-4e67-88ef-3ae30bfdbd3f)

مشکلات مشابه سایر دوستان:
https://t.me/gozargah_marzban/1/519453
https://t.me/gozargah_marzban/1/519455

**Comment by atropates** [comment]
کسی هنوز جواب نداده ؟ مشکل منم دقیقا همینه

**Comment by wrath1300** [comment]
یه مشکلی است اینه که وقتی Sni یا public key چیزی عوض میکنی اگه کسی آپدیت نکنه اشتراکشو و به همون قبلی وصل بشه یه ترافیک زیادی معلوم نیست کجا میره و منابع سرور هم فشار زیادی روش میاره. نمیدونم که روی آپدیت های جدید مرزبان حل شده یا نه ولی پورت همه اینباندهارو عوض کنید مشکلتون حل میشه

**Comment by iamtheted** [comment]
سلام، آیا در ورژن های جدید مرزبان هم مشکل هنوز پا برجاست؟ @TahaRJI

**Comment by erfjab** [comment]
این ایشو به خاطر در اختیار نزاشتن اطلاعات بیشتر بسته میشود و در صورت داشتن مشکل لطفا ایشوی جدید باز کنید. با تشکر
