### ISSUE TITLE
Xtls not working on grpc

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#558]
Hi , i trying to make a reality + grpc + xtls as flow config but xtls only apply on tcp and not on grpc
![IMG_20230922_112158](https://github.com/Gozargah/Marzban/assets/117955130/7ca83ef2-e640-4e5c-8539-675b7270cfcd)

**Comment by M03ED** [comment]
Flow it's not for grpc , it's only work on tcp and kmpc , this is xray default settings and it's not because of marzban

**Comment by xmohammad1** [comment]
Ok my bad then soz
