### ISSUE TITLE
New Protocols

### ISSUE THREAD

**Issue by itmanpro** [Gozargah/Marzban#561]
Could you Please add new protocols like TUIC 5 and Hysteria 2?
I know the X-UI panel is based on Xray and Xray does not support those protocols, but maybe somehow you could bring them together to work beside each other separately but all the user management part could be integrated into one panel especially if you could bring all of them into one subscription account, that would be really great.

Thank you for all the grate jobs you've done already.

**Comment by M03ED** [comment]
There is no plan to add these protocols
