### ISSUE TITLE
باگ اصلی پروژه مرزبان

### ISSUE THREAD

**Issue by oneoneishere** [Gozargah/Marzban#564]
ضمن تشکر از بانیان اصلی این پروژه که قدردان زحماتشون هستیم همگی.

بنده به عنوان یک متخصص فناوری اطلاعات با چیزی حدود 22 سال فعالیت در حوزه برنامه نویسی، شبکه و اینترنت تا چند وقت پیش فکر میکردم بزرگترین ضعف و باگ مرزبان داکیومنت ناقصش هست که چندین مورد نقص رو شاهدش بودم.

که البته اینها کاملا طبیعیه، یک پروژه اوپن سورس و رایگان و جدید هست توسط عده ای جوان خوش ذوق و شور شروع شده و داره تکمیل میشه
وجود باگ یا ضعف در پروژه های برنامه نویسی یک امر طبیعی و غیر قابل اجتناب هست.

از طرفی انکار ضعف یا ناراحت شدن از اظهار اون ضعف ها یه امر غیر طبیعی و کودکانه است، شرکتهای غولی مثل مایکروسافت، گوگل، آمازون، اپل، اوراکل و... با صدها هزار کارمند و نخبه که میلیاردها مشتری دارن و کل صنعت و تکلنولوژی دنیا رو دارن هدایت میکنن به خاطر ضعف در محصولشون زیر سوال میرن چه برسه به یک پروژه معمولی برنامه نویسی.

تا زمانی که شخص با الفاظ غیر توهینی و فحش از پروژه انتقاد میکنه چه انتقاد تند و تعصبی باشه چه انتقاد منطقی و سازنده نباید ناراحت بشیم و بخوایم صداشو قطع کنیم.

طی چند روز اخیر در گروه تلگرام مرزبان فعالیت میکردم، بیشتر از سوال جواب ارسال کرده بودم و در حد و توان خودم کمک کردم به حل مشکلات کاربران، منتی سر کسی نیست، کاری بود که خودم در جهت کمک به هموطنانم دلی انجام میدادم.

ولی امروز به خاطر اینکه محترمانه و منطقی با توضیح مثال گفتم که داکیومنت مرزبان ضعیفه از طرف یکی از ادمینهای به شدت متعصب بن شدم!!
طرف مشخص بود سن و سالی نداره، شاید همسن پسر من یا حتی کوچکتر، چون جوابهای تعصبی و بن کردن سریع بدون هیچ دلیل منطقی نشانه عقل خیلی خام و کودکانه است.

برای همین به نظر من بزرگترین باگ مرزبان، باگهای فنی، یا حتی ضعف در داکیومنتیشن نیست، استفاده از چنین ادمینی هست که آبروی پروژه و زحمات بانیان اصلی پروژه رو زیر سوال میبره.

تیمی که برنامه نویسی میکنه و پروژه چنین زیبایی رو شروع میکنه و پیش میبره انصاف نیست اینچنین وجهه خودش رو با استفاده از چنین اشخاصی زیر سوال ببره، امیدوارم برنامه نویسان یا هدایت کنندگان اصلی این پروژه این مورد رو مد نظر قرار بدن و در استفاده و توجیه ادمینهای گروه تجدید نظر کنند.

براتون آرزوی موفقیت میکنم و قدردان تلاشهای بی چشمداشت شما هستم.

**Comment by araadzandi** [comment]
درود دوست عزیز
کاملا با صحبت های شما موافق هستم 
بنده هم مدتیه مشکلی با پنل روبرو شدم و متاسفانه راهنمای خوبی از گروه تلگرامی دریافت نکردم و امیدوارم این موضوع هر چه سرعی تر  از طرف دوستان حل بشود.

**Comment by talamag** [comment]
منم با شما موافقم و این مورد رو دیدم

**Comment by oXIIIo** [comment]
سلام دوست عزیز
من نه ادمینم گروهم و نه برنامه نویس مرزبان و فقط داشتم issue ها رو چک میکردم که به این issue بر خوردم و فکر کردم واقعا باگی تو پروژه وجود داره که بررسی کنم و واقعا تاسف خوردم که شما با 22 سال سابقه فعالیت هنوز نمیدونید که بخش issues گیت هاب برای این بحث ها نیست و میتونید تو [discussions](https://github.com/Gozargah/Marzban/discussions) مرزبان این بحث ها رو انجام بدین.
در ضمن مرزبان یه پروژه اوپن سورس رایگانه و کسی وظیفه ای نداره که به سوالاتتون جواب بده و یا حتی پروژه رو اپدیت کنه و اگر اینکارو انجام میدن دارن بهتون لطف میکنن.
شما راجب داکیومنت حرف زده بودین که کامل نیست، بله کاملا حرفتون درسته و کامل نیست ولی شما میتونید توی ریپو [gozargah.github.io](https://github.com/Gozargah/gozargah.github.io) مشارکت کنید و کاملش کنید.
من واقعا بحثی با شما ندارم و اگر هم ریپلی کنید جوابی به حرفای شما نخواهم داد، فقط نسبت به اون سنی که دارین و بهش افتخار میکنید، این یک رفتار بچه گانست.
امیدوارم روز خوبی داشته باشین.

**Comment by LonUp** [comment]
ادمین های خیلی گستاخی که حتی کوچک ترین نقدی بهشون میکنی بن میکنن . کاملا موافقم .
