### ISSUE TITLE
انتقال کاربران از xui به مرزبان

### ISSUE THREAD

**Issue by storevpsnet** [Gozargah/Marzban#565]
سلام از توسعه دهندگان مرزبان خیلی تشکر میکنم و واقعا کارشون درسته که این اسکریپت رو زدن.
فقط سوالی داشتم این بود که میخواستم کاربران را از xui به مرزبان انتقال بدم داخل گروه کسی جواب نمیده گفتم اینجا بزار شاید کسی جواب داد آیا راهی هسته؟؟

**Comment by OxJ4ck** [comment]
سلام
اگر از پورت های متفاوت برای هر یوزر استفاده میکنید خیر ولی اگر از یک پورت استفاده میکنید میتونی با تغییر دیتابیس اینکارو انجام بدین.

**Comment by Habib1385** [comment]
سلام 
مرزبان نامه رو چک کنید 


https://t.me/Marzban_Nameh


💠‌ مهاجرت x-ui به marzban 

انتظارها به پایان رسید❗️
بالاخره همه می‌توانند از پنل مرزبان استفاده کنند. 

[ https://github.com/ItsAML/X-Ui-to-Marzban ]

1⃣ یوزرنیم ، حجم ، تاریخ‌انقضا کاربرها از پنل x-ui به پنل marzban منتقل میشه.🍂

2⃣ شما اول باید اینباندهای مورد نظر خودتون رو حالا یا TLS و یا Reality رو روی مرزبان ایجاد کنید و از صحت کار کردنشون مطمئن بشید.🍂

3⃣ در نهایت ، این سکریپت فقط اطلاعات یوزرهای شمارو از x-ui به marzban منتقل می‌کنه اما وصل موندن اونها رو پس از مهاجرت روی marzban تضمین نمیکنه لذا پس از مهاجرت باید تک تک به همه کاربرها لینک ساب مرزبان رو بدین.🍂

4⃣ بخاطر اساس کار متفاوتی که x-ui و marzban دارن وصل موندن کاربرها پس از مهاجرت امکان پذیر نیست و لازمه همه کاربرها لینک ساب مرزبان رو وارد کنند.🍂

**Comment by mortezaafshar92** [comment]
مشکل همین لینک ساب هست که باید مجدد به همه مشتری ها بدیم

**Comment by Habib1385** [comment]
@mortezaafshar92 سلام 
مشکل عدم اتصال کاربرا بعد از انتقال رفع شده 
هر وقت مشتری خواست تمدید کنه سابکریشن براش ارسال کن

**Comment by mohsenzt** [comment]
> Refere

خب فرمت لینکشون یکیه ساب رو هم منتقل میشه کرد دیگه
