### ISSUE TITLE
Nekoray Subscription problem

### ISSUE THREAD

**Issue by mmtech2012** [Gozargah/Marzban#568]
**Describe the bug**
1.in nekoray (core: sing-box & xray) when setup subscription , Vmess H2 REALITY dosent detect the correct 'transport' excpected to be 'http' but 'tcp' detected.
2.in nekoray (core: sing-box & xray) when setup subscription , Vmess H2 REALITY dosent detect the correct 'security' excpected to be 'tls' but field remain empty and REALITY fields also remain empty.
3..in nekoray (core: sing-box & xray) when setup subscription , Trojan H2 REALITY dosent detect the correct 'transport' excpected to be 'http' but 'tcp' detected.
4.in nekoray (core: sing-box & xray) when setup subscription , Trojan WS dosent detect Allow-insecure expected to tick 'Allow insecure' but is not happen.

**To Reproduce**
1. Setup Vmess H2 REALITY + Trojan H2 REALITY + Trojan WS (self-sign tls)
2. setup Sub link and import in nekoray dosent matter which core you select (mine problem on sing-box but I`m test on xray too)
4. check the configs and See errors.

**Expected behavior**
in context

**Screenshots**

**Machine details (please complete the following information):**
 - OS: Linux x86_64

**Additional context**

**Comment by OxJ4ck** [comment]
Hi,
can you share your inbound configuration?

**Comment by OxJ4ck** [comment]
as you can see in the [xray document](https://xtls.github.io/config/transport.html#streamsettingsobject), the network section in streamSettings does not accept the value "h2", change it to "http" and probably your problem will be fixed.
