### ISSUE TITLE
Inbound jumppaintpolitical.store doesn't exist

### ISSUE THREAD

**Issue by oneoneishere** [Gozargah/Marzban#569]
وقتی میخوام یوزر اضافه کنم این خطا رو دریافت میکنم

Inbound jumppaintpolitical.store doesn't exist

دیتابیسم MySQL هست
آخرین نسخه مرزبان هستم روی اوبونتو 22.04 و ایکس ری کور 1.8.4

**Comment by oXIIIo** [comment]
سلام از دیتای جدول inbounds تون میتونید عکس بدین؟

**Comment by oneoneishere** [comment]
حل کردم خودم

**Comment by milad73n** [comment]
> مشکل دسترسی به phpmyadmin رو حل کردم وارد شدم دیدم اینباندهایی که پاک کردم هنوز اونجا مونده، از جمله همونی که توی متن خطا هستش به خاطر وابستگی کلیدهای ایندکسشون اونها رو نمیتونم مستقیم پاکشون کنم چه جوری میشه راحت پاکشون کرد که اختلالی هم در عملکرد دیتابیس به وجود نیاد؟ کوئری خاصی داره؟ یا دستور خاصی در کامند خود مرزبان؟

چطوری حلش کردین؟

**Comment by oneoneishere** [comment]
> > مشکل دسترسی به phpmyadmin رو حل کردم وارد شدم دیدم اینباندهایی که پاک کردم هنوز اونجا مونده، از جمله همونی که توی متن خطا هستش به خاطر وابستگی کلیدهای ایندکسشون اونها رو نمیتونم مستقیم پاکشون کنم چه جوری میشه راحت پاکشون کرد که اختلالی هم در عملکرد دیتابیس به وجود نیاد؟ کوئری خاصی داره؟ یا دستور خاصی در کامند خود مرزبان؟
> 
> چطوری حلش کردین؟

مشکلتون دقیقا چیه ؟ بگید تا راهنمایی کنم
