### ISSUE TITLE
nickname for each user

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#577]
سلام، لطفا این قابلیت بزارید که بتونیم برای هر یوزر یه اسم فارسی تعیین کنیم. با تشکر

**Comment by oXIIIo** [comment]
سلام تو قسمت note میتونید یه یادداشت برای هر کاربر قرار بدین، مثلا همین اسم فارسی که میخایین رو اونجا میتونید وارد کنید.
