### ISSUE TITLE
مشکل تانل 

### ISSUE THREAD

**Issue by ShadowFredi** [Gozargah/Marzban#580]
سلام خسته نباشید برای تانل روی مرزبان منکه تانل رو میزنم ولی نه با ایپی ایران وارد پنل میشه نه کانفیگ ها کار میکنن با دامنه ایران

**Comment by M03ED** [comment]
تانل ربطی به مرزبان و یا هر نرم افزاری که شما دارید استفاده می کنید نداره ، کانفیگ تانل تون اشتباه هست

**Comment by MMRP77** [comment]
برای تانل کردن همانند پنل های دیگر با روش آی پی تیبل
بعد از اینکه ایپی هارو ست کردید 
وارد پنل مرزبان بشید
قسمت تنظیمات هاست ها
بعد از اینکه اینباند خودتون رو انتخاب کردید(نوع اتصال به سرور خودتون)
قسمت adderss  با دامین و یا سابدامین تونل خودتون آدرس دهی کنید
قسمت های دیگه رو طبق اتصال اپراتور های خودتون تنظیم کنید.(میتونید خالی بذارید)(در هر صورت همه مواردشو میتونید طبق خواسته خودتون تنظیم کنید)
