### ISSUE TITLE
آی پی اشتباه در access.log

### ISSUE THREAD

**Issue by morteza-rashidi** [Gozargah/Marzban#581]
در فایل لاگ اتصال (access.log) وقتی از این سرویس پشت سی دی ان استفاده میشه بجای آی پی واقعی استفاده کننده آی پی سی دی ان لاگ میخوره

**Comment by M03ED** [comment]
هیچ اشتباهی در کار نیست ، اگه میخواهید ای پی اصلی رو داشته باشید باید از نسخه های گرون تر cdn استفاده کنید ، ربطی هم به مرزبان ندارد این مورد
