### ISSUE TITLE
استفاده از یک هاست برای یک یا چند پنل مجزا

### ISSUE THREAD

**Issue by hamedefatian** [Gozargah/Marzban#582]
سلام
آیا امانش هست ما از یک هاست برای چند پنل مجزا از هم استفاده کنیم؟

**Comment by oXIIIo** [comment]
سلام،
همین اولش بگم این روش رو من خودم تست نکردم ولی احتمالا با این روش بتونید این کارو انجام بدین.
شما تو فایل .env پنلون بیایین و `XRAY_SUBSCRIPTION_URL_PREFIX` رو به این صورت ست کنید که بعد از دامنه یک مسیر مشخص برای هر پنل هم اضافه کنید یعنی برای مثال
`XRAY_SUBSCRIPTION_URL_PREFIX = "https://example.com/panel1/"`
که با این کار لینک سابسکریپشن شما بصورت
`https://example.com/panel1/sub/token`
کپی میشه که میتونید تو هاستتون پوشه panel1 رو ایجاد کنید و تو اون پوشه درخواست رو به سمت پنل اولتون بفرستید.
برای پنل های دیگتونم به همینصورت عمل میکنید و فقط پوشه های مختلف روی هاستتون ایجاد میکنید.

**Comment by hamedefatian** [comment]
> سلام، همین اولش بگم این روش رو من خودم تست نکردم ولی احتمالا با این روش بتونید این کارو انجام بدین. شما تو فایل .env پنلون بیایین و `XRAY_SUBSCRIPTION_URL_PREFIX` رو به این صورت ست کنید که بعد از دامنه یک مسیر مشخص برای هر پنل هم اضافه کنید یعنی برای مثال `XRAY_SUBSCRIPTION_URL_PREFIX = "https://example.com/panel1/"` که با این کار لینک سابسکریپشن شما بصورت `https://example.com/panel1/sub/token` کپی میشه که میتونید تو هاستتون پوشه panel1 رو ایجاد کنید و تو اون پوشه درخواست رو به سمت پنل اولتون بفرستید. برای پنل های دیگتونم به همینصورت عمل میکنید و فقط پوشه های مختلف روی هاستتون ایجاد میکنید.

ممنون
انجام دادم ولی نشد

**Comment by hamedefatian** [comment]
با روش دوستمون به این خطا میخورم
{"detail":"Not Found"}
با ساب دامنه اصلا صفحه لود نمیشه
میشه یک مثال بزنید؟

**Comment by yaramahmadi** [comment]
سلام
دوست عزیز شما باید از طریق داکر و اینجاد شبکه های مختلف با رنج آی پی های محتلف و پورت فورواردینگ استفاده کنید
سپاس
