### ISSUE TITLE
Display warning for duplicate inbound ports

### ISSUE THREAD

**Issue by mdjvd** [Gozargah/Marzban#585]
سلام به مرزبان. امیدوارم خوب باشید.

خیلی وقت‌ها بعضی از دوستان در کانفیگ Xray از یک پورت چند بار استفاده میکنن و این تداخل پورت باعث یکسره ری‌استارت شدن هسته، کند شدن کانفیگ‌ها و یا بالا رفتن مصرف رم میشه.
اگر امکانش هست، به نظرم بهتره در قسمت Core Settings در صورت وجود پورت تکراری در اینباندها، یک Warning به کاربر برای اصلاح پورت‌ها نمایش داده بشه. 

ممنون از زحماتتون 💙

**Comment by iamtheted** [comment]
ایده بسیار مفیدی هست، در عجبم چرا تاکنون بهش توجهی نشده /:
