### ISSUE TITLE
sub Auto-Update آپدیت خودکار

### ISSUE THREAD

**Issue by mewhrzad** [Gozargah/Marzban#588]
آپدیت خودکار سابسکریپشن از سمت کلاینت قابل تنظیم هست؟

**Comment by oXIIIo** [comment]
سلام
بله اپدیت خودکار سمت کلاینته.
اگر منظورتون سمت سروره، تو نسخه dev پنل مرزبان میتونید از [SUB_UPDATE_INTERVAL](https://github.com/Gozargah/Marzban/blob/0712061815f9eee22e4844cf78f3feb8c0331935/.env.example#L38C3-L38C23) تو فایل .env استفاده کنید ولی باید کلاینت این قابلیت رو ساپورت کنه.
