### ISSUE TITLE
UnicodeDecodeError in marzban container

### ISSUE THREAD

**Issue by dry-stan** [Gozargah/Marzban#598]
A UnicodeDecodeError occurs in the "marzban" container after a period of execution. The error is specifically triggered in the capture_only thread. The error message and stack trace indicate that the 'utf-8' codec cannot decode a byte at a certain position, leading to an "invalid start byte" error.

Logs :  marzban-marzban-1     | Exception in thread Thread-4 (capture_only):
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
marzban-marzban-1     |     self.run()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
marzban-marzban-1     |     self._target(*self._args, **self._kwargs)
marzban-marzban-1     |   File "/code/app/xray/core.py", line 70, in capture_only
marzban-marzban-1     |     output = self.process.stdout.readline()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
marzban-marzban-1     |     (result, consumed) = self._buffer_decode(data, self.errors, final)
marzban-marzban-1     | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 368: invalid start byte

**Comment by M03ED** [comment]
try to reinstall marzban 
test what happen

**Comment by mamdali96** [comment]
> > try to reinstall marzban
> > test what happen
> 
> I did, but this problem occurred again

i had and still have this problem with one of my servers 
the issue is unsolvable
 
 but after few days the problem disappers and wont happen
