### ISSUE TITLE
Updating the limit when adding from a template

### ISSUE THREAD

**Issue by sm1ky** [Gozargah/Marzban#599]
I would like to see the column “Dump traffic every n days” to be added from the template. So as not to change manually in the panel every time

Also add a method for receiving logs from nodes and the main server to the DOCS API

**Comment by erfjab** [comment]
این مورد ذاتا در دسترس می باشد.
https://github.com/Gozargah/Marzban/blob/349451da0de5f590f19b4a84b865ed376aacef63/app/views/core.py#L17C2-L17C5
https://github.com/Gozargah/Marzban/blob/349451da0de5f590f19b4a84b865ed376aacef63/app/views/node.py#L79
