### ISSUE TITLE
V2board integration

### ISSUE THREAD

**Issue by shinya-dono** [Gozargah/Marzban#6]
it would be graet to have users fetched from v2board. with maybe predefined config since v2board does not support that many protocols.

v2board endpoints (`/api/v1/server/Deepbwork/user?node_id=51&token=token` for example) send responses like:
`
{
  "msg": "ok",
  "data": [
    {
      "id": 2,
      "v2ray_user": {
        "uuid": "f7c3a7db-5313-4356-a40c-0fabedc90d13",
        "email": "f7c3a7db-5313-4356-a40c-0fabedc90d13@v2board.user",
        "alter_id": 0,
        "level": 0
      }
    },
    ...
]
}
`

and that could be inserted into x-ray inbounds without limitations since v2board itself handles traffic limit sent by the node in defined time periods.

**Comment by amirho3inf** [comment]
Agreed, some script to migrate from X-UI would be useful too.

**Comment by SaintShit** [comment]
Nice idea, I've been thinking that it would be great if we had migration scripts to come up with other panels such X-UI. I go work on it soon

**Comment by shinya-dono** [comment]
V2board is a node management system.
https://github.com/v2board/v2board

you can create VPN nodes with tools like https://github.com/XrayR-project/XrayR
and use the v2board to manage your nodes.
i was thinking that MArzban can be used like XrayR as a dependant node that relies on v2board to manage it's users, traffics and etc and only provides connection solution.
