### ISSUE TITLE
عدم کار کردن دستور مرزبان در سرور پس از ریبوت 

### ISSUE THREAD

**Issue by mamdali96** [Gozargah/Marzban#600]
با عرض خسته نباشید

سیستم عامل ابونتو 20
سرور از هتزنر هستش اگه کمکی میکنه
مرزبان تک پورت ngnix

برنامه 
روی سرور نیست به جز 
مرزبان  و نت دیتا 

مشکل این هستش
پس از زدن دستور marzban down
البته یک ارور نشون داد با پیغام
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to github.com:443
و ری استارت کردن سرور

دستور marzban up ، marzban update هیچ کدوم کار نمیکنه
حتی اسکریپت نصب هم کار نمیکنه

![Screenshot 2023-10-22 140813](https://github.com/Gozargah/Marzban/assets/126720242/b7e3aeed-33df-4072-b9a0-ae19eebcc50b)

پ . ن : تنها راه حل موقتی که تونستم کاری که کنم که سرور بالا بیاید دوباره این بود

cd /opt/marzban/

docker compose up

**Comment by xshayank** [comment]
I think your have to set a dns server like shecan
Your server is having a little trouble connecting to GitHub
