### ISSUE TITLE
امکان شخصی سازی لینک ساب

### ISSUE THREAD

**Issue by ZakariaRasoli** [Gozargah/Marzban#601]
سلام

لطفا امکان شخصی سازی لینک ساب رو اضافه کنین

**Comment by Habib1385** [comment]
سلام 
منظور شما چی هست ؟ 
در حال حاضر تمپلیت برای لینک ساب توسط دو دوست عزیز منتشر شده 
https://github.com/x0sina/marzban-sub
هاست و سرور مستر سینا 👆 
https://github.com/MuhammadAshouri/marzban-templates
سرور مستر عاشوری  👆
https://github.com/AC-Lover/AC-Subcription
هاست مستر AC-Lover 👆
تمپلیت مستر سینا نسخه جدید هست و دیزاین بهتری داره 
اگر فرانت بلد باشید راحت می تونید تغییر بدید

**Comment by Habib1385** [comment]
درصورتی که مشکل شما حل شده لطفا issues را ببندید

**Comment by ZakariaRasoli** [comment]
من خود لینک منظورم هست تمپلیت و که میدونم

**Comment by Habib1385** [comment]
منظرتون اینه مثل پنل سنایی بتونید اسم دستی اضافه کنید ؟

**Comment by ZakariaRasoli** [comment]
دقیقا چون وقتی پنلو به یه سرور دیگه انتقال میدی کل لینک های ساب غیرفعال میشه

**Comment by OxJ4ck** [comment]
> دقیقا چون وقتی پنلو به یه سرور دیگه انتقال میدی کل لینک های ساب غیرفعال میشه

سلام اگر از همون دامنه استفاده کنید غیر فعال نمیشن و لینک سابسکریپشن قبلیا کار میکنن فقط کافیه ip پشت دامنه رو عوض کنید.

**Comment by ZakariaRasoli** [comment]
اقا دمت گرم اینو نمیدونستم ❤️

**Comment by ZakariaRasoli** [comment]
> > دقیقا چون وقتی پنلو به یه سرور دیگه انتقال میدی کل لینک های ساب غیرفعال میشه
> 
> سلام اگر از همون دامنه استفاده کنید غیر فعال نمیشن و لینک سابسکریپشن قبلیا کار میکنن فقط کافیه ip پشت دامنه رو عوض کنید.
