### ISSUE TITLE
Webhook غیرفعال شدن ناگهانی

### ISSUE THREAD

**Issue by KAJOOSH** [Gozargah/Marzban#604]
پس از گذشت چند ساعت Webhook از کار می افتد و با ریسیت مرزبان حل می شود و دوباره پس از چند متوقف می شود.
بنده نتوانستم لاگ آن یا خطای آن را استخراج کنم.
ممنون میشوم راهنمایی کنید

**Comment by M03ED** [comment]
از ورژن dev استفاده کنید

**Comment by KAJOOSH** [comment]
@M03ED آیا راهکار دیگری دارد؟ 
بیش از ۱۰۰۰ اکانت در نسخه stable وجود دارد و نگارنم به مشکل بر خورم.

**Comment by M03ED** [comment]
من خودم با 300 اکانت روی نسخه dev هستم و مشکلی ندارم

**Comment by gozarman** [comment]
سلام.
به زودی ورژن dev استیبل میشه و مشکلی در فرآیند upgrade به وجود نمیاد. جای نگرانی نیست.
توی کانال تلگرام اطلاع رسانی میکنیم.

**Comment by lilcheti** [comment]
This is a real problem is it fixed yet?

**Comment by M03ED** [comment]
fixed in 0.4.0 version

**Comment by lilcheti** [comment]
> fixed in 0.4.0 version

I have version 0.4.1 and It's not working!

**Comment by M03ED** [comment]
you probably doing something wrong , its ok for me
