### ISSUE TITLE
نمایش بارکد لینک سابسکرایپشن در ربات تلگرام

### ISSUE THREAD

**Issue by H4m3d84** [Gozargah/Marzban#605]
با سلام. ربات تلگرام خیلی عالیه فقط نمیدونم چرا بارکد لینک ساب رو بهش اضافه نکردید؟ بارکد رو برای لینک های معمولی نشون میده ولی برای لینک ساب نه. اگر اضافه کنید که خیلی عالی میشه ممنون

**Comment by Habib1385** [comment]
سلام 
درحال حاضر این امکان فعال هست نسخه (dev)
آموزش مهاجرت به نسخه dev 
https://t.me/Marzban_Nameh/84
درصورتی که مشکل شما حل شده لطفا issues را ببندید

**Comment by H4m3d84** [comment]
این نسخه که فرمودید کی نهایی حدودا؟ مشخصه؟

**Comment by Habib1385** [comment]
@H4m3d84 معلوم نیست 
ولی درحال حاضر نسخه dev مشکلی نداره 
خواستید می تونید مهاجرت کنید
