### ISSUE TITLE
شروع تاریخ با اولین اتصال

### ISSUE THREAD

**Issue by soheilkhaledabdi** [Gozargah/Marzban#606]
سلام وقت بخیر خسته نباشید خیلی ممنون از پنل عالیتون
اقا اگه میشه این قابلیت که تاریخ انقضای کانفیگ با اولین اتصال شروع بشه رو اضافه بکنید مثل پنل سنایی ممنون میشم

**Comment by Habib1385** [comment]
سلام 
بزودی اضافه میشه
