### ISSUE TITLE
Marzban-node: timed out

### ISSUE THREAD

**Issue by Armania1997** [Gozargah/Marzban#609]
سلام
چندتا از نودهای من قطع شده:
![image](https://github.com/Gozargah/Marzban/assets/72545851/6387d181-9130-4feb-8a74-50bdc31c39dc)

timed out
Marzban (v0.3.2) - Xray core (v1.8.4)

**Comment by Habib1385** [comment]
سلام 
سرور های شما متصل هستند ؟ 
تایم اوت به دلیل عدم اتصال سرور هست معمولا 
چه نسخه ای هستید ؟ 
dev & releases?

**Comment by Armania1997** [comment]
> سلام سرور های شما متصل هستند ؟ تایم اوت به دلیل عدم اتصال سرور هست معمولا چه نسخه ای هستید ؟ dev & releases?
نه این نود قطعه باقی نودها وصله، اخرین نسخه پایدار، بتا نیستم، نسخه نود رو دوباره نصب کردم

**Comment by Habib1385** [comment]
بعد از نصب مجدد سرتیفیکت جدید رو بهش دادید ؟‌
نسخه جدید نود در نسخه بتا پنل باید سرتیفیکت از پنل گرفته بشه و وارد سرور نود بشه

**Comment by Armania1997** [comment]
> بعد از نصب مجدد سرتیفیکت جدید رو بهش دادید ؟‌ نسخه جدید نود در نسخه بتا پنل باید سرتیفیکت از پنل گرفته بشه و وارد سرور نود بشه

بله سرتیفیکیت رو دوباره تنظیم کردم، نشد
نه خب عرض کردم بتا نیستم، اخرین نسخه پایدارم
سرور مستر من ایرانه، ولی هر دوشون به هم دیگه ssh میخوره پس فیلتر نیست

**Comment by Habib1385** [comment]
اگر سرور مستر ایران هست 
ایپی رو عوض کنید 
پیشنهاد من اینه ایران رو برای مستر نزارید

**Comment by gozarman** [comment]
سلام.
برای این issue هیچ لاگی قرار داده نشده. به همین خاطر این issue بسته میشه.
اگر مجدد میخواید issue رو باز کنید، حتما لاگ از سرور با اطلاعات کامل و مورد نیاز قرار بدید.
