### ISSUE TITLE
اتصال نود در Haproxy

### ISSUE THREAD

**Issue by reza3723** [Gozargah/Marzban#622]
سلام ممنون بابت پروژه عالی مرزبان

مشکل اینجاست که سرور اصلی را با HAproxy تک پورت کردم ولی سرور نود را نمیتونم وصل کنم و هیچ اموزشی وجود نداره خواهشااا در این مورد راهنمایی کنید چون هیچ منبعی در این رابطه وجود نداره.
طبق مطلبی که در این اینجا هست 
https://gozargah.github.io/marzban/examples/all-on-one-port
تمام تنظیمات
cfg
سرور مرکزی را توی سرور نود قرار دادم 
سوال اینجاست دامنه پنل و یا بقیه تنظیمات باید تغییر کنند یا خیر ؟ 
توی کانفیگ مرزبان به چه صورت باید تغییرات را اعمال کرد؟
 
تشکر

**Comment by iamtheted** [comment]
سلام اگر می خواین نودهاتون هم بصورت تک پورت استفاده کنید باید HAProxy رو روی تک تک نودها نصب کنید و front و backend رو طبق آموزش تعیین کنید.
