### ISSUE TITLE
SNI doesn't work

### ISSUE THREAD

**Issue by Sa1ch** [Gozargah/Marzban#628]
Hi! I have a customized subdomain.

The certificate is generated for all subdomains *.mydomain.com

But if I write serv-* in SNI.mydomain.com the configuration stops working
![изображение_2023-11-10_044557642](https://github.com/Gozargah/Marzban/assets/28288185/dca61e13-d0b6-4c83-9dd7-855157a830d1)

How to set up SNI?

**Comment by M03ED** [comment]
don't use *

**Comment by iamtheted** [comment]
Hi, It depends on the A record you have created. 
Your A record must only have a star in the name section so it would include all subdomains. 

Like this:  Type: A / Name: * / IPv4: IP.IP.IP.IP

**Comment by Sa1ch** [comment]
> Hi, It depends on the A record you have created. Your A record must only have a star in the name section so it would include all subdomains.
> 
> Like this: Type: A / Name: * / IPv4: IP.IP.IP.IP

it's set up. but it doesn't work
![изображение_2023-11-14_002933997](https://github.com/Gozargah/Marzban/assets/28288185/8ff1ac05-e6b9-40c0-a255-998c110c2c46)

**Comment by Sa1ch** [comment]
> don't use *

Why?

**Comment by iamtheted** [comment]
> > Hi, It depends on the A record you have created. Your A record must only have a star in the name section so it would include all subdomains.
> > 
> > Like this: Type: A / Name: * / IPv4: IP.IP.IP.IP
> 
> it's set up. but it doesn't work
> ![изображение_2023-11-14_002933997](https://github.com/Gozargah/Marzban/assets/28288185/8ff1ac05-e6b9-40c0-a255-998c110c2c46)
> 
> 
> 
> 
> 
> 

What kind of CDN is this?
Use Cloudflare.

**Comment by M03ED** [comment]
if you wanna marzban send random sub domain you just need to do this : *.domain.com

**Comment by Sa1ch** [comment]
> if you wanna marzban send random sub domain you just need to do this : *.domain.com

I did it! but it doesn't work

**Comment by Sa1ch** [comment]
> > > Hi, It depends on the A record you have created. Your A record must only have a star in the name section so it would include all subdomains.
> > > Like this: Type: A / Name: * / IPv4: IP.IP.IP.IP
> > 
> > 
> > it's set up. but it doesn't work
> > ![изображение_2023-11-14_002933997](https://user-images.githubusercontent.com/28288185/282540104-8ff1ac05-e6b9-40c0-a255-998c110c2c46.png)
> 
> What kind of CDN is this? Use Cloudflare.

this is the dns editor on reg.ru

**Comment by mohammadi939** [comment]
i think the problem is request host, you should set request host url to your real domain address,
