### ISSUE TITLE
Node Resource Load Percentage as a Variable

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#629]
Hi,
Every VPN app let the users know which servers are full to ask them not use full ones
I.e. NordVPN :
![image](https://github.com/Gozargah/Marzban/assets/41063376/8c67a2ca-ccd7-45b2-9fcf-dac52d497184)
Please add new variable to set Server Load in the config name
Thanks.

**Comment by M03ED** [comment]
marzban hosts dosen't work like this and we cant make it real time , you can just singbox or clash meta to connect automatily to best server

**Comment by M03ED** [comment]
i said hosts don't work like this 
also at least 90% of users don't care about this 
don't ask for features that have conflict with marzban codes

**Comment by gozarman** [comment]
@APT-ZERO 
We currently do not gather the information required for this feature. As soon as we implemented its requirements, it will be added to the project.

Keep it in mind that avoid any arguments in the issues section.
