### ISSUE TITLE
DEBUG and DOCS

### ISSUE THREAD

**Issue by Epic-R-R** [Gozargah/Marzban#634]
When we turn on DEBUG mode or DOCS, Docker gives an error when restarting

**Expected behavior**

**Screenshots**
![Screenshot from 2023-11-16 15-42-08](https://github.com/Gozargah/Marzban/assets/38718448/7f1d031b-853f-4197-a7d4-eaedc3fddf2f)

**Machine details (please complete the following information):**
 - OS: Ubuntu 22
- Python version: 3.10
- Nodejs version: 20
- Npm version: 10.1
- Browser: Chrome

**Comment by M03ED** [comment]
using debug require to install npm and npm packages , you can't use it with docker 
if you wanna use it you should run marzban manually

**Comment by mahanhpn** [comment]
can you please provide more info about to do it ?
