### ISSUE TITLE
Support for Wireguard Inbound (Xray-core v1.8.6)

### ISSUE THREAD

**Issue by APT-ZERO** [Gozargah/Marzban#642]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.6

**Comment by Iambabyninja** [comment]
> @APT-ZERO Thank you for the update
> 
> but do you have a step-by-step guide on how to set up WireGuard inbound and outbound correctly?
> 
> I appreciate your assistance in advance.

```json 
{
  "tag": "WG_OUTBOUND",
  "protocol": "wireguard",
  "settings": {
    "secretKey": "Your_Secret_Key",
    "DNS": "1.1.1.1",
    "address": ["172.16.0.2/32", "2606:4700:110:8756:9135:af04:3778:40d9/128"],
    "peers": [
      {
        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
        "endpoint": "engage.cloudflareclient.com:2408"
      }
    ]
  }
}
```

**Comment by realartin** [comment]
درود قراره به صورت هاست ستینگ اضافه بشه و قابلیت اکانتینگ هم اعمال بشه که هر یوزر رو بشه تعین کرد میزان ترافیک و زمان رو براش ؟

**Comment by m0x61h0x64i** [comment]
سلام. خبری نشد؟ پیر شدیم

**Comment by m0x61h0x64i** [comment]
> > سلام. خبری نشد؟ پیر شدیم
> 
> [http://github.com/Gozargah/Marzban/releases/latest](https://github.com/Gozargah/Marzban/releases/latest)

خب؟

**Comment by m0x61h0x64i** [comment]
> > > > سلام. خبری نشد؟ پیر شدیم
> > > 
> > > 
> > > [http://github.com/Gozargah/Marzban/releases/latest](https://github.com/Gozargah/Marzban/releases/latest)
> > 
> > 
> > خب؟
> 
> پنل پرمخاطب #مرزبان که اخیرن به‌دلیل عدم بروزرسانی طی ۵ ماه، ۲ مورد از فورک‌های اون‌رو معرفی کردم، ساعتی قبل یک بروزرسانی تقریبن بزرگ ارائه کرده. اضافه‌شدن فیلدهای مربوط به تنظیمات فرگمنت به رابط کاربری، پشتیبانی از Path برای GRPC، خروجی کانفیگ به‌صورت Json برای v2rayN، درنظر گرفتن کانفیگ سفارشی برای streisand و خیلی از موارد دیگه

داش این چه ربطی به موضوع داشت. تاپیک این ایشو رو بخون

**Comment by M03ED** [comment]
not planned.
