### ISSUE TITLE
Warp + wireguard and simple warp dont work

### ISSUE THREAD

**Issue by ValentineMWAY** [Gozargah/Marzban#643]
I installed warp-cli first and try insturct from site for configure warp and unblock openai.com, but its not working.
Also i try via wireguard warp, and get error what i need port. And also i need port in first try.

**Comment by M03ED** [comment]
Use marzban documentation to setup warp 
Marzban don't suggest 3rd scripts
https://gozargah.github.io/marzban/examples/warp

**Comment by ValentineMWay11** [comment]
> Use marzban documentation to setup warp Marzban don't suggest 3rd scripts https://gozargah.github.io/marzban/examples/warp

i use marzban documentation and get this issue

**Comment by M03ED** [comment]
You just said you get error , but what error ?

**Comment by ValentineMWay11** [comment]
sry, i use ru instruction.
when i use original from your link all start working
