### ISSUE TITLE
How to Add nodes After New Update 

### ISSUE THREAD

**Issue by speedforce-lk** [Gozargah/Marzban#645]
![image](https://github.com/Gozargah/Marzban/assets/122682099/b3861d24-9f72-4044-a360-d6b101947f3a)

**Comment by M03ED** [comment]
https://t.me/Marzban_Nameh/123

**Comment by speedforce-lk** [comment]
How Update Master Node ? I Updated via CLI Command but did not Updated ! I can not download the file to import to nodes.

**Comment by M03ED** [comment]
docker compose down
docker compose pull
docker compose up -d
Also there is no official cli for node

**Comment by M03ED** [comment]
Updating main server and nodes are separated , you need to update nodes too

**Comment by M03ED** [comment]
I send a guide here before
And there is another one 
https://github.com/Gozargah/gozargah.github.io/blob/patch-1/marzban/fa/docs/marzban-node.md

**Comment by M03ED** [comment]
I send a guide here before
And there is another one 
https://github.com/Gozargah/gozargah.github.io/blob/patch-1/marzban/fa/docs/marzban-node.md

**Comment by Iambabyninja** [comment]
> > I send a guide here before And there is another one https://github.com/Gozargah/gozargah.github.io/blob/patch-1/marzban/fa/docs/marzban-node.md
> 
> 
> 
> 404 error

https://github.com/Gozargah/gozargah.github.io/blob/91a294c38fe33f45335855a61caefc810b03f516/marzban/fa/docs/marzban-node.md

**Comment by M03ED** [comment]
> > I send a guide here before And there is another one https://github.com/Gozargah/gozargah.github.io/blob/patch-1/marzban/fa/docs/marzban-node.md
> 
> 404 error

https://github.com/Gozargah/gozargah.github.io/blob/91a294c38fe33f45335855a61caefc810b03f516/marzban/fa/docs/marzban-node.md
