### ISSUE TITLE
More details in bot reports while editing users with panel

### ISSUE THREAD

**Issue by CIAHAT** [Gozargah/Marzban#647]
سلام.
آیا امکان داره تغییرات حجم و زمانی که از طریق پنل برای یوزر ها اعمال میشه، مشابه قالب زیر ارسال بشه؟

📶 #Traffic_Change #From_Bot
➖➖➖➖➖➖➖➖➖
Username : Jafar
Last Traffic Limit : 10.0 GB
New Traffic Limit : 35.0 GB
➖➖➖➖➖➖➖➖➖ 

📅 #Expiry_Change #From_Bot
➖➖➖➖➖➖➖➖➖
Username : Jafar
Last Expire Date : 00:00:00 2023-10-24
New Expire Date : 00:00:00 2023-09-25
➖➖➖➖➖➖➖➖➖

**Comment by M03ED** [comment]
امکانش هست ولی نیازی نخواهید داشت 
بزودی قراره تمامی تغییرات یوزر ها به صورت لاگ در دیتابیس ذخیره بشن

**Comment by CIAHAT** [comment]
> امکانش هست ولی نیازی نخواهید داشت بزودی قراره تمامی تغییرات یوزر ها به صورت لاگ در دیتابیس ذخیره بشن

واقعا عالی میشه هرزمان این اتفاق بیفته.
الان لاگ هایی که ثبت میشه هم انقضا رو دقیق نمیزنه هم تغییرات زمان کلا ثبت نمیشه. تاریخ انقضا (نه تایم باقیمانده)، تاریخ آخرین تغییرات حجم یا زمان (یا تغییر حجم و تغییر زمان مجزا) چیز هاییه که تو users بنظرم نبودنشون حس میشه.
تو بخش user_usage_logs هم admin_id، تاریخ انقضا، لیمیت دیتای جدید بعد ریست، تاریخ انقضای جدید بعد ریست، چیزایی هستن که بنظرم میتونن کاربردی باشن. نمیدونم از نظر فنی و کاربردی بودن چقدر منطقی هستن بهرحال ایده بود.
نهایتا تشکر فراوان برای همه زحماتتون.
