### ISSUE TITLE
خرابی SQLite بعد از جابجای بکا اپ در ورژن جدید

### ISSUE THREAD

**Issue by araadzandi** [Gozargah/Marzban#653]

**Comment by sinakhorsi** [comment]
من بعد از آپدیت به نسخه یک هفته پیش، دیگه لیست یوزر هامون نشون داده نمیشه به هیچ وجه
حتی روی هر 4 تا سرور هم مجدد بکاپ برگردوندیم، هم روش کپی پیست و هم روش دونه دونه اضافه کردن به دیتابیس خام
اما لیست یوزر ها میپره و باز دیگه نشون نمیده
لطفا اگه میشه یه پیگیری جدی بکنید برای این موضوع
گروه تلگرام هم کسی جوابم نمیده

**Comment by sinakhorsi** [comment]
سلام مجدد عزیزان
مشکل نشون ندادن یوزر ها استفاده از علائم { } توی host settings هست.
به محض اینکه علائم { } پاک کنید مجدد لیست یوزر ها قابل مشاهد میشود.
باتشکر از دوست عزیز @Mosed3 در گروه تلگرام مرزبان
