### ISSUE TITLE
ناتوانی در ادیت نوت

### ISSUE THREAD

**Issue by yasbija** [Gozargah/Marzban#654]
با سلام. در آپدیت نسخه 0.4.1 مسئله اول اینکه برای کاربران قبلی نمیشود نوت اضافه کرد مسئله دوم اینکه برای کاربران جدید هم فقط در حین ساخت کانفیگ مبشود نوت اضافه کرد و بعد از اضافه کردن نوت امکان حذف و یا ویرایش آن وجود ندارد ظاهرا در نسخه dev این مشکل نبوده. روی سرور جدید هم نصب کردم همچنان این مشکلات هستش...با تشکر

**Comment by Iambabyninja** [comment]
It's fixed in DEV, 

https://github.com/Gozargah/Marzban/commit/2f3bfde407af2aaad67b1ffbcb73f1f2aa99b03a
