### ISSUE TITLE
اضافه نمودن نود

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#655]
سلام و احترام
سرور نودی که ساختم را در چند پنل اصلی در سرورهای مختلف از قسمت اضافه نمودن نودها اضافه کردم و هیچ سرتیفیکیتی از من نخواست و فقط با آی پی و پورت دیفالت اضافه شد (میدونم که یک جای کارو اشتباه کردم) خواهشمند است راهنمایی فرمایید
- فایلی که در هنگام اضافه کردن نود ارائه میشه (دانلود گواهینامه)را باید به کجا انتقال بدهیم؟  (تصویر پیوست)
سپاس

![2023-11-25_14-32-58](https://github.com/Gozargah/Marzban/assets/103871792/da17fa3b-9c3a-48b5-afe9-0a989751c0cd)

**Comment by Multivpnlive** [comment]
سلام دوست عزیز شما باید فایل رو از پنل دانلود کنید و داخل فایل SFTP سرور نود که مسیرش مشخص شده انتقال بدید ادرس پوشه سرور نود var/lib/marzban/serts

**Comment by Iambabyninja** [comment]
in the new authorization implementation of the pair central panel <-> node, authorization is carried out using the panel certificate. You can copy the certificate or file using FTP or import  value using a text editor:

1) GET SERT VALUE
![image](https://github.com/Gozargah/Marzban/assets/104270279/f2bb31a7-e93d-4e06-9549-9501d48da9bf)
2) CREATE FOLDER IN NODE SERVER
```
mkdir -p /var/lib/marzban-node/

```
3) Create file and open in text editor 

```
nano /var/lib/marzban-node/ssl_client_cert.pem

```
4) Past cert value  
 ![image](https://github.com/Gozargah/Marzban/assets/104270279/15f3cc98-8546-4481-abdb-483a44a3895b)

5) Edit docker-compose file 
![image](https://github.com/Gozargah/Marzban/assets/104270279/2c9cf05f-7368-479f-9945-bbe6ac0fea86)

6) run node 

```
docker compose up -d

```

**Comment by yaramahmadi** [comment]
> serts

سلام مجدد
دوست عزیز ممنون از راهنمایی - این انتقال را انجام دادم اما مشکل اینجاست که اگر 10 تا پنل مرکزی روی سرورهای مختلف داشته باشیم و نود را بهشون اضافه کنیم، بدون هیچ مشکلی قبول میکنه و امنیتی برای سرورهای نود وجود نداره، نمیدونم منظورمو درست انتقال دادم یا خیر

**Comment by yaramahmadi** [comment]
> in the new authorization implementation of the pair central panel <-> node, authorization is carried out using the panel certificate. You can copy the certificate or file using FTP or import value using a text editor:
> 
> 1. GET SERT VALUE
>    ![image](https://private-user-images.githubusercontent.com/104270279/285607715-f2bb31a7-e93d-4e06-9549-9501d48da9bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Nzc1MTYsIm5iZiI6MTcwMDk3NzIxNiwicGF0aCI6Ii8xMDQyNzAyNzkvMjg1NjA3NzE1LWYyYmIzMWE3LWU5M2QtNGUwNi05NTQ5LTk1MDFkNDhkYTliZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwNTQwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmFlMjI5ZGYwYjk1NDdlY2JlMzEzZDRhNDAxZmU1NzhkMDQxY2FmMzJkODFmZDZlN2IyOTE2YzI5M2NkODExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G0m7ewlg17uJCmM2U_XkpFXHHhMnr0HbYGSEge8jrI0)
> 2. CREATE FOLDER IN NODE SERVER
> 
> ```
> mkdir -p /var/lib/marzban-node/
> ```
> 
> 3. Create file and open in text editor
> 
> ```
> nano /var/lib/marzban-node/ssl_client_cert.pem
> ```
> 
> 4. Past cert value
>    ![image](https://private-user-images.githubusercontent.com/104270279/285607785-15f3cc98-8546-4481-abdb-483a44a3895b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Nzc1MTYsIm5iZiI6MTcwMDk3NzIxNiwicGF0aCI6Ii8xMDQyNzAyNzkvMjg1NjA3Nzg1LTE1ZjNjYzk4LTg1NDYtNDQ4MS1hYmRiLTQ4M2E0NGEzODk1Yi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDU0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDEzNDE4NGQ4MGZjMzM1M2VkYTI4M2YxMTI3MTM2M2E1MjI3ODgzZWZiM2MzN2ZiOWUyNDM1YjgzNTFhMmM2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SsM082uZtip_lEfY0u2U5A7p_8WUeccrCccryqVsiOw)
> 5. Edit docker-compose file
>    ![image](https://private-user-images.githubusercontent.com/104270279/285607890-2c9cf05f-7368-479f-9945-bbe6ac0fea86.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Nzc1MTYsIm5iZiI6MTcwMDk3NzIxNiwicGF0aCI6Ii8xMDQyNzAyNzkvMjg1NjA3ODkwLTJjOWNmMDVmLTczNjgtNDc5Zi05OTQ1LWJiZTZhYzBmZWE4Ni5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDU0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjUwZWJmNmNhMjU1OTg2NTZhZjBjNWNiOTJjZTU0YTZmYzlmMmE5NmVlNjk0YWFmZTA4OWI3OTc4NTJkZDVhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hG6Qnj6z_Wbehgfhiixzb02fafryF6csJL1D7VfCbxI)
> 6. run node
> 
> ```
> docker compose up -d
> ```

**THX**

**Comment by yaramahmadi** [comment]
> in the new authorization implementation of the pair central panel <-> node, authorization is carried out using the panel certificate. You can copy the certificate or file using FTP or import value using a text editor:
> 
> 1. GET SERT VALUE
>    ![image](https://private-user-images.githubusercontent.com/104270279/285607715-f2bb31a7-e93d-4e06-9549-9501d48da9bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Nzc1MTYsIm5iZiI6MTcwMDk3NzIxNiwicGF0aCI6Ii8xMDQyNzAyNzkvMjg1NjA3NzE1LWYyYmIzMWE3LWU5M2QtNGUwNi05NTQ5LTk1MDFkNDhkYTliZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwNTQwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmFlMjI5ZGYwYjk1NDdlY2JlMzEzZDRhNDAxZmU1NzhkMDQxY2FmMzJkODFmZDZlN2IyOTE2YzI5M2NkODExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G0m7ewlg17uJCmM2U_XkpFXHHhMnr0HbYGSEge8jrI0)
> 2. CREATE FOLDER IN NODE SERVER
> 
> ```
> mkdir -p /var/lib/marzban-node/
> ```
> 
> 3. Create file and open in text editor
> 
> ```
> nano /var/lib/marzban-node/ssl_client_cert.pem
> ```
> 
> 4. Past cert value
>    ![image](https://private-user-images.githubusercontent.com/104270279/285607785-15f3cc98-8546-4481-abdb-483a44a3895b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Nzc1MTYsIm5iZiI6MTcwMDk3NzIxNiwicGF0aCI6Ii8xMDQyNzAyNzkvMjg1NjA3Nzg1LTE1ZjNjYzk4LTg1NDYtNDQ4MS1hYmRiLTQ4M2E0NGEzODk1Yi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDU0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDEzNDE4NGQ4MGZjMzM1M2VkYTI4M2YxMTI3MTM2M2E1MjI3ODgzZWZiM2MzN2ZiOWUyNDM1YjgzNTFhMmM2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SsM082uZtip_lEfY0u2U5A7p_8WUeccrCccryqVsiOw)
> 5. Edit docker-compose file
>    ![image](https://private-user-images.githubusercontent.com/104270279/285607890-2c9cf05f-7368-479f-9945-bbe6ac0fea86.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Nzc1MTYsIm5iZiI6MTcwMDk3NzIxNiwicGF0aCI6Ii8xMDQyNzAyNzkvMjg1NjA3ODkwLTJjOWNmMDVmLTczNjgtNDc5Zi05OTQ1LWJiZTZhYzBmZWE4Ni5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMDU0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjUwZWJmNmNhMjU1OTg2NTZhZjBjNWNiOTJjZTU0YTZmYzlmMmE5NmVlNjk0YWFmZTA4OWI3OTc4NTJkZDVhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hG6Qnj6z_Wbehgfhiixzb02fafryF6csJL1D7VfCbxI)
> 6. run node
> 
> ```
> docker compose up -d
> ```

**The solution you offered to fix the problem was exceptionally thorough and effective, completely resolving the issues. I sincerely appreciate your assistance.**

**Comment by amirmhm** [comment]
با سلام
برای من اصلا گزینه ی دانلود سرتیفیکیت نشون داده نمیشه و کلا خالیه.
![Uploading Screenshot 2024-02-24 123247.png…]()

**Comment by amirmhm** [comment]
با سلام
برای من اصلا گزینه ی دانلود سرتیفیکیت نشون داده نمیشه و کلا خالیه.
![Screenshot 2024-02-24 123247](https://github.com/Gozargah/Marzban/assets/63209512/3d4fa3aa-4867-46b0-8f90-cf1b39089253)
