### ISSUE TITLE
Support grpc mode  - gun or multi 

### ISSUE THREAD

**Issue by Lordrichard23** [Gozargah/Marzban#659]
Please add multi mode support for grpc transmission to the panel, because this feature creates better stability and speed in connecting the configurations to the Internet.  

I tried to add this feature to the xray core in the panel, but I noticed that even if it is added to the core, the feature is not enabled in the config made by the panel. 
I suggest to add this feature like utls or alpn in the host setting.
Thanks.

**Comment by YamlEngineer** [comment]
For now, you can use this piece of code in the app/utils/share.py file
```py
if net == 'grpc':
    payload['type'] = 'multi'
```
and add it to the container as a volume in Docker.
```docker
    volumes:
      - ./share.py:/code/app/utils/share.py
```

**Comment by amebrahimi** [comment]
@Lordrichard23 Can you please send a sample of the xray configuration you were trying to make?

**Comment by yasin0111** [comment]
> For now, you can use this piece of code in the app/utils/share.py file
> 
> ```python
> if net == 'grpc':
>     payload['type'] = 'multi'
> ```
> 
> and add it to the container as a volume in Docker.
> 
> ```
> volumes:
>      - ./share.py:/code/app/utils/share.py
> ```

مسیر فایل share.py دقیق تو سرور کجاست؟ میخوام gun مود روی کانفیگا اوتوماتیک فعال بشه این کدو بزارم حله؟

**Comment by realartin** [comment]
> app/utils/share.py

where is this file in installation version on server ?

**Comment by YamlEngineer** [comment]
Everything is clear ☹️

**Comment by M03ED** [comment]
> Everything is clear ☹️

yes it is
[12b21b1](https://github.com/Gozargah/Marzban/pull/961/commits/12b21b14f87ee2f49f80359f1ca2ce7a77dd5f44)
