### ISSUE TITLE
How Can edit ssl_client_cert .pem in Marzban center panel

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#660]
با سلام و احترام
چطور میتونم  ssl_client_cert .pem  اختصاصی خودم را قرار بدم ، مسیر این فایل کجاست

![image](https://github.com/Gozargah/Marzban/assets/103871792/0c09ca09-1977-4168-9dd4-ff910e7ddec5)

سپاس

**Comment by M03ED** [comment]
سلام 
فایل نیست و برای هر پنل به صورت رندوم ایجاد میشه 
اگر نیاز به تغییر دارید با استفاده از phpmyadmin میتونید انجام بدید ولی پیشنهاد نمیشه
