### ISSUE TITLE
Admin Traffic

### ISSUE THREAD

**Issue by Meytiz** [Gozargah/Marzban#668]
سلام خسته نباشید.
اگه امکانش هست به marzban cli این قابلیت رو هم اضافه کنید که بتونم به ادمینا ها محدودیت حجم تعریف کنیم (همراه با زمان انقضا).

**Comment by erfjab** [comment]
این قابلیت های تجاری می باشد که بهتر از بات و راه حل های جانبی استفاده کنید. زیرا این مورد در حال حاضر با سیاست های مرزبان همخوانی نداره، به همین خاطر اضافه نخواهد شد. با تشکر از پیشنهاد شما.
