### ISSUE TITLE
Adding Sing-Box

### ISSUE THREAD

**Issue by Hiradpi** [Gozargah/Marzban#674]
I propose integrating Sing-Box Core into Marzban and enabling a switch between Xray-Core and Sing-Box Core.

Sing-Box offers superior speed and diverse functionalities like WireGuard outbound connections (Warp) and inbound/outbound chaining. Currently, I'm using a SOCKS proxy outbound connection to link the panel's X-ray Core to Sing-Box Core, but it's causing performance issues.

Integrating Sing-Box Core directly would optimize system performance and enable seamless utilization of its advanced features within Marzban. This enhancement would significantly benefit users and elevate Marzban's capabilities.

**Comment by Hiradpi** [comment]
well he has a point btw im facing a bug rn that doesn't let me open ports on 443 or 3309 or 80 
and I double checked they are not being used 
it just says permission denied

**Comment by SaintShit** [comment]
> I propose integrating Sing-Box Core into Marzban and enabling a switch between Xray-Core and Sing-Box Core.
> 
> Sing-Box offers superior speed and diverse functionalities like WireGuard outbound connections (Warp) and inbound/outbound chaining. Currently, I'm using a SOCKS proxy outbound connection to link the panel's X-ray Core to Sing-Box Core, but it's causing performance issues.
> 
> Integrating Sing-Box Core directly would optimize system performance and enable seamless utilization of its advanced features within Marzban. This enhancement would significantly benefit users and elevate Marzban's capabilities.

I can't see the superiority of Sing-box. to my knowledge, Sing-box is a great core for the client, but I don't see much for the server. although the benchmark results mentioned in its documentation say it's faster, the results were different in my tests.

The two features you mentioned are included in Xray-core already ( wireguard outbound and fallbacks ).
if you're experiencing bad performance with socks outbound, might links below be useful for you.
[using "redirect" in freedom outbound](https://xtls.github.io/config/outbounds/freedom.html#outboundconfigurationobject)
[using sockops](https://xtls.github.io/config/transport.html#sockoptobject)
or simply setup a wireguard connection.

By the way, my first attempt to work with `v2ray_api` of Sing-box wasn't successful. and this doesn't mean that it's not possible to have Sing-box in Marzban in the future, just at this moment, it's not a priority.

**Comment by kiomarzsss** [comment]
@Hiradpi @SaintShit 
hi friends
im trying to implement sing-box in [oblivion-desktop](https://github.com/bepass-org/oblivion-desktop).
anyone can give me a hint on:
What configuration file should we define for sing-box (https://github.com/SagerNet/sing-box) to come and use the socks proxy that [warp-plus](https://github.com/bepass-org/warp-plus) creates (by default on 127.0.0.1:8086) and Tunnel all network traffics (TUN)?

**Comment by Hiradpi** [comment]
hello you need to whitelist warp-plus presses using routing rules and then use tun mode as an inbounds and a socks5 as an outbound  and then route incoming connection to proxy's outbound 
Good luck

**Comment by kiomarzsss** [comment]
thanks @Hiradpi
this was very helpful. is it ok with you to mention your username in changelog when tun feature comes to the app?

**Comment by Hiradpi** [comment]
yes thank you
happy to help
