### ISSUE TITLE
کار نکردن sni 

### ISSUE THREAD

**Issue by mokhtarabdi** [Gozargah/Marzban#679]
سلام من هم پنل سنایی دارم هم علیرضا هم مرزبان
روی پنل سنایی بعضی  sni ها رو میزنم کار میکنه اما روی مرزبان کلا reality واسه همراه اول قفله با هیچ sni کار نمیکنه یه جای پنل درست نیست اگه خواستید تو تلگرام پیام بدید کانفیگ تست با یک sni  .روی دو پنل
ID: @mokhtarabdi22

**Comment by mokhtarabdi** [comment]
آی پی هیچ مشکلی نداره دامنه رو هم چک کردم عزیز مشکل نداره تو تلگرام پیام بدین تا آی پی و دامنه رو بدم خودتون هم چک کنید من پنل مرزبان رو واقعا دوس دارم اما مطئنم یه جاش درست نیست

**Comment by Lordrichard23** [comment]
ربطی به چک کردن نداره یک سری رنج ها کلا توی همراه اول محدود شدن ، دقت کنید محدود شدن نه فیلتر یعنی شما از آی پی پینگ میگیری میبینی پینگ خوبی بهت میده ولی روی ریالیتی کار نمیکنه ، برای اثبات حرفم روی یک سرور با یک آی پی هردوپنل رو بالا بیارید و تست کنید اگر براتون مقدور هست اونوقت متوجه منظورم میشید

**Comment by SaintShit** [comment]
> سلام من هم پنل سنایی دارم هم علیرضا هم مرزبان روی پنل سنایی بعضی sni ها رو میزنم کار میکنه اما روی مرزبان کلا reality واسه همراه اول قفله با هیچ sni کار نمیکنه یه جای پنل درست نیست اگه خواستید تو تلگرام پیام بدید کانفیگ تست با یک sni .روی دو پنل ID: @mokhtarabdi22

لینک پروکسی هاتون رو برای من ارسال کنید
t.me/saintshitxd

**Comment by M03ED** [comment]
> آی پی هیچ مشکلی نداره دامنه رو هم چک کردم عزیز مشکل نداره تو تلگرام پیام بدین تا آی پی و دامنه رو بدم خودتون هم چک کنید من پنل مرزبان رو واقعا دوس دارم اما مطئنم یه جاش درست نیست

احتمالا در مرزبان sni رو فقط از هاست ستینگ تغییر دادید و در core setting تغییری ایجاد نکردید
