### ISSUE TITLE
Seprate panel port from subscription domain port

### ISSUE THREAD

**Issue by Lordrichard23** [Gozargah/Marzban#682]
Hello, please add the ability to separate the panel port from the subscription port.

This feature can increase the security of the panel by separating the subscription domain and port  from the panel domain and port.

**Comment by M03ED** [comment]
you can use host or ha proxy

**Comment by Lordrichard23** [comment]
> you can use host or haproxy

The same problem exists with haproxy because the request that reaches haproxy with the subscription domain is referred to the panel port in the backend.  So, the user can be redirected to the panel login page by adding the "/dashboard" patch to the sub link.

When you can upgrade the panel in terms of security by fixing this problem, why waste money on hosting purchases?

**Comment by Lordrichard23** [comment]
This feature is very simple and can be seen even in panels like 3xui, it is better that Marzban panel also has the ability to support it.

**Comment by M03ED** [comment]
> > you can use host or haproxy
> 
> The same problem exists with haproxy because the request that reaches haproxy with the subscription domain is referred to the panel port in the backend. So, the user can be redirected to the panel login page by adding the "/dashboard" patch to the sub link.
> 
> When you can upgrade the panel in terms of security by fixing this problem, why waste money on hosting purchases?

you can block other data except come to /sub path

**Comment by M03ED** [comment]
> This feature is very simple and can be seen even in panels like 3xui, it is better that Marzban panel also has the ability to support it.

at this point user still can port scan your panel so its useless

**Comment by SaintShit** [comment]
changing dashboard path is implemented on branch `next` and will come up with a major update.
in the case of using different ports for the application, you can use HAProxy, Nginx, Apache, whatever.

**Comment by SaintShit** [comment]
these tools are out there designed for these purposes, Marzban's just an **application**.

**Comment by Lordrichard23** [comment]
> changing dashboard path is implemented on branch `next` and will come up with a major update. in the case of using different ports for the application, you can use HAProxy, Nginx, Apache, whatever.

Your explanation was very good and complete, my idea and opinion was that with this work, Marzban will provide the capability of these changes, which makes it a comprehensive web panel that offers many possibilities for personalization.

As a result, there is no need to use other services such as haproxy, apache, etc.

But after hearing your explanation, I was convinced that this feature can be ignored and used through other services.

Thank you so much 

@M03ED @SaintShit ⚘️🙏🏻
