### ISSUE TITLE
ارور در مرزبان لاگ

### ISSUE THREAD

**Issue by mahanhpn** [Gozargah/Marzban#688]
با عرض سلام و خسته نباشید متاسفانه بنده پس از  مدتی پلنم حجم کاربر هارو حساب نمیکنه و وضعیت انلاین بودن کاربر هارو اشتباه نشون میده . یعنی تمام کاربر ها افلاین نمایش داده میشن اما انلاین هستن . در مرزبان لاگ با این ارور مواجه میشم

<img width="1470" alt="Screenshot 1402-09-17 at 12 54 02 PM" src="https://github.com/Gozargah/Marzban/assets/153385069/948c1432-54bc-4ee6-89fa-1ace584bcf61">

**Comment by M03ED** [comment]
سلام 
یکی دیگه از کاربر ها همین مشکل رو داشت و مشکل از سمت یکی از نود ها بود ، نود ها رو یکی یکی خاموش کنید ببینید از کدوم هست ، فعلا دلیل این اتفاق مشخص نیست

**Comment by mahanhpn** [comment]
متاسفانه با گذشت ۲ هفته و تست شرایط مختلف این مشکل هنوز حل نشده
