### ISSUE TITLE
Node distribution

### ISSUE THREAD

**Issue by Genry777Morgan** [Gozargah/Marzban#689]
We need to add the ability to select nodes for users individually. So that some users are on node number one, and some users are on node number 2

**Comment by M03ED** [comment]
you can do this with making seperated inbound for each node

**Comment by Genry777Morgan** [comment]
Yes, but it will be immediately added to all users

**Comment by Genry777Morgan** [comment]
But I want some users to be served by one node, and some by another

**Comment by Genry777Morgan** [comment]
> you can do this with making seperated inbound for each node


But I want some users to be served by one node, and some by another

**Comment by Genry777Morgan** [comment]
@M03ED But I want some users to be served by one node, and some by another

**Comment by M03ED** [comment]
Read my massage again.

**Comment by Genry777Morgan** [comment]
@M03ED Either you don’t understand what I’m asking, or I don’t understand what you’re talking about and I need an explanation. I want the Internet speed not to be divided between users, for this I need the user’s subscription to always have a server that has the least number of clients

**Comment by M03ED** [comment]
this feature can't be added to marzban or if we add it you need high configuration to make it full real time.
instead of adding this feature you can just use a load balancer

**Comment by Goosegit11** [comment]
but xray supports load balancing natively, wouldn't that be better than using third-party load balancer like Nginx? 

https://github.com/XTLS/Xray-core/pull/2999
