### ISSUE TITLE
Multiple port

### ISSUE THREAD

**Issue by 8zizek8** [Gozargah/Marzban#69]
I think it's a critical feature to be able to set up multiple standby ports for each inbound, as can be quickly done in a reverse proxy.
Also, the ability to share and update this port through the subscription link should be made.

**Comment by SaintShit** [comment]
@8zizek8 Yes, that's alright now on development. perhaps I merge it to dev to test it publicly.
by that you're gonna be able to set particular port for each host (entry), sni and request host. they all will be available on dashboard.

**Comment by SaintShit** [comment]
@8zizek8 perhaps I merge it to dev to test it publicly *tomorrow*. *
