### ISSUE TITLE
Add path to host settings

### ISSUE THREAD

**Issue by parhawm** [Gozargah/Marzban#690]
Currently it's not possible to specify a path in host settings.
That makes it hard using nginx as a proxy. honestly I don't see a way for clients to connect to multiple ports.

**Comment by M03ED** [comment]
path its not part of host setting , you should define it in core setting

**Comment by parhawm** [comment]
You should understand that the path for client is different than the path for core.
In some cases it is necessary to change it

Please reopen the issue

**Comment by M03ED** [comment]
Explain situation you need to change path with host

**Comment by parhawm** [comment]
As I mentioned I used nginx as a proxy; to capture all the traffic on port 443 and then redistribute to xray inbounds
the main motive being that behind a cdn that only passes 8443 and 443, to be able to use 3 inbounds that would be the best way

So I used the following nginx config suggested in README.md, under the section called manual install:
```
    # xray-core ws-path: /
    # client ws-path: /marzban/me/2087
    #
    # All traffic is proxed through port 443, and send to the xray port(2087, 2088 etc.).
    # The '/marzban' in location regex path can changed any characters by yourself.
    #
    # /${path}/${username}/${xray-port}
    location ~* /marzban/.+/(.+)$ {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:$1/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```
You could clearly see here that this solution requires the path nginx receives(e.g. "/marzban/user/8080") to be different than the one xray receives(here nginx passes "/").

And that makes setting path in host settings an important feature if not a crucial one.

**Comment by M03ED** [comment]
you just need to change it from core setting 
```json
"streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/marzban/user/8080"
        },
```
there is no different

**Comment by parhawm** [comment]
Nice trick but doesn't allow setting username dynamically
For some reasons it is useful to be included in http path e.g. limiting users based on ip, recording reverse proxy logs,...

Anyways I implemented it myself to use with a haproxy script.

**Comment by M03ED** [comment]
i test and its possible , no need to change host setting or anything 
just need to add format_map for path 
you path its gonna be like this in core setting 
```json
"path": [
                "/marzban/{username}/8080"
              ],
```
then it will generate with user username 
then you send data to this path "/marzban/{username}/8080"

**Comment by M03ED** [comment]
also you know user can bypass your ip limit with changing username in path to a random value , right ?

**Comment by parhawm** [comment]
> i test and its possible , no need to change host setting or anything just need to add format_map for path you path its gonna be like this in core setting
> 
> ```json
> "path": [
>                 "/marzban/{username}/8080"
>               ],
> ```
> 
> then it will generate with user username then you send data to this path "/marzban/{username}/8080"

I guess yours is a better solution.


> also you know user can bypass your ip limit with changing username in path to a random value , right ?

Not if you implement it correctly.

**Comment by M03ED** [comment]
> Not if you implement it correctly.

im curious how you wanna implement it, surely you need real time access to database and check each username after each connection probebly

**Comment by parhawm** [comment]
Not gonna spoil it. 
I'll share the config here after setting it up

**Comment by parhawm** [comment]
> i test and its possible , no need to change host setting or anything just need to add format_map for path you path its gonna be like this in core setting
> 
> ```json
> "path": [
>                 "/marzban/{username}/8080"
>               ],
> ```
> 
> then it will generate with user username then you send data to this path "/marzban/{username}/8080"

Just noticed this shouldn't work, since Xray doesn't run regex or anything on path. so it would be static.

**Comment by M03ED** [comment]
> Just noticed this shouldn't work, since Xray doesn't run regex or anything on path. so it would be static.
I think you didn't get it
We make path like that , then in share.py file we use format variable on path to use dynamic path for each user 
Than in nginx we use static path

**Comment by parhawm** [comment]
Oh I get it nice hack.
this is unnecessary then.
