### ISSUE TITLE
مشکل اساسی در اتصال نود ها و داون شدن پنل

### ISSUE THREAD

**Issue by ashkanmafi2** [Gozargah/Marzban#691]
با درود و احترام خدمت تمامی دولوپر های عزیز مرزبان ....

چند روز اخیر باید بصورت مرتب پنل رو هر چندساعت یکبار ریستارت  کنم وگرنه تمام کانفیگ ها یا بهتره بگم لینک های اشتراک قطع میشنوند.. 

طبق بررسی هایی با چند نفر از دوستان عزیز در تلگرام ( #ERROR و Not found  (  انجام دادیم متوجه شدیم که مشکل اصلی در اتصال نود ها هستش که گاها روی حالت connectimg  میروند و بعد از چند لحظه ایکس ری را ریستارت میکند .. که این عمل باعث اختلال بسیار زیادی در کارکرد منظم پنل و کانفیگ های کاربران ایجاد کرده است ... 

نسخه پنل 0.4.1 هست . 
بر روی میزبان وارپ  فعال است .. 
نسخه xray هم روی 1.8.4 هست . 
و دیتابیس  mysql هم هست...

**Comment by upgo7502** [comment]
توی نسخه 0.4.1 خیلی نسبت به نسخه قبلی کندی در پنل دیده میشه . مخصوصا اگر تعدا کاربرا بالای 600 نفر باشه
