### ISSUE TITLE
قابلیت های جدید در API

### ISSUE THREAD

**Issue by mahanhpn** [Gozargah/Marzban#693]
با عرض سلام 
تشکر میکنم بابت توسعه مرزبان 
چندین مورد جدید وجود داره که خیلی عالی میشه اگر به api اضافه بشه
۱- در قسمت api/system دیتا های incoming_bandwidth_speed و outgoing_bandwidth_speed شامل ترافیک نود ها هم بشه و ترافیک ورودی خروجی لحظه ای نود ها هم نمایش داده بشه . و یا در قسمت /api/node که مشخصات نود وجود داره این اطلاعات نمایش داده بشه
۲- مشخصات سرور نود به مثل مشخصات api/system نمایش داده بشه . برای مثال رم سی پی یو و ترافیک لحظه ای نمایش داده بشه
۳- امکان حذف و یا اضافه کردن یک اینباند برای تمام یوزر ها
۴- نمایش TCP Connection / UDP Connection های نود ها و سرور مستر
۵- امکان دریافت لیست و یا تعداد یوزر های انلاین / افلاین و یوزر هایی که تا به حال به سرور کانکت نشده اند (این فرایند با برنامه نویسی درحال حاضر امکان پذیر هست اما متاسفانه زمانی که کل یوزر ها از پنل درخواست بشه درصورتی که تعداد یوزر ها بالا باشه کند عمل میکنه)

**Comment by lilcheti** [comment]
number 3 is so important

**Comment by M03ED** [comment]
> number 3 is so important

available in telegram bot and [This Script](https://github.com/M03ED/Marzban_Inbound_Updater)
