### ISSUE TITLE
امکان ویرایش نام کاربری در آپدیت بعدی

### ISSUE THREAD

**Issue by hayousef68** [Gozargah/Marzban#694]
کاش می شد این قابلیت فعال باشه بدون اینکه لینک ساب تغیر کنه نام کاربری رو ویرایش کرد

میشه ظوری تنظیم کنین در اپدیت بعدی که لینک ساب بر اساس شماره بندی مخصوص خودش داخل دیتایس لینک بده که در صورت تغیر یوزرنیم اون عوض نشه

**Comment by M03ED** [comment]
در صورتی که چنین تغییری اعمال بشه تمام لینک های قبلی غیر فعال میشن پس خیر امکانش نیست
