### ISSUE TITLE
شروع تاریخ کاربر با اولین وصل شدن

### ISSUE THREAD

**Issue by hayousef68** [Gozargah/Marzban#695]
میشه این قابلیت هم اضافه کنین که تاریخ شروع اکانت کاربر از اولین کانکتش باشه تو پنل فقط به صورت عددی مثلا  30 روز رو وارد کنیم تا کاربر مثلا بعد از 5 روز اگه وصل شد از اون روز دوره اش شروع بشه

**Comment by M03ED** [comment]
قبل از باز کردن issue از تکراری نبودن مطمئن بشید 
همچنین این قابلیت هم اکنون در مرزبان دردسترس هست #618
