### ISSUE TITLE
راهنمایی در مورد شروع تاریخ کاربر با اولین وصل شدن 

### ISSUE THREAD

**Issue by hayousef68** [Gozargah/Marzban#696]
میشه راهنمایی کنین چجوری میشه اینو فعال کرد  

شروع تاریخ کاربر با اولین وصل شدن

**Comment by zapzocket** [comment]
مرزبان نداره

**Comment by ImMohammad20000** [comment]
> مرزبان نداره

داره ولی فعلا فقط از طریق api قابل انجامه

**Comment by rbsdotnet** [comment]
این قسمت چه جوری باید در api مقدا دهی بشه؟ روش کار به چه صورت هست

**Comment by erfjab** [comment]
> این قسمت چه جوری باید در api مقدا دهی بشه؟ روش کار به چه صورت هست

با این میشه ، ستاره یادت نره
https://github.com/Gozargah/Marzban/discussions/729

**Comment by erfjab** [comment]
> مرزبان نداره
با این میشه ، ستاره یادت نره

https://github.com/Gozargah/Marzban/discussions/729
