### ISSUE TITLE
the panel works with delays

### ISSUE THREAD

**Issue by yremac** [Gozargah/Marzban#697]
If there are more than 100 inbounds, setting them up in the drop-down menu takes much longer, loading after a click takes several seconds with a noticeable delay, a more powerful server did not solve the problem.

**Comment by M03ED** [comment]
its very normal thing , you have a 100 inbound and marzban should add users to every single one of them , marzban designed to have few inbound and use them for all users , if you need single inbound per user use other panels like x-ui

**Comment by M03ED** [comment]
I don't know what is drop down menu but marzban didn't designed for to much inbound, if you have same inbound with different port you can do that same thing with docker compose settings or adding multiple port for single inbound
