### ISSUE TITLE
باگ در اتصال نوها ( ارور مختلف پایتون )

### ISSUE THREAD

**Issue by MrCjxer** [Gozargah/Marzban#698]
سلام وقتتون بخیر

من روی دیتابیس SQLite که بودم ارورهای زیادی گرفتم
و دو رزو پیش یه سرور کلین اینستال کردم و از همون ابتدا بردم روی MySQL و مجدد تمام کاربرهارو دستی ایجاد کردم
( یعنی از روی دیتابیس SQLite قبلی دامپ و کپی نکردم )

اما همچنان ارور عجیبی روی هردو Node میگیرم که از اولین خط تا آخرین خط رو توی عکس زیر گذاشتم :

![Screenshot_20231215_030755](https://github.com/Gozargah/Marzban/assets/26128739/ca9ddb49-54bb-448f-a457-f4ee0963c111)

و تنظیمات هر دوتا Node هم به این صورت هستش :

![Screenshot_20231215_032645](https://github.com/Gozargah/Marzban/assets/26128739/1f4fe399-4740-4b2a-a75b-36f0cd3f6cb6)

ممنون میشم راهنمایی بفرمائید مشکل از چیه

**Comment by azirbugfixer** [comment]
ببینید سرتیفیکیت ها رو درست وارد کردید یا نه
