### ISSUE TITLE
XTLS+RPRX+VISION BUG

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#701]
درود من ویژن رو روشن میکنم روشن نمیشه و توی پورکسی ها اعمال نمیشه . در حالی ک همون کاربر در دیتابیس و پنل روشنه براش اما کانفیاش اعم از VLESS TCP / GRPC بدون ویژن میشه . روی پنل تازه هم تست کردم
![image](https://github.com/Gozargah/Marzban/assets/91155537/2349ac2c-5cf9-4f16-9155-baf2e1ae7ddc)

![Screenshot 2023-12-17 031442](https://github.com/Gozargah/Marzban/assets/91155537/c8d3e3ec-584a-4fa5-89c0-3b5f1b5f9524)

سکیوریتی هم ریلیتی هست در کانفیگ ها . در اپدیت های قبلی درست بود

**Comment by ImMohammad20000** [comment]
این flow به صورت اوتوماتیک فقط برای tcp reality اعمال میشه

**Comment by LonUp** [comment]
> این flow به صورت اوتوماتیک فقط برای tcp reality اعمال میشه

خب روی تیسیپی هم فلو رو ندارم و از توی پنل روشن میکنم اما روی کانفیگ های تیسیپی نیست .  و اینکه قبل اپدیت روی جی ار پیسی ریلیتی ها هم میشد و کار میکردن

**Comment by LonUp** [comment]
> فلو فقط روی TCP ساپورت میشه و نباید هدر داشته باشه باقی پروتکل ها از فلو پشتیبانی نمی کنند

میخواید ویدئو یا اسکرین شات بدم؟ دقیقا فلو رو روشن میکنم و یکی از کانفیگ هام ریلیتی تیسیپی بدون هدر هست و اون کانفیگ فلو توی کلاینت نمیاد. درحالی که توی پنل تیک خورده و فلو هم دستی روشن میکنم براش کار نمیکنه
