### ISSUE TITLE
Internet speed limit

### ISSUE THREAD

**Issue by Genry777Morgan** [Gozargah/Marzban#703]
There are many different IP limiters that limit the user's number of connections with one key, but they have too many disadvantages and problems to use them.
But it would be great if it were possible to limit the user’s speed, so that there would be no desire to share this speed with his friend.
For example, the allowed speed for each user is 100 Mb/s, if the user uses his key alone, this speed will be enough for him to use, but if he wants to share the key, his speed will be divided between him and his neighbor (50 Mb/s), which is already too slow so he won't want to share the key with him

**Comment by parhawm** [comment]
There were attempts to do this in xray-core, I don't think they were ever merged though.
obviously not a job for Marzban.

**Comment by erwamohammed** [comment]
> There are many different IP limiters that limit the user's number of connections with one key, but they have too many disadvantages and problems to use them.
> But it would be great if it were possible to limit the user’s speed, so that there would be no desire to share this speed with his friend.
> For example, the allowed speed for each user is 100 Mb/s, if the user uses his key alone, this speed will be enough for him to use, but if he wants to share the key, his speed will be divided between him and his neighbor (50 Mb/s), which is already too slow so he won't want to share the key with him
