### ISSUE TITLE
api method post users doesn't check expire time validity

### ISSUE THREAD

**Issue by parhawm** [Gozargah/Marzban#707]
to reproduce just try creating a user where expire time is too large.
database functions doesn't work after that and you'd have to recreate the database or manually modify it. 
this is also a security vulnerability, since an admin without sudo rights could practically crash the db functions.

**Comment by M03ED** [comment]
its because marzban use timestamp for now , it will be change in next update 
check #670

**Comment by parhawm** [comment]
Great job. this causes problems with existing api users though.

I found another minor issue btw, it's worth to mention that xray has updated their proto and some fields have been removed. e.g. proto/proxy/trojan/config.proto doesn't have account.id anymore,
it's used in xray_api.types.account. that could cause problems next time you're updating.
