### ISSUE TITLE
مشکل محاسبه حجم اشتباه 

### ISSUE THREAD

**Issue by theonewhopassed** [Gozargah/Marzban#713]
با سلام
وقتی یوزر به نود از طریق کلودفلر وصل میشه سرور حجم رو چند برابر مصرف اصلی محاسبه میکنه ولی حالت مستقیم اوکی هست
 
مخصوصا وقتی اسپید تست گرفته میشه

**Comment by theonewhopassed** [comment]
طبق توضیح یکی از دوستان عزیز داخل چنل تلگرام بابت این مساله داستان به این صورت هست که اگر از طریق سرور خارجی تست انجام بشه که محدودیتی در شبکه وجود ندارد کاملا درست محاسبه می شود 
این پست رو هم برای دوستانی ممکن هست به این مشکل بخورن میزارم که باگی در سیستم نیست

**Comment by parhawm** [comment]
یک نفر دیگه این مشکلو داشت با آپدیت xray از 1.8.4 به 1.8.6 حل شد
