### ISSUE TITLE
گروه بندی یوزر ها

### ISSUE THREAD

**Issue by hoorad1** [Gozargah/Marzban#716]
سلام وقت بخیر
ممنون از پنل خوبی که رایگان در اختیار همه قرار گذاشتین

فقط کاش قابلیت گروه بندی یوزر ها رو اضافه میکردین و مثل پنل xmplus هر نود رو اول تعیین کنیم که برای کدوم گروه باشه و نیاز به اضافه کردن دستی نباشه ، اگر این قابلیت باشه واقعا عالی میشه

**Comment by realartin** [comment]
به نظرم بسیار ایده عالیه و خیلی میتونه مفید باشه وقتی هر گروه مثلا 50 نفره رو بتونیم تعین کنیم به نود های خاص و کانفیگ های خاص وصل بشوند و بقیه رو گروه بندی کنیم به همین ترتیب ترافیک هر نود زیاد بالا نمیره و احتمال دیتکت شدن و فیلتر شدن کمتر میشه و اگر مشتری پیش بیاد میشه با تغیر نود و اختصاص دادن نود و کانفیگ هایی که از قبل اماده کرده بودیم سریع میتونیم جایگزین کنیم و مشکل کاربر هارو حل کنیم به نظرم این ایده خیلی خوبیه برای کم کردن ریسک دیتکت شدن

**Comment by hoorad1** [comment]
اگر برای سرور گروهی تعیین کنیم و اون گروه رو هم برای یوزر ها اعمال کنیم فوق العاده میشه ، یعنی به هر یوزر ، گروه خاصی تعیین کنیم

**Comment by parhawm** [comment]
من این مشکل رو با تغییر ساختار دیتابیس و اضافه کردن "service" حل میکنم، تو ساختار جدید هر سرویس متشکل از تعدادی اینبانده و هر اینباند مربوط به یه نود خاصه.
یعنی میتونید با اضافه کردن یه سرویس و اضافه کردن چند اینباند به اون از هر نودی که میخواید و سپس اضافه کردن سرویس ها به کاربر، هر کاربر رو با دقت تفکیک کنید.
به عبارتی میتونید با یک سرور مرزبان همزمان نود هایی با کانکشن مستقیم، پشت cdn و تونل داشته باشید و کاربر ها فقط دسترسی وصل شدن به اینباند های سرویس هاشون رو داشته باشن.

اگر کسی راه حل بهتری داره یا مشکل مربوطی داره که با این ساختار حل نمیشه لطفا همینجا اعلام کنه.

**Comment by realartin** [comment]
> من این مشکل رو با تغییر ساختار دیتابیس و اضافه کردن "service" حل میکنم، تو ساختار جدید هر سرویس متشکل از تعدادی اینبانده و هر اینباند مربوط به یه نود خاصه.
> یعنی میتونید با اضافه کردن یه سرویس و اضافه کردن چند اینباند به اون از هر نودی که میخواید و سپس اضافه کردن سرویس ها به کاربر، هر کاربر رو با دقت تفکیک کنید.
> به عبارتی میتونید با یک سرور مرزبان همزمان نود هایی با کانکشن مستقیم، پشت cdn و تونل داشته باشید و کاربر ها فقط دسترسی وصل شدن به اینباند های سرویس هاشون رو داشته باشن.
> دقت کنید برخلاف ساختاری که اشاره کردید(گروه) اینجا قابلیت اضافه کردن یک کاربر به چند سرویس هم وجود داره. 
> 
> اگر کسی راه حل بهتری داره یا مشکل مربوطی داره که با این ساختار حل نمیشه لطفا همینجا اعلام کنه.

بسیار عالی ❤️❤️

**Comment by hoorad1** [comment]
> من این مشکل رو با تغییر ساختار دیتابیس و اضافه کردن "service" حل میکنم، تو ساختار جدید هر سرویس متشکل از تعدادی اینبانده و هر اینباند مربوط به یه نود خاصه. یعنی میتونید با اضافه کردن یه سرویس و اضافه کردن چند اینباند به اون از هر نودی که میخواید و سپس اضافه کردن سرویس ها به کاربر، هر کاربر رو با دقت تفکیک کنید. به عبارتی میتونید با یک سرور مرزبان همزمان نود هایی با کانکشن مستقیم، پشت cdn و تونل داشته باشید و کاربر ها فقط دسترسی وصل شدن به اینباند های سرویس هاشون رو داشته باشن. دقت کنید برخلاف ساختاری که اشاره کردید(گروه) اینجا قابلیت اضافه کردن یک کاربر به چند سرویس هم وجود داره.
> 
> اگر کسی راه حل بهتری داره یا مشکل مربوطی داره که با این ساختار حل نمیشه لطفا همینجا اعلام کنه.

تقریبا چیری که ذهن منم هست اینه ، یعنی چندین سرویس بشه و هر سرویس بشه به تعداد مشخصی کاربر تعلق بگیره و گروه بندی بشه ، حالا اگر خود مرزبان اینو اضافه کنه خیلی بهتر میشه

**Comment by LonUp** [comment]
> سلام وقت بخیر ممنون از پنل خوبی که رایگان در اختیار همه قرار گذاشتین
> 
> فقط کاش قابلیت گروه بندی یوزر ها رو اضافه میکردین و مثل پنل xmplus هر نود رو اول تعیین کنیم که برای کدوم گروه باشه و نیاز به اضافه کردن دستی نباشه ، اگر این قابلیت باشه واقعا عالی میشه

بسیار موافقم
من وقتی میخوام یه اینباند به کاربرام اضافه کنم و اما یک سری کاربر دارم که نمیخوام اون اینباند براشون اضافه شه یجورایی مجبورم یه پنل دیگه بزنم برای اینکار که کنترل خوبی روی کاربرام داشته باشم و  اما با این قابلیت میشه همشو روی یه پنل بزرگ مدیریت کرد

**Comment by realartin** [comment]
> این فیچر بیشتر به درد فروشندگان میخوره که در حال حاضر با سیاست های توسعه مرزبان همخوانی نداره. آینده دوباره راجبش صحبت میکنیم. با تشکر از پیشنهاد شما

گل من به مرزنشین اضافه اش کردیم (:

**Comment by erfjab** [comment]
> > این فیچر بیشتر به درد فروشندگان میخوره که در حال حاضر با سیاست های توسعه مرزبان همخوانی نداره. آینده دوباره راجبش صحبت میکنیم. با تشکر از پیشنهاد شما
> 
> گل من به مرزنشین اضافه اش کردیم (:

خوشحال شدم که مشکل‌تون حل شده. موفق باشید عزیز.
