### ISSUE TITLE
راه اندازی پراکسی برای تانل

### ISSUE THREAD

**Issue by xxamr** [Gozargah/Marzban#718]
سلام
با توجه به اینکه موقع تانل زدن دیتاهای اصلی (مثل ای پی و پورت و ..)  به سرورر منتقل نمیشن و لاگی روی سرور نمیشینه. اگر فرایند فعال سازی پراکسی روی Nginx‌ سرور مقصد (سرور خارج کشور برای وی پی ان) را هم پیاده سازی کنید و آموزش اش را قرار بدید عالی میشه/
ممنونم

**Comment by M03ED** [comment]
اینگونه اموزش ها موارد فرعی هستن و هر کسی بسته به نیازش کانفیگ متفاوتی داره 
شما باید با توجه به نیاز خودتون برید اموزش های مورد نظر تون رو ببینید و انجام بدید
