### ISSUE TITLE
dashboard cpu usage too high using dev branch

### ISSUE THREAD

**Issue by parhawm** [Gozargah/Marzban#721]
try switching to dev branch and rebuilding the dashboard,
cpu usage is too high, It's even worse after opening xray config settings or other dialogs.

**Comment by parhawm** [comment]
I have this problem also on the main branch, 
everything is fine when there are no users though.

firefox uses 100% cpu, any help is appreciated.

**Comment by M03ED** [comment]
did you test it on another vps ?

**Comment by parhawm** [comment]
yes I've tested on 2 vpses and my own desktop.
both chromium and firefox have this problem, I'm using their latest version on linux.

**Comment by erfjab** [comment]
این ایشو به خاطر در اختیار نزاشتن اطلاعات بیشتر بسته میشود و در صورت داشتن مشکل لطفا ایشوی جدید باز کنید. با تشکر.
