### ISSUE TITLE
تانل در  نود ها

### ISSUE THREAD

**Issue by sourenprs** [Gozargah/Marzban#723]
ممنون از همه زحمت های که میکشید آیا راهی هست بشه سرور های نود رو تانل کرد ؟

**Comment by M03ED** [comment]
تانل ربطی به پنل نداره و یه چیز کاملا جداگانه هست ، قبلا هم تو [discussions](https://github.com/Gozargah/Marzban/discussions) به طور مفصل راجع بهش بحث شده
