### ISSUE TITLE
تک پورت شدن پنل و کانفیگ ها

### ISSUE THREAD

**Issue by rbsdotnet** [Gozargah/Marzban#725]
درود  برای اینکه تمام کانفیگ ها روی پورت 443 باشه و پنل هم روی پورت 443 باشه باید از چه روشی این کار رو انجام بدم؟
من از خرین نسخه دارم استفاده میکنم
ممنون میشم راهنمایی کنید

**Comment by M03ED** [comment]
https://gozargah.github.io/marzban/examples/all-on-one-port
