### ISSUE TITLE
vmess http tcp header camuflage

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#726]
vmess http tcp header camuflage 

درست کار نمیکنه مقادیر رو عین داک ایکس ری وارد میکنم ولی وقتی از ادرس و پورت مدنظر به همراه مسیر صحیح کرل میگیرم مقدار هایی که ست کردم رو برنمیگردونه

**Comment by realartin** [comment]
مثال :

من برای vmess تعین کرده بودم مقادیری که سایت اصلی که دارم ازش به عنوان camouflage استفاده میکنم رو برگردونه ولی درست کار نمیکنه

ببین وقتی از دامنه

tabriz1.irancell.ir:8080
کرل میگیریم

این رو برمیگردونه :

`HTTP/1.1 200 OK
Date: Mon, 01 Jan 2024 05:50:25 GMT
Connection: Keep-Alive
Content-Type: text/html
Content-Length: 109

<html><head><title>OoklaServer</title></head><body><h1>OoklaServer</h1><p>It worked!<br /></p></body></html>
`

**Comment by realartin** [comment]
خب حالا من میام و این اینباند رو اینطور میسازم :

`  {
      "tag": "vmess-tcp-header",
      "port": 8080,
      "protocol": "vmess",
      "settings": {
        "clients": []
      },
      "streamSettings": {
        "sockopt": {
          "tcpFastOpen": true,
          "tcpKeepAliveInterval": 30,
          "tcpcongestion": "bbr"
        },
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "method": "GET",
              "path": [
                "/download",
                "/upload"
              ],
              "headers": {
                "Host": [
                  "tabriz1.irancell.ir"
                ],
                "User-Agent": [
                  "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0",
                  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1",
                  "Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; RM-1152) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.15254"
                ]
              }
            },
            "response": {
              "Connection": [
                "Keep-Alive"
              ],
              "Content-Length": [
                "109"
              ],
              "Content-Type": [
                "text/html"
              ]
            },
            "reason": "OK",
            "status": "200",
            "version": "1.1"
          }
        },
        "security": "none"
      }
    },`

**Comment by realartin** [comment]
این کانفیگ کار میکنه ولی بخش camufalge آن درست کار نمیکند چون وقتی کرل میگیرم از سرور خودم 
curl -i ip:8080/download

مقدار صحیح را که تعین کردم بر نمیگرداند و این یعنی درست کار نمیکند و زود تر دیتکت می شود !
ممنون میشوم بررسی کنید با تشکر

**Comment by SaintShit** [comment]
سلام
این بخش رو مرزبان کنترل نمیکنه، مرزبان این کانفیگ رو مستقیم به هسته میده و هسته رو اجرا میکنه.
به هرحال چیزی که شما گفتین رو با خود هسته xray تست کردم.
``` json
{
    "log": {
        "loglevel": "debug"
    },
    "inbounds": [
        {
            "tag": "vmess-tcp-header",
            "port": 8080,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "0c2cd0d5-b8a9-45ca-a57f-6e03ad231da2"
                    }
                ]
            },
            "streamSettings": {
                "sockopt": {
                    "tcpFastOpen": true,
                    "tcpKeepAliveInterval": 30,
                    "tcpcongestion": "bbr"
                },
                "network": "tcp",
                "tcpSettings": {
                    "header": {
                        "type": "http",
                        "request": {
                            "method": "GET",
                            "path": [
                                "/download",
                                "/upload"
                            ],
                            "headers": {
                                "Host": [
                                    "tabriz1.irancell.ir"
                                ],
                                "User-Agent": [
                                    "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0",
                                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
                                    "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1",
                                    "Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; RM-1152) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.15254"
                                ]
                            }
                        },
                        "response": {
                            "Connection": [
                                "Keep-Alive"
                            ],
                            "Content-Length": [
                                "109"
                            ],
                            "Content-Type": [
                                "text/html"
                            ],
                            "Date": [],
                            "body": "<html><head><title>OoklaServer</title></head><body><h1>OoklaServer</h1><p>It worked!<br /></p></body></html>"
                        }
                    },
                    "reason": "OK",
                    "status": "200",
                    "version": "1.1"
                }
            },
            "security": "none"
        }
    ],
    "outbounds": [
        {
            "tag": "direct",
            "protocol": "freedom",
            "streamSettings": {
                "sockopt": {
                    "tcpFastOpen": false
                }
            }
        }
    ]
}
```

این کانفیگ رو با xray اجرا میکنم. 

`xray run -c config.json`

لینک پروکسی:

`vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiIwIiwiaG9zdCI6InRhYnJpejEuaXJhbmNlbGwuaXIiLCJpZCI6IjBjMmNkMGQ1LWI4YTktNDVjYS1hNTdmLTZlMDNhZDIzMWRhMiIsIm5ldCI6InRjcCIsInBhdGgiOiIvdXBsb2FkIiwicG9ydCI6IjgwODAiLCJwcyI6IlRFU1QiLCJzY3kiOiJhdXRvIiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6Imh0dHAiLCJ2IjoiMiJ9`


نتیجه برای من هم مشابه شماست. سرور (xray) نتیجه‌ای بهم بر نمیگردونه وقتی curl میکنم.

**Comment by realartin** [comment]
درود با تشکر از مشاهده و بررسی شما ، باید ی فکری کنیم چطور میتونیم فیکس اش کنیم حالا که معلوم شد مشگل از هسته هست ، صدای من رو rprx نمیشنوه ولی شاید شما دوستان گزارش کنید بررسی کنه یا نحوه استفاده رو بهتر کنه ❤️🙏

**Comment by parhawm** [comment]
نمیبینم چطور مشکل از هستست.

**Comment by realartin** [comment]
خب مهندس چطور با انجین ایکس یا ... زوی همین پورت مدنظر و همین path مدنظر میتونیم همزمان با ایکس ری بیاییم و ریسپانس مدنظر رو نشون بدیم نمیشه

**Comment by realartin** [comment]
> نمیبینم چطور مشکل از هستست.
> https://xtls.github.io/en/config/transports/tcp.html#httpheaderobject
> اینجا نوشته این آبجکت برای مبهم کردن ریکوسته. و واضحه توی کانفیگ بخشی از تنظیمات استریمینگه
> ارتباطی به ساخت ریسپانس کمفلاج هم نداره
> برای اون باید از nginx یا در کنار vless و trojan از fallback استفاده کنید

و چون کانفیگ tls نداره نمیشه فالبک زد درسته؟

**Comment by M03ED** [comment]
> خب مهندس چطور با انجین ایکس یا ... روی همین پورت مدنظر و همین path مدنظر میتونیم همزمان با ایکس ری بیاییم و ریسپانس مدنظر رو نشون بدیم نمیشه

میتونی پورت کانفیگ رو یه چیز دیگه بزاری بعد با nginx پورت اصلی رو بگیری و بفرستی به پورت کانفیگ 
پورتی هم که به دست یوزر میرسه رو از هاست میشه تغییر داد

**Comment by parhawm** [comment]
> > نمیبینم چطور مشکل از هستست.
> > https://xtls.github.io/en/config/transports/tcp.html#httpheaderobject
> > اینجا نوشته این آبجکت برای مبهم کردن ریکوسته. و واضحه توی کانفیگ بخشی از تنظیمات استریمینگه
> > ارتباطی به ساخت ریسپانس کمفلاج هم نداره
> > برای اون باید از nginx یا در کنار vless و trojan از fallback استفاده کنید
> 
> و چون کانفیگ tls نداره نمیشه فالبک زد درسته؟

آره و چون vmess اصلا فالبک نداره

> خب مهندس چطور با انجین ایکس یا ... روی همین پورت مدنظر و همین path مدنظر میتونیم همزمان با ایکس ری بیاییم و ریسپانس مدنظر رو نشون بدیم نمیشه


همونطور که mo3ed گفت باید با nginx یا haproxy یا envoy و... پروکسیش کنی. راه دیگه‌ای نداره.

**Comment by realartin** [comment]
میدونم میشه با هاپروکسی و انجین ایکس رو یک پورت چند تا برنامه لیسن کنن ولی سوالم اینجاست که من میخوام 
/download
/upload
یک فایل html هم نشون بدم و تو config.json هم از این path برای vmess استفاده کردم این رو چه کنم

**Comment by realartin** [comment]
> > خب مهندس چطور با انجین ایکس یا ... روی همین پورت مدنظر و همین path مدنظر میتونیم همزمان با ایکس ری بیاییم و ریسپانس مدنظر رو نشون بدیم نمیشه
> 
> میتونی پورت کانفیگ رو یه چیز دیگه بزاری بعد با nginx پورت اصلی رو بگیری و بفرستی به پورت کانفیگ 
> پورتی هم که به دست یوزر میرسه رو از هاست میشه تغییر داد

یعنی پورت ۸۰۸۰ رو بزارم برای پروکسی میتونم رو همین پورت ی وب سرور هم بیارم بالا ؟ 
پورت و path یکسان بین وب سرور و پروکسی؟!
