### ISSUE TITLE
مشکل در اتصل به mysql در نسخه 0.4.2

### ISSUE THREAD

**Issue by azirbugfixer** [Gozargah/Marzban#727]
در نسخه 0.4.2 اتصال به mysql به مشکل برمیخوره. به این صورت که فقط تعداد کاربرها نمایش داده میشن و ترافیک کلی سرور. امکان ساخت یوزر هم وجود داره اما هیچ اطلاعات دیگه ای نشون داده نمیشه. در لاگ مرزبان هم Operational Error نمایش داده میشه

**Comment by SaintShit** [comment]
@azirbugfixer لاگ هاتون رو ارسال کنید

**Comment by oooookeyyyyy** [comment]
منم امروز به همین مشکل خوردم

**Comment by M03ED** [comment]
> منم امروز به همین مشکل خوردم

لاگ تون رو ارسال کنید

**Comment by oooookeyyyyy** [comment]
> > منم امروز به همین مشکل خوردم
> 
> لاگ تون رو ارسال کنید

توی قسمت هاست ستینگ بخش {SERVER-IP} رو تغییر داده بودم از اون موقع لود نمیشد الان شک کردم به خاطر اون باشه برگردوندم به حالت اولیه درست شد

**Comment by M03ED** [comment]
> توی قسمت هاست ستینگ بخش {SERVER-IP} رو تغییر داده بودم از اون موقع لود نمیشد الان شک کردم به خاطر اون باشه برگردوندم به حالت اولیه درست شد

این دلیل مشکل خوردن دیتابیس نیست 
یک بار دیگه همون تغییر رو انجام بدید و از ارور اسکرین شات بگیرید

**Comment by azirbugfixer** [comment]
اینو قبلا شات گرفتم
<img width="875" alt="Screenshot 1402-10-13 at 2 13 33 at night" src="https://github.com/Gozargah/Marzban/assets/149825707/ab36d1dc-a6ab-4c2b-b3b7-33b8139be8b1">

**Comment by M03ED** [comment]
> اینو قبلا شات گرفتم <img alt="Screenshot 1402-10-13 at 2 13 33 at night" width="875" src="https://private-user-images.githubusercontent.com/149825707/294708999-ab36d1dc-a6ab-4c2b-b3b7-33b8139be8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjY0OTQsIm5iZiI6MTcwNDU2NjE5NCwicGF0aCI6Ii8xNDk4MjU3MDcvMjk0NzA4OTk5LWFiMzZkMWRjLWE2YWItNGMyYi1iM2I3LTMzYjgxMzliZThiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxODM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTc5MmE3YTZmYjRjOGY2YTQ5ZDU2OGZiNTRhM2ZmMzNlOTlhNThlOTZjOTNjMmY3ZGZjOWUyZWZkMzdmMjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L6KJt1QV2tIvTkKimoR_TKkMKYFnv5E96CT5zjx5P6I">

دیتابیس اپدیت نشده 
صرفا یک بار down و up نیاز داره

**Comment by azirbugfixer** [comment]
> > اینو قبلا شات گرفتم <img alt="Screenshot 1402-10-13 at 2 13 33 at night" width="875" src="https://private-user-images.githubusercontent.com/149825707/294708999-ab36d1dc-a6ab-4c2b-b3b7-33b8139be8b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjY0OTQsIm5iZiI6MTcwNDU2NjE5NCwicGF0aCI6Ii8xNDk4MjU3MDcvMjk0NzA4OTk5LWFiMzZkMWRjLWE2YWItNGMyYi1iM2I3LTMzYjgxMzliZThiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxODM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTc5MmE3YTZmYjRjOGY2YTQ5ZDU2OGZiNTRhM2ZmMzNlOTlhNThlOTZjOTNjMmY3ZGZjOWUyZWZkMzdmMjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L6KJt1QV2tIvTkKimoR_TKkMKYFnv5E96CT5zjx5P6I">
> 
> دیتابیس اپدیت نشده صرفا یک بار down و up نیاز داره

اگه منظورتون دستور marzban stop و marzban start هست که انجام دادم. درست نشد

**Comment by M03ED** [comment]
> اگه منظورتون دستور marzban stop و marzban start هست که انجام دادم. درست نشد

دستور marzban start و marzban stop نداری 
باید از marzban down و marzban up استفاده کنید

**Comment by azirbugfixer** [comment]
> > اگه منظورتون دستور marzban stop و marzban start هست که انجام دادم. درست نشد
> 
> دستور marzban start و marzban stop نداریم باید از marzban down و marzban up استفاده کنید

ببخشید... بله همون انجام دادم. درست نشد

**Comment by M03ED** [comment]
> ببخشید... بله همون انجام دادم. درست نشد

اگر بعد down و up دیتابیس اپدیت نمیشه باید دستی وارد کانتینر بشید و خودتون کامند رو به صورت دستی وارد کنید

**Comment by azirbugfixer** [comment]
> > ببخشید... بله همون انجام دادم. درست نشد
> 
> اگر بعد down و up دیتابیس اپدیت نمیشه باید دستی وارد کانتینر بشید و خودتون کامند رو به صورت دستی وارد کنید

کانتینر mySql؟

**Comment by M03ED** [comment]
> > > ببخشید... بله همون انجام دادم. درست نشد
> > 
> > 
> > اگر بعد down و up دیتابیس اپدیت نمیشه باید دستی وارد کانتینر بشید و خودتون کامند رو به صورت دستی وارد کنید
> 
> کانتینر mySql؟

مرزبان

**Comment by azirbugfixer** [comment]
> > > > ببخشید... بله همون انجام دادم. درست نشد
> > > 
> > > 
> > > اگر بعد down و up دیتابیس اپدیت نمیشه باید دستی وارد کانتینر بشید و خودتون کامند رو به صورت دستی وارد کنید
> > 
> > 
> > کانتینر mySql؟
> 
> مرزبان

متاسفانه با وارد کردن دستی دستور هم مشکل برطرف نشد

**Comment by M03ED** [comment]
> متاسفانه با وارد کردن دستی دستور هم مشکل برطرف نشد

چه دستوری وارد کردید و چه اروری گرفتید ؟

**Comment by azirbugfixer** [comment]
> > متاسفانه با وارد کردن دستی دستور هم مشکل برطرف نشد
> 
> چه دستوری وارد کردید و چه اروری گرفتید ؟

در پوشه /opt/marzban
docker compose down
docker compose up -d

همون خطایی که در اسکرین شات بود

**Comment by M03ED** [comment]
> > > متاسفانه با وارد کردن دستی دستور هم مشکل برطرف نشد
> > 
> > 
> > چه دستوری وارد کردید و چه اروری گرفتید ؟
> 
> در پوشه /opt/marzban docker compose down docker compose up -d
> 
> همون خطایی که در اسکرین شات بود

این دستور وارد کانتینر نمیشه و فقط خاموش روشن انجام میده
باید وارد پوشه مرزبان بشید و بهد دستور `docker compose exec marzban bash` رو وارد کنید 
دقت کنید که مرزبان باید فعال باشه
بعد دستور `alembic upgrade head` رو استفاده می کنید که برای اپدیت کردن دیتابیس هست 
ببینید چه اروری می گیرید

**Comment by azirbugfixer** [comment]
> > > > متاسفانه با وارد کردن دستی دستور هم مشکل برطرف نشد
> > > 
> > > 
> > > چه دستوری وارد کردید و چه اروری گرفتید ؟
> > 
> > 
> > در پوشه /opt/marzban docker compose down docker compose up -d
> > همون خطایی که در اسکرین شات بود
> 
> این دستور وارد کانتینر نمیشه و فقط خاموش روشن انجام میده باید وارد پوشه مرزبان بشید و بهد دستور `docker compose exec marzban bash` رو وارد کنید دقت کنید که مرزبان باید فعال باشه بعد دستور `alembic upgrade head` رو استفاده می کنید که برای اپدیت کردن دیتابیس هست ببینید چه اروری می گیرید

```
root@Marzban:/code# alembic upgrade head
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ERROR [alembic.util.messaging] Requested revision e56f1c781e46 overlaps with other requested revisions fc01b1520e72
  FAILED: Requested revision e56f1c781e46 overlaps with other requested revisions
  fc01b1520e72
```

**Comment by M03ED** [comment]
از طریق phpmyadmin وارد دیتابیس بشید 
یه تیبل alembic وجود داره و یه ورژن داخلش درج شده 
اون رو ارسال کنید

**Comment by azirbugfixer** [comment]
> از طریق phpmyadmin وارد دیتابیس بشید یه تیبل alembic وجود داره و یه ورژن داخلش درج شده اون رو ارسال کنید
دو تا row داره
e56f1c781e46
fc01b1520e72

**Comment by M03ED** [comment]
خب پس مشکل دقیقاً از همینه 
باید چک کنید ببینید دیتابیس تون روی کدوم ورژن هست و اون یکی رو پاک کنید

**Comment by azirbugfixer** [comment]
> خب پس مشکل دقیقاً از همینه باید چک کنید ببینید دیتابیس تون روی کدوم ورژن هست و اون یکی رو پاک کنید

ممنون از راهنمایی شما
از کجا میتونم این alembic version رو پیدا کنم؟

**Comment by M03ED** [comment]
اگر آشنایی ندارید خودتون انجام ندید بهتره 
اطلاعات سرور تون رو بفرستید خودم فردا براتون انجام میدم 
T.me/mosed3

**Comment by azirbugfixer** [comment]
> اگر آشنایی ندارید خودتون انجام ندید بهتره اطلاعات سرور تون رو بفرستید خودم فردا براتون انجام میدم T.me/mosed3

خیلی خیلی ممنون از راهنمایی شما

مشکل به این صورت برطرف شد:
برای پیدا کردن alembic version فعلی، بعد از دستور `docker compose exec marzban bash` ، دستور `alembic history --indicate-current` رو اجرا کردم. یه سری اطلاعات از نسخه ها نمایش داده میشه که کنار نسخه فعلی نوشته  `(head) (current)` . 
بعدش از phpmyadmin رکوردی که مشکل ساز شده بود رو حذف کردم. مثلا برای من `fc01b1520e72` بود.

در نهایت با `marzban update` مرزبان با موفقیت اپدیت شد.

**Comment by M03ED** [comment]
خیلی هم خوب 
اگر مشکل دیگه ای ندارید issue رو close کنید 
شب خوبی داشته باشید
