### ISSUE TITLE
مشکل اتصال در همراه اول

### ISSUE THREAD

**Issue by alihemmatnia** [Gozargah/Marzban#728]
سلام
روی اینترنت ایرانسل به خوبی کار میکند ولی توی همراه اول اصلا کار نمیکنه 
اگه کانفیگ خاصی میخاد لطفا بگید

**Comment by rbsdotnet** [comment]
درود 
از کانفیگ های زیر استفاده کن

VLESS WS TLS
VLESS GPRC TLS
TROJAN WS TLS

**Comment by alihemmatnia** [comment]
متشکرم ولی همچنان کار نکرد

**Comment by alihemmatnia** [comment]
> درود از کانفیگ های زیر استفاده کن
> 
> VLESS WS TLS VLESS GPRC TLS TROJAN WS TLS


متشکرم ولی همچنان کار نکرد

**Comment by rbsdotnet** [comment]
دامین تو حتما پشت پروکسی کلود فلر بزار

**Comment by lvlrf** [comment]
> درود از کانفیگ های زیر استفاده کن
> 
> VLESS WS TLS VLESS GPRC TLS TROJAN WS TLS

درود به 24 ساعت نمیرسه دامنم فیلتر میشه با اینکه زیر 100 گیگ دیتا میره روش

براش شما هم همینه؟ کار خاصی باید بکنم؟ با آی پی تمیز باید بزنم یا همون دامنه tls دار رو توی address بزنم؟

**Comment by rbsdotnet** [comment]
> > درود از کانفیگ های زیر استفاده کن
> > VLESS WS TLS VLESS GPRC TLS TROJAN WS TLS
> 
> درود به 24 ساعت نمیرسه دامنم فیلتر میشه با اینکه زیر 100 گیگ دیتا میره روش
> 
> براش شما هم همینه؟ کار خاصی باید بکنم؟ با آی پی تمیز باید بزنم یا همون دامنه tls دار رو توی address بزنم؟

من با پروکسی کلودفلر و haproxy پنل و کانفیگ هامو مدیریت میکنم 
برای هر کانفیگ یه ساب دامین و tls گرفتم
و اینکه از reality  استفاده نمی کنم

**Comment by lvlrf** [comment]
سپاس از جواب گوییت
1.
پس میگی پنل و کانفیگ ها رو بیارم روی پورت 443، درسته؟
2.
از آی پی سالم کلادفلر هم باید استفاده کنم؟
3.
address & sni & host رو متفاوت میزنی؟

**Comment by rbsdotnet** [comment]
> سپاس از جواب گوییت 1. پس میگی پنل و کانفیگ ها رو بیارم روی پورت 443، درسته؟ 2. از آی پی سالم کلادفلر هم باید استفاده کنم؟ 3. address & sni & host رو متفاوت میزنی؟

1: بله - این روش باعث امنیت بیشتر میشه.
2. از آی پی تمیز و یا استفاده از domian های تمیز
3: زیاد این بخش مهم نیست چون من هم یکی و هم متفاوت استفاده میکنم

از همه مهمتر استفاده از پروکسی هست همچنین میتونی از warp هم استفاده کنی

**Comment by rbsdotnet** [comment]
درود

این تظیمات Xray

[xray.conf.txt](https://github.com/Gozargah/Marzban/files/13848708/xray.conf.txt)

این تنظیمات HAProxy
[haproxy.txt](https://github.com/Gozargah/Marzban/files/13848696/haproxy.txt)


خدمت شما دوست عزیز

**Comment by lvlrf** [comment]
دستت دردنکنه لطف کردی

من چون توی یک سری از کانفیگ هام از wildcard استفاده میکردم دوست داشتم با فالبک راه بندازم چون راههکار دیگه ندارم اما ممنون ازت






> درود
> 
> این تظیمات Xray [xray.conf.txt](https://github.com/Gozargah/Marzban/files/13848708/xray.conf.txt)
> 
> این تنظیمات HAProxy [haproxy.txt](https://github.com/Gozargah/Marzban/files/13848696/haproxy.txt)
> 
> برای تمام دامنه ها حتما certificate گرفته شود و سپس پروکسی دامین ها فعال شود
> 
> خدمت شما دوست عزیز
