### ISSUE TITLE
انتخاب هاست و کانکشن مجزا برای هر کاربر

### ISSUE THREAD

**Issue by Lordrichard23** [Gozargah/Marzban#730]
سلام 
خسته نباشید میگم خدمت دولوپرهای پنل خوب مرزبان

۲ تا پیشنهاد دارم
 اول اینکه اگر ممکن هست همینطور که امکان انتخاب پروتکل برای هر کاربر وجود داره ، انتخاب هاست های زیر مجموعه هر پروتکل هم امکان پذیر باشه
یکی از مهم ترین مزیت های این مسئله در شرایط فعلی این هست که برای مثال من یک پروتکل vless + ws + tls دارم که روی اون از قسمت هاست ۱۰ تا کانکشن با sni مختلف ایجاد کردم ، با امکانات فعلی پنل وقتی این پروتکل انتخاب میشه کل این هاست ها یا کانکشن ها برای کاربر اتصال میشه و کاربرها هم معمولا نهایتا به اولین یا دومین هاست وصل میشن و معمولا خیلی کم پیش میاد به لینک های آخر لیست متصل بشن در نتیجه کل ترافیک میفته روی یکی دوتا sni و سریع فیلتر میشن

اما اگر بشه انتخاب کرد مثلا من انتخاب می‌کنم که کاربر x از این اینباند فقط هاست شماره یک رو در یافت کنه با لینک ساب و کاربر y فقط هاست شماره ۱۰ رو ، درواقع یجورایی بهتر میشه ترافیک رو روی sni ها مختلف پخش کرد .

پیشنهاد دوم که اولویت کمتری داره،اگر امکان داره قابلیت انتخاب ساعت انقضا هم به کانفیگ افزوده بشه که مثلا بتونیم تعیین کنیم کاربر x در تاریخ ۲۰ دی ماه و ساعت مثلا ۱۵ اکانتش به اتمام برسه

با تشکر

**Comment by M03ED** [comment]
> اما اگر بشه انتخاب کرد مثلا من انتخاب می‌کنم که کاربر x از این اینباند فقط هاست شماره یک رو در یافت کنه با لینک ساب و کاربر y فقط هاست شماره ۱۰ رو ، درواقع یجورایی بهتر میشه ترافیک رو روی sni ها مختلف پخش کرد .
> 


برای پخش کردن sni میتونید از ساب دامین با * استفاده کنید که ساب رندوم ساخته بشه 
![Screenshot 2024-01-05 155436](https://github.com/Gozargah/Marzban/assets/50927468/fed896a6-0cec-4977-86fd-3d7923ff318b)

**Comment by Lordrichard23** [comment]
> > اما اگر بشه انتخاب کرد مثلا من انتخاب می‌کنم که کاربر x از این اینباند فقط هاست شماره یک رو در یافت کنه با لینک ساب و کاربر y فقط هاست شماره ۱۰ رو ، درواقع یجورایی بهتر میشه ترافیک رو روی sni ها مختلف پخش کرد .
> 
> برای پخش کردن sni میتونید از ساب دامین با * استفاده کنید که ساب رندوم ساخته بشه ![Screenshot 2024-01-05 155436](https://private-user-images.githubusercontent.com/50927468/294487053-fed896a6-0cec-4977-86fd-3d7923ff318b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NTc5ODksIm5iZiI6MTcwNDQ1NzY4OSwicGF0aCI6Ii81MDkyNzQ2OC8yOTQ0ODcwNTMtZmVkODk2YTYtMGNlYy00OTc3LTg2ZmQtM2Q3OTIzZmYzMThiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDEyMjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MTE5MzZmOWIxNDUyMDE0NmUyYzBlN2I5OGU1ZTUwOWM5MDg4YmRhNTBjN2QyZGZmNmI1MGYxZjRhZGU2ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HIWhkZFK7tfVIEycmLp-seK8cMXmPTJeuTB5K_cxcKU)

آها یعنی اگر من در قسمت sni علامت * بزارم خودش sni و host رو رندوم می‌سازه ؟

**Comment by M03ED** [comment]
> آها یعنی اگر من در قسمت sni علامت * بزارم خودش sni و host رو رندوم می‌سازه ؟

خیر به این صورت باید وارد کنید
 `*.domain.com`

**Comment by M03ED** [comment]
هر کجا * قرار بدید به صورت رندوم جنریت میشه

**Comment by Lordrichard23** [comment]
> هر کجا * قرار بدید به صورت رندوم جنریت میشه

ممنون بابت توضیحاتتون⚘️

**Comment by Lordrichard23** [comment]
> هر کجا * قرار بدید به صورت رندوم جنریت میشه

البته این روش یک مشکل داره برای مثال من یا افرادی مثل من که از haproxy استفاده میکنن و نمیتونن بزارن رندوم جنریت کنه sni چون موقعی که درخواست به سرور ارسال میشه اگر sni هایی که تعریف شده نباشن اصلا کانفیگ کار نمیکنه
بنابراین بازم جای خالی این قابلیت حس میشه

**Comment by Lordrichard23** [comment]
> > البته این روش یک مشکل داره برای مثال من یا افرادی مثل من که از haproxy استفاده میکنن و نمیتونن بزارن رندوم جنریت کنه sni چون موقعی که درخواست به سرور ارسال میشه اگر sni هایی که تعریف شده نباشن اصلا کانفیگ کار نمیکنه بنابراین بازم جای خالی این قابلیت حس میشه
> 
> قطعا همچین مواردی تو haproxy از قبل پیش بینی شده و باید بشه مشخص کرد که تمام ساب دامنه های یک دامنه رو قبول کنه

اینو بلدم ولی مشکل این هست که من دارم روی یک دامین چندتا پروتکل رو میدن به کاربر یعنی صرفا ws+tls نیست grpc +tls هم دارم که درخواست به پورت ۴۴۳ میرسه و ha proxy برای تعیین کردم که اگر sni مثلا sub1.domain.com بود بفرست پورت مثلا ۱۲۷۸ اگر sub2.domain.com بود بفرست پورت ۳۴۵۶ حالا وقتی من بیام وایلد کارت dns براش تعریف کنم و بگم پنل رندوم sni جنریت کنه. از کجا میخاد بفهمه که کدوم ساب دامین رندوم رو بده به پورت ۱۲۷۸ و کدوم رو بده به ۳۴۵۶ ؟
مگه اینکه کلا به تعداد پروتکل هایی که میخای بزنی دامین داشته باشی و تعیین کنی دامنه × با هر سابی رو بفرست له پورت ۱۲۷۸ و دامنه y به هر سابی رو بفرست به پورت ۳۴۵۶

در واقع این راهکاری که شما میفرمایید درصورتی که دامین کلا یکی باشه مشکل ساز میشه

**Comment by M03ED** [comment]
از path استفاده کنید

**Comment by lvlrf** [comment]
> لا sub1.domain.com بود بفرست پورت مثلا ۱۲۷۸ اگر

توی ریالیتی باید چیکار کرد؟

**Comment by lvlrf** [comment]
> > اما اگر بشه انتخاب کرد مثلا من انتخاب می‌کنم که کاربر x از این اینباند فقط هاست شماره یک رو در یافت کنه با لینک ساب و کاربر y فقط هاست شماره ۱۰ رو ، درواقع یجورایی بهتر میشه ترافیک رو روی sni ها مختلف پخش کرد .
> 
> برای پخش کردن sni میتونید از ساب دامین با * استفاده کنید که ساب رندوم ساخته بشه ![Screenshot 2024-01-05 155436](https://private-user-images.githubusercontent.com/50927468/294487053-fed896a6-0cec-4977-86fd-3d7923ff318b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTM5NDgsIm5iZiI6MTcwNDQ5MzY0OCwicGF0aCI6Ii81MDkyNzQ2OC8yOTQ0ODcwNTMtZmVkODk2YTYtMGNlYy00OTc3LTg2ZmQtM2Q3OTIzZmYzMThiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIyMjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYmY4NDllZTQ3OGI2ZTA3YTk3NTU0MzQ2Y2Q2YmFkZGZhMzQ3YzdjYjY0OWUzYTljZGFmOTZkMTA2ZGE1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LpEcwNQGtyg76krKjBqho8nSDsXqPJf3df3tYLLzi68)

توی ریالیتی باید چیکار کرد؟
