### ISSUE TITLE
sni رندم در ریالیتی

### ISSUE THREAD

**Issue by lvlrf** [Gozargah/Marzban#731]
دوستان آیا راهی هست بشه برای ریالیتی توی فایل کانفیگ servername / sni رو با * گذاشت مرزبان   به صورت رندم یک مقدار بسازه و xray قبول کنه؟

من یه سایت با tls 1.3 آووردم بالا و تنظیم کردم روی همه ساب دامنه هام هم هم سایت میاره بالا اما مشکل اینه وقتی توی فایل xray configuration وقتی مقدار *.domain.com رو میزنم کاربر اگهه لینک رندم ساخته شده به واسطه مرزبان رو بزنه، که مثلا میشه 68464.domain.com xray core قبول نمیکنه حتما باید مقدارش با مقدار وارد شده توی فایل configuration یکی باشه یعنی *.domain.com میزنم دیتا رد میکنه و ریالیتی فعالیت میکنه و وقتیم میام فایل کانفیگ رو بدون severname خالی میزارم که یا تگش رو حذف میکنم که هرجی گذاشتم قبول کنه xraycore خطا میده و اجرا نمیشه

پ. ن. : میدونم اینجا جای درست مطرح کردن سوال نیست، اما گروه زیاد نمیشه نتیجه گرفت یا جواب سوال اینجا حداقل چندتا راهنمایی درست میشه.

**Comment by lvlrf** [comment]
علت این خواسته: توی 24 ساعت سرورم ریالیتیش رو همراه فیلتر میشه اما دیدم چند تا از دوستان سرور ریالیتیشون روی sni github.io داره کار میکنه در صورتی که من sni روی همین آی پی آووردم بالا

**Comment by ImMohammad20000** [comment]
متاسفانه امکان استفاده از دامین های wildcard برای ریلیتی توی xray وجود نداره

**Comment by lvlrf** [comment]
دستت دردنکنه
