### ISSUE TITLE
آپدیت هسته xray

### ISSUE THREAD

**Issue by WhyMan1** [Gozargah/Marzban#735]
با سلام

چند وقتیه که ورژن‌های جدید xray اومدن یه درخواستی داشتم اگر پنل و نودها به ورژن‌های بالاتر آپدیت بشن می‌تونیم امکانات جدید مثل وایرگارد رو امتحان کنیم این میتونه به ما کمک زیادی بکنه

پیشاپیش ممنون از زحماتتون

**Comment by M03ED** [comment]
نحوه انجام اینکار قبلا در داکیومنت توضیح داده شده
https://gozargah.github.io/marzban/examples/change-xray-version
