### ISSUE TITLE
جدا سازی حجم مصرفی

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#738]
برای اپدیت بعدی این مورد که تو پنل هر ادمین حجم مصرف شده کاربرا خودشو نشون بده بجای مجموع مصرف همه پنل ,
بنظرم یکی از ضعف های بزرگ مرزبان در مقابل هیدیفای , چون اکثرا بر حسب مصرف حجم با ادمینا حساب میکنن هزینه رو .
پیشاپیش تشکر از تیم مرزبان

**Comment by parhawm** [comment]
من هم موافقم باید اضافه بشه. دیگه متوجه چه ضعف هایی شدید؟

**Comment by M03ED** [comment]
> برای اپدیت بعدی این مورد که تو پنل هر ادمین حجم مصرف شده کاربرا خودشو نشون بده بجای مجموع مصرف همه پنل , بنظرم یکی از ضعف های بزرگ مرزبان در مقابل هیدیفای , چون اکثرا بر حسب مصرف حجم با ادمینا حساب میکنن هزینه رو . پیشاپیش تشکر از تیم مرزبان

بله این نکته هست و میخواسم این مورد رو هم پیاده سازی کنم ولی به یک سری دلایل نرسیدم انجام بدم ، اگر تا یه مدت دیگه کسی از دوستان انجام نداد خودم به عهده می گیرم

**Comment by xmohammad1** [comment]
> من هم موافقم باید اضافه بشه. دیگه متوجه چه ضعف هایی شدید؟

یکی دیگه از قابلیت هایی که میشه اضافه کرد مثلا یه کانفیگی وجود داشته باشه ولی داخل سابسکریپشن لینک نمایش داده نشه
مثال یه کانفیگ vmess http header بسازی ولی مثلا تیک نمایش داخل سابسکریپشن خاموش کنی
تو این مورد میتونه به کار بیاد که به کاربرا میگی اپدیت کنن و وقتی اپدیت کنن اون مدل کانفیگ قدیمی از لیست پاک میشه ولی اگه کاربری هنوز اپدیت نکرده چون کانفیگ حذف نکردی از داخل پنل هنوز وصل میشه براش

**Comment by M03ED** [comment]
> > من هم موافقم باید اضافه بشه. دیگه متوجه چه ضعف هایی شدید؟
> 
> یکی دیگه از قابلیت هایی که میشه اضافه کرد مثلا یه کانفیگی وجود داشته باشه ولی داخل سابسکریپشن لینک نمایش داده نشه
> مثال یه کانفیگ vmess http header از قبل ساختی ولی مثلا تیک نمایش داخل سابسکریپشن خاموش کنی
> مثلا این مورد میتونه اینجا به کار بیاد که به کاربرا میگی اپدیت کنن و وقتی اپدیت کنن اون مدل کانفیگ قدیمی از لیست پاک میشه ولی اگه کاربری هنوز اپدیت نکرده چون کانفیگ حذف نکردی از داخل پنل هنوز وصل میشه براش

امکان غیر فعال کردن هاست ها خیلی وقته به بک اند اضافه شده ولی متاسفانه با فرانت اضافه نشده

**Comment by xmohammad1** [comment]
> برای اپدیت بعدی این مورد که تو پنل هر ادمین حجم مصرف شده کاربرا خودشو نشون بده بجای مجموع مصرف همه پنل , بنظرم یکی از ضعف های بزرگ مرزبان در مقابل هیدیفای , چون اکثرا بر حسب مصرف حجم با ادمینا حساب میکنن هزینه رو . پیشاپیش تشکر از تیم مرزبان

این موردو کی باید منتظرش باشیم؟

**Comment by xmohammad1** [comment]
> > برای اپدیت بعدی این مورد که تو پنل هر ادمین حجم مصرف شده کاربرا خودشو نشون بده بجای مجموع مصرف همه پنل , بنظرم یکی از ضعف های بزرگ مرزبان در مقابل هیدیفای , چون اکثرا بر حسب مصرف حجم با ادمینا حساب میکنن هزینه رو . پیشاپیش تشکر از تیم مرزبان
> 
> بله این نکته هست و میخواسم این مورد رو هم پیاده سازی کنم ولی به یک سری دلایل نرسیدم انجام بدم ، اگر تا یه مدت دیگه کسی از دوستان انجام نداد خودم به عهده می گیرم

این موردو کی باید منتظرش باشیم؟

**Comment by ALIRA1** [comment]
این مورد اگر به این صورت باشه که هم حجم کلی و هم حجم مصرف شده هر ادمین هر ماه ریست بشه عالی میشه یعنی توی قسمتی که حجم نشون داده میشه حجم کلی کل پنل هست حجم استفاده شده کل ادمین و حجم استفاده شده ماهانه وجود داشته باشه که فقط حجم ماهانه هر ماه ریست بشه

**Comment by LonUp** [comment]
> برای اپدیت بعدی این مورد که تو پنل هر ادمین حجم مصرف شده کاربرا خودشو نشون بده بجای مجموع مصرف همه پنل , بنظرم یکی از ضعف های بزرگ مرزبان در مقابل هیدیفای , چون اکثرا بر حسب مصرف حجم با ادمینا حساب میکنن هزینه رو . پیشاپیش تشکر از تیم مرزبان

مشکلتون با کوئری در دیتابیس قابل حله که خودتون چک کنید چقدر حجم اضافه مصرف شده ولی خب ایده خوبیه د رکل 
حتی اگه برای ادمین ها فقط تعداد کاربری خودش نمایش داده بشه عالی میشه

**Comment by xmohammad1** [comment]
> > برای اپدیت بعدی این مورد که تو پنل هر ادمین حجم مصرف شده کاربرا خودشو نشون بده بجای مجموع مصرف همه پنل , بنظرم یکی از ضعف های بزرگ مرزبان در مقابل هیدیفای , چون اکثرا بر حسب مصرف حجم با ادمینا حساب میکنن هزینه رو . پیشاپیش تشکر از تیم مرزبان
> 
> مشکلتون با کوئری در دیتابیس قابل حله که خودتون چک کنید چقدر حجم اضافه مصرف شده ولی خب ایده خوبیه د رکل حتی اگه برای ادمین ها فقط تعداد کاربری خودش نمایش داده بشه عالی میشه 
این مورد میتونید بیشتر توضیح بدید , چطوری داخل دیتابیس چک کنم هر ادمین چقدر مصرف کرده

**Comment by LonUp** [comment]
برای مشاهده حجم مصرفی ادمین ها
‍‍```
SELECT admins.username, (SUM(users.used_traffic) + IFNULL(SUM(user_usage_logs.used_traffic_at_reset), 0)) / 1073741824
FROM admins 
  LEFT JOIN users ON users.admin_id = admins.id 
  LEFT JOIN user_usage_logs ON user_usage_logs.user_id = users.id
Group By admins.username
```

تفکیک تعداد اکانت با هرحجم متفاوت گرفته شده برای هر ادمین(مورادی که ادمین مالک ان اکانت پاک شده یا از فایل env( ست شدن با نام LonUP نمایش داده میشن
```
SELECT 
  CASE
    WHEN admins.id IS NOT NULL THEN admins.username
    ELSE 'No Admin'
  END AS username,
  users.data_limit/1073741824,
  Count(*)
FROM users 
  LEFT JOIN admins ON users.admin_id = admins.id
GROUP BY 
  CASE
    WHEN admins.id IS NOT NULL THEN admins.username
    ELSE 'LonUP'
  END,
  users.data_limit
```

**Comment by SaintShit** [comment]
@LonUp اینو اضافه میکنم به مرزبان cli, یک PR هم براش اومده

**Comment by LonUp** [comment]
> @LonUp اینو اضافه میکنم به مرزبان cli, یک PR هم براش اومده

ممنونم الان چک کردم توی اپدیتای جدید و محشره

**Comment by xmohammad1** [comment]
سمت cli زیاد کاربردی نیست بنظرم بهتر بود میومد تو فرانت

**Comment by ahwazi12** [comment]
سلام  برلی دبتا بیس sqlلایت 
برای دیدن حجم مصرف  ادمین ها   چه باید کرد

**Comment by ahwazi12** [comment]
واگه  یه  قیمت  تو  پنل  اضاف بسه برای ربات بکاپ  که خودکار  هم  بکاپ بگیر از دیتابیس  و هم رستور کنه  
مثال پنل ثناییوپنل های دیگهx-ui
