### ISSUE TITLE
غیرفعال کردن اینباندها با ی دکمه کوچیک کنارشون

### ISSUE THREAD

**Issue by abedin70** [Gozargah/Marzban#739]
سلام وقت بخیر
اگه میشه ی دکمه کوچیک کنار اینبادها بزارید برای وقتایی ک نیاز شد بشه راحت خاموششون کرد ک دیگه تو لیست مشتری بالا نیاد
سپاس از زحمات شما

**Comment by SaintShit** [comment]
6bbc09af79ce6add3e3583a5d21779439a2d3d01
