### ISSUE TITLE
wireguard error in xray 1.8.6+

### ISSUE THREAD

**Issue by ImMohammad20000** [Gozargah/Marzban#740]
the wireguard outbound not connected in xray 1.8.6+ 

**xray log**

```
2024/01/10 06:11:51 [Info] [2174229861] app/dispatcher: sniffed domain: mtalk.google.com

2024/01/10 06:11:51 [Info] [2174229861] app/dispatcher: taking detour [warp] for [tcp:mtalk.google.com:5228]
2024/01/10 06:11:51 [Info] switching dialer
2024/01/10 06:11:51 [Info] [2174229861] app/proxyman/outbound: failed to process outbound traffic > proxy/wireguard: failed to create virtual tun interface > failed to disable ipv4 rp_filter for all: open /proc/sys/net/ipv4/conf/all/rp_filter: read-only file system
2024/01/10 06:11:51 [Info] [2174229861] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > io: read/write on closed pipe
```

i think it a docker container issue 
Any idea how to fix it?

**Comment by parhawm** [comment]
You'd have to run the container with --privileged flag.

**Comment by Artin70** [comment]
i get the same error after using the last version of marzban-node (v 3.1) when creating new nodes. i dont have any problem with the nodes already added to marzban panel. i use warp with xray core. this is the node log:

```
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [2036529734] proxy: CopyRawConn readv
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] proxy/vless/inbound: firstLen = 554
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] proxy/vless/inbound: received request for tcp:www.google.com:443
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/dispatcher: sniffed domain: www.google.com
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/dispatcher: taking detour [warp] for [tcp:www.google.com:443]
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] switching dialer
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/proxyman/outbound: failed to process outbound traffic > proxy/wireguard: failed to create virtual tun interface > failed to disable ipv4 rp_filter for all: open /proc/sys/net/ipv4/conf/all/rp_filter: read-only file system
marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > io: read/write on closed pipe
```

how can i fix this? @parhawm does running container with --privileged flag fix the problem? how can i do that?
thanks

**Comment by ImMohammad20000** [comment]
> i get the same error after using the last version of marzban-node (v 3.1) when creating new nodes. i dont have any problem with the nodes already added to marzban panel. i use warp with xray core. this is the node log:
> 
> ```
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [2036529734] proxy: CopyRawConn readv
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] proxy/vless/inbound: firstLen = 554
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] proxy/vless/inbound: received request for tcp:www.google.com:443
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/dispatcher: sniffed domain: www.google.com
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/dispatcher: taking detour [warp] for [tcp:www.google.com:443]
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] switching dialer
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/proxyman/outbound: failed to process outbound traffic > proxy/wireguard: failed to create virtual tun interface > failed to disable ipv4 rp_filter for all: open /proc/sys/net/ipv4/conf/all/rp_filter: read-only file system
> marzban-node-1  | DEBUG: 2024/03/07 23:58:18 [Info] [117869521] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > io: read/write on closed pipe
> ```
> 
> how can i fix this? @parhawm does running container with --privileged flag fix the problem? how can i do that?
> i tried this:
> 
> `docker run --privileged gozargah/marzban-node:latest`
> 
> but i get this error:
> 
> ```
> Traceback (most recent call last):
>   File "/code/main.py", line 28, in <module>
>     generate_ssl_files()
>   File "/code/main.py", line 18, in generate_ssl_files
>     with open(SSL_KEY_FILE, 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/marzban-node/ssl_key.pem'
> ```
> 
> thanks
> 

In docker compose file set this
`privileged: true`
