### ISSUE TITLE
Progressive memory usage

### ISSUE THREAD

**Issue by nimahedayati** [Gozargah/Marzban#741]
بعد از نصب مرزبان مصرف رم همینجوری بالا میره 

![Screenshot (53)](https://github.com/Gozargah/Marzban/assets/26443823/01b9a6e9-7712-4754-a444-f7ee257bc696)
![Screenshot (52)](https://github.com/Gozargah/Marzban/assets/26443823/6faca473-91c0-45db-afb1-562002b50abc)

**Comment by M03ED** [comment]
سلام 
مصرف رم در حد 400 مگ برای پروژه ای مثل مرزبان کاملا طبیعیه و چیز عجیبی نیست 
هر چقدر هم تعداد یوزر ها تون بالاتر بره میزان استفاده رم هم بالاتر میره
