### ISSUE TITLE
Bulk Action

### ISSUE THREAD

**Issue by Xyl0d** [Gozargah/Marzban#742]
سلام
با تشکر از زحمات شما
لطفا Bulk Action رو به پنل اضافه کنید
بخوایم یه دسته کاربر expire شده رو پاک کنیم خیلی کار دشواریه
یا از توی پنل یه اینباند رو برای همه کاربرا ها فعال کنیم
واقعا نیازه
دوستانی زحمت کشیدن اسکریپت هایی نوشتن برای این کاراما واقعا ایده ال نیستن
اگر بشه زحمت بکشید ترتیبی بدید بتونیم یه تعداد کاربر رو انتخاب کنیم و روشون کار خاصی انجام بدیم خیلی عالی میشه

**Comment by M03ED** [comment]
مورد اول توی API همین الان در دسترسه ، مورد دوم هم با بات تلگرام در دسترس هست
