### ISSUE TITLE
ارور در انتقال به mysql

### ISSUE THREAD

**Issue by mahsamcse** [Gozargah/Marzban#745]
سلام
طبق آموزش مرزبان نامه سعی کردم دیتابیس رو به mysql منتقل کنم اما ارور میگیرم
همه چی رو چند بار چک کردم
اما نشد
تو نسخه 0.4.2 یک بار این کارو انجام دادم و مشکلی نبود
اما این نسخه نتونستم
البته با ha-proxy هم تک پورت کردم پنل رو نمیدونم مربوط هست یا نه اما غیر فعال کردم تست کردم بازم نشد
ممنون میشم بررسی کنید

marzban 0.4.3
![photo_2024-01-12_02-30-45](https://github.com/Gozargah/Marzban/assets/114700120/f5a4eb82-fe12-429e-8ef6-b4ab6b873d06)

**Comment by parhawm** [comment]
پسووردی که تو فایل .env هست باید با پسوورد دیتابیس یکی باشه

**Comment by mahsamcse** [comment]
یکی هست عزیز
مشکل از تک پورت کردن ha-proxy بوجود میاد احتمالا
چون بعد از ریبیلد سرور این بار قبل از تک پورت کردن انجام دادم و مشکلی نداشت

**Comment by parhawm** [comment]
خیر ارتباطی به haproxy نداره. mysql به درستی پیکربندی نشده.
