### ISSUE TITLE
یک سری فیچر کاربردی و جالب برای پیاده سازی

### ISSUE THREAD

**Issue by FreeDomManIR** [Gozargah/Marzban#748]
درود، بنظرم این فیچرهایی که میگم هم کاربردی هست و هم جالب.

اولیش اینکه امکانش باشه برای یک ادمین، اینباندهایی رو محدود کرد. بنظرم خیلی کاربردی هست برای زمانی که میخوای صرفا یکسری اینباند رو خودت داشته باشی.

بعدیش اینکه بشه حجم مصرفی و حجم گرفته شده توسط هر ادمین رو دید (مجموع Usage یوزرهای هر ادمین و جمع Data Limit یوزر های هر ادمین)
توی مدیریت بنظرم اینم کاربردی هست.

بعدیش برای محدودیت به هر ادمین هست، برای مثال بشه اجازه داد هر ادمین فقط تا 1 ترابایت بتونه یوزر بسازه یا برای مثال فقط بتونه نهایتا 20 یوزر بسازه.

نکته بعد غیرفعالسازی اینباند ها برای یک ادمین هست
مثلا یک ادمین رو میخوایم یه اینباند رو براش غیر فعال کنیم (محدود کردن نه)
لازم نباشه تک تک یوزر ها غیرفعال بشه
بشه یه اینباند برای یک یوزرهای یک ادمین غیرفعال بشه عالیه
(مثل عمل ربات تلگرام که remove inbound 
انجام میده اما بشه فیلتر کرد برای یک ادمین اینکار رو انجام بده)

اگر احیانا مورد دیگه ای بود سعی میکنم اضافه کنم.

ممنون از شما

**Comment by M03ED** [comment]
فیچر هایی که شما درخواست دارید صرفا فیچر های تجاری هستند و تو اولویت مرزبان نیستند
پیشنهاد می کنم برای پیاده سازی اینگونه موارد از بات تلگرامی و یا پروژه ای که بتونه با api مرزبان کار میکنه استفاده کنید

**Comment by FreeDomManIR** [comment]
ممنون از شما درست میفرمایید.
یک فیچر دیگه که نمیدونم امکان پذیر هست یا نه، امکان فعال سازی یک سایت (برای مثال لود کردن فایل های html,css,js) به عنوان سایت روی دامین اصلی باشه برای سخت تر تشخیص دادن وی پی ان.
و دومین فیچر که بنظرم کاربردی توی شناسایی هست اینکه بشه اون مقدار جلوی دامین که به صورت دیفالت /dashboard هست رو تغییر داد.
اگر این فیچر ها هم امکان پیاده سازی داشته باشند بنظر کاربردی هست برای سخت تر شدن شناسایی سرور ها.

**Comment by M03ED** [comment]
> ممنون از شما درست میفرمایید. یک فیچر دیگه که نمیدونم امکان پذیر هست یا نه، امکان فعال سازی یک سایت (برای مثال لود کردن فایل های html,css,js) به عنوان سایت روی دامین اصلی باشه برای سخت تر تشخیص دادن وی پی ان. و دومین فیچر که بنظرم کاربردی توی شناسایی هست اینکه بشه اون مقدار جلوی دامین که به صورت دیفالت /dashboard هست رو تغییر داد. اگر این فیچر ها هم امکان پیاده سازی داشته باشند بنظر کاربردی هست برای سخت تر شدن شناسایی سرور ها.

برای راهانداز وبسایت رو همون پورت باید از ابزار هایی مثل nginx استفاده کنید 
تغییر بخش /dashboard هم توی برنامه هست و در اپدیت های بعدی اضافه میشه

**Comment by FreeDomManIR** [comment]
ممنون از شما
این فیچر ها هم در ربات اگر امکان پیاده سازی داشته باشند عالیه.
وقتی تعداد یوزر ها بالا میره خیلی سخته هی باید بری صفحه قبل تا یوزر رو پیدا کنی
اگر یک سیستم سرچ یوزر باشه داخل ربات به این صورت که چند کلمه اول کاربر رو بگیره و بعد کاربرهارو نشون بده عالیه
بعد اینکه داخل سیستم غیرفعال سازی کلی اگر بشه یه پروتکل (نه یک اینباند) رو برای همه بشه غیرفعال کرد عالیه.

**Comment by parhawm** [comment]
>  تغییر بخش /dashboard هم توی برنامه هست و در اپدیت های بعدی اضافه میشه


خوشحالم که حداقل شما همیشه پیگیر مشکلات این پروژه هستید و با دقت بررسی میکنید @M03ED 
ولی تغییر /dashboard یا /sub کار بیهوده‌ایه چرا که با کانفیگ کردن صحیح nginx میشه راحت انجامش داد و هر مسیری قبلش گذاشت. امیدوارم کسی وقتشو دوباره برای این کار تلف نکنه. و حتی اگر همه مسیر ها رو تغییر بدید وقتی یدونش وجود داشته باشه با active probing میشه شناساییش کرد

از طرفی مثلا بات تلگرام جای کار و بررسی زیادی داره، امیدوارم کمی هم رو اون تمرکز بشه

**Comment by parhawm** [comment]
> ممنون از شما درست میفرمایید. یک فیچر دیگه که نمیدونم امکان پذیر هست یا نه، امکان فعال سازی یک سایت (برای مثال لود کردن فایل های html,css,js) به عنوان سایت روی دامین اصلی باشه برای سخت تر تشخیص دادن وی پی ان. و دومین فیچر که بنظرم کاربردی توی شناسایی هست اینکه بشه اون مقدار جلوی دامین که به صورت دیفالت /dashboard هست رو تغییر داد. اگر این فیچر ها هم امکان پیاده سازی داشته باشند بنظر کاربردی هست برای سخت تر شدن شناسایی سرور ها.

اولین مورد که نوشتید کار مرزبان نیست، باید خودتون کانفیگ کنید، دومین مورد هم با nginx به سادگی قابل انجامه

**Comment by Rezaros** [comment]
@M03ED سلام ببخشید میشه ایدی تلگرامتون رو داشته باشم؟

**Comment by ImMohammad20000** [comment]
> یک فیچر دیگه که نمیدونم امکان پذیر هست یا نه، امکان فعال سازی یک سایت (برای مثال لود کردن فایل های html,css,js) به عنوان سایت روی دامین اصلی باشه برای سخت تر تشخیص دادن وی پی ان.

میتونید از `HOME_PAGE_TEMPLATE` برای لود یک صفحه html ساده استفاده کنید.

**Comment by ImMohammad20000** [comment]
> >  تغییر بخش /dashboard هم توی برنامه هست و در اپدیت های بعدی اضافه میشه
> 
> 
> خوشحالم که حداقل شما همیشه پیگیر مشکلات این پروژه هستید و با دقت بررسی میکنید @M03ED 
> ولی تغییر /dashboard یا /sub کار بیهوده‌ایه چرا که با کانفیگ کردن صحیح nginx میشه راحت انجامش داد و هر مسیری قبلش گذاشت. امیدوارم کسی وقتشو دوباره برای این کار تلف نکنه. و حتی اگر همه مسیر ها رو تغییر بدید وقتی یدونش وجود داشته باشه با active probing میشه شناساییش کرد
> 
> از طرفی مثلا بات تلگرام جای کار و بررسی زیادی داره، امیدوارم کمی هم رو اون تمرکز بشه

امکان عوض کردن /sub اضافه شده 
بنظرم بهتره که امکان اضافه کردن یه prefix یه کل path ها ایده خیلی خوبیه

**Comment by Rezaros** [comment]
سلام داداش

در تاریخ دوشنبه ۵ فوریه ۲۰۲۴،‏ ۱۹:۳۶ Mohammad ***@***.***>
نوشت:
