### ISSUE TITLE
TeleBot: "Infinity polling exception: <UserStatus.on_hold

### ISSUE THREAD

**Issue by linehman** [Gozargah/Marzban#749]
**Describe the bug**
After Creating some new users with on_hold status using the below script, Marzban telegram bot can't "List users" anymore.
https://github.com/M03ED/Marzban_Bulk_Account_Maker
The following error is displayed on the server side.
`marzban-marzban-1  | 2024-01-13 09:15:14,490 (__init__.py:960 Thread-4 (infinity_polling)) ERROR - TeleBot: "Infinity polling exception: <UserStatus.on_hold: 'on_hold'>"
marzban-marzban-1  | 2024-01-13 09:15:14,491 (__init__.py:962 Thread-4 (infinity_polling)) ERROR - TeleBot: "Exception traceback:
marzban-marzban-1  | Traceback (most recent call last):
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 955, in infinity_polling
marzban-marzban-1  |     self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 1043, in polling
marzban-marzban-1  |     self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 1118, in __threaded_polling
marzban-marzban-1  |     raise e
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 1074, in __threaded_polling
marzban-marzban-1  |     self.worker_pool.raise_exceptions()
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 156, in raise_exceptions
marzban-marzban-1  |     raise self.exception_info
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 100, in run
marzban-marzban-1  |     task(*args, **kwargs)
marzban-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 6395, in _run_middlewares_and_handler
marzban-marzban-1  |     result = handler['function'](message)
marzban-marzban-1  |   File "/code/app/telegram/handlers/admin.py", line 485, in users_command
marzban-marzban-1  |     reply_markup=BotKeyboard.user_list(
marzban-marzban-1  |   File "/code/app/telegram/utils/keyboard.py", line 242, in user_list
marzban-marzban-1  |     text=f"{p.username} ({status[p.status]})",
marzban-marzban-1  | KeyError: <UserStatus.on_hold: 'on_hold'>
marzban-marzban-1  | "`

**To Reproduce**
1. Create new users with on_hold status using Marzban_Bulk_Account_Maker
2. Click on 'List users' in marzban telegram bot
3. Nothing happens

**Expected behavior**
Telegram bot should output a list of users.

**Additional context**
This is run on marzban dev version v0.4.1

**Comment by Snyaify** [comment]
on my setup with v0.4.3 same issue

**Comment by linehman** [comment]
Thank you. Tested this on the latest commit and it's fixed.
