### ISSUE TITLE
problem in adding , changing protocols and enabling ssl

### ISSUE THREAD

**Issue by M03ED** [Gozargah/Marzban#75]
hi.
today I tried multi-port installation using docker but i can't change a single thing
I try to make more protocols for each user ( i add vless + grpc + tls and vmess + ws + tls ) and when I replace new xray_config.json file web panel doesn't show up again.
after that, i test changing xray_hosts in env file and after updating file i got the same issue after updating file.
last time I just make enable tls for vless and didn't change anything at all and I had the same problem.
        {
            "tag": "VLESS_INBOUND",
            "listen": "0.0.0.0",
            "port": 2083,
            "protocol": "vless",
            "settings": {
                "clients": [],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/"
                },
                "security": "tls",
                "tlsSettings": {
                    "serverName": "XXXXX.online",
                    "certificates": [
                        {
                            "ocspStapling": 3600,
                            "certificateFile": "/var/lib/marzban/certs/fullchain.pem",
                            "keyFile": "/var/lib/marzban/certs/key.pem"
                        }
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
                }
            }
        },
and please make options to change all these changeable from web panel.

**Comment by SaintShit** [comment]
Hi, plz post your logs.
`docker compose logs`

**Comment by M03ED** [comment]
root@localhost:~/marzban# docker compose logs
marzban-marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-marzban-1  | INFO:     Started server process [1]
marzban-marzban-1  | INFO:     Waiting for application startup.
marzban-marzban-1  | INFO:     2023/03/15 13:22:08 [Warning] core: Xray 1.7.5 started
marzban-marzban-1  | INFO:     Application startup complete.
marzban-marzban-1  | INFO:     Uvicorn running on https://0.0.0.0:8880 (Press CTRL+C to quit)

in 0.2.0 version is need to change files for tls ? or changing from web panel is enough?

**Comment by SaintShit** [comment]
surely u should add tls settings in config.

**Comment by M03ED** [comment]
after i add tls setting in configs panel not gonna show up again 
اگه دوست دارید و نیاز به کمک برای توسعه مرزبان دارید یه ای دی تلگرام و یا هر شبکه اجتماعی ای که میتونید قرار بدید که باهاتون در ارتباط باشم 
من دانشجو رشته کامپیوتر هستم و تو تعطیلات میخواستم یه زبان جدید یاد بگیرم و چه بهتر که واسه کمک به بقیه باشه

**Comment by SaintShit** [comment]
- [گروه تلگرام](https://t.me/gozargah_marzban)

- [ادیت کردم اما پنلم نیومد! ارور چی بوده؟](https://t.me/gozargah_marzban/1/1090)

- [مشارکت در توسعه](https://github.com/Gozargah/Marzban/blob/master/README-fa.md#%D9%85%D8%B4%D8%A7%D8%B1%DA%A9%D8%AA-%D8%AF%D8%B1-%D8%AA%D9%88%D8%B3%D8%B9%D9%87)
