### ISSUE TITLE
Inaccurate traffic usage statistics for users

### ISSUE THREAD

**Issue by Glide01** [Gozargah/Marzban#755]
**Describe the bug**
Inaccurate traffic usage statistics for users.
It can be inaccurate if there is a lot of instantaneous traffic, such as during an internet speed test.
If I use Xray with version 1.8.4 there is no problem.
marzban version 4.2 and 4.3
xray version 1.8.6

**Comment by M03ED** [comment]
this problem its not from marzban , this is xray core bug and they should fix it
