### ISSUE TITLE
inbounds 

### ISSUE THREAD

**Issue by MrCjxer** [Gozargah/Marzban#76]
سلام وقتتون بخیر
خیلی ممنونم از زحماتی که می کشید 
من یه درخواست داشتم که اگر امکانش هست پیاده سازی کنید در پنل ( دلیل اصلی من هم برای نصب نکردن مرزبان همین هست که چندباری تلاش کردم اما باعث شدم پنل کلا بالا نیاد و برام سخت هست )

اگر امکانش هست ، برای ساخت inbound نیازی نباشه که از طریق فایل xray configs اقدام کنیم ، این موضوع کمی پیچیده هست برای افراد مبتدی تر ( مخصوصا تو نسخه فول سینگل پورت )

مثلا پنل x-ui برای این کار راحت هستش 

![Screenshot_20230310_052623](https://user-images.githubusercontent.com/26128739/224206647-13b98d16-5072-4523-9b79-19f7312b592e.png)
![Screenshot_20230310_052655](https://user-images.githubusercontent.com/26128739/224206652-e9ff0e0c-7f6a-4f8c-86b1-dadbd6528b64.png)

====================================================================================
یا مثلا در قسمتی که پروتکل رو برای کاربر انتخاب می کنیم ، طوری نباشه که همه Wmess ها براش ساخته بشه و بشه انتخاب کرد که کدوم Wmess ساخته بشه براش

![photo_2023-03-10_05-51-38](https://user-images.githubusercontent.com/26128739/224207081-b87fa634-bc20-4fb5-9ce8-b11c8b118324.jpg)

با این کار قول میدم رشد کاربران پنل چند برابر خواهد شد و افراد مبتدی یا کسانی که آشنایی زیادی ندارن هم جذب پروژه میشن
اولین نفرش هم خود من :)

بازم ممنونم از زحمات شما 3>

**Comment by SaintShit** [comment]
سلام، این آپدیت زمان بر و بزرگی هست. درحال حاضر همه این تنظیمات بدون UI میشه با یک فایل json پیاده سازی شه، پس فعلا تو لیست آپدیت ها، در اولویت نیست. ازونجایی که مدل کار مرزبان کاملا با X-UI متفاوته. مرزبان کانفیگ xray شما رو میگیره، اجرا میکنه و به اینباند های اون کاربر اضافه و حذف میکنه.  درحال حاضر داشبورد برای فقط برای مدیریت کاربر ها هست.
