### ISSUE TITLE
پینگ ندادن در برنامه nekoray

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#766]
توی برنامه nekoray ویندوز کانفیگا پنل مرزبان پینگ نمیدن ولی وصل میشی همه سایتا و اینا بالا میاد , با کانفیگا بقیه پنلا چک کردم این مشکل نبود فقط کانفیگا مرزبان این مورد بود

![Untitled](https://github.com/Gozargah/Marzban/assets/117955130/a86e9efb-acd3-49bd-a2c2-b4bcef6bf0ee)

**Comment by M03ED** [comment]
این مشکل ربطی به مرزبان نداره ، برای من بدون هیچ مشکلی کانفیگ ها پینگ میدن

**Comment by xmohammad1** [comment]
> این مشکل ربطی به مرزبان نداره ، برای من بدون هیچ مشکلی کانفیگ ها پینگ میدن

داخل برنامه nekoray نسخه 3.26 چک کردید؟ اخه داخل گوشی برام پینگ میده ولی روی ویندوز با nekoray نمیده

**Comment by xmohammad1** [comment]
اروری که موقع تست پینگ میده این هست

![image](https://github.com/Gozargah/Marzban/assets/117955130/6af1e325-8251-4385-b796-26e6773a3b78)

اگه میخواین کانفیگمم واستون بفرستم چک کنید ای دی تلگرامم 
@Mohammadxmz
