### ISSUE TITLE
درخواست اضافه شدن Shadowsocks 2022 

### ISSUE THREAD

**Issue by 123asd321dsa** [Gozargah/Marzban#767]
سلام، Shadowsocks 2022 از Xray-core v1.6.0 اضافه شده اما تو مرزبان هنوز پشتیبانی نمیشه
تست‌هایی که کردم کیفیت بهتری نسبت به Shadowsocks AEAD داره و به این راحتی‌ها بسته نمیشه ( حداقل فعلا روی روش‌های tlsدار زوم کردن)
با توجه به اینکه هسته Xray این قابلیت رو ساپورت میکنه لطفا اضافه شدن این مورد رو بررسی و در صورت امکان در اولویت قرار بدین ممنون میشم.

https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022

**Comment by M03ED** [comment]
#329
