### ISSUE TITLE
کانکت نشدن داکر

### ISSUE THREAD

**Issue by sarboy1371** [Gozargah/Marzban#768]
دستور docker compose up -d رو که میزنم با خطای
 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
رو میگیرم.
راه حلی دارین؟
![Screenshot (23)](https://github.com/Gozargah/Marzban/assets/139820090/eecf6e80-457d-4543-b71d-5f763d1e9bb6)

**Comment by thezass** [comment]
مشکل docker هستش چک کنید داکر روشن باشه همینطوری که توی تصویر هستش
