### ISSUE TITLE
Feature title

### ISSUE THREAD

**Issue by mehdisamurai** [Gozargah/Marzban#77]
سلام برادر . روزت بخیر دادا. اولا بابت زحماتت سپاسگزارم و دم شما خیلی گرمه.

جسارتا و بخاطر قلب بزرگ خودت که نوشتی نظرات رو بگیم، عرض میکنم:
اگه میشد داخل پنل مرزبان، تنظیمات قرار بگیرن و یو آی یوزرفرندلی تر باشه خیلی بهتره.
همینطور تنظیم اس اس ال اگه از داخل پنل باشه، قطعا پنل فراگیرتر و در نتیجه اختلالاتش زودتر مشخص میشه.
ضمن اینکه نسخه ایکس ری و آپدیت اون مشخص نیست و دلچسب تر میشه اگه باشه.
موضوع بعدی اینکه با اینکه در روند نصب و گرفتن اس اس ال، ساب دامینم رو معرفی کردم، اما همچنان کانفیگ ها بدون اس اس ال ارائه میشن و نمیدونم دقیقا چطور باید موضوع رو برطرف کنم.
سرت سلامت و ایشالا همیشه موفق باشی.
ارادت.

**Comment by SaintShit** [comment]
سلام ممنون بابت بازخورد، لحاظ میشه
اگر مشکل داشبورد رفع نشد براتون توی گروه فارسی پیام بدین حتما کمک میشه بهتون
t.me/gozargah_marzban
