### ISSUE TITLE
کار نکردن لینک ساب روی بعضی اپراتور ها

### ISSUE THREAD

**Issue by rzavortx** [Gozargah/Marzban#770]
سلام.من پنلم به یه ساب دامین از مدل wild card وصله و کاملا اوکیه و فیلتر نیست، سرتیفیکیت گرفتم واسش و فعاله اما پنل بدون فیلترشکن بالا نمیاد در حالی نه ساب دامینم و نه ایپیم فیلتره ولی تو سایت check_host.net میزنم توی قسمت http سه تا ادرس ایران جز اصفهان connection تایم  اوت میزنه .لطفا اگه میدونید کمک کنید لینک ساب من الان به مشتری میدم دارای مشکله و هر بار میخوام تغییری بدم بدون زدن update sub از سمت کاربر توی برنامه v2rayng واقعا سخت میشه کار.

**Comment by thezass** [comment]
این مشکل پنل نیستش دامنه و ای پی شما کامل تمیز نیستش که اینطوری میشه

**Comment by thezass** [comment]
میتونین از هاست ایرانی یا cdn مثل کلود فلیر استفاده کنید
