### ISSUE TITLE
ترتیب بندی کانفیگا

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#774]
سلام و خسته نباشید به همه توسعه دهندگان مرزبان
لطفا یه امکانی اضافه کنید که بشه ترتیب بندی کانفیگا رو تنظیم کرد
مثال ما یه کانفیگ vless داریم که میخوایم اول لیست باشه و یه کانفیگ vmess هم هست که میخوایم بره اخر لیست

**Comment by sarboy1371** [comment]
> سلام و خسته نباشید به همه توسعه دهندگان مرزبان لطفا یه امکانی اضافه کنید که بشه ترتیب بندی کانفیگا رو تنظیم کرد مثال ما یه کانفیگ vless داریم که میخوایم اول لیست باشه و یه کانفیگ vmess هم هست که میخوایم بره اخر لیست

از تو پنل قسمت core setting کانفیگ رو ویرایش کن و vless رو بیار بالا

**Comment by M03ED** [comment]
قبلا راجع به این موضوع بسیار بحث شده ، امکانش هست ولی کاربردی نیست چون همین الان با دستکاری core setting و هاست ها میتونید این کار رو انجام بدید.
