### ISSUE TITLE
Note column

### ISSUE THREAD

**Issue by alicewebs** [Gozargah/Marzban#779]
Hi! It would be cool to be able to add a note column between the keyname and status.  Or a second string under the keyname!

Thank you!

**Comment by M03ED** [comment]
we already have note column

**Comment by alicewebs** [comment]
> we already have note column

Sorry, but i don't see it. Should i enable it in settings or something?

**Comment by M03ED** [comment]
> > we already have note column
> 
> Sorry, but i don't see it. Should i enable it in settings or something?
> 
> I mean note column in users list

![image](https://github.com/Gozargah/Marzban/assets/50927468/48096f1a-b948-45d6-9581-bc85113fc971)

**Comment by alicewebs** [comment]
Thank you. But i meant note column in userlist table
![Screenshot 2024-02-03 143002](https://github.com/Gozargah/Marzban/assets/150247007/1e86fce2-733d-41ee-b6ac-686b0b4907da)

**Comment by M03ED** [comment]
why you should have note in users list ?
its gonna make problem with making page responsive

**Comment by alicewebs** [comment]
for example note under the username with small font in same column

**Comment by M03ED** [comment]
> for example note under the username with small font in same column

i don't think this be a good change because you can just click and read it 
adding so many things to list its not good thing
if you need something you can implement it and make pr for it 
maintainers will review it
