### ISSUE TITLE
اضافه کردن کاستوم کانفیگ

### ISSUE THREAD

**Issue by sirvan32** [Gozargah/Marzban#781]
راهی هست که یه کانفیگ کاستوم رو به عنوان مثال یه فایل json  رو به کانفیگا اضافه کرد؟🙏

**Comment by M03ED** [comment]
امکانش هست ولی اگر تعداد کانفیگ از یکی بیشتر بشه باید چندین فایل ارسال بشه به همین دلیل فعلا نمیتونه با لینک ساب ارسال بشه مگر اینکه دولوپر های v2rayng و باقی آپ ها امکان دریافت چند کانفیگ در یک فایل رو فراهم کنند.

**Comment by sirvan32** [comment]
مثل سایت هایی مثل ircfspace که کانفیگ رو وارد میکی و خروجی رو به صورت json دریافت میکنی. امکانش هست یک نوع کانفیگ به مرزبان اضافه بشه که در صفحه ی سابسکریپشن این نوع کانفیگ رو به صورت jsonخروجی‌بده؟

**Comment by M03ED** [comment]
تو پیام قبلی بهتون توضیح دادم

**Comment by projectsx-sx** [comment]
برای همون تک کانفیگ چطور باید اقدام کنیم که ارسال بشه؟

**Comment by M03ED** [comment]
#806
