### ISSUE TITLE
Add TLS fragmentation support in proxy links (in the future)

### ISSUE THREAD

**Issue by mdjvd** [Gozargah/Marzban#784]
Hello there!
Due to the recent SNI blocking, Please if possible, consider adding TLS fragmentation support in proxy links, sometime in the future.
Although it's possible to edit JSON config manually and add it in the client, it's really not convenient and it would be great if it were possible with the help of subscription link.
For now, most apps do not support importing proxy links with fragmentation enabled (So maybe this feature will be more practical in the future), but Streisand on iOS supports fragmentation values in proxy links in this format:
```
vless://e89b4cf7-2771-48c9-a54b-e6048bcae764@domain.com:443?type=ws&host=domain.com&path=/&security=tls&sni=domain.com&fragment=100-200,20-30,tlshello#TEST
```
Where "100-200" is for "Length", "20-30" for "Interval", and "tlshello" for "Packets".

**Comment by M03ED** [comment]
#806
