### ISSUE TITLE
Add path to host settings v0.4.3

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#788]
با عرض درود و خسته نباشید این با نسخه v0.4.2 مرج شده بود و الان روی نسخه v0.4.3 ظاهرا درست بیلد نشده لطفا در صورت امکان چک کنید (در نسخه v0.4.3 اصلا نیست تو هاست ستینگ )
باتشکر

https://github.com/Gozargah/Marzban/pull/699

![photo_2024-02-09_17-33-06](https://github.com/Gozargah/Marzban/assets/52799129/ea8057bb-de5d-4056-9cd5-ff2b13886cc4)

**Comment by realartin** [comment]
@SaintShit

**Comment by M03ED** [comment]
مشکلی نداره برای من نشون داده میشه

<img width="304" alt="image" src="https://github.com/Gozargah/Marzban/assets/50927468/6c3f400d-998a-4726-b412-ddac8c5b048f">

**Comment by realartin** [comment]
> مشکلی نداره برای من نشون داده میشه
> 
> <img alt="image" width="304" src="https://private-user-images.githubusercontent.com/50927468/303727077-6c3f400d-998a-4726-b412-ddac8c5b048f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDE5MjAsIm5iZiI6MTcwNzUwMTYyMCwicGF0aCI6Ii81MDkyNzQ2OC8zMDM3MjcwNzctNmMzZjQwMGQtOTk4YS00NzI2LWI0MTItZGRhYzhjNWIwNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE4MDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNzYxYTU4ZDIyODk0Njk4MTgyMWE3YjMxN2Q0YjgzNTIzM2M4MjE0ODJkMTYxZjdmY2MxNDZjMzJiZWIzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GUDOpbqmHjD2wSdHJDGFRCEz4ZkJVU6UsKufa53O9uY">

ورژن 0.4.3 ؟ برای من چرا نشون نمیده 
marzban update 
اپدیت کردم

**Comment by realartin** [comment]
> مشکلی نداره برای من نشون داده میشه
> 
> <img alt="image" width="304" src="https://private-user-images.githubusercontent.com/50927468/303727077-6c3f400d-998a-4726-b412-ddac8c5b048f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDE5MjAsIm5iZiI6MTcwNzUwMTYyMCwicGF0aCI6Ii81MDkyNzQ2OC8zMDM3MjcwNzctNmMzZjQwMGQtOTk4YS00NzI2LWI0MTItZGRhYzhjNWIwNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE4MDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNzYxYTU4ZDIyODk0Njk4MTgyMWE3YjMxN2Q0YjgzNTIzM2M4MjE0ODJkMTYxZjdmY2MxNDZjMzJiZWIzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GUDOpbqmHjD2wSdHJDGFRCEz4ZkJVU6UsKufa53O9uY">

ظاهرا نسخه dev هست ، من چنل استیبل هستم

**Comment by realartin** [comment]
> مشکلی نداره برای من نشون داده میشه
> 
> <img width="304" alt="image" src="https://github.com/Gozargah/Marzban/assets/50927468/6c3f400d-998a-4726-b412-ddac8c5b048f">
> 

لطفا بررسی بفرمایید روی نسخه ریلیز نیست من چند تا سرور رو از صفر بیلد کردم بالا نمیاد چنین گزینه ای یا مشکل داره یا روی نسخه dev هست لطفا چک بفرمایید

**Comment by M03ED** [comment]
> > مشکلی نداره برای من نشون داده میشه
> > <img alt="image" width="304" src="https://private-user-images.githubusercontent.com/50927468/303727077-6c3f400d-998a-4726-b412-ddac8c5b048f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1Njc1MzQsIm5iZiI6MTcwNzU2NzIzNCwicGF0aCI6Ii81MDkyNzQ2OC8zMDM3MjcwNzctNmMzZjQwMGQtOTk4YS00NzI2LWI0MTItZGRhYzhjNWIwNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDEyMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTcyZmVlYTlmMmQ4ZGYwMzU1MDlmZTE5YzQ5NDA0NDU2NTIzOTlmNzE1YjhmNzU3NDhiOTIyNjEwZTVkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XQ9o9sU5rxUM5_adk5460J5Vblt8brXMGu9lMiAMz3k">
> 
> لطفا بررسی بفرمایید روی نسخه ریلیز نیست من چند تا سرور رو از صفر بیلد کردم بالا نمیاد چنین گزینه ای یا مشکل داره یا روی نسخه dev هست لطفا چک بفرمایید

اگر روی dev هست و استیبل نیست باید صبر کنید تا نسخه حدید بیاد ، انتشار نسخه جدید هم دست من نیست

**Comment by realartin** [comment]
> > > مشکلی نداره برای من نشون داده میشه
> > > <img alt="image" width="304" src="https://private-user-images.githubusercontent.com/50927468/303727077-6c3f400d-998a-4726-b412-ddac8c5b048f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1Njc1MzQsIm5iZiI6MTcwNzU2NzIzNCwicGF0aCI6Ii81MDkyNzQ2OC8zMDM3MjcwNzctNmMzZjQwMGQtOTk4YS00NzI2LWI0MTItZGRhYzhjNWIwNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDEyMTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTcyZmVlYTlmMmQ4ZGYwMzU1MDlmZTE5YzQ5NDA0NDU2NTIzOTlmNzE1YjhmNzU3NDhiOTIyNjEwZTVkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XQ9o9sU5rxUM5_adk5460J5Vblt8brXMGu9lMiAMz3k">
> > 
> > لطفا بررسی بفرمایید روی نسخه ریلیز نیست من چند تا سرور رو از صفر بیلد کردم بالا نمیاد چنین گزینه ای یا مشکل داره یا روی نسخه dev هست لطفا چک بفرمایید
> 
> اگر روی dev هست و استیبل نیست باید صبر کنید تا نسخه حدید بیاد ، انتشار نسخه جدید هم دست من نیست
> 

برای شما رو کدوم نسخه هست؟
جالب اینجاست رو نسخه ۴.۲ میگن مرج شده استیبل !
ولی رو استیبل ۴.۳ نیست ؟

**Comment by peymansh68** [comment]
روی نسخه dev هست اسم گزینه path  خالی هست

**Comment by realartin** [comment]
> روی نسخه dev هست اسم گزینه path  خالی هست

خب کی میاد استیبل
