### ISSUE TITLE
import sub failure problem

### ISSUE THREAD

**Issue by piuma1** [Gozargah/Marzban#790]
سلام. من بعد از اینکه لینک ساب یا qrcode رو در برنامه v2rayng اد می کنم بعد از update subscription ارور import sub failure میگیرم. مشکل از چی میتونه باشه؟

**Comment by piuma1** [comment]
import_sub->Start getting subscriptions
import_sub->No connection could be made because the target machine actively refused it. (m.d*********click:443)
import_sub->No connection could be made because the target machine actively refused it.
import_sub->No connection could be made because the target machine actively refused it. (m.d********:443)
import_sub->No connection could be made because the target machine actively refused it. (m.d********:443)
import_sub->No connection could be made because the target machine actively refused it. (m*********:443)
import_sub->No connection could be made because the target machine actively refused it. (m*********:443)
import_sub->Invalid subscription content

پورت پنل 2053 هست به نظرتون درسته 443 می زنه؟

**Comment by piuma1** [comment]
پورت پنل رو در فایل env ویرایش و روی 443 گذاشتم. توی برنامه v2rayn ویندوز اوکی شده اما در v2rayng همچنان fail میزنه. کجای تنظیماتم مشکل داره؟؟

**Comment by thezass** [comment]
این باگ از طرف مرزبان نیستش زدین باگ
اگه توی ویندوز ساب آپدیت میشه توی گوشی نه ربطی به پنل نداره
