### ISSUE TITLE
عدم گزارش لاگ در ربات دیفالت بعد از آپدیت

### ISSUE THREAD

**Issue by echo-333** [Gozargah/Marzban#796]
من بعد از آپدیت ٢تا مشکل البته غیر اورژانسی برام پیش اومده،
یکی اینکه ربات دیفالت دیگه لاگ رو نمیفرسته، دوم اینکه موقع ساخت یوزر جدید پنجره ساخت بسته نمیشه و تا رفرش نکنم یوزر جدید رو نمایش نمیده

**Comment by echo-333** [comment]
![error1](https://github.com/Gozargah/Marzban/assets/115120779/89ece104-7dd0-4c03-a51e-8b775c27fdcf)
همزمان با ادیت یا ساخت یوزر جدید من لاگ هم بررسی کردم و متوجه شدم که موقع ساخت یا ادیت یوزر این ارور در لاگ ظاهر میشه

**Comment by SaintShit** [comment]
> ![error1](https://private-user-images.githubusercontent.com/115120779/305242504-89ece104-7dd0-4c03-a51e-8b775c27fdcf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzYyNjcsIm5iZiI6MTcwODAzNTk2NywicGF0aCI6Ii8xMTUxMjA3NzkvMzA1MjQyNTA0LTg5ZWNlMTA0LTdkZDAtNGMwMy1hNTFlLThiNzc1YzI3ZmRjZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQyMjI2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDAyOTg3NjFiNzhkNzBkZTkxZDE2NzNkMGY2M2E0NzM5MjJkZWRlNDRkZWE3ODgzYjlhMzRiOThjNWFhZmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FhLcaSAn3CAPxfZTwiwx9_Likzlme_wiYWg51fZv15Y) همزمان با ادیت یا ساخت یوزر جدید من لاگ هم بررسی کردم و متوجه شدم که موقع ساخت یا ادیت یوزر این ارور در لاگ ظاهر میشه

سلام
 لطفا از بخش های پایین تر ارور هم عکس بفرستین

**Comment by echo-333** [comment]
سلام وقت بخیر، ممنون از پاسختون، خدمت شما:
![error2](https://github.com/Gozargah/Marzban/assets/115120779/4c3a67ea-2acc-470b-afcd-e386d26fd842)

**Comment by SaintShit** [comment]
> سلام وقت بخیر، ممنون از پاسختون، خدمت شما: ![error2](https://private-user-images.githubusercontent.com/115120779/305251134-4c3a67ea-2acc-470b-afcd-e386d26fd842.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDA2NjgsIm5iZiI6MTcwODEwMDM2OCwicGF0aCI6Ii8xMTUxMjA3NzkvMzA1MjUxMTM0LTRjM2E2N2VhLTJhY2MtNDcwYi1hZmNkLWUzODZkMjZmZDg0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQxNjE5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGM2OWVjYzc4ODI4Zjc4ZjkzOGYxOTU2YzRiMTI1YWYxOWFkYmYyNWRkZTllMGRlMmI3NzU1ZWE4NWM2NGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NdggBYQ1JmbYbDzD_X5X7UY9aJpZ4h9a0-WAf6sDTJ4)

تغییراتی توی فایل ها ایجاد کردین؟
تابع report.user_updated یک آرگومان جدید میگیره به اسم user_admin
https://github.com/Gozargah/Marzban/blob/ab41c533ddcae3cd5cbc6aacd8587afdf600acfb/app/utils/report.py#L67
که به نظر توی کد های شما وجود نداره
