### ISSUE TITLE
Add option to reset user limit at different points in time

### ISSUE THREAD

**Issue by The-Daishogun** [Gozargah/Marzban#8]
Hi, thank you for the amazing work you're doing 🙌🏼 

how do you feel about adding an option to make user bandwith limit rest weekly or monthly or even yearly?

i can get started on the pull request if you feel this would be a good adition

**Comment by gozarman** [comment]
Hi @The-Daishogun, 
First of all, thanks for helping to improve Marzban.

This feature seems cool, feel free to make a PR.

Just before implementing, could you pls tell us more about how you gonna add this feature? (Which APIs are going to be changed) and how it's going to be implemented on the UI? 

I would appreciate it if you use the [Feature request template](https://github.com/Gozargah/Marzban/issues/new/choose) for future requests.
