### ISSUE TITLE
بعد از بروزرسانی به آخرین ورژن ربات هیچ کاربری رو جستجو نمیکنه!!

### ISSUE THREAD

**Issue by abedin70** [Gozargah/Marzban#801]
بعد از بروزرسانی به آخرین ورژن ربات هیچ کاربری رو جستجو نمیکنه!!

**Comment by M03ED** [comment]
از دستور /user استفاده کنید

**Comment by abedin70** [comment]
> از دستور /user استفاده کنید

جواب نمی‌ده بازم!!؟!!!!!

**Comment by M03ED** [comment]
> > از دستور /user استفاده کنید
> 
> جواب نمی‌ده بازم!!؟!!!!!

![image](https://github.com/Gozargah/Marzban/assets/50927468/5a7807cf-b6b6-42f4-8ff1-fd51fddd7344)

**Comment by abedin70** [comment]
> > > از دستور /user استفاده کنید
> > 
> > 
> > جواب نمی‌ده بازم!!؟!!!!!
> 
> ![image](https://private-user-images.githubusercontent.com/50927468/305664251-5a7807cf-b6b6-42f4-8ff1-fd51fddd7344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTU3NzQsIm5iZiI6MTcwODE5NTQ3NCwicGF0aCI6Ii81MDkyNzQ2OC8zMDU2NjQyNTEtNWE3ODA3Y2YtYjZiNi00MmY0LThmZjEtZmQ1MWZkZGQ3MzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE4NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYmMwZTg1NWYzODcwYzJhY2MxM2Q2NTI2ZjMyMDAyOTM1YTNjYzk1YjNiMjBjZmJhYmJhOWJlZGM5NzgzMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DGEsXahykO6G1Wxe38qOsxz94P6KrJ8fmJ2YgRasMKU)

ممنون حل شد
ولی قبلا فقط اسم رو می‌زدی نیومد!!
