### ISSUE TITLE
Problem with expired subscriptions.

### ISSUE THREAD

**Issue by OwnerLink** [Gozargah/Marzban#802]
When the proxy expires, the icon on the panel remains in the "active" status and the user can safely continue using the subscription proxy.

The latest version of Marzban is DEV 0.4.4.

![image](https://github.com/Gozargah/Marzban/assets/76668238/af6faecf-b130-4362-b46b-f00882d120fc)

**Comment by M03ED** [comment]
check `marzban logs`

**Comment by OwnerLink** [comment]
> чек `marzban logs`

Unfortunately I delete these users almost immediately. You'll have to wait 3 days.

**Comment by OwnerLink** [comment]
After switching to Latest version and updating to currently 0.4.6 the problem went away :)
