### ISSUE TITLE
مشکل رسپانسیو در موبایل

### ISSUE THREAD

**Issue by hamed221** [Gozargah/Marzban#805]
سلام دوستان
وقتی توی پنل مرزبان یه یوزر میسازم که کارکترش زیاده
صفحه توی موبایل بهم ریختگی داره 
کسی میتونه راهنمایی کنه؟
ممنون

**Comment by M03ED** [comment]
سلام
فرانت قراره به طور کامل باز سازی بشه و روی برنچ next در حال انجام هست.
تا تکمیل شدن فرانت جدید باید منتظر بمونید

**Comment by hamed221** [comment]
هنوز مشکل پا برجاست بعد از آپدیت به نسخه جدید
تعداد کارکتر رو از یه اندازه که بیشتر میذارم برای یوزرها کلا رسپانسیو بهم میریزه و بخش ویرایش کاربران از صفحه خارج میشه
![Screenshot 2024-03-01 192447](https://github.com/Gozargah/Marzban/assets/59690279/dd4146cc-97b6-4a7f-b90e-51294e24c6e6)
