### ISSUE TITLE
قطع ارتباط کاربر در زمان ریست کردن یا قطع وصلی ارتباط نود با مستر

### ISSUE THREAD

**Issue by peymansh68** [Gozargah/Marzban#809]
سلام
ورژن 4.6 هستم 
وقتی مستر رو ریبوت میکنم ارتباط کاربر که به نود هست هم قطع میشه قبلا اینجوری نبود 
یا گاهی مشکلات اینترنتی هست نود و مستر ارتباطشون همش قطع و وصل میشه این وسط کاربر هم همش قطع و صل میشه

**Comment by M03ED** [comment]
https://t.me/Gozargah_news/29

**Comment by peymansh68** [comment]
سلام 
اتفاقا protocol rest  هست هم مستر و هم نود هر دو اخرین ورژن هستند

**Comment by M03ED** [comment]
ارور تون چی هست ؟

**Comment by peymansh68** [comment]
یک یوزر متصل هست به نود تا اینجا اوکی هست 
حالا یک لحظه من مستر رو ریبوت میکنم یا ارتباط بین مستر و نود یک لحظه قطع میشه 
در نتیجه اون یوزر هم قطع میشه تا ارتباط نود با مستر برقرار شه 
قبلا اینجوری نبود 

فایل داکر نود هم این هست 

services:
  marzban-node:
    # build: .
    image: gozargah/marzban-node:v0.3.0
    restart: always


    environment:
      SERVICE_PROTOCOL: rest
      SSL_CERT_FILE: "/var/lib/marzban-node/ssl_cert.pem"
      SSL_KEY_FILE: "/var/lib/marzban-node/ssl_key.pem"
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert.pem"

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node

**Comment by M03ED** [comment]
همیشه همینجوری بوده 
هنگام خاموش کردن سرور مستر نود ها هم خاموش میشن مگر اینکه ارتباط به صورت ناگهانی قطع بشه مثل مواقعی که سرور خاموش بشه یا دارتباط بین مستر و نود هرگونه اختلالی به وجود بیاد

**Comment by peymansh68** [comment]
تو 0.4.2 اینطوری نبود من سرور مشکل داشت ریبوت میکردم آبدیت میکردم و کلی کار دیگه مثلا اصلا خاموش کرده بودم اسنپشات بگیرم ولی یوزری که از قبل وصل بود متصل میموند درجا قطع نمیشد الان تا ارتباط نود با مستر قطع میشه یوزر هم همون لحظه قطع میشه

**Comment by M03ED** [comment]
می تونید برید کد ورژن های قبلی رو بخونید 
همون طور که گفتم اگر به طور غیر معمول سرور خاموش بشه و مرزبان هم همزمان خاموش بشه نود ها متصل خواهند موند
