### ISSUE TITLE
هنگ کردن سیستم

### ISSUE THREAD

**Issue by upgo7502** [Gozargah/Marzban#814]
با درود و خسته نباشید خدمت شما و سپاس از زحمات بسایر فراوانی که میکشید . 

از نسخه 4.x به بعد مشکلاتی مثل هنگ کردن هسته v2ray و مصرف بالای پردازنده زیاد مشاهده میشه و هر از گاهی باید کلا مرزبان رو up/down کنم . 

سپاس فراوان

**Comment by M03ED** [comment]
در ورژن 0.4.6 رفع شده

**Comment by upgo7502** [comment]
با وجود اینکه 48 ساعتی هست نسخه رو به 0.4.6 ارتقا دادم بازم سرویس هنگ میکنه . 
در این حالت پنل باز میشه ولی ترافیک رد نمیشه . ری استارت که میکنم یا مرزبان رو down/up میکنم درست میشه . 

منابع برای 400 کاربر برح زیر است :
سرور اختصاصی 24 هسته
64 گیگ رم
هارد NVMe pro

**Comment by ImMohammad20000** [comment]
> با وجود اینکه 48 ساعتی هست نسخه رو به 0.4.6 ارتقا دادم بازم سرویس هنگ میکنه . 
> در این حالت پنل باز میشه ولی ترافیک رد نمیشه . ری استارت که میکنم یا مرزبان رو down/up میکنم درست میشه . 
> 
> منابع برای 400 کاربر برح زیر است :
> سرور اختصاصی 24 هسته
> 64 گیگ رم
> هارد NVMe pro

لاگ پنل رو ارسال کنید

**Comment by SaintShit** [comment]
@upgo7502 سلام، از نود استفاده میکنید؟ وضعیت نود ها چطوره؟ قطع میشن؟
و لطفا بررسی کنید وقتی پیک مصرفی دارین دقیقا از چه پراسسی هست، با htop یا هر ابزاری که راحت هستین.

**Comment by upgo7502** [comment]
1 . لاگ چیزی نشون نمیده .
2 . پنل بالا میاد . 
3 . ترافیک رد نمیشه .
وقتی میزنم marzban restart ترافیک کاربرا میاد . 

یکی دیگه دز دوستان هم که نسخه 0.3.1 بوده و کرده 0.4.6 اونم همینطوری شده . حتی مجبور شد نسخه رو پاک کنه از نو نصب کنه و بعد از چند روز دوباره اینطوزی شد . 


سپاس

**Comment by upgo7502** [comment]
![faild](https://github.com/Gozargah/Marzban/assets/75158856/b16cbb48-7931-4844-9473-97452d9774f3)

طبق تصویر اینم لاگ خدمت شما
حتی وقتی دکمه Restart رو میزنم همینطوری روی حالت Restarting میمونه

**Comment by upgo7502** [comment]
اینم یک تصویر دیگه :
![faild 2](https://github.com/Gozargah/Marzban/assets/75158856/b02b2444-da55-4c3b-9c68-edb6094dfbc6)
![log 3](https://github.com/Gozargah/Marzban/assets/75158856/516d612f-a97a-4519-8135-3a719c65ace2)

**Comment by upgo7502** [comment]
اینم تصویر دیگه :  
![faild 2](https://github.com/Gozargah/Marzban/assets/75158856/18c6bbd1-afd4-419b-b47b-05dce4f593a6)
![log 3](https://github.com/Gozargah/Marzban/assets/75158856/7baeaf3f-9b12-4fbf-ac9e-1f67bcd9585a)

**Comment by upgo7502** [comment]
یکی دیگه از دوستان که کلا توی پنلش 12 تا کاربر داره اونم از زمانی که آپدیت کرده اینطوری شده . میگه روزی 4 5 بار باید ری استارت بزنم

**Comment by ImMohammad20000** [comment]
سرورتون از چه دیتاسنتری هست

**Comment by mohsensaremi** [comment]
منم همین مشکل @upgo7502 رو دارم
بعد یه مدت سرویس هنگ میکنه و مجبورم ریبوت بدم

**Comment by spyp** [comment]
سلام

آره برا منم همین شده . سرویسم کرده .

**Comment by ImMohammad20000** [comment]
> فن آوا و صفرو یک دارم . وقتی میزنم marzban restart درست میشه . 
> نکته : ترافیک توی خود لینوکس اوکیه و تانل برقرار هست

تانل پنل به پنل؟
مشخصات سرورتون رو هم بگید

**Comment by upgo7502** [comment]
پورت forward زدم از میکروتیک به لینوکس

**Comment by upgo7502** [comment]
نکته : توی خود لینوکس وقتی میزنم curl ifconfig.net دقیقا آی پی سرور هلند رو بهم میده

**Comment by Fahime-1992** [comment]
با سلام

مدتیه بعد از بروز رسانی گفتم شاید مشکل از سرورم باشه حتی سیستم عامل عوض کردم ولی انگار نه انگار .... بازم باید روزی 2 3 4 5 بار سرویس مرزبان رو همینی که ایشون گفتن بزنم marzban restart یا لینوکس رو ریاستارت کنم

**Comment by Nitron2020** [comment]
با درود
متاسفانه از زمانی که من هم از نسخه 0.3.1 به نسخه 0.4x بروز کردم توی روز باید حتی بعضی مواقع 7 الی 8 باری ری استارت کنم . کلا مصرف بالایی روی پردازنده ندارم ولی با این حال بازم باید ری استارت بزنم . نمیدونم چرا اینطوری شده . ممنون میشم مشکلش رو برطرف کنید . 

سپاس بسیار از زحمات شما

**Comment by SaintShit** [comment]
@upgo7502 لطفا بررسی کنید چه پراسسی زیاد میشه توی سیستمون اینجا بگین
درباره قطع شدن پروکسی‌ها، توی نسخه جدید یکی از تغییراتی که ایجاد شده نسخه هسته به ۱.۸.۷ تغییر کرده. اگر براتون مقدوره نسخه هسته رو به ۱.۸.۴ تغییر بدین بررسی کنید همچنان مشکل قطع شدن وجود داره؟
https://gozargah.github.io/marzban/examples/change-xray-version

**Comment by upgo7502** [comment]
فعلا ست کردم روی 1.8.4 ببینم چی میشه . نتیجه رو همینجا اعلام کینم .

مرسی

**Comment by upgo7502** [comment]
من دقت نکردم ... نسخه 1.8.4 از چه نستخه ای از مرزبان اضافه شده ؟

**Comment by KAJOOSH** [comment]
من نسخه ی 0.3.2 در حال استفاده هستتم و همیشه نسخه xray رو به روز نگه می دارم .. الان 1.8.7 ارتقاء دادم ( که حدودا دو ماهی میشه .. ) اصلا مشکل دوستان رو ندارم ! 
* سرور هم مشخصات معمولی دارد !

**Comment by upgo7502** [comment]
فعلا که نسخه xray رو روی 0.4.6 کردم 1.8.4 .. تا اینجا فعلا خبری نیست و ری استارت نکردم . بازم باید زمان بدم ببینم چی میشه . 
اما هر چی هست از نسخه 0.4.x که کردم اینطوری شد .

**Comment by SaintShit** [comment]
> من نسخه ی 0.3.2 در حال استفاده هستتم و همیشه نسخه xray رو به روز نگه می دارم .. الان 1.8.7 هستم ( که حدودا دو ماهی میشه .. ) اصلا مشکل دوستان رو ندارم !
> 
> * سرور هم مشخصات معمولی دارد !

برای من هم مشکل خاصی نداره بعضی باگ ها تو شریط خاص پیش میاد مثلا اینکه اینباندت چیه، هدر داره، grpc هست و اینجور چیزا... توی مرزبان هم همینطور... مثلا ممکنه یه یوزر از قابلیت on_hold استفاده کنه و یک یوزر نکنه، و اون بخش باگ داشته باشه.

**Comment by SaintShit** [comment]
> فعلا که نسخه xray رو روی 0.4.6 کردم 1.8.4 .. تا اینجا فعلا خبری نیست و ری استارت نکردم . بازم باید زمان بدم ببینم چی میشه . اما هر چی هست از نسخه 0.4.x که کردم اینطوری شد .

سلام تا اینجا تغییر خاصی پیش نیومده؟

**Comment by upgo7502** [comment]
> > فعلا که نسخه xray رو روی 0.4.6 کردم 1.8.4 .. تا اینجا فعلا خبری نیست و ری استارت نکردم . بازم باید زمان بدم ببینم چی میشه . اما هر چی هست از نسخه 0.4.x که کردم اینطوری شد .
> 
> سلام تا اینجا تغییر خاصی پیش نیومده؟

فعلا چیزی هنگ نکرده . هر زمان که هنگ کنه درجا همینجا اصلاع میدم

مرسی

**Comment by SaintShit** [comment]
> > > فعلا که نسخه xray رو روی 0.4.6 کردم 1.8.4 .. تا اینجا فعلا خبری نیست و ری استارت نکردم . بازم باید زمان بدم ببینم چی میشه . اما هر چی هست از نسخه 0.4.x که کردم اینطوری شد .
> > 
> > 
> > سلام تا اینجا تغییر خاصی پیش نیومده؟
> 
> فعلا چیزی هنگ نکرده . هر زمان که هنگ کنه درجا همینجا اصلاع میدم
> 
> مرسی

سلام، همچنان قطع نشده؟

**Comment by upgo7502** [comment]
> > > > فعلا که نسخه xray رو روی 0.4.6 کردم 1.8.4 .. تا اینجا فعلا خبری نیست و ری استارت نکردم . بازم باید زمان بدم ببینم چی میشه . اما هر چی هست از نسخه 0.4.x که کردم اینطوری شد .
> > > 
> > > 
> > > سلام تا اینجا تغییر خاصی پیش نیومده؟
> > 
> > 
> > فعلا چیزی هنگ نکرده . هر زمان که هنگ کنه درجا همینجا اصلاع میدم
> > مرسی
> 
> سلام، همچنان قطع نشده؟

نه فعلا خبری نیست

مرسی

**Comment by SaintShit** [comment]
اگر هنوز این مشکل وجود داره، پنل رو به نسخه v.0.4.8 آپدیت کنید (نسخه هسته xray به 1.8.8 تغییر کرده). ممنون میشم در صورتی که ادامه دار بود مشکل اینجا گزارش کنید.

**Comment by upgo7502** [comment]
> اگر هنوز این مشکل وجود داره، پنل رو به نسخه v.0.4.8 آپدیت کنید (نسخه هسته xray به 1.8.8 تغییر کرده). ممنون میشم در صورتی که ادامه دار بود مشکل اینجا گزارش کنید.

یه کم میترسم بروز کنم .. ولی چشم بروز میکنم . الان که با 1.8.4 هست اوکیه ولی مجبورم بروز کنم . 

سپاس

**Comment by SaintShit** [comment]
> > اگر هنوز این مشکل وجود داره، پنل رو به نسخه v.0.4.8 آپدیت کنید (نسخه هسته xray به 1.8.8 تغییر کرده). ممنون میشم در صورتی که ادامه دار بود مشکل اینجا گزارش کنید.
> 
> یه کم میترسم بروز کنم .. ولی چشم بروز میکنم . الان که با 1.8.4 هست اوکیه ولی مجبورم بروز کنم .
> 
> سپاس

اگر نسخه هسته رو 1.8.4 کردین بعد از آپدیت هم همون نسخه میمونه، تغییرات عمده‌ای پیش نیومده توی نسخه جدید. فقط برای درخواست هایی که به سمت نود های رست ساخته میشه تایم‌اوت تعیین شده تا از گیر کردن جاب هایی که حجم کاربر ها رو محاسبه میکنه و سلامت نود هارو بررسی میکنه جلوگیری کنه.

**Comment by upgo7502** [comment]
چشم انجام میدم . 

سپاس

**Comment by LonUp** [comment]
سینت عزیز . یکی از دوستان منم این مشکلو داره ولی من ندارم این مشکلو . رم و سی پیو سرور تا حد زیادی بالا میره 
اینم شاتیه که هنگام بالا رفتن رم و سیپیو داده
![image](https://github.com/Gozargah/Marzban/assets/91155537/6331ced1-85fc-4d17-95f7-0d1904c632af)

ایشون گفتن مشکل از اپدیت ۴.۶ به وجود اومده روی نسخه پایدار

**Comment by ImMohammad20000** [comment]
> سینت عزیز . یکی از دوستان منم این مشکلو داره ولی من ندارم این مشکلو . رم و سی پیو سرور تا حد زیادی بالا میره 
> اینم شاتیه که هنگام بالا رفتن رم و سیپیو داده
> ![image](https://github.com/Gozargah/Marzban/assets/91155537/6331ced1-85fc-4d17-95f7-0d1904c632af)
> 
> ایشون گفتن مشکل از اپدیت ۴.۶ به وجود اومده روی نسخه پایدار

توی ورژن جدید هم این مشکل رو دارید؟

**Comment by LonUp** [comment]
> > سینت عزیز . یکی از دوستان منم این مشکلو داره ولی من ندارم این مشکلو . رم و سی پیو سرور تا حد زیادی بالا میره
> > اینم شاتیه که هنگام بالا رفتن رم و سیپیو داده
> > ![image](https://private-user-images.githubusercontent.com/91155537/309040217-6331ced1-85fc-4d17-95f7-0d1904c632af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzM0NDQsIm5iZiI6MTcwOTIzMzE0NCwicGF0aCI6Ii85MTE1NTUzNy8zMDkwNDAyMTctNjMzMWNlZDEtODVmYy00ZDE3LTk1ZjctMGQxOTA0YzYzMmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE4NTkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYmJmNTZiZWU4YmYyNDg4Mzg3OTQ5YjZiZDQ4YjcxZmJhMzU2ODBjNzkyM2Q0OTBiOWZlMzVkN2Y1NTA5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OA3Xb94xfBmFtAsEYwZxb_vHxF1UUFf_Lbb09R35rww)
> > ایشون گفتن مشکل از اپدیت ۴.۶ به وجود اومده روی نسخه پایدار
> 
> توی ورژن جدید هم این مشکل رو دارید؟

الان بهش گفتم اپدیت کنه و بگه نتیجه رو  .

**Comment by upgo7502** [comment]
فعلا با 0.4.8 و 1.8.4 دارم کار میکنم خبری نیست . اوکیه

**Comment by upgo7502** [comment]
چشم

**Comment by LonUp** [comment]
خب دوست منم گفت در 0.4.8 فعلا مشکلی پیش نیومده .  ولی گفت باید چند روز بگذره تا مطمئن شه

**Comment by upgo7502** [comment]
از زمانی که هسته رو کردم 1.8.8 و نسخه رو به 0.4.9 بروز کردم بازم باید هر چند ساعت 1 بار ری استارت بدم . با این تفاوت که خیلی کمتر ...
ولی در روز 2 3 باری ری استارت نیاز داره . اونم از نوع restart core از توی پنل مرزبان

**Comment by upgo7502** [comment]
سوالم اینه که هسته 1.8.4 چه مشکلاتی داره ؟ اگر مشکلی نداره فعلا روی 1.8.4 باشم

**Comment by upgo7502** [comment]
نسخه 1.8.4 باگ بخصوصی نداره که ؟

**Comment by ImMohammad20000** [comment]
> نسخه 1.8.4 باگ بخصوصی نداره که ؟

نه مشکلی نداره

**Comment by KAJOOSH** [comment]
من نسخه ی 0.3.2 و 1.8.8 هستم و **مشکلی ندارم** !

**Comment by upgo7502** [comment]
**بعد از مدت ها تست نتیجه زیر بدت اومد :**

برای بالای 500 کاربر Online اگر نسخه 0.4.9 مربازن رو با xray 1.8.8 / 1.8.9 / 1.8.7 نصب کنید قطعا توی طول روز نیاز 1 الی 5 بار ری استارت دارید ولی اگر نسخه xray 1.8.4 رو نصب کنید نیازی به ری استارت پیدا نمیکنید . 

**تست بالا روی شرایط متفاوت و سرور های متفاوتی با دوستان انجام شده .** 
رم های تست شده : 32 گیگ الی 128 گیگ DDR3 / DDR4
پردازنده ها : 24 هسته الی 56هسته ( با احتساب ترد ) سرور اختصاصی میباشد ( مدل G8 / G9 )
پورت شبکه در همه حالت ها فیبر 10 گیگابیت . 
هارد های تست شده : سامسونگ SSD EVO و NVMe Pro

**Comment by upgo7502** [comment]
جهت اطلاعرسانی :
خب الان بیشتر از 1 ماه گذشته و بانسخه 0.4.9 و xray 1.8.4 داریم کار میکنیم و تا حالا نیاز به 1 بار ری استارت هم نبوده .

**Comment by storevpsnet** [comment]
سلام مرزبان ورژن v0.5.2

 مصرف رم از 500 مگ میبره یک دفعه به 1.8 گیگ و هنگ میکنه و کانکشن ها هم قطع میشن

**Comment by LonUp** [comment]
یکی دیگه هم همین مشکلو داشت . متوجه شدیم داره دیداس میخوره و از مرزبان نیست ...

**Comment by Hsnmsri** [comment]
سلام من این مشکل رو روی ورژن 0.7.0 مرزبان با ورژن v24.10.31 دارم و کرون جاب نوشتم هر 10 دقیقه دستور marzban restart اجرا بشه تا قطعی پیش نیاد ولی با این حال دوباره به مشکل میخورم . چیکار کنم؟ بالای 500 یوزر هم دارم

**Comment by M03ED** [comment]
> سلام من این مشکل رو روی ورژن 0.7.0 مرزبان با ورژن v24.10.31 دارم و کرون جاب نوشتم هر 10 دقیقه دستور marzban restart اجرا بشه تا قطعی پیش نیاد ولی با این حال دوباره به مشکل میخورم . چیکار کنم؟ بالای 500 یوزر هم دارم

ورژن دیگه ای از xray رو استفاده کنید

**Comment by Hsnmsri** [comment]
> > سلام من این مشکل رو روی ورژن 0.7.0 مرزبان با ورژن v24.10.31 دارم و کرون جاب نوشتم هر 10 دقیقه دستور marzban restart اجرا بشه تا قطعی پیش نیاد ولی با این حال دوباره به مشکل میخورم . چیکار کنم؟ بالای 500 یوزر هم دارم
> 
> ورژن دیگه ای از xray رو استفاده کنید

فقط ورژن های 
1: v24.10.31
2: v24.10.16
3: v24.9.30
4: v24.9.19
5: v24.9.16 
رو دارم و همشون رو امتحان کرد. هیچکدوم درست کار نمیکنه

**Comment by ImMohammad20000** [comment]
> > > سلام من این مشکل رو روی ورژن 0.7.0 مرزبان با ورژن v24.10.31 دارم و کرون جاب نوشتم هر 10 دقیقه دستور marzban restart اجرا بشه تا قطعی پیش نیاد ولی با این حال دوباره به مشکل میخورم . چیکار کنم؟ بالای 500 یوزر هم دارم
> > 
> > ورژن دیگه ای از xray رو استفاده کنید
> 
> فقط ورژن های 
> 1: v24.10.31
> 2: v24.10.16
> 3: v24.9.30
> 4: v24.9.19
> 5: v24.9.16 
> رو دارم و همشون رو امتحان کرد. هیچکدوم درست کار نمیکنه

سلام مشکل از هسته هست v1.8.24 رو استفاده کنید

**Comment by LonUp** [comment]
> > سینت عزیز . یکی از دوستان منم این مشکلو داره ولی من ندارم این مشکلو . رم و سی پیو سرور تا حد زیادی بالا میره
> > اینم شاتیه که هنگام بالا رفتن رم و سیپیو داده
> > ![image](https://private-user-images.githubusercontent.com/91155537/309040217-6331ced1-85fc-4d17-95f7-0d1904c632af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTAxMjMsIm5iZiI6MTczMDk0OTgyMywicGF0aCI6Ii85MTE1NTUzNy8zMDkwNDAyMTctNjMzMWNlZDEtODVmYy00ZDE3LTk1ZjctMGQxOTA0YzYzMmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAzMjM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNjE5ODRhN2U4ODkwNjU1ZTUzOWJkMGI5MWMzYzg1OWY2MDI4ZjkzZjE5ZmIxNGI5ZDZjMDA0MzZkY2VjMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPlYdnLvuS5sTa1vGGh0mnm2shblBehzpX70gUmAfDU)
> > ایشون گفتن مشکل از اپدیت ۴.۶ به وجود اومده روی نسخه پایدار
> 
> توی ورژن جدید هم این مشکل رو دارید؟

با تغییر هسته حل شده . و با ۱.۸.۲۴ و ورژن ۷ مشکلی نیست
