### ISSUE TITLE
مشکل بهم ریختگی تاریخ در واست آپ

### ISSUE THREAD

**Issue by upgo7502** [Gozargah/Marzban#815]
با درود فراوان خدمت شما و سپاس از زحماتتان

در وی تو ری تاریخ واتس آپ بعضی مواقع بهم میریزه  . حتی آی پی هم تغییر میدم ولی بازم خود به خود بهم میریزه و تاریخ 1900 رو نشون میده و بعد از چند ساعت خودش درست میشه . 

مشکل از چی میتونه باشه ؟

سپاس فراوان

**Comment by M03ED** [comment]
لطفا از باز کردن issue راجع به موضوعات غیر مرتبط با مرزبان خود داری کنید

**Comment by upgo7502** [comment]
بله . میدونم و پوزش میخواهم . ولی خیلی کلافم کرد گفتم از تجربیات شما هم کمک بگیرم . بازهم پوزش
