### ISSUE TITLE
مصرف دو یا چند برابر کاربر در صورت استفاده از برنامه دانلود منیجر

### ISSUE THREAD

**Issue by qirmizialma** [Gozargah/Marzban#817]
![dynamic](https://github.com/Gozargah/Marzban/assets/119656991/b60292ca-09a0-4c5d-a3c3-3de733750ddd)
 با سلام و و خسته نباشید خدمت توسعه دهندگان گرامی مرزبان!
 من اخیرا به این نکته پی بردم که وقتی کاربری برای دانلود از برنامه اینترنت دانلود منیجر (تصویر بالا) استفاده میکنه حجم مصرفی برای کاربر بیشتر می افته. حدودا دو یا دو و نیم برابر. در صورتی که تعدا کانکشن ها رو فقط روی یک تنظیم کردم مشکل برطرف شد. (تضویر پایین)
![Screenshot 2024-02-24 233311](https://github.com/Gozargah/Marzban/assets/119656991/6b6572ee-9935-4470-b5f1-6bde112ea037)
لطفا اگه این قضیه به خود اسکریپت مرزبان مربوط میشه بررسی کنید

**Comment by mdjvd** [comment]
قبلا دوستان بررسی کردن و نتیجه این شد که به خاطر پکت لاس هست و به مرزبان مربوط نیست.

**Comment by SaintShit** [comment]
@qirmizialma سلام، درواقع مرزبان اطلاعات مصرف کاربر رو از Xray میگیره و ذخیره میکنه.
اگر براتون مقدور بود، با هسته های دیگه یا پنل دیگه‌ای هم بررسی کنید ببینید برای اون‌ها هم پیش میاد یا نه.

**Comment by qirmizialma** [comment]
@SaintShit 
با پنل ثنایی هم امتحان کردم و با اون هم این مشکل وجود داره. حتی تو اون بدتره و با یک کانکشن حجم رو یک و نیم برابر نشون میده. فقط موقع دانلود با خود گوگل کروم حجم اضافه نمی اندازه. با پنل های دارای هسته سینگ باکس چون آشنا نیستم نتونستم امتحان کنم

**Comment by xmohammad1** [comment]
> @SaintShit با پنل ثنایی هم امتحان کردم و با اون هم این مشکل وجود داره. حتی تو اون بدتره و با یک کانکشن حجم رو یک و نیم برابر نشون میده. فقط موقع دانلود با خود گوگل کروم حجم اضافه نمی اندازه. با پنل های دارای هسته سینگ باکس چون آشنا نیستم نتونستم امتحان کنم

هیدیفای رو هم چک کنید اگه میتونید

**Comment by LonUp** [comment]
پنل xm plus هم بر پایه ایکسری هست و فکنم مشکلی نداشته باشه . ولی خب دوستان تست کنن بهتره. میشه جز اپشن ها برای الگو برداری قرارداد . چون پنل نسخه پولی هم داره و نسبتا حرفه ای تره فکر میکنم مشکلی نداشته باشه در این مورد

**Comment by LonUp** [comment]
هیدیفای هم چون ایکسری کاستوم شده داره میتونه مناسب باشه . چون هرچی هست مرتبط با هسته ایکسری هست .  و مال هیدیفای و ایکس ام پلاس کاستوم شدس هر دو . حالا این کاستوم شدن چه تغییراتی کرده رو باید برسی کرد ولی ممکنه حل شده باشه این مشکلات

**Comment by ZakariaRasoli** [comment]
> هیدیفای هم چون ایکسری کاستوم شده داره میتونه مناسب باشه . چون هرچی هست مرتبط با هسته ایکسری هست . و مال هیدیفای و ایکس ام پلاس کاستوم شدس هر دو . حالا این کاستوم شدن چه تغییراتی کرده رو باید برسی کرد ولی ممکنه حل شده باشه این مشکلات

از این xm plus میشه تو مرزبان استفاده کرد ؟

**Comment by raminsajedi** [comment]
> @qirmizialma سلام، درواقع مرزبان اطلاعات مصرف کاربر رو از Xray میگیره و ذخیره میکنه. اگر براتون مقدور بود، با هسته های دیگه یا پنل دیگه‌ای هم بررسی کنید ببینید برای اون‌ها هم پیش میاد یا نه.

من الان یه عالمه تست گرفتم این مشکل برای من فقط روی یک حالت رخ میده 
مولتی کانکشن و کانفیگ های cdn ام !
خیلی عجیبه 
روی کانفیگ مستقیم مولتی تست کردم اوکیه
روی کانفیگ مستقیم هم سینگل میزنم اوکیه
کانفیگ سی دی انم هم سینگل میزنم اوکیه
کانفیگ سی دی ان مولتی که میزنم قشنگ 2-3 برابر حجم را محاسبه میکنه 😳
ویرایش : یه تونل ریورس هم دارم اونم 2 برابر حساب میکنه توی مولتی کانکشن

**Comment by AliM1988** [comment]
بنظرم پنل مرزبان بهتره محاسبه حجم ترافیک رو بجای XRAY از nginx یا سرویس های مشابه بخونه. اینجوری مشکل حل میشه
