### ISSUE TITLE
Record by domain the amount of traffic spent

### ISSUE THREAD

**Issue by Jolymmiles** [Gozargah/Marzban#818]
**Is your feature request related to a problem? Please describe.**
Tracking and recording the amount of traffic spent by domain is crucial for a variety of reasons. Firstly, it provides a granular understanding of where our users are spending the most time, which can help us better tailor content, improve user experience, and optimize our platform for increased engagement. Additionally, it can help identify and mitigate issues, such as slow-loading pages or high bounce rates, that might be affecting the user experience negatively. Lastly, having this data can also be useful for marketing and sales purposes, as it provides valuable insights into user behavior and preferences.

**Describe the solution you'd like**
I would like to implement a feature that allows us to track and record the amount of traffic spent by domain. This feature should be easy to use and integrate seamlessly with our existing analytics tools. It should also provide detailed reports and visualizations that allow us to easily analyze the data and draw meaningful insights from it. 

**Describe alternatives you've considered**
One alternative solution would be to manually track and record the amount of traffic spent by domain using spreadsheets or other tools. However, this would be time-consuming and error-prone, and would not provide the same level of detailed analysis and insights as an automated solution. Another alternative would be to use third-party analytics tools that offer similar functionality. However, this would require us to invest in additional tools and services, and may not be as customizable or tailored to our specific needs as a custom-built solution.

**Comment by M03ED** [comment]
this feature have few problem 
first of all implementing this feature can make database grow very fast and make slow marzban slow and hard to use 
second marzban it's a project to help people access to free internet adding this feature can transform marzban to a spyware 
if you need this feature you can implement it as a third party project that use marzban api to record data you want
