### ISSUE TITLE
مشکل در اضافه کردن سایت هایی با ای پی v4

### ISSUE THREAD

**Issue by fireggod75** [Gozargah/Marzban#823]
![New Project](https://github.com/Gozargah/Marzban/assets/11144763/cb13cbdf-bb89-4366-b0ca-d349831a2fe1)

این دو مدل کد رو به config اضافه میکنم ولی برنامه ارور میده.ممتوت میشم راهنمایی کنید
1-
{
    "type": "field",
    "outboundTag": "IPv4",
    "domain": [
      "domain:google.com",
      "domain:instagram.com"
    ]
  }
2-
{
        "domain": [
          "domain:google.com",
          "domain:instagram.com"
        ],
        "outboundTag": ""IPv4",
        "type": "field"
      }

**Comment by SaintShit** [comment]
سلام
اوتباند IPv4 وجود داره؟

**Comment by M03ED** [comment]
لطفا اگر مشکلی براتون پیش میاد و براش issue باز می کنید حداقل به issue جواب بدید و اطلاعات خواسته شده رو ارسال کنید
