### ISSUE TITLE
ارور در دیتابیس  بعد از اپدیت

### ISSUE THREAD

**Issue by mahanhpn** [Gozargah/Marzban#824]
با عرض سلام بنده از ورژن 4.3 استفاده میکنم زمانی که قصد اپدیت به ورژن 4.6 را دارم و از کامند marzban update استفاده میکنم بعد از اتمام اپدیت دیگر امکان ورود به پنل برای من مقدور نمیباشد
در مرزبان لاگ با ارور زیر مواجه میشوم که مربوط به عدم وجود فیلد های دیسکورد وبهوک و تلگرام ایدی میباشد
<img width="1470" alt="Screenshot 1402-12-09 at 1 57 58 AM (2)" src="https://github.com/Gozargah/Marzban/assets/153385069/7deffe8c-9e06-4137-966a-6497a171510d">

**Comment by mahanhpn** [comment]
بنده تلاش کردم تا به صورت پله ای از ورژن 0.4.3 به ورژن 0.4.4 و سپس بقیه ورژن ها برم اما متاسفانه ورژن 0.4.4 رو که نصب میکنم باز هم با این ارور مواجه میشم

**Comment by mdjvd** [comment]
سلام. مرزبان رو ری استارت کردید ببینید مشکل حل میشه یا نه؟
`marzban restart`

**Comment by SaintShit** [comment]
سلام، بعد از ری‌استارت یه سری لاگ مرتبط با alembic پرینت میشه براتون. از اونا عکس بفرستید

**Comment by mahanhpn** [comment]
بله ری استارت کردم . الان مجدد اپدیت میکنم خدمتتون عکس ارسال میکنم

**Comment by mahanhpn** [comment]
<img width="1470" alt="Screenshot 1402-12-09 at 4 15 54 PM 2" src="https://github.com/Gozargah/Marzban/assets/153385069/51cbfbaf-1a0c-465b-ace8-5f359d710b5e">

**Comment by SaintShit** [comment]
توی عکسی که فرستاین MySQL هنوز کامل بالا نیومده و هنوز مرزبان بهش وصل نشده، پایین تر بعد چند بار ری‌استارت بهش وصل میشه، از اونجا عکس بدین. یا depend کنید کانتینر مرزبان رو به کانتینر mysql که این ارورو گاهی اوقات نده بهتون

**Comment by mahanhpn** [comment]
<img width="1470" alt="Screenshot 1402-12-09 at 7 11 27 PM" src="https://github.com/Gozargah/Marzban/assets/153385069/8a6259bf-bb48-43bd-9636-5be19cdf59d0">
<img width="1470" alt="Screenshot 1402-12-09 at 7 11 31 PM" src="https://github.com/Gozargah/Marzban/assets/153385069/f895ab66-a2e9-45b9-ab94-e3e2671d0ebc">
<img width="1470" alt="Screenshot 1402-12-09 at 7 11 35 PM" src="https://github.com/Gozargah/Marzban/assets/153385069/8a2b967c-4c3b-4b79-a7af-af67b8dc22b0"><img width="1470" alt="Screenshot 1402-12-09 at 7 11 41 PM" src="https://github.com/Gozargah/Marzban/assets/153385069/ece5c076-8b63-4fc0-8915-9d817b11693e">


این تمام ارور هایی هست که بنده از مرزبان میگیرم بعد از ران شدن دیتابیس هم depend شده

**Comment by SaintShit** [comment]
متاسفانه توی هیچکدوم از لاگ ها اسکریپت های migration اجرا نشده
چون اون تایمی که migration ها اجرا میشه، دیتابیس هنوز لود کامل نشده و کانکشن ارور میشه، و بعد پنل ران میشه
این دستور رو ران کنید
```bash
cd /opt/marzban
docker compose exec marzban alembic upgrade head
```
نتیجشو اینجا ارسال کنید
بعدش پنلتون رو مجدد ری‌استارت کنید بررسی کنید ارور ها میره؟

**Comment by mahanhpn** [comment]
بله با استفاده از این کامند مشکل حل شد
ممنونم

**Comment by mahanhpn** [comment]
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 470465472326 -> 5575fe410515, add_telegram_id_to_admin
INFO  [alembic.runtime.migration] Running upgrade 5575fe410515 -> dd725e4d3628, fix_mysql_collations

🙏🏻این اطلاعات پرینت شد گفتم خدمتتون ارسال کنم شاید نیاز بشه . ممنونم بابت پاسخگوییتون

**Comment by Ebrahim49932** [comment]
سلام امروز پنل به مشکل خورده و اصلا بالا نمیاد 
با مرزبان ری استارت خطا میده از سمت دیتابیس راهی نیست اوکی شه ؟

**Comment by Ebrahim49932** [comment]
![Uploading Screenshot_2024-09-06-19-35-12-638_com.server.auditor.ssh.client.jpg…]()
