### ISSUE TITLE
وارد کردن لینک اشتراک در هیدیفای نکست

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#827]
در اپدیت جدید نسخه dev که همین ۳ ساعت پیش عرضه شده .  هنگام وارد کردن لینک اشتراک بر برنامه hiddify next به مشکل میخوره 
در اندروید که کلا میپره بیرون از برنامه
در ویندوز این پنجره نمایش داده میشه
![image](https://github.com/Gozargah/Marzban/assets/91155537/269f99ff-cca6-4df3-8142-94dabfe5d924)

این مشکل در نسخه پایدار latest نیست و فقط در نسخه اخر به این مشکل خورده .  و کاربران من روی این برنامه مشکل اپدیت دارن که مجبور شدم برگردم به نسخه latest

**Comment by SaintShit** [comment]
@LonUp سلام
فعلا روی نسخه v.0.4.6 بمونید، روی نسخه دو بخش سابکریپشن تغییر کرده برای اضافه شدن فرگمنت و custom config

**Comment by LonUp** [comment]
حله ممنون از زحماتتون  . درست خواهد شد ؟
فقر کنم بشه توی همون لینک اشتراک برای این برنامه کانفیگ جدا تعریف کرد . یعنی وقتی کلاینت هیدیفای نکست داره ریکوئیت میده که ساب رو بگیره .  نوع کلاینت اگه برابر با هیدیفای نکست بود کانفیگ جیسون رو وارد نکنه و یا طبق استاندارد های هیدیفای نکست وارد کنه

این برنامه هیدفای نکست از وارپ و فرگمنت پشتیبانی میکنه در خود برنامه ... فقط فکر کنم نوع وارد شدن کانفیگا اشتباه باشه حدس میزنم

**Comment by M03ED** [comment]
> حله ممنون از زحماتتون . درست خواهد شد ؟ فکر کنم بشه توی همون لینک اشتراک برای این برنامه کانفیگ جدا تعریف کرد . یعنی وقتی کلاینت هیدیفای نکست داره ریکوئست میده که ساب رو بگیره . نوع کلاینت اگه برابر با هیدیفای نکست بود کانفیگ جیسون رو وارد نکنه و یا طبق استاندارد های هیدیفای نکست وارد کنه
> 
> این برنامه هیدفای نکست از وارپ و فرگمنت پشتیبانی میکنه در خود برنامه ... فقط فکر کنم نوع وارد شدن کانفیگا اشتباه باشه حدس میزنم

نیازی به لینک اشتراک جدا نداره چون از همون استاندارد ها v2ray استفاده می کنه ، الان هم کانفیگ json ارسال نمیشه

**Comment by LonUp** [comment]
منظورم لینک جدا نبود
مثلا برای clash وقتی پنل میفهمه ریکوئست از سمت این برنامس.. با تمپلیت و قوانین و داکیومنت کلش میده اون کانفیگو بهش ... منظورم اینه برای هیدیفای نکست هم اگ مشکلی با جیسون داشته باشه میشه اینکارو کرد که اگه درخواست از سمت این برنامه بود جیسون نده کلا ..

**Comment by M03ED** [comment]
> منظورم لینک جدا نبود مثلا برای clash وقتی پنل میفهمه ریکوئست از سمت این برنامس.. با تمپلیت و قوانین و داکیومنت کلش میده اون کانفیگو بهش ... منظورم اینه برای هیدیفای نکست هم اگ مشکلی با جیسون داشته باشه میشه اینکارو کرد که اگه درخواست از سمت این برنامه بود جیسون نده کلا ..

همون طور که گفتم json ارسال نمیشه ...

**Comment by LonUp** [comment]
خب مشکلش از چیه پس. یعنی الان درست شده مشکل در ادد شدن کانفیگ یا اپدیت در هیدیفای نکست ؟
