### ISSUE TITLE
مرتب سازی هاست ها 

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#828]
بنظر من قابلیت مرتب سازی هاست ها بدون توجه به پرتکل میتونه ایده جالبی باشه تا کانفیگ هایی که میخوایم کنار هم قرار بگیرن. این مرتب سازیم میتونه با یک مقدار ولیو از ۰۱ تا مثلا ۱۰۰ ادامه پیدا کنه .  یه کادر باشه برای اینکه مقدار مدنظر رو وارد کنیم و اون کانفیگ در ترتیب مدنظر  در کلاینت به ترتیبی که عدد گزاری شده نمایش داده بشه

**Comment by M03ED** [comment]
این ایده چندین بار قبلا مطرح شده ، لطفا قبل از باز کردن issue جدید از تکراری نبودن اون مطمئن بشید
