### ISSUE TITLE
فرگمنت

### ISSUE THREAD

**Issue by tohid3aeed** [Gozargah/Marzban#829]
ترتیب متغیرهای فرگمنت تو v2boxمنفاوته
و اصلا پکت tlshello رو قبول نمیکنه
اگر امکانش باشه جداگانه تنظیم بشه عالی میشه
بازم دمتون گرم که این قابلیت رو اضافه کردید
همینجوریشم عالیه

**Comment by M03ED** [comment]
> ترتیب متغیرهای فرگمنت تو v2boxمنفاوته و اصلا پکت tlshello رو قبول نمیکنه اگر امکانش باشه جداگانه تنظیم بشه عالی میشه بازم دمتون گرم که این قابلیت رو اضافه کردید همینجوریشم عالیه

ایجاد یک کلاس جدید صرفا برای یک فیلد کار منطقی ای نیست ، ارتباط گرفتن با سازنده برنامه و رفع مشکل راح حل بهتری هست
