### ISSUE TITLE
ادیت نشدن یوزر ها

### ISSUE THREAD

**Issue by esodrevo** [Gozargah/Marzban#831]
بعد از اپدیت به نسخه 0.4.6 lastest ، دکمه edit user کاربرا از کار افتاده و فقط کابر های جدید ایجاد شده رو میشه ادیت زد ، این مشکل هم از سمت پنل وجود داره و هم ربات خود مرزبان. 
ممنون میشم بررسی کنید. با تشکر از زحمات تیم مرزبان

**Comment by M03ED** [comment]
> بعد از اپدیت به نسخه 0.4.6 lastest ، دکمه edit user کاربرا از کار افتاده و فقط کابر های جدید ایجاد شده رو میشه ادیت زد ، این مشکل هم از سمت پنل وجود داره و هم ربات خود مرزبان. ممنون میشم بررسی کنید. با تشکر از زحمات تیم مرزبان

لاگ مرزبان رو ارسال کنید

**Comment by esodrevo** [comment]
> > بعد از اپدیت به نسخه 0.4.6 lastest ، دکمه edit user کاربرا از کار افتاده و فقط کابر های جدید ایجاد شده رو میشه ادیت زد ، این مشکل هم از سمت پنل وجود داره و هم ربات خود مرزبان. ممنون میشم بررسی کنید. با تشکر از زحمات تیم مرزبان
> 
> لاگ مرزبان رو ارسال کنید

![Screenshot (1)](https://github.com/Gozargah/Marzban/assets/134785284/5504225f-c2ca-4353-9c3b-2ca6cedeedc2)
![Screenshot (2)](https://github.com/Gozargah/Marzban/assets/134785284/faf43393-8e2a-4829-b8ca-a6754d12f4c1)

**Comment by esodrevo** [comment]
> > بعد از اپدیت به نسخه 0.4.6 lastest ، دکمه edit user کاربرا از کار افتاده و فقط کابر های جدید ایجاد شده رو میشه ادیت زد ، این مشکل هم از سمت پنل وجود داره و هم ربات خود مرزبان. ممنون میشم بررسی کنید. با تشکر از زحمات تیم مرزبان
> 
> لاگ مرزبان رو ارسال کنید

حتی نمیتونم پاک کنم اکانت هارو

**Comment by LonUp** [comment]
ایا دیتابیست مای اس کیو ال هست ؟

**Comment by esodrevo** [comment]
> ایا دیتابیست مای اس کیو ال هست ؟

بله

**Comment by esodrevo** [comment]
بله فکر کنم مشکل از همین مورد که فرمودید بود،

DELETE FROM exclude_inbounds_association
WHERE (proxy_id, inbound_tag) IN (
    SELECT proxy_id, inbound_tag
    FROM (
        SELECT proxy_id, inbound_tag
        FROM exclude_inbounds_association
        GROUP BY proxy_id, inbound_tag
        HAVING COUNT(*) > 1
    ) AS ACLover
);

به راهنمایی یکی از بچه ها ، این کوئری رو اجرا کردم ، مثل اینکه مشکل حل شده
