### ISSUE TITLE
برخورد با ارور 500 بعد از اپدیت به 4.6

### ISSUE THREAD

**Issue by janahnovin** [Gozargah/Marzban#832]
سلام  بعد از اپدیت پنل بعضی مواقع روی پورتوکل gepc و پنل داشبود ارور 500 سرور داخلی دریافت میشه عکس ارور ضمیمه شد
![IMG_۲۰۲۴۰۲۲۹_۱۵۱۴۴۴](https://github.com/Gozargah/Marzban/assets/134630315/6ba24d23-6888-4dc4-af39-48bfeb045c1b)

**Comment by SaintShit** [comment]
سلام، اروری که ارسال کردید برای nginx هست و ممکنه به دلیل کانفیگ های شما باشه. بهتره اطلاعات بیشتری درباره نحوه کانفیگ کردنتون و دلیل استفاده از nginx ارائه بدین.

**Comment by arian24b** [comment]
از error log انجینیکست و لاگ پنل خروجی بگیر، بفرستین اینجا بتونیم چک کنیم.
البته ممکنه بخاطر تنظیمات اشتباه ssl سمت nginx هم باشه.
