### ISSUE TITLE
مشکل رسپانسیو در موبایل

### ISSUE THREAD

**Issue by hamed221** [Gozargah/Marzban#834]
هنوز مشکل پا برجاست بعد از آپدیت به نسخه جدید
تعداد کارکتر رو از یه اندازه که بیشتر میذارم برای یوزرها کلا رسپانسیو بهم میریزه و بخش ویرایش کاربران از صفحه خارج میشه
![Screenshot 2024-03-01 192447](https://github.com/Gozargah/Marzban/assets/59690279/69cea43d-afd7-4280-80fe-2606fab8e830)

**Comment by gozarman** [comment]
This issue should be fixed in [ccbe12d](https://github.com/Gozargah/Marzban/commit/ccbe12d3a7085cc626834413b32a4748ea831de2) commit.

Stay tuned for the next version release.
