### ISSUE TITLE
Sing-box & v2rayNG Json Config Critical Bugs ❗️❗️❗️

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#837]
TCP config have no Header and Path in v2rayNG Json config! (i use latest dev)

2 other bugs was not related to panel i removed from issue

**Comment by M03ED** [comment]
> TCP config have no Header and Path in v2rayNG Json config! (i use latest dev)
> 
> 2 other bugs was not related to panel i removed from issue

this bug is fixed cdd87e197d27dae0904901787e9458f5dfd670b4 but if you set host and path in host settings this will happen

**Comment by fodhelper** [comment]
Ah so that was the problem, will it get fixed?

**Comment by M03ED** [comment]
just make path and host empty

**Comment by fodhelper** [comment]
I did it, not works

**Comment by M03ED** [comment]
> I did it, not works

be sure you have lastest version of dev

**Comment by fodhelper** [comment]
Yes, i am sure. Maybe it's because of Case Sensitivity of Header names
Could you send a working sample please?

**Comment by M03ED** [comment]
> Yes, i am sure. Maybe it's because of Case Sensitivity of Header names Could you send a working sample please?

![image](https://github.com/Gozargah/Marzban/assets/50927468/0dbd5f8f-fa5d-405c-aad2-2db2682c1f65)

**Comment by M03ED** [comment]
ok now im sure your not using latest version of dev because in last version useragent in tcp http is empty and its not mozila
https://github.com/Gozargah/Marzban/blob/dev/app/subscription/v2ray.py#L298

**Comment by fodhelper** [comment]
That was actually another Issue and that was screenshot of my custom xray config
I am using latest dev image
And your temporary solution not worked for me. i tested it many times
Even if it does work- i need to set custom path in host settings of panel for each tcp host (for routing)

> this bug is fixed [cdd87e1](https://github.com/Gozargah/Marzban/commit/cdd87e197d27dae0904901787e9458f5dfd670b4) but if you set host and path in host settings this will happen

Please fix it

**Comment by M03ED** [comment]
> That was actually another Issue and that was screenshot of my custom xray config I am using latest dev image And your temporary solution not worked for me. i tested it many times Even if it does work- i need to set custom path in host settings of panel for each tcp host (for routing)
> 
> > this bug is fixed [cdd87e1](https://github.com/Gozargah/Marzban/commit/cdd87e197d27dae0904901787e9458f5dfd670b4) but if you set host and path in host settings this will happen
> 
> Please fix it

path and are only available for tcp http header , not other configurations with tcp , this is xray limite 
check [document](https://xtls.github.io/en/config/transports/tcp.html#httpheaderobject)

**Comment by fodhelper** [comment]
Yes, i am talking tcp http header too with custom header and path in marzban's host settings
It's literally working on every single app like nekoray for example
the only problem is v2rayNG Json config

**Comment by M03ED** [comment]
#842

**Comment by fodhelper** [comment]
by this Patch, can we set custom Header and Path in Host Settings for TCP+HTTP Hosts?
