### ISSUE TITLE
Random User-Agent for non-TLS configs

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#839]
Many clients are accepting json config list so Marzban can send each user a random User-agent
We can add a list ourselves or can use Fingerprint in Hosts settings or non-tls configs
![image](https://github.com/Gozargah/Marzban/assets/161948085/9970dc3c-aebb-490d-b29b-124e423f6a80)

**Comment by M03ED** [comment]
fingerprint and user agent are not same thing , also adding column to database for just a specific type of config its irrational.
in this case were using v2rayn default user-agent

**Comment by fodhelper** [comment]
That default Golang user-agent of most of clients seems really bad to me

**Comment by M03ED** [comment]
> That default Golang user-agent of most of clients seems really bad to me

your not only guy use marzban

**Comment by fodhelper** [comment]
yes, but i mean if user agent be like a browser, it's harder for firewall to detect and block our ips
cores made it possible to have custom request headers, it was good if panels use that options to make proxy ip and connections more undetectable

**Comment by M03ED** [comment]
> yes, but i mean if user agent be like a browser, it's harder for firewall to detect and block our ips
> cores made it possible to have custom request headers, it was good if panels use that options to make proxy ip and connections more undetectable

Do you have any proof that show GFW check user agent and use it for detection?

**Comment by fodhelper** [comment]
They detect notls ws cloudflare connections really fast and block domains, maybe they use this?
But even if they didn't used it yet, what if they do in future? we can make connections like regular web browsing by setting a fake user-agent, as proxy cores did for tls proxies before (by using uTLS that makes tls fingerprints look like regular web browsers)

**Comment by SaintShit** [comment]
@fodhelper hello, I really don't get the point. You already can define a response header and put user-agent what you like in your json config, isn't it?

**Comment by SaintShit** [comment]
@fodhelper https://xtls.github.io/config/transports/tcp.html#httpheaderobject

**Comment by SaintShit** [comment]
@fodhelper My bad. it's request that sends user-agent not response. Maybe I shouldn't trynna response to issues at 2AM.

**Comment by SaintShit** [comment]
@fodhelper that's not a big deal tho, I'll add it

**Comment by fodhelper** [comment]
Yes i meant request packets too, Panel can add a random User-Agent in Clash, Clash Meta, Sing Box and v2rayNG Json
Then when client start connection, it will use a browser user-agent and firewall can't tell if user is using a browser or a custom golang script (that is mostly proxy in this days)

**Comment by M03ED** [comment]
#1067
