### ISSUE TITLE
Feature title

### ISSUE THREAD

**Issue by hootlond** [Gozargah/Marzban#843]
Add json format in "links"(in this moment it's the plain text).
GET api/user/{username}
{
  "proxies": {},
  "expire": 0,
  "data_limit": 0,
  "data_limit_reset_strategy": "no_reset",
  "inbounds": {},
  "note": "string",
  "sub_updated_at": "2024-03-04T10:32:22.606Z",
  "sub_last_user_agent": "string",
  "online_at": "2024-03-04T10:32:22.606Z",
  "on_hold_expire_duration": 0,
  "on_hold_timeout": "2024-03-04T10:32:22.606Z",
  "username": "string",
  "status": "active",
  "used_traffic": 0,
  "lifetime_used_traffic": 0,
  "created_at": "2024-03-04T10:32:22.606Z",
  "links": [],
  "subscription_url": "",
  "excluded_inbounds": {}
}

**Comment by M03ED** [comment]
> Add json format in "links"(in this moment it's the plain text). GET api/user/{username} { "proxies": {}, "expire": 0, "data_limit": 0, "data_limit_reset_strategy": "no_reset", "inbounds": {}, "note": "string", "sub_updated_at": "2024-03-04T10:32:22.606Z", "sub_last_user_agent": "string", "online_at": "2024-03-04T10:32:22.606Z", "on_hold_expire_duration": 0, "on_hold_timeout": "2024-03-04T10:32:22.606Z", "username": "string", "status": "active", "used_traffic": 0, "lifetime_used_traffic": 0, "created_at": "2024-03-04T10:32:22.606Z", "links": [], "subscription_url": "", "excluded_inbounds": {} }

v2ray json format its too long and its not good to add it here 
you can add /v2ray-json to end of your sub link to download it
