### ISSUE TITLE
باگ رسپانسیو موبایل

### ISSUE THREAD

**Issue by hamed221** [Gozargah/Marzban#844]
سلام وقت بخیر

ممنون بابت برطرف کردن باگ قبلی

ولی همچنان مشکل داره باگ رسپانسیو موبایل

وقتی چندین یوزر با تعداد کارکترهای زیاد ساخته میشه و میخوام سرچ کنم فقط اون یدونه رو نمیاره و همه یوزرهایی که شبیه به هم هست رو بهم نشون میده

![Screenshot 2024-03-04 144708](https://github.com/Gozargah/Marzban/assets/59690279/5eb32b4d-e4c2-48a2-a569-2eaa497be039)

همینجور که میبینید کامل یوزر رو نشون نمیده 
اگر میشه یه کاریش کنید که یوزر رو به صورت کامل نمایش بده
تشکر

**Comment by M03ED** [comment]
> 
> وقتی چندین یوزر با تعداد کارکترهای زیاد ساخته میشه و میخوام سرچ کنم فقط اون یدونه رو نمیاره و همه یوزرهایی که شبیه به هم هست رو بهم نشون میده

در سرچ یوزر های مشابه سرچ میشه ، سرچ دقیق username وارد شده انجام نمیشه
> 
> همینجور که میبینید کامل یوزر رو نشون نمیده اگر میشه یه کاریش کنید که یوزر رو به صورت کامل نمایش بده تشکر

برای کامل نشون دادن باید فونت کوچک بشه که کار درستی نیست
