### ISSUE TITLE
Telegram bot doesn't work properly

### ISSUE THREAD

**Issue by mahdim10** [Gozargah/Marzban#845]
Hello,
First of all, I would like to thanks all Marzban developers. However, there seems to be an issue with the Telegram bot not sending notifications for users who are about to expire. This problem mostly occurs at 00:00 when multiple users are reaching their expiration time. While it successfully notifies about some users, as indicated in the screenshot, it fails to notify all of them.
Im using the 0.4.9 version.
![photo_2024-03-04_15-28-02](https://github.com/Gozargah/Marzban/assets/30717578/1cf379b2-2a35-4baf-840f-a3b0e9d2b115)
![photo_2024-03-04_15-28-06](https://github.com/Gozargah/Marzban/assets/30717578/204318c6-1827-4f96-bbce-755dad68577f)

**Comment by M03ED** [comment]
i have the same bug and i couldn't find why this is happening , if you find why this is happening send it here

**Comment by fodhelper** [comment]
seems like rate limit of telegram api

**Comment by M03ED** [comment]
> seems like rate limit of telegram api

nope its not that because users in begining of list will be skiped not last ones

**Comment by fodhelper** [comment]
maybe should change
https://github.com/Gozargah/Marzban/blob/b2ad111eaf7d802e9c747ff34710a407ba3d3319/app/telegram/handlers/report.py#L25-L26

to
```
        except Exception as e:
            logger.error(e)
```
to see what the error is?

**Comment by fodhelper** [comment]
I guess the problem could be this
https://github.com/Gozargah/Marzban/blob/1949717c0a622c20705f998e8e609263d660b269/app/utils/system.py#L119
It's a global variable, it can cause problems for urllib3 ipv6 connections (used in pyTelegramBotAPI too)
I have changed it in https://github.com/Gozargah/Marzban/pull/915 - maybe helps
