### ISSUE TITLE
تفاوت پورت لینک ساب با پورت پنل

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#846]
در جهت افزایش امنیت بیشتر . امکان این باشه که پورت ساب با پورت پنل متفاوت باشه تا کسی نتونه با برداشتن شناسه لینک ساب و افزودن /DASHBOARD به پنل برسه

همچنین بشه مقدار عبارت dashboard رو تغییر داد در جهت افزایش امنیت

**Comment by M03ED** [comment]
پیاده سازی این موارد روی مرزبان کار درستی نیست چرا که همین الان با ابزار هایی مثل haproxy و nginx میتونید همین الان این کار رو انجام بدید ، همچنین این تنظیمات میتونه برای هر فرد متفاوت باشه 
اموزش استفاده از haproxy هم در داکیومنت و هم در Discussions نوشته شده و می تونید مطالعه کنید
