### ISSUE TITLE
ساپورت کردن چندین هدر تی سی پی در یک کانفیگ

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#847]
درود و عرض خسته نباشید

امکان ست کردن چندین هدر در کانفیگ رو میشه داشته باشیم ؟ مثل این کانفیگ
vless://cbb26198-1272-4405-8179-887d4a7a52b6@1.1.1.1:443?encryption=none&security=none&type=tcp&headerType=http&host=1.com%2C2.com%2C3.com%2C4.com#LonUP

در حال حاضر میشه چند هدر تعیین کرد در ایکسری کور و هاست ستینگ که یکی ازونها برای کاربر بره به صورت رندوم .  امکان فرستادن چندین هدر هزمان هست؟ (چون این مورد رو در چندین کانفیگ دیدم دارم میگمش
و اگر در مرزبان چنین امکانی هست بگید از چه علائمی در هاست ستینگز استفاده کنم تا همه چند هدر تعریف شده همزمان برای کاربر ارسال شه

**Comment by ImMohammad20000** [comment]
میتونید توی hosts settings تعریف کنید به این شکل
```
1.com,2.com,3.com
```

**Comment by LonUp** [comment]
من تعریف کردم فقط یکیش میره متاسفانه . اینو تست کردم

**Comment by iamtheted** [comment]
Hi @LonUp 
have you tried adding them in host settings in the same format as you said?
It should include one of them randomly in the proxies each time you update your sub link

**Comment by erfjab** [comment]
امکان گذاشتن چندین آدرس آیپی و دامنه در قسمت address اضافه شده. ایشو به خاطر قدیمی بودن بسته میشه، اگر مشکل یا درخواستی داشتید ایشوی جدید باز کنید لطفا. با تشکر از همکاری شما.
