### ISSUE TITLE
تغیر ریسپانس برای یوزرایجنت دریافتی لینک ساب کاربر

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#848]
اگر بشه مقادیری در env تنظیم کرد که در بین یوزرایجنت هایی که وجود داره چه ریسپانسی دریافت بشه . عالی میشه .  مثلا ممکنه من بخوام ویتوری ان به صورت کاستوم کانفیگ بره . اما ویتوری انجی در اندروید کانفیگ عادی بره
مقادیر ساده سازی شده ای مثل
v2rayn_client_json = true / false

که بشه در env تغییر داد

**Comment by M03ED** [comment]
#782
