### ISSUE TITLE
how to configure Warp for specific websites

### ISSUE THREAD

**Issue by vahidxo** [Gozargah/Marzban#849]
I configure warp as wireguard in Xray-core like this
{
  "log": {
    "loglevel": "info"
  },
  "inbounds": [
    {
      "tag": "VLESS TCP REALITY",
      "listen": "0.0.0.0",
      "port": 8443,
      "protocol": "vless",
      "settings": {
        "clients": [],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "http",
            "request": {
              "method": "GET",
              "path": [
                "/"
              ],
              "headers": {
                "Host": [
                  ""
                ]
              }
            },
            "response": {}
          }
        },
        "security": "none"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIPv4"
      },
      "tag": "DIRECT"
    },
    {
      "protocol": "blackhole",
      "tag": "BLOCK"
    },
    {
      "protocol": "wireguard",
      "settings": {
        "secretKey": "2HU4Oseb9IpdiuK7BpIcj4nnQFiqnI5rinAf7WNjt3Q=",
        "address": [
          "172.16.0.2/32",
          "2606:4700:110:8114:b69f:cb69:4aec:bdf6/128"
        ],
        "peers": [
          {
            "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "allowedIPs": [
              "0.0.0.0/0",
              "::/0"
            ],
            "endpoint": "engage.cloudflareclient.com:2408"
          }
        ],
        "reserved": [
          0,
          0,
          0
        ],
        "mtu": 1280,
        "domainStrategy": "ForceIPv4"
      },
      "tag": "warp"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "domain": [
          "openai.com",
          "ai.com",
          "ipinfo.io",
          "iplocation.net",
          "spotify.com",
          "check-host.net"
        ],
        "outboundTag": "WARP",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "BLOCK",
        "type": "field"
      },
      {
        "domain": [
          "geosite:private"
        ],
        "outboundTag": "BLOCK",
        "type": "field"
      },
      {
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "BLOCK",
        "type": "field"
      }
    ]
  }
}

But it doesn't affect any sites that I have put in routing. Can someone explain where I have gone wrong?

 - OS: ubuntu 20
- Xray-core: 1.8.8

**Comment by vahidxo** [comment]
I literally tried all of the ways that described in documentation and in Marzban's group before submitting issue, but none of them seems to work.
My only problem is when I try to warp ALL it works, but when I try to warp some specific sites it doesn't work and I want some serious help

**Comment by SaintShit** [comment]
@vahidxo outbound tag's case sensitive, in the routing rule you made, you're routing traffic to WARP which is wrong, because your warp's outbound tag is "warp"
