### ISSUE TITLE
Wireguard

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#851]
با عرض درود و خسته نباشید
درخواست دارم تا در صورت امکان قابلیت پیکربندی وایرگارد هسته ایکس ری رو به هاست ستینگ مرزبان اضافه کنید
و همچنین قابلیت اکانتینگ رو اضافه کنید به وایرگارد تا بشه برای هر یوزر مانند دیگر پروتکل ها اکانت حجم / زمان مشخص تعین کرد
باتشکر

**Comment by M03ED** [comment]
#642 
لطفا از باز کردن issue تکراری کنید.
