### ISSUE TITLE
Hide unused icons and menu items for no-sudo admins

### ISSUE THREAD

**Issue by evkravchenko** [Gozargah/Marzban#857]
**Problem**
Every administrator wants to go to all menu items and click on the gear. If they don't work, it's anger. Moreover, the xray config is cached in the browser and if an no-sudo admin logs in after sudo admin, he sees its contents.

**Solution**
Simply hide Core settings (gear) and menu items that require sudo for no-sudo admins.

**Look of Core Settings for an no-sudo admin**
![Core Settings](https://github.com/Gozargah/Marzban/assets/57258743/ce1a5ead-f207-4daf-a582-2201cb6fdd31)

**Comment by M03ED** [comment]
dear @evkravchenko , new front end is under development on next branch , you need to wait become complete

**Comment by erfjab** [comment]
fixed
