### ISSUE TITLE
مشکل نصب دارم

### ISSUE THREAD

**Issue by maaghaei** [Gozargah/Marzban#860]
درود وقتتون بخیر بنده مشکل نصب پنل با هر دو تا روش رو دارم
هرجوری نصب میکنم این ارور رو میده بهم و حتی این پکیج رو که داره ارورش رو میده هم نصب کردم براش ولی باز هم ارور میده

![Screenshot_20240307_085535](https://github.com/Gozargah/Marzban/assets/154073284/f23f0873-b049-4044-a5e7-57dc706f2b01)

ممنون میشم اگه کسی میدونه راهنماییم کنه

**Comment by LonUp** [comment]
داکر رو یکبار دیگه نصب کن .  مرزبان ان اینستال کن .دوباره اینستال کن .  فکر کنم حل شه مشکلت

**Comment by M03ED** [comment]
لطفا از باز کردن issue تکراری خود داری کنید ، اگر کسی راه حلی بلد باشه اعلام می کنه.
