### ISSUE TITLE
Marzban Mux Problem

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#861]
There is a huge problem with Mux in Marzban

The problem is that :
The only Mux algorithm that is supported by Xray-core server is Mux.Cool
And the only client that supports Mux.Cool is Xray-core itself!

Sing-Box does not Support Mux.Cool
Clash.Meta does not support Mux.Cool

Can't use smux or other algorithms to connect to Xray-core servers
And Xray-core's main dev don't like to support other Mux algorithms because he believes they have weaknesses like TLS over(in) TLS

So Marzban must enable Mux only for Xray-core based client apps like v2rayNG, not others

**Comment by M03ED** [comment]
for the last time , before you open issue , check codes and documents
https://github.com/Gozargah/Marzban/blob/dev/app/templates/mux/default.json

**Comment by fodhelper** [comment]
I mean Sing-box Mux settings is useless for Marzban and only makes troubles
Enabling Mux from Hosts settings will enable it for Sing-box too
And as Sing-box does not support Mux.Cool so that Host/Config will become useless in Sing-box client

Also there is another problem with Mux
Mux must be disabled only for gRPC and H2 configs and xtls-rprx-vision configs (no matter if tls or reality)
but Marzban disables Mux for all REALITY configs (even for TCP+REALITY without vision)
I didn't tested regular TCP+Vision+TLS or non reality gRPC or H2, mux must be disabled for them too
@M03ED

**Comment by M03ED** [comment]
sing-box support mux
https://sing-box.sagernet.org/configuration/shared/multiplex/#outbound

**Comment by fodhelper** [comment]
sing-box does not support Mux.Cool, the only mux algorithm that is supported by xray-core
It is not possible to use smux/yamux/h2mux to connect to xray servers so enabling mux in Marzban currently breaks sing-box client

**Comment by M03ED** [comment]
can you read the damn code and then talk ?

**Comment by fodhelper** [comment]
I have read the code, I see you enabled mux for v2rayNG but disabled for sing-box by default in template, but it's useless
try it yourself, if you enable mux for a host, that host's client mux setting will be enabled for both clients (v2rayng and sing-box) even if mux is disabled for sing-box in the mux template
Look at your code :
https://github.com/Gozargah/Marzban/blob/db53013614770cc0295e9539fb0054eb95dcca89/app/subscription/singbox.py#L182
you override the template's value by host's value, you ignored template's value
I fixed it in that PR, i made Marzban to check if Template 'enabled' value is true or false, if it's false then ignore the host's mux setting, but if template's 'enabled' value is true, then check the host's mux setting, if mux setting is true in both, then enable it in the final client setting, and if it's false in one of them then it will be false in the final client setting
