### ISSUE TITLE
Telegram bot 

### ISSUE THREAD

**Issue by phoenix-marzban** [Gozargah/Marzban#862]
سلام خسته نباشید خدمت تیم مرزبان
من مشکلی در ربات خود مرزبان دارم که وقتی از داخل ربات تلگرام اینباندی رو تیک غیر فعال میزنم بعد میخام ذخیره کنم ارور میده عکساشم گرفتم براتون
![Screenshot_20240311-011222](https://github.com/Gozargah/Marzban/assets/22157772/919cd73e-857e-45e4-aab4-5baa4d35f1fd)
![Screenshot_20240311-011228](https://github.com/Gozargah/Marzban/assets/22157772/19ab3f71-d5d0-48d1-b1e6-3ba2ea457a35)

**Comment by mdjvd** [comment]
سلام. احیانا تگ اینباند تکراری ندارید؟

**Comment by phoenix-marzban** [comment]
> سلام. احیانا تگ اینباند تکراری ندارید؟

سلام خیر من این مشکل را وقتی پنل را تازه نصب کنم و هیچ تغییری هم ندم هست از چند نفر هم پرسیدم ظاهرن مشکل داره

**Comment by mmdchnar** [comment]
✅ fixed #876
