### ISSUE TITLE
xray core 1.8.9

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#863]
درود 
با عرض خسته نباشید ،

لطفا مرزبان رو بروز کنید قابلیت http upgrade به هسته اضافه شده که باعث میشه فینگرپرینت کمتری در مواقع استفاده از cdn به جای بگذاره و لطفا این رو به مرزبان اضافه کنید با تشکر

ی سری باگ هم فیکس شده و ی پچ امینتی هم برای vmess اومده رو همین ورژن 

https://github.com/XTLS/Xray-core/releases/tag/v1.8.9

لطفا قابلیت استفاده از ماکس و تعین مقادیر اش رو هم به پنل اضافه کنید 
tcp
xudp
xudp allow

با تشکر

**Comment by M03ED** [comment]
قابلیت استفاده از mux و تنظیم مقادیر روی ورژن dev و با استفاده از تمپلیت وجود داره

**Comment by realartin** [comment]
> قابلیت استفاده از mux و تنظیم مقادیر روی ورژن dev و با استفاده از تمپلیت وجود داره

منتظر انتشار روی نسخه پایدار میمونم ولی مسئله اینجاست اپدیت جدید هسته چیز های جالبی دارند

**Comment by M03ED** [comment]
#882
