### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by rastinrastini** [Gozargah/Marzban#866]
**Describe the bug**
از فایل script که گذاشته شده برای نصب استفاده کردم. صفحه سفید میمونه و داشبورد کامل بالا نمیاد. pending میشه
![Screenshot from 2024-03-12 14-06-32](https://github.com/Gozargah/Marzban/assets/7768900/b32d4384-849c-48b4-b452-b64f7f78b9d1)

**Machine details (please complete the following information):**
 - OS: ubuntu 18.04

**Comment by M03ED** [comment]
سلام
از کدوم اسکریپت استفاده کردید و اینکه ترجیحا از ubuntu 22 استفاده کنید

**Comment by M03ED** [comment]
لطفا اگر مشکلی براتون پیش میاد و براش issue باز می کنید حداقل به issue جواب بدید و اطلاعات خواسته شده رو ارسال کنید
