### ISSUE TITLE
تنظیم حداکثر تعداد دستگاه

### ISSUE THREAD

**Issue by rmoradi2019** [Gozargah/Marzban#867]
سلام و درود خدمت شما و خسته نباشید

اگه بشه قابلیتی اضافه بشه مبنی بر اینکه ادمین بتونه تنظیم کنه کاربری که داره میسازه حداکثر بتونه با 2 دستگاه یا ... متصل بشه عالیه

با تشکر

**Comment by M03ED** [comment]
فعلا در برنامه مرزبان نیست ، در صورتی که روی خود xray اضافه بشه به مرزبان هم اضافه میشه
