### ISSUE TITLE
چندتا قابلیت کاربردی

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#868]
سلام و وقت بخیر به تیم خوبه مرزبان
یه چندتا مورد هست که به پنل اضافه بشه خیلی عالیه
1- بشه مثل ایکس یو ای یا هیدیفای مثلا بزنی کاربر 30 روز لینکاش اعتبار داشته بجای اینکه توی تاریخ بگردی کدوم روز میشه 30 روز
2- رفرش خودکار اضافه کنید مثلا هر 5 ثانیه یا یه همچین چیزی
3- بشه اسم کاربر رو تغییر داد

**Comment by sarboy1371** [comment]
سلام و وقت بخیر منم با مورد 1و 4 موافقم

**Comment by sfeorg** [comment]
همه ی موارد نیازه و عالی

**Comment by bimarzvpn** [comment]
**1- مشخص شدن تعداد کاربران آنلاین**
2- قابلیت انتخاب چند کاربر (در کنار نام کاربر گزینه تیک داشته باشه که بشه چند کاربر رو انتخاب کرد و عملیات گروهی انجام داد. مثلا افزایش یا کاهش روز، حجم یا حذف کردن)
3- فیلتر کردن بر اساس حجم یا روز باقیمانده
4- ایجاد بالک یوزر
5- ایجاد یوزر هولد
6- امکان ایجاد یوزر همکار

**Comment by erfjab** [comment]
> سلام و وقت بخیر به تیم خوبه مرزبان یه چندتا مورد هست که به پنل اضافه بشه خیلی عالیه 1- بشه مثل ایکس یو ای یا هیدیفای مثلا بزنی کاربر 30 روز لینکاش اعتبار داشته بجای اینکه توی تاریخ بگردی کدوم روز میشه 30 روز 2- رفرش خودکار اضافه کنید مثلا هر 5 ثانیه یا یه همچین چیزی 3- بشه اسم کاربر رو تغییر داد

مورد سوم به خاطر استفاده از یوزرنیم در ساب ها امکان نداره. الباقی موارد هم مربوط به فرانت می باشد. البته اون رفرش خودکار نباشد بهتره، چون مصرف منابع پنل رو بیشتر میکنه اگر باشد هم میتونه دفیقه ای باشد تا ثانیه
