### ISSUE TITLE
date left and total usage column in mysql

### ISSUE THREAD

**Issue by tohid3aeed** [Gozargah/Marzban#872]
سلام خسته نباشید
جای خالی ستون های Data_ left  و total usage تو دیتابیس مرزبان احساس میشه.
به نظرم بودنشون توی محاسبه دقیق تر حجم مصرفی ادمین ها کمک میکنه

**Comment by M03ED** [comment]
مقدار data_left با یه تفریق ساده به دست میاد و دلیلی نداره یه ستون اضافه تو دیتابیس براش وجود داشته باشه
مقدار lifetime_used_traffic هم با استفاده از کوئری محاسبه و در api ارسال میشه
