### ISSUE TITLE
اشتباه در رابط کاربری پنل

### ISSUE THREAD

**Issue by matin497** [Gozargah/Marzban#873]
توی پنل مرزبان به جای note نوشته userDialog.note و به جای revoke subscription link نوشته userDialog.revokeSubscription

مرزبان نسخه 0.4.3 هست، از یه نسخه ی پایینتر آپدیت کردم به این نسخه و alembic upgrade head زدم، نمیخواستم یوزر های پنل پاک بشن و از نو بیارمشون. ممکنه از این باشه؟

**Comment by M03ED** [comment]
کش مرورگر رو پاک کنید مشکل حل میشه
