### ISSUE TITLE
باگ پنل

### ISSUE THREAD

**Issue by mtohidipour** [Gozargah/Marzban#877]
result = self.session.execute(
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
marzban-1     |     conn = self._connection_for_bind(bind)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
marzban-1     |     return self._transaction._connection_for_bind(
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
marzban-1     |     conn = bind.connect()
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
marzban-1     |     return self._connection_cls(self, close_with_result=close_with_result)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
marzban-1     |     else engine.raw_connection()
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
marzban-1     |     return self._wrap_pool_connect(self.pool.connect, _connection)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
marzban-1     |     return fn()
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 325, in connect
marzban-1     |     return _ConnectionFairy._checkout(self)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 888, in _checkout
marzban-1     |     fairy = _ConnectionRecord.checkout(pool)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 491, in checkout
marzban-1     |     rec = pool._do_get()
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
marzban-1     |     raise exc.TimeoutError(
marzban-1     | sqlalchemy.exc.TimeoutError: QueuePool limit of size 10 overflow 30 reached, connection timed out, timeout 10.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)

سلام مرزبانم بعد از چند ساعت پنل کامل از کار میفته کانکشنا وصلن ولی پنل بالا نمیاد حتما باید ریستارت کنم که بیاد بالا بعد پایتون حجم پردازشی خیلی بالایی میبره تو سیستم دیتا بیس رو هم mysql کردم

**Comment by M03ED** [comment]
سلام
ورژن چند رو استفاده می کنید ؟

**Comment by mtohidipour** [comment]
اخرین نسخس

**Comment by M03ED** [comment]
> اخرین نسخس

لطفا ورژن دقیق رو اعلام بفرمایید

**Comment by M03ED** [comment]
لطفا اگر مشکلی براتون پیش میاد و براش issue باز می کنید حداقل به issue جواب بدید و اطلاعات خواسته شده رو ارسال کنید
