### ISSUE TITLE
Subscription JSON

### ISSUE THREAD

**Issue by farshadl** [Gozargah/Marzban#884]
با توجه به فیلتر شدن زیاد دامنه‌ها، لطفا قابلیت لینک اشتراک JSON را به پنل اضافه کنید تا بتونیم برای کانفیگ فرگمنت لینک اشتراک بدیم به کاربر.

**Comment by M03ED** [comment]
سلام
این مورد 3 هفته پیش به مرزبان اضافه شده و در نسخه Dev در دسترس هست

**Comment by farshadl** [comment]
نسخه dev کجاست؟
