### ISSUE TITLE
multi custom config for v2rayN & gRPC updates

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#885]
multi custom config added to v2rayN>6.39 https://github.com/2dust/v2rayN/commit/262466303bb147ec03cdb5c1f15ddb3592716b18

xray-core added support for gRPC Authority (Supported by v2rayNG>1.8.18 and v2rayN>6.39)

gRPC's serviceName must be url-encoded in share-links
https://github.com/XTLS/Xray-core/discussions/716#:~:text=an%20empty%20string.-,4.3.13,-(gRPC)%20authority

**Comment by M03ED** [comment]
these commits are for 12 hour ago and latest version of v2rayn (6.39) its for 2 weeks ago , you need to wait for new version.
Please be patient and do not rush

**Comment by realartin** [comment]
> these commits are for 12 hour ago and latest version of v2rayn (6.39) its for 2 weeks ago , you need to wait for new version. Please be patient and do not rush

we need this please :) http upgrade
