### ISSUE TITLE
Http upgrade

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#887]
درود با عرض خسته نباشید ، الان تقریبا همه کلاینت ها و پنل ها http upgrade و اضافه کردن ، ممنون میشم در صورت امکان این قابلیت رو به مرزبان اضافه کنید با تشکر

**Comment by M03ED** [comment]
قبلا اضافه شده

**Comment by realartin** [comment]
منظورم نسخه استیبل هست
