### ISSUE TITLE
custom config subscriptions 

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#888]
درود با عرض خسته باشید ،
تو نسخه dev قابلیت روشن کردن mux و fragment و allow insecure و اضافه کردید
ممنون میشم ، قابلیت تعین اجزا mux شامل tcp connections , xudp connections , handling quic in mux tunnel رو هم اضافه کنید  تا بشه این مقادیر رو هم از بخش  host setting تغیر داد 
درضمن قابلیت اضافه کردن دی ان اس داخل کاستوم کانفیگ رو هم به بخش هاست ستینگ اضافه کنید تا بتونیم از سمت پنل دی ان اس رو برای کاربر تعین کنیم 
با تشکر از تیم فعال مرزبان

**Comment by M03ED** [comment]
این موارد رو باید از طریق تمپلیت انجام بدید و نه هاست ستینگ

**Comment by realartin** [comment]
> Collaborator

اصلا منطقی نیست !

**Comment by realartin** [comment]
> این موارد رو باید از طریق تمپلیت انجام بدید و نه هاست ستینگ

یعنی برای هر یوزر باید ی تمپلت بسازم ؟ وقتی هنوز اینها به نسخه استیبل اضافه نشدن چطور این کارو بکنم ، اموزش مناسبی برای استفاده و ساخت تمپلت نیست

**Comment by realartin** [comment]
![image](https://github.com/Gozargah/Marzban/assets/52799129/3e69d6c2-06cc-44d4-95cf-3e8587e96648)
اصالا این قابلیت هارو نداره این ها باید توسط مرزبان ساپورت بشوند تا بشه ایمپلیمنت کرد

**Comment by M03ED** [comment]
> > Collaborator
> 
> اصلا منطقی نیست !

کاملا منطقیه
این موارد ربطی به یوزر تمپلیت ندارن 
با استفاده از این فایل ها باید این تغییرات رو در کانفیگ اعمال کنید 
https://github.com/Gozargah/Marzban/blob/dev/.env.example#L36-L38

**Comment by realartin** [comment]
متشکرم اصلا نمیدونستم چنین چیزی وجود داره هیچ داکیومنتی نبود با تشکر
