### ISSUE TITLE
اتصال به دیتابیس

### ISSUE THREAD

**Issue by ehssanehs** [Gozargah/Marzban#889]
با سلام
آیا می تونم از یک سرور دیگه به صورت ریموت وصل بشم به دیتابیس mysql روی پنل مرزبان و چطور ؟
یک مشکل هم در ربات تلگرام هست که ادمینها به یوزرهای همه دسترسی دارند حتی ادمینهایی که سودو نیستند.
با سپاس

**Comment by M03ED** [comment]
سلام بله میتونید ، در قسمت ادرس باید ای پی یا دامنه سروری که MYSQL روش ران هست رو بدید 
تمامی ای دی هایی که توی env مشخص می کنید به عنوان sudo شناسایی میشن و فعلا امکان تفکیک یوزر های هر ادمین به صورت جدا وجود نداره

**Comment by ehssanehs** [comment]
> سلام بله میتونید ، در قسمت ادرس باید ای پی یا دامنه سروری که MYSQL روش ران هست رو بدید تمامی ای دی هایی که توی env مشخص می کنید به عنوان sudo شناسایی میشن و فعلا امکان تفکیک یوزر های هر ادمین به صورت جدا وجود نداره

من می خوام mysql در داکر روی سروری که مرزبان هست اجرا بشه ولی از سرور دیگه دسترسی داشته باشم به دیتابیش و کویری بگیرم

**Comment by M03ED** [comment]
> > سلام بله میتونید ، در قسمت ادرس باید ای پی یا دامنه سروری که MYSQL روش ران هست رو بدید تمامی ای دی هایی که توی env مشخص می کنید به عنوان sudo شناسایی میشن و فعلا امکان تفکیک یوزر های هر ادمین به صورت جدا وجود نداره
> 
> من می خوام mysql در داکر روی سروری که مرزبان هست اجرا بشه ولی از سرور دیگه دسترسی داشته باشم به دیتابیش و کویری بگیرم

خب اینکه مشکلی نداره ، MySQL قابلیت این رو داره ، خودتون باید اشنایی داشته باشید و انجامش بدید
