### ISSUE TITLE
ای پی لیمیت

### ISSUE THREAD

**Issue by hossein2** [Gozargah/Marzban#893]
روشی نیست که ای پی لیمیت تعریف کنیم تو مرزبان ؟
دوتا اسکریپت هست ولی خیلی باگ داره سازندشم جواب گو نیست

**Comment by M03ED** [comment]
لطفا از باز کردن issue هایی که مربوط به مرزبان نیست خود داری کنید
ایشون هم یه iplimit توسعه دادن ولی رایگان نیست 
https://t.me/Taajer_Panel
