### ISSUE TITLE
در قسمت آدرس 

### ISSUE THREAD

**Issue by NoRRt** [Gozargah/Marzban#9]
سلام و خسته نباشید - من از طریق داکر اسکریپت رو نصب کردم- لینک ها که دریافت میکنم (vless & vmess ...)  به صورت ای پی ادرس در نرم افراز ست میشه - من که دومین ست کردم - دومینم در قسمت آدرس نمیاد - آی پی نشون میده ..
![Untitled](https://user-images.githubusercontent.com/4822035/214418648-6478c082-2b88-4884-9916-709160e8e0a4.jpg)

**Comment by amirho3inf** [comment]
سلام، توی فایل env، متغیر XRAY_HOSTS رو به درستی ست کردید؟

**Comment by gozarman** [comment]
سلام
به صورت پیش فرض در صورتی که شما نامی تعیین نکنید مرزبان آیپی سرور شما رو به عنوان هاست با اسم
🚀 Marz
قرار میده.
شما میتونید این رو تغییر بدین و میتونید تعداد هاست هارو هم افزایش بدین

توی فایل env با متغییر XRAY_HOSTS میتونید اینارو تعریف کنید به شکل زیر‌ :

XRAY_HOSTS = "
⬆️ Direct@123.123.123.123
↕️ CDN@discord.com
🔥 Iran@example.com
"
(دقت کنید که علامت # اول هر خط وجود نداشته باشه. چون اینطوری کامنت در نظر گرفته میشه.)
به این شکل. حالا اگر شما برای یک یوزر به مثلا دوتا پروتکل ست کنید, vless و trojan
برای کاربر ۶ لینک ساخته میشه که سه تاش trojan هست و سه تاش vless و به ازایه هر پروتکل، ۳ تا هاست خواهید داشت با آدرس هایی که در XRAY_HOSTS تعریف کردید.
