### ISSUE TITLE
سبز نشدن چراغ کاربرا انلاین در برخی موارد

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#901]
سلام وقت بخیر یه موردی که بهش برخوردم داخل پنل ام جلو اسم نوشته کاربر انلاین هست ولی چراغ انلاین بودن قرمزه کاربر اکتیو هم هست
![image](https://github.com/Gozargah/Marzban/assets/117955130/f1cd3019-66c0-44a5-aacf-565c0c6f85d8)

پنل v0.4.9
دیتاسنتر هتزنر
کرنل xanmode
اوبونتو 22
ایکس ری کور 1.8.9
البته برای برخی کاربر ها وقتی انلاین نوشته,  چراغشون سبز هست ولی برای برخی قرمز

**Comment by M03ED** [comment]
این مشکل در برنچ next حل شده
