### ISSUE TITLE
fragment not working on windows v2rayN (Dev Vesion)

### ISSUE THREAD

**Issue by farshadl** [Gozargah/Marzban#905]
قابلیت جدید fragment که در نسخه dev پنل مرزبان در نظر گرفته شده است، روی برنامه v2rayN ویندوز جواب نمیده. کانفیگی که در برنامه v2rayN ایجاد میشه، یک کانفیگ بدون فرگمنت است!
البته در برنامه v2rayNG آندروید بدون مشکل کار میکنه و این مشکل تنها روی v2rayN ویندوز وجود دارد.

لطفا این باگ را برطرف کنید

**Comment by M03ED** [comment]
امکان ارسال فرگمنت از طریق لینک ساب هنوز برای v2rayn وجود نداره 
مشکل اصلی ای که وجود داره اینه که اگر کانفیگ ها به صورت custom config ارسال بشن دیگه امکان استفاده از url test وجود نداره
برای رفع این مشکل یک issue باز کردم ولی توسط 2dust رد شده 
میتونید با اعلام این مشکل به نویسده سعی کنید نظرش رو تغییر بدید تا این مشکل رو برطرف کنه
https://github.com/2dust/v2rayN/issues/4894#issuecomment-2027757541

**Comment by ImMohammad20000** [comment]
برای استفاده از کاستوم کانفیگ ها در v2rayn آخر لینک سابسکریشن `/v2ray-json` رو اضافه کنید

**Comment by farshadl** [comment]
> امکان ارسال فرگمنت از طریق لینک ساب هنوز برای v2rayn وجود نداره مشکل اصلی ای که وجود داره اینه که اگر کانفیگ ها به صورت custom config ارسال بشن دیگه امکان استفاده از url test وجود نداره برای رفع این مشکل یک issue باز کردم ولی توسط 2dust رد شده میتونید با اعلام این مشکل به نویسده سعی کنید نظرش رو تغییر بدید تا این مشکل رو برطرف کنه [2dust/v2rayN#4894 (comment)](https://github.com/2dust/v2rayN/issues/4894#issuecomment-2027757541)

من هم رفتم و پیام گذاشتم. به نظرم یک issue باز کنید و یعد تو گروه از بقیه هم بخوایم که برن کامنت بگذارن. اینطوری شاید مقبول 2dust بیفته 😊

**Comment by farshadl** [comment]
> برای استفاده از کاستوم کانفیگ ها در v2rayn آخر لینک سابسکریشن `/v2ray-json` رو اضافه کنید

جواب نمیده

**Comment by farshadl** [comment]
@ImMohammad20000 
@M03ED 
توی این لینک [()](https://github.com/2dust/v2rayN/commit/262466303bb147ec03cdb5c1f15ddb3592716b18) 2dust  توضیح داده که در آخرین نسخه v2rayN که نسخه ۶.۴۰ هست، امکان اضافه شدن چند کانفیگ کاستوم با استفاده از لینک اشتراک مهیا شده. 
من خودم نسخه ۶.۴۰ را دانلود کردن و انتهای لیتک اشتراک /v2ray-json را اصافه کردم. همه کانفیگ‌های کاستوم (با قابلیت فرگمنت) به v2rayN اضافه شدند

**Comment by ImMohammad20000** [comment]
> سلام
> @ImMohammad20000 
> @M03ED 
> توی این لینک (https://github.com/2dust/v2rayN/commit/262466303bb147ec03cdb5c1f15ddb3592716b18) خود 2dust  توضیح داده که در آخرین نسخه v2rayN که نسخه ۶.۴۰ هست، امکان اضافه شدن چند کانفیگ کاستوم با استفاده از لینک اشتراک مهیا شده. 
> من خودم نسخه ۶.۴۰ را دانلود کردن و انتهای لیتک اشتراک /v2ray-json را اصافه کردم. همه کانفیگ‌های کاستوم (با قابلیت فرگمنت) به v2rayN اضافه شدند 


دیشب اضافه کردم ساپورتشو منتظر تاییدیم
#840

**Comment by farshadl** [comment]
> 
> دیشب اضافه کردم ساپورتشو منتظر تاییدیم #840

@ImMohammad20000 
آقا من این موضوع را تو یک issue دیگه هم مطرح کردم ولی invalid زد!
مشکلی که هست اینه که لینک اشتراک json را باید با اضافه کردن پسوند /v2ray - json به انتهای لینک اشتراکی که از پنل می‌گیریم، بسازیم. اینکار احتمال فیلتر شدن دامنه مورد استفاده برای لینک اشتراک را زیاد میکنه چون عبارت json داخلش هست و فیلترچی راحت متوجه میشه دامنه برای فیلترشکن استفاده میشه.
لطفا این قابلیت را اضافه کنید که برای دریاقت لینک اشتراک json از یک **پسوند دلخواه** استفاده کنیم.

**Comment by M03ED** [comment]
> > 
> > دیشب اضافه کردم ساپورتشو منتظر تاییدیم #840
> 
>  
> آقا من این موضوع را تو یک issue دیگه هم مطرح کردم ولی invalid زد!
> مشکلی که هست اینه که لینک اشتراک json را باید با اضافه کردن پسوند /v2ray - json به انتهای لینک اشتراکی که از پنل می‌گیریم، بسازیم. اینکار احتمال فیلتر شدن دامنه مورد استفاده برای لینک اشتراک را زیاد میکنه چون عبارت json داخلش هست و فیلترچی راحت متوجه میشه دامنه برای فیلترشکن استفاده میشه.
> لطفا این قابلیت را اضافه کنید که برای دریاقت لینک اشتراک json از یک **پسوند دلخواه** استفاده کنیم.

تو همون issue جواب تون داده شد

**Comment by farshadl** [comment]
> > > دیشب اضافه کردم ساپورتشو منتظر تاییدیم #840
> > 
> > 
> > آقا من این موضوع را تو یک issue دیگه هم مطرح کردم ولی invalid زد!
> > مشکلی که هست اینه که لینک اشتراک json را باید با اضافه کردن پسوند /v2ray - json به انتهای لینک اشتراکی که از پنل می‌گیریم، بسازیم. اینکار احتمال فیلتر شدن دامنه مورد استفاده برای لینک اشتراک را زیاد میکنه چون عبارت json داخلش هست و فیلترچی راحت متوجه میشه دامنه برای فیلترشکن استفاده میشه.
> > لطفا این قابلیت را اضافه کنید که برای دریاقت لینک اشتراک json از یک **پسوند دلخواه** استفاده کنیم.
> 
> تو همون issue جواب تون داده شد

جوابی که داده شد اینه که از ssl برای لینک اشتراک استفاده بشه. ولی ssl باعث رمزنگاری محتوای ارسال و دریافت میشه نه رمزنکاری آدرس url. اگه اطلاعات من اشتباه هست، تصحیح کنید

**Comment by ImMohammad20000** [comment]
> جوابی که داده شد اینه که از ssl برای لینک اشتراک استفاده بشه. ولی ssl باعث رمزنگاری محتوای ارسال و دریافت میشه نه رمزنکاری آدرس url. اگه اطلاعات من اشتباه هست، تصحیح کنید


ssl تمام محتوای پکت به جز sni رو رمزنگاری میکنه
