### ISSUE TITLE
عدم نمایش چند مورد در پنل بعد از تعویض دیتاسنتر

### ISSUE THREAD

**Issue by davidnkam01** [Gozargah/Marzban#906]
سلام. من از نسخه 0.4.9 استیبل استفاده میکنم. به یه دیتاسنتر دیگه مهاجرت کردم. ( دیتابیس رو هم انتقال دادم.) توی دیتاسنتر جدید این موارد نمایش داده نمیشن توی پنل.
![image](https://github.com/Gozargah/Marzban/assets/112153874/08aff578-f2c0-4c22-80fe-9122b6191972)

توی بات هم  Download usage , Upload usage , Total Usage ثابت موندن و آپدیت نمیشن.

در ضمن دیتابیس رو هم از sqlite به mysql تغییر دادم  ولی مشکل حل نشد.
یه نود وصل کردم، و ورژن xray هر دو سرور رو به 1.8.10 تغییر دادم.

 حجم مصرف شده هر کاربر اوکیه و شمرده میشه. ( هم توی بات و هم توی پنل).
لطفا رفع بشه این مشکل. ممنون.

**Comment by M03ED** [comment]
لطفاً لاگ تون رو ارسال کنید
