### ISSUE TITLE
arbitrary "path" for json subscription link

### ISSUE THREAD

**Issue by farshadl** [Gozargah/Marzban#907]
بالاخره توی نسخه 6.40 برنامه v2rayN امکان اضافه کردن چند کانفیگ کاستوم با استفاده لینک اشتراک اضافه شد. مشکلی که هست اینه که لینک اشتراک json را باید با اضافه کردن پسوند /v2ray - json به انتهای لینک اشتراکی که از پنل می‌گیریم، بسازیم. اینکار احتمال فیلتر شدن دامنه مورد استفاده برای لینک اشتراک را زیاد میکنه چون عبارت json داخلش هست و فیلترچی راحت متوجه میشه دامنه برای فیلترشکن استفاده میشه.
لطفا این قابلیت را اضافه کنید که برای دریاقت لینک اشتراک json از یک **پسوند دلخواه** استفاده کنیم.

**Comment by fodhelper** [comment]
just use SSL for subscription domain

**Comment by M03ED** [comment]
همون طور که @fodhelper گفتن از ssl استفاده کنید تا کسی نتونه path رو ببینه

**Comment by farshadl** [comment]
یعنی اگه من از ssl برای لینک اشتراک استفاده کنم، فیلترچی نمیتوه آدرس url لینک اشتراک را ببینه؟
من فکر میکردم فقط data ارسال شده رمزنگاری میشن ولی url قابل مشاهده هست.
اگه اینطوری هست، پس چرا پنل‌هایی مثل ثنایی و مرزبان اینقدر تاکید دارن که یک path خوب برای پنل و لینک اشتراک قرار بدین؟
