### ISSUE TITLE
لاگ ورود

### ISSUE THREAD

**Issue by ZakariaRasoli** [Gozargah/Marzban#909]
لطفا لاگ ورود ادمین هارو اضافه کنین داخل ربات

و ساخت یوزر هولد داخل ui

**Comment by erfjab** [comment]
> لطفا لاگ ورود ادمین هارو اضافه کنین داخل ربات
> 
> 
> و ساخت یوزر هولد داخل ui

@M03ED  بی زحمت ببندش.
