### ISSUE TITLE
مشکل لینک ساب در نسخه dev 

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#912]
درود
در اخرین نسخه جدید از چنل dev که لینک ساب رو کوتاه کردید یک مشکلی وجود داره
وقتی یوزر جدید میسازیم و لینک ساب رو از پنل میگیرم کار نمیکنه متاسفانه و باید یکبار revoke بشه لینک .
کار نکردن به این معنی که توی مرورگر بالا نمیاد و توی برنامه هم ادد نمیشه ولی وقتی تغییر میزنم لینک ساب رو مشکل حل میشه و لینک جدید کار میکنه
لازم به ذکره من path سابسکرایبشن رو از فایل env تغییر دادم (شاید مشکل فقط توی مواردی که path تغییر کرده پیش میاد برای همین گفتم...شایدم مشکل از این نباشه)

**Comment by M03ED** [comment]
@fodhelper

**Comment by fodhelper** [comment]
Set your server's timezone to UTC until i fix it

for docker you need to share your server's timezone with container too
```
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

**Comment by LonUp** [comment]
> Set your server's timezone to UTC until i fix it
> 
> for docker you need to share your server's timezone with container too
> 
> ```
>     volumes:
>       - /etc/timezone:/etc/timezone:ro
>       - /etc/localtime:/etc/localtime:ro
> ```

Thanks for following up. Are these changes needed only for Docker in the master server?

**Comment by fodhelper** [comment]
Wait for merge if not fixed

**Comment by fodhelper** [comment]
Problem was not Timezone only
You need to wait for merge or replace the changed file yourself to your docker container
If you found any other bugs report here

**Comment by sinaaa01** [comment]
> درود در اخرین نسخه جدید از چنل dev که لینک ساب رو کوتاه کردید یک مشکلی وجود داره وقتی یوزر جدید میسازیم و لینک ساب رو از پنل میگیرم کار نمیکنه متاسفانه و باید یکبار revoke بشه لینک . کار نکردن به این معنی که توی مرورگر بالا نمیاد و توی برنامه هم ادد نمیشه ولی وقتی تغییر میزنم لینک ساب رو مشکل حل میشه و لینک جدید کار میکنه لازم به ذکره من path سابسکرایبشن رو از فایل env تغییر دادم (شاید مشکل فقط توی مواردی که path تغییر کرده پیش میاد برای همین گفتم...شایدم مشکل از این نباشه)



> درود در اخرین نسخه جدید از چنل dev که لینک ساب رو کوتاه کردید یک مشکلی وجود داره وقتی یوزر جدید میسازیم و لینک ساب رو از پنل میگیرم کار نمیکنه متاسفانه و باید یکبار revoke بشه لینک . کار نکردن به این معنی که توی مرورگر بالا نمیاد و توی برنامه هم ادد نمیشه ولی وقتی تغییر میزنم لینک ساب رو مشکل حل میشه و لینک جدید کار میکنه لازم به ذکره من path سابسکرایبشن رو از فایل env تغییر دادم (شاید مشکل فقط توی مواردی که path تغییر کرده پیش میاد برای همین گفتم...شایدم مشکل از این نباشه)

درود منم دقیقا همین مشکل رو دارم ایا شما راحلی براش پیدا کردین ؟

**Comment by M03ED** [comment]
مشکل رفع شد ؟
