### ISSUE TITLE
Introducing One-Click Traffic Forwarding Feature for Node Servers

### ISSUE THREAD

**Issue by qingqingziying** [Gozargah/Marzban#913]
I suggest adding a feature for one-click port forwarding of traffic between node servers and among node servers. This feature would enable Node Server A to forward received traffic to Node Server B for processing, thus facilitating data landing. Additionally, it could be beneficial to consider implementing multi-level traffic forwarding among node servers, such as A-B-C, to meet the data transmission requirements of various network architectures and needs.

**Comment by M03ED** [comment]
handle port forwarding its not marzban job , there is lots of program you can do this with simple configuration
