### ISSUE TITLE
مشکل اتصال نود به پنل

### ISSUE THREAD

**Issue by sarboy1371** [Gozargah/Marzban#916]
دوستانی که بااین روش https://github.com/Gozargah/Marzban/discussions/38#discussioncomment-6139133
سایت های ایرانی رو  بستن با اپدیت جدید نود چطوری میشه نود اضافه کرد؟
من هرچی تلاش کردم موفق نشدم.راهنمایی لطفا

**Comment by erfjab** [comment]
نمیدونم هنوزم نیاز دارید یا نه ولی روش های زیادی در دیسکاشن موجوده، میتونید از اینم استفاده کنید.
https://t.me/Gozar_Xray/25
