### ISSUE TITLE
نسخه dev سوالات

### ISSUE THREAD

**Issue by hossein2** [Gozargah/Marzban#918]
سلام 
ببخشید الان تعداد یوزر های من بالاست تنها مشکلی که دارم روی فعال کردن فرگمنت که وقتی لینک بروز رسانی میکنن یا از نرم افزار ها خارج میشن فرکمنت غیر فعال میشه و مجدد باید دستی ثبت بکنن
الان دیدم نسخه هست به نام dev 

اگر بخوام به این نسخه برم ممکنه الان باگی داشته باشه ؟؟

۱۲ تا سرور به صورت نود انجام دادم نیازی نیست تو اون سرور ها کاری انجام بدم ؟؟ 

معمولا چه کارهایی باید انجام بشه تا یوزرهام به مشکل نخوره ؟؟

**Comment by LonUp** [comment]
نسخه dev برای کساییه که دنبال  اخرین اپدیت های مرزبان هستند و اگر شما نیاز به پایداری دارید . بهتره که از نسخه latest استفاده کنید
برخی تغییرات در dev ممکنه باعث قطی یا باگ بشه در پنل شما و استفاده یوزرهاتون و برگشتن از dev به latest هم کار توصیه شده ای نیست . کار خاصی نیاز نیست انجام بدید . باید در داکر به حای عبارت latest عبارت dev رو قرار بدید و یکبار marzban update و یکبار marzban resstart کنید

اما توجه داشته باشید  که حتما بکاپ داشتاه باشید از دیتابیستون و اینکهترجیحا منتظر این قابلیت روی نسخه پایدار بمونید

**Comment by hossein2** [comment]
تنها رفتن من به نسخه dev فقط فقط برای گوشی های ایفون که وقتی فرگمنت به صورت دستی ثبت میکنن و بعد از چند دقیقه از نرم افزار خارج میشوند خود به خود گزینه فرگمنت غیر فعال میشه 

اگر به نسخه dev برم و بعد از مدتی استفاده کردم و هر زمانی نسخه پایدار مرزبان فرگمنت بهش اضافه شد مجدد میتوانم به نسخه پایدار برگردم ؟
برای یوزر ها مشکلی پیش میاد ؟

**Comment by LonUp** [comment]
اگه توی ساختار دیتابیس تغییری ایجاد نشده باشه  توی نسخه dev نسبت به نسخه latest مشکلی پیش نمیاد و میتونید برگردید(توصیه ولی نمیشه)
 . در غیر اینصورت دیتابیس شما روی latest بلا استفاده میشه تا وقتی که اون تغییرات روی latest هم اضافه بشن یا دستی باید دیتابیسو به حالت قابل خوندن برای نسخه latest تبدیل کنید
