### ISSUE TITLE
How to find out on what day and time the traffic?

### ISSUE THREAD

**Issue by whitehatqq** [Gozargah/Marzban#921]
- How to find out on what day and time the traffic will be reset, there are parameters in the database such as the month. How can I make changes to the database at the time when it will be reset?

- Как узнать в какой день и время произойдет сброс трафика, есть такие параметры в базе данных как например месяц. Как я могу в БД внести изменения и поставить то время, когда он будет сброшен?

**Comment by whitehatqq** [comment]
Может быть он сбрасывается после каждого переназначения data_limit?
![image](https://github.com/Gozargah/Marzban/assets/94949898/6b09d9ca-103e-4a93-8bb9-375903867344)

**Comment by M03ED** [comment]
There is a periodic usage reset field you can use it 
It depends on last reset time.
For example if you choose monthly traffic will be rested 1 month after last time you reset user usage.

**Comment by whitehatqq** [comment]
> Существует поле периодического сброса, которое вы можете использовать. Это зависит от времени последнего сброса. Например, если вы выберете ежемесячный трафик, он будет восстановлен через 1 месяц после последнего сброса использования пользователя.

So I can take the current time, do a reset via the API, and the time will reset exactly 30 days from now?

**Comment by M03ED** [comment]
> So I can take the current time, do a reset via the API, and the time will reset exactly 30 days from now?

Time will not be reset , data usage will be reset

**Comment by whitehatqq** [comment]
> > То есть я могу взять текущее время, сделать сброс через API, и время обнулится ровно через 30 дней?
> 
> Время не будет сброшено, использование данных будет сброшено

I mean the time until the next reset, I am writing a personal account and I want to show users the exact date when its use will be reset.

**Comment by M03ED** [comment]
> I mean the time until the next reset, I am writing a personal account and I want to show users the exact date when its use will be reset.

last reset time will not be send in api response , to see this variable you need access to database

**Comment by whitehatqq** [comment]
> > Я имею в виду время до следующего сброса, пишу личный кабинет и хочу показать пользователям точную дату, когда его использование будет сброшено.
> 
> время последнего сброса не будет отправлено в ответе API. Чтобы увидеть эту переменную, вам нужен доступ к базе данных

I'm in the database now, maybe it's one of these variables?
![image](https://github.com/Gozargah/Marzban/assets/94949898/f0cb529c-6626-4674-aa02-f6df2ad08aff)

**Comment by M03ED** [comment]
nope its not, there is a different table for this `user_usage_logs`
