### ISSUE TITLE
502 bad gateway  =grpc

### ISSUE THREAD

**Issue by janahnovin** [Gozargah/Marzban#922]
سلام 
بعد از یکی دو روزکلاینت در اتصال grpc  با مشکل 502 مواجه میشه و تمام کانفینگ ها به جز grpc کار میکنه  و اینکه اگه دوباره پنل نصب مجدد بشه درست میشه بعد دو روز دوباره از کار می افته سرور با ngnix به صورت تک پورت کار میکنه و ورژن 4.9 هم هست ممنون میشم راهنماییم کنید  لاگ سرور هم نمیشه گرفت تنظیمات ngnix میزارم 

server {
    listen unix:/run/nginx-h1.socket proxy_protocol;

    location ~* ^\/(dashboard|api|sub|docs|openapi.json).* {
        proxy_pass http://unix:/run/marzban.socket;
        set_real_ip_from unix:;
        real_ip_header proxy_protocol;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}

server {
    listen unix:/run/nginx-h2c.socket http2 proxy_protocol;
    set_real_ip_from unix:;
    real_ip_header proxy_protocol;

    location ~* ^\/(dashboard|api|sub|docs|openapi.json).* {
        proxy_pass http://unix:/run/marzban.socket;
        set_real_ip_from unix:;
        real_ip_header proxy_protocol;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        }

    grpc_set_header X-Real-IP $remote_addr;
    grpc_read_timeout 1h;
    grpc_send_timeout 1h;

    location /tg {
        if ($content_type !~ "application/grpc") {
                        return 404;
                }

                client_body_buffer_size 512k;
        client_body_timeout 52w;
        client_max_body_size 0;

                grpc_pass unix:/run/xray-trojan-grpc.socket;
        }

    location /mg {
        if ($content_type !~ "application/grpc") {
                        return 404;

**Comment by erfjab** [comment]
درود وقت بخیر، این ایشو به خاطر تغییرات زیاد در بکند مرزبان  و فدیمی بودن بسته میشه. در صورت وجود مشکل لطفا دوباره ایشو کنید.
