### ISSUE TITLE
میزان استفاده کاربر در هر روز

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#925]
با توجه به لاگ هایی که مرزبان جمع میکنه . میتونید قابلیتی برای مشاهده میزان استفاده هر کاربر در هر روز رو بزارید و همجنین بشه به تفکیک هر نود هم این اطلاعات رو دید . با کوئری تا حدی میشه انجام داد  ولی محیط گرافیکی و چارت طبیعتا کاربردی تره

**Comment by M03ED** [comment]
همین الان این امکان وجود داره

**Comment by LonUp** [comment]
من بخوام بدونم کاربر من ۳ روز پیش از فلان نود چقدر استفاده کرده بدون کوئری نمیشه تا جایی که میدونم . کوئری رو که خودم میزنم . بحثم اینه قابل دسترس باشه برای همه کاربرا

**Comment by M03ED** [comment]
> من بخوام بدونم کاربر من ۳ روز پیش از فلان نود چقدر استفاده کرده بدون کوئری نمیشه تا جایی که میدونم . کوئری رو که خودم میزنم . بحثم اینه قابل دسترس باشه برای همه کاربرا

![image](https://github.com/Gozargah/Marzban/assets/50927468/f9f0cb66-5236-4870-bde3-c4d95de173fc)

://////////
