### ISSUE TITLE
صفر کردن مصرف پنل

### ISSUE THREAD

**Issue by Mehtijafari** [Gozargah/Marzban#926]
من حدود 50 ترا استفاده کردم در پنل 
میخوام مجموع استفاده پنل  رو صفر کنم بدون اینکه حجم استفاده شده کاربرا صفر بشه لطفا راهنمایی کنید

**Comment by M03ED** [comment]
باید با استفاده از phpmyadmin و تغییر در خود دیتابیس این کار رو انجام بدید
