### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Omidrng** [Gozargah/Marzban#928]
سلام وقت بخیر

متاسفانه مرزبان من که روش چنتایی پنل ادمینی هست روش هر چند وقت یکبار به طور کامل سرور مستر قطع میشه و کانفیگاشون همش قطع میشه

با خودم گفتم شاید بخاطر نود ها هستش و نود هارو کلا پاک کردم اما بازم این اتفاق افتاد

خواهش میکنم کمکم کنین خیلی واجبه
![photo_5805197919375180275_y](https://github.com/Gozargah/Marzban/assets/108338782/07c3bf0f-fc75-40df-8530-50ec2cd02e1a)
![photo_5805197919375180279_y](https://github.com/Gozargah/Marzban/assets/108338782/a23a7932-4a5d-4610-9110-e358d28e9f04)
![photo_5805197919375180278_y](https://github.com/Gozargah/Marzban/assets/108338782/8681ba09-e389-4dc5-8cde-a5a206aa72ed)
![photo_5805197919375180277_y](https://github.com/Gozargah/Marzban/assets/108338782/9220a6d2-f7e1-47ea-92cb-ad4f36010c58)

**Comment by Omidrng** [comment]
![Uploading photo_5805197919375180275_y.jpg…]()

**Comment by Omidrng** [comment]
ورژنم هم ورژن اخر هستش

**Comment by ImMohammad20000** [comment]
سلام 
لطفا لاگ ها رو کپی و ارسال کنید.

**Comment by Omidrng** [comment]
والا قطع شدنی سریع ری استارت میکنم
الانم فقط تونستم عکس فرستم وقت نداشتم تا سریع وصل بشه

**Comment by ImMohammad20000** [comment]
> والا قطع شدنی سریع ری استارت میکنم
> الانم فقط تونستم عکس فرستم وقت نداشتم تا سریع وصل بشه

با عکس ها خیلی واضح نیست

**Comment by UbiVPN** [comment]
به نظر می‌رسد کاربر موجود نیست، شما یک کاربری که وجود ندارد را حذف کرده‌اید.

**Comment by Omidrng** [comment]
marzban-1  | Execution of job "record_node_usages (trigger: interval[0:00:10], n                                                                                        ext run at: 2024-04-15 18:39:03 UTC)" skipped: maximum number of running instanc                                                                                        es reached (1)

ببینین این ارورو میده

**Comment by Omidrng** [comment]
> به نظر می‌رسد کاربر موجود نیست، شما یک کاربری که وجود ندارد را حذف کرده‌اید.



واقعا بخاطر اینه؟

**Comment by UbiVPN** [comment]
من مدت‌هاست که روی این موضوع تحقیق می‌کنم، خطاهای مشابهی را قبلاً نیز تجربه کرده‌ام.
می‌توانید از VPN من استفاده کنید.
