### ISSUE TITLE
Not supported Unix domain socket listener

### ISSUE THREAD

**Issue by Willh92** [Gozargah/Marzban#931]
inbound config not supported Unix domain socket listener when not set port

**Comment by M03ED** [comment]
This is what xray should do not marzban , marzban it's just a program to manage your users.
You can report this to xtls organization

**Comment by Willh92** [comment]
> This is what xray should do not marzban , marzban it's just a program to manage your users. You can report this to xtls organization

Xray is supported, but marzban checking inbound config not ignored port
# port settings
            try:
                settings['port'] = inbound['port']               
            except KeyError:
                if not self._fallbacks_inbound:
                    raise ValueError(
                        f"port missing on {inbound['tag']}"
                        "\nset XRAY_FALLBACKS_INBOUND_TAG if you're using an inbound containing fallbacks"
                    )
                try:
                    settings['port'] = self._fallbacks_inbound['port']
                    settings['is_fallback'] = True
                except KeyError:
                    raise ValueError("fallbacks inbound doesn't have port")

**Comment by M03ED** [comment]
@SaintShit

**Comment by evkravchenko** [comment]
It's a strange have to specify the port for inbound if it listening the unix socket. In my opinion Marzban should allow xray inbound configuration without port but with socket.

**Comment by M03ED** [comment]
> It's a strange have to specify the port for inbound if it listening the unix socket. In my opinion Marzban should allow xray inbound configuration without port but with socket.

can you send a inbound with socket ?

**Comment by evkravchenko** [comment]
Of course
for example, my real inbound of reality, for which I was forced to specify an extra port number:
```
{
    "tag": "reality",
    "listen": "/run/xray/nginx.socket,0666",
    "port": 443,
    "protocol": "vless",
    "settings": {
        "clients": [],
        "decryption": "none"
    },
    "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
            "acceptProxyProtocol": true
        },
        "security": "reality",
        "realitySettings": {
            "dest": "/run/nginx/xray.socket",
            "xver": 1,
            "serverNames": [
                "server.name.sni"
            ],
            "privateKey": "*******************************************",
            "shortIds": [
                ""
            ]
        }
    },
    "sniffing": {
        "enabled": true,
        "destOverride": [
            "http",
            "tls",
            "quic"
        ],
        "routeOnly": true
    }
}
```
Here reality works behind nginx

**Comment by Willh92** [comment]
> Of course
> 
> for example, my real inbound of reality, for which I was forced to specify an extra port number:
> 
> ```
> 
> {
> 
>     "tag": "reality",
> 
>     "listen": "/run/xray/nginx.socket,0666",
> 
>     "port": 443,
> 
>     "protocol": "vless",
> 
>     "settings": {
> 
>         "clients": [],
> 
>         "decryption": "none"
> 
>     },
> 
>     "streamSettings": {
> 
>         "network": "tcp",
> 
>         "tcpSettings": {
> 
>             "acceptProxyProtocol": true
> 
>         },
> 
>         "security": "reality",
> 
>         "realitySettings": {
> 
>             "dest": "/run/nginx/xray.socket",
> 
>             "xver": 1,
> 
>             "serverNames": [
> 
>                 "server.name.sni"
> 
>             ],
> 
>             "privateKey": "*******************************************",
> 
>             "shortIds": [
> 
>                 ""
> 
>             ]
> 
>         }
> 
>     },
> 
>     "sniffing": {
> 
>         "enabled": true,
> 
>         "destOverride": [
> 
>             "http",
> 
>             "tls",
> 
>             "quic"
> 
>         ],
> 
>         "routeOnly": true
> 
>     }
> 
> }
> 
> ```
> 
> Here reality works behind nginx

In fact, the port can be ignored and deleted here, but if Marzban does not fill in the port, it will directly report an error
