### ISSUE TITLE
shacowsocks

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#933]
درود 
chacha20-ietf-poly1305

این رمزنگاری رو تعین میکنم کار نمیکنه شادوساکس ولی با بقیه کار میکنه ! لطفا چک کنید این رمزنگاری مناسب و خوبیه و بهش نیازه

**Comment by realartin** [comment]
درضمن حالت udp رو هیچ جوره نمیتونم استفاده کنم ، درست کار میکنه ؟ یا ارتباط udp محدود شده ؟

**Comment by UbiVPN** [comment]
Shadowsocks به طور پیش‌فرض از پروتکل TCP استفاده می‌کند، برخی از آن‌ها نیز از UDP پشتیبانی می‌کنند، اما به طور کلی، پشتیبانی از UDP خوب نیست. این وابسته به شبکه شما است؛ در محیط‌های شبکه NAT، نمی‌توان اطمینان داشت که UDP به درستی کار می‌کند.

**Comment by realartin** [comment]
حاجی من اصلا متوجه نمیشم چی میگی رقتی چت جی پی تی باز کردی؟
