### ISSUE TITLE
Feature title

### ISSUE THREAD

**Issue by realartin** [Gozargah/Marzban#934]
لطفا این رمزنگاری هارو به شادوساکس اضافه کنید (توسط xray ساپورت می شوند ) :
Recommended encryption methods:
2022-blake3-aes-128-gcm
2022-blake3-aes-256-gcm
2022-blake3-chacha20-poly1305
Other encryption methods:
aes-256-gcm
aes-128-gcm
chacha20-poly1305/chacha20-ietf-poly1305
xchacha20-poly1305/xchacha20-ietf-poly1305
با تشکر

**Comment by UbiVPN** [comment]
قبل از این، روش‌های رمزنگاری قدیمی دیگر امنیت کافی را ندارند و ممکن است به راحتی مسدود یا مورد حملهٔ بازگردانی قرار گیرند، می‌توان در نظر گرفت روش‌های قدیمی رمزنگاری را حذف کرد. سایر پروژه‌ها روش‌های قدیمی رمزنگاری را حذف کرده‌اند. فقط روش‌های رمزنگاری AEAD و جدیدترین SS2022 باقی مانده‌اند.

**Comment by fodhelper** [comment]
ShadowSocks + 2022 Encryptions = ShadowSocks2022
And it's not supported by Marzban yet > https://github.com/Gozargah/Marzban/issues/329

Why do you even want to use ShadowSocks of Xray-core, it's useless, no plugin support, no client support...

**Comment by TahaRJI** [comment]
We need this!
