### ISSUE TITLE
گیر کردن وسط کلیپا شورت

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#937]
سلام و وقت بخیر به تیم خوب مرزبان
من یه مشکلی که دارم خیلی از کاربرا میان میگن که توی اینستا و یوتیوب مثلا بعد هر 5 یا 6 تا کلیپ که نگاه میکنن یه بارگی یکی وسطش گیر میکنه دیگه بخش نمیشه , من هرچقدر گشم راه حلی واسش پیدا نکردم مطمعن هم نیستم از سمت پنله یا کانفیگ هسته xray
لطفا راهنمایی کنید با تشکر

**Comment by xmohammad1** [comment]
> هسته رو به 1.8.4 تغییر بده تست بگیر

از قبل رو هسته 1.8.4 بودم این issue رو باز کردم

**Comment by sarboy1371** [comment]
من این مشکل رو با آی پی v6 داشتم.رفتم رو ای پی v4 اوکی شد

**Comment by xmohammad1** [comment]
> من این مشکل رو با آی پی v6 داشتم.رفتم رو ای پی v4 اوکی شد

یعنی ipv6 رو کلا خاموش کردید؟ اخه من با ipv6 تانل میزنم برای همین روشن گذاشتم

**Comment by sarboy1371** [comment]
اره منم تانلم با ip v6بود .ایسنتا کلا با ip v6 مشکل داره
تانل با ipv4 بزن

**Comment by xmohammad1** [comment]
> اره منم تانلم با ip v6بود .ایسنتا کلا با ip v6 مشکل داره تانل با ipv4 بزن

میشه بپرسم روس تانلتون چیه، چون من هر بار با ipv4 تانل زدم فیلتر شد

**Comment by sarboy1371** [comment]
rathole reverse azumi

https://github.com/Azumi67/Rathole_reverseTunnel

**Comment by xmohammad1** [comment]
> rathole reverse azumi
> 
> https://github.com/Azumi67/Rathole_reverseTunnel

ممنون 🙏
