### ISSUE TITLE
نمایش آخرین به روزرسانی

### ISSUE THREAD

**Issue by tohid3aeed** [Gozargah/Marzban#938]
سلام وقت بخیر
اگه بشه متغیر آخرین به روزرسانی در کنار بقیه چیزها داخل هاست ستینگ اضافه بشه عالی میشه.
یا حتی داخل پنل کنار زمان آنلاین بودن نمایش داده بشه
راحت تر میشه مشکل مشتریارو حل کرد 
تشکر
![IMG_20240413_032726_291](https://github.com/Gozargah/Marzban/assets/136030898/c2480f89-c725-413f-ac97-71ee9888da80)

**Comment by M03ED** [comment]
در برنچ next این مورد توی داشبورد نمایش داده میشه 
دلیل وجود نداره اینگونه موارد برای کاربر ارسال بشه
