### ISSUE TITLE
نمایش تعداد کاربر متصل به اکانت

### ISSUE THREAD

**Issue by MrOtto94** [Gozargah/Marzban#939]
باسلام و احترام و تشکر از زحمات مدیران محترم
آیا امکانش هم تعداد کاربران متصل به اکانت در پنل به نمایش در بیاد ؟
فکر میکنم کمک خوبی به همه بکنه برای مدیریت بهتر اکانتها

**Comment by nsa14** [comment]
اگر این امکان اضافه بشه عالیه. تعداد یوزری که به یه کانفیگ متصل هست. حتی جهت اطلاع ادمین هم باشه خیلی عالیه

انشالا ک اضافه بشه🙏

**Comment by UbiVPN** [comment]
این که می‌تواند تعداد کاربران جدید روزانه، تعداد کل کاربران و همچنین تعداد کاربران آنلاین را نشان دهد، خیلی خوب است.

**Comment by M03ED** [comment]
اینگونه موارد همزمان با داشبورد فرانت جدید اضافه میشه و فعلا قصد ایجاد تغییر روی داشبورد فعلی وجود نداره
همه این موارد هم قبلا در issue گفته شده
