### ISSUE TITLE
Daily reset is not working well

### ISSUE THREAD

**Issue by Sensetize** [Gozargah/Marzban#940]
Hi, The daily package of gbs is not reset on time, can you tell me the exact time?
Also, if you fill out the daily GB package and after Marzban auto resets the daily package, the keys are not restored automatically (it is impossible to connect to them), we have to reboot the core or reset the traffic manually. Please fix the daily reset of the package, it does not work correctly, it resets the package whenever it wants and does not restore access to the keys

**Comment by UbiVPN** [comment]
I wonder if this has something to do with your settings?

**Comment by whitehatqq** [comment]
> Hi, The daily package of gbs is not reset on time, can you tell me the exact time? Also, if you fill out the daily GB package and after Marzban auto resets the daily package, the keys are not restored automatically (it is impossible to connect to them), we have to reboot the core or reset the traffic manually. Please fix the daily reset of the package, it does not work correctly, it resets the package whenever it wants and does not restore access to the keys

Yes, the same thing!

Traffic is being reset, the subscription status is changing, but only restarting marzban helps to connect to the key, have you found anything to do with it?

Marzban is fresh on a new server with no settings.

**Comment by whitehatqq** [comment]
> > > Привет! Ежедневный пакет gbs не сбрасывается вовремя, можете сказать точное время? Также, если вы заполняете ежедневный пакет ГБ и после того, как Marzban автоматически сбрасывает ежедневный пакет, ключи не восстанавливаются автоматически (к ним невозможно подключиться), приходится перезагружать ядро ​​или сбрасывать трафик вручную. Исправьте пожалуйста ежедневный сброс пакета, он работает некорректно, сбрасывает пакет когда захочет и не восстанавливает доступ к ключам
> > 
> > 
> > Да, то же самое!
> > Трафик сбрасывается, статус подписки меняется, но подключиться к ключу помогает только перезапуск марзбана, нашли что-нибудь с этим сделать?
> > Marzban свеж на новом сервере, без настроек.
> 
> Нет, будем надеяться на хорошие новости по этому поводу.

Tell me, does the monthly reset work correctly?

> > > Hi, The daily package of gbs is not reset on time, can you tell me the exact time? Also, if you fill out the daily GB package and after Marzban auto resets the daily package, the keys are not restored automatically (it is impossible to connect to them), we have to reboot the core or reset the traffic manually. Please fix the daily reset of the package, it does not work correctly, it resets the package whenever it wants and does not restore access to the keys
> > 
> > 
> > Yes, the same thing!
> > Traffic is being reset, the subscription status is changing, but only restarting marzban helps to connect to the key, have you found anything to do with it?
> > Marzban is fresh on a new server with no settings.
> 
> No, let's hope for a good update on it

Tell me, does the monthly reset work correctly?

**Comment by Sensetize** [comment]
> > > > Привет! Ежедневный пакет gbs не сбрасывается вовремя, можете сказать точное время? Также, если вы заполняете ежедневный пакет ГБ и после того, как Marzban автоматически сбрасывает ежедневный пакет, ключи не восстанавливаются автоматически (к ним невозможно подключиться), приходится перезагружать ядро ​​или сбрасывать трафик вручную. Исправьте пожалуйста ежедневный сброс пакета, он работает некорректно, сбрасывает пакет когда захочет и не восстанавливает доступ к ключам
> > > 
> > > 
> > > Да, то же самое!
> > > Трафик сбрасывается, статус подписки меняется, но подключиться к ключу помогает только перезапуск марзбана, нашли что-нибудь с этим сделать?
> > > Marzban свеж на новом сервере, без настроек.
> > 
> > 
> > Нет, будем надеяться на хорошие новости по этому поводу.
> 
> Tell me, does the monthly reset work correctly?
I guess so but I'm not sure because I use daily reset

**Comment by mehdidelghavi** [comment]
سلام متاسفانه هنوز این مشکل برقرار هست برای همه نیست اما برای بعضی اکانتا به وجود میاد حجم کاربر ریست میشه اما کانفیگ وصل نمیشه تا زمانی که reset usage نزنیم درست نمیشه

**Comment by TrustCane** [comment]
> Tell me, does the monthly reset work correctly?
Not either

**Comment by erfjab** [comment]
درود و وقت بخیر ، به زودی بخش ریست ترافیک دوره ای ریفکتور خواهد شد.

**Comment by erfjab** [comment]
ایشو به خاطر تکراری بودن بسته شد
