### ISSUE TITLE
اضافه نشدن تنظیمات به هسته x-ray

### ISSUE THREAD

**Issue by mshahr1** [Gozargah/Marzban#941]
بعد از اضافه کردن تنظیمات جدید در قسمت host settings تنظیمات در هسته x-ray و در فایل json آپدیت نمیشه

**Comment by xmohammad1** [comment]
تنظیمات خودت باید سمت هسته اوکی کنی

**Comment by mshahr1** [comment]
اینو تست کردم اکی شد. وقتی هاست ستینگ هست اونم باید همین کارو بکنه دیگه... اون تیکه باگ داره

**Comment by M03ED** [comment]
خیر هاست ستینگ و هسته کار شون متفاوت هست ، به هیچ وجه نباید تغییر ایجاد کنه
