### ISSUE TITLE
Marzban users states not updating and console errors after prolonged use

### ISSUE THREAD

**Issue by GuardCat** [Gozargah/Marzban#948]
**Describe the bug**
After several days of operation, the Marzban service begins to exhibit errors. Initially, the service functions correctly, but after a couple of weeks, sometimes sooner, an error occurs. The console displays multiple errors, and the web panel fails to update user states, showing all users as offline despite the service remaining operational.

**To Reproduce**
1. Start the Marzban service and use it normally for a few days.
2. After a couple of weeks, observe the console for any error messages.
3. Check the web panel to view user states.
4. Notice that all users appear offline and the console logs multiple errors.

**Expected behavior**
The expected behavior is for the Marzban service to run continuously without errors, with the web panel accurately reflecting user states.

**Errors' details**
https://gist.github.com/GuardCat/7b932e2fb8486d5dd2c46ebeeae1598e

**Machine details (please complete the following information):**
 - OS: Linux 5.15.0-101-generic Ubuntu x86_64 x86_64 x86_64 GNU/Linux
   Ubuntu 22.04.4 LTS jammy
- Python version: Python 3.10.12 

**Additional context**
I use the docker version of Marzban.

**Comment by GuardCat** [comment]
> which version of marzban you using ?

v0.4.9 from releases. To be accurate: I installed version 0.4.6 and have had several updates through the default script.

**Comment by M03ED** [comment]
> v0.4.9 from releases. To be accurate: I installed version 0.4.6 and have had several updates through the default script.

which node protocol ?

**Comment by GuardCat** [comment]
> > v0.4.9 from releases. To be accurate: I installed version 0.4.6 and have had several updates through the default script.
> 
> which node protocol ?

I'm sorry, but I'm not sure where to find that information. Could you please guide me on where to look?

**Comment by M03ED** [comment]
i'm waiting

**Comment by M03ED** [comment]
i close this issue because i didn't get any answer
