### ISSUE TITLE
از کارت افتادن کانفیگها بعد از تغییر پورت پنل

### ISSUE THREAD

**Issue by FreeMan1359** [Gozargah/Marzban#949]
دورد:
بعد از تغییر پورت و ریست کردن پنل کانفیگها از کار میوفتن. آیا به جز تغییر پورت در فایل env باید کار دیگه ای انجام داد یا این یه مشکله؟

**Comment by M03ED** [comment]
پورت پنل تون با پورت یکی از کانفیگ ها تون یک سان هست و موجع به اجتلال میشه و ایکس ری نمیتونه ران بشه

**Comment by FreeMan1359** [comment]
برای تمام کانفیگها از یک پورت استفاده میکنم و مشابه به پورت پنل نیست. فایروال هم فعال نیست چون از ریورس تانل استفاده میکنم. نمیدونم مشکل کجاست

**Comment by M03ED** [comment]
لاگ تون رو ارسال کنید

**Comment by FreeMan1359** [comment]
با سپاس.
در لاگ زده بود پورت انتخابی قبلا انتخاب شده. رفتم چک کردم دیدم پورتی که برای پنل میذارم پیش فرض یکی از پورتهایی هست که خود هسته برای یکی از کانفیگها انتخاب کرده بود در صورتی که من اون رو اصلا استفاده نمیکردم و حتی از بخش هاست ستینگ پاکش کرده بودم. پورت کانفیگی که استفاده نمیشد رو از Configuration تغییر دادم و پورت مورد نظرم برای پنل انتخاب کردم و کانفیگها کار کردن. فکر میکردم چون استفاده ای نداره نباید مشکل ساز هم باشه.
ممنون بابت پیگیری
