### ISSUE TITLE
لینک ساب خراب در نسخه دولوپر

### ISSUE THREAD

**Issue by sinaaa01** [Gozargah/Marzban#951]
درود 
توسعه دهندگان مرزبان 
روی نسخه دولوپر هستم ساب هایی که با ربات ساخته میشن یکی درمیون باگ میخوره و لینک ساب خالی ساخته میشه 
بیشتر لینک ها روی دو ساخته شده کوچ کنم به نسخه لتست ساب های قبلیم از کار میوفتن
 کسی میتونه مشکل من رو حل کنه؟

**Comment by M03ED** [comment]
#912
