### ISSUE TITLE
set id for hosts like node_id (api)

### ISSUE THREAD

**Issue by erfjab** [Gozargah/Marzban#952]
برای تفکیک هاست ها و ویرایش و دسترسی راحت تر ، بهتره هاست ها مثل نودها یک آیدی داشته باشند.
فقط به این مورد باید توجه شود که با اضافه/حذف اینباند های دیگه ایدی هاست ها عوض نشه.

**Comment by M03ED** [comment]
تمامی تیبل ها دارای primary key ای دی هستند

**Comment by erfjab** [comment]
درسته ولی منظور من برای api ها بود. تو api ها id نداریم. وقتی میخواییم نود رو ادیت بزنیم id از اول مشخصه ولی تو هاست اینطوری نیست.
/api/host/{host_id}
باشه خیلی خوب میشه، مثلا بگم برای مانیتورینگ آیپی های کلود و چنج اتوماتیک نیاز به این مورد داریم.

**Comment by M03ED** [comment]
> مثلا بگم برای مانیتورینگ آیپی های کلود و چنج اتوماتیک نیاز به این مورد داریم.

استفاده از دامنه مورد خیلی معقول تری هاست تا اینکه با اسکریپت ای پی تغییر بدید

**Comment by erfjab** [comment]
حالا مثال زدم، آیدی هاست واقعا نیازه در کل
