### ISSUE TITLE
جدا کردن گزارش ربات برای یک گروه انجمن

### ISSUE THREAD

**Issue by hamedefatian** [Gozargah/Marzban#955]
سلام
راهی هست بشه گزارشات ربات رو از هم جداکرد؟
مثلا یک انجمن درست کرد و هر گزارشی که برای هر ادمین میره رو به اون انجمن منتقل کرد؟

**Comment by M03ED** [comment]
سلام
این قابلیت قبلا در مرزبان اضافه شده ، کافیه از cli استفاده کنید و برای هر ادمین یه ای دی تلگرام ثبت کنید ، علاوه بر چنل اصلی پیام های مربوط به هر کاربر به ادمین اون کاربر هم ارسال میشه
