### ISSUE TITLE
قطع و وصلی نود

### ISSUE THREAD

**Issue by vahidyeganeh1373** [Gozargah/Marzban#956]
خسته نباشید
از وقتی نود هامو آپدیت کردم به ورژن 1.8.10 ( از اینجا https://github.com/Gozargah/Marzban-node/releases )
روزی یکی دوبار هرکدوم از نودها کرش میخوره و مجدد خودش کانکت میشه
اینم متن گزارش مرزبان هلدر :
❗️ (Checker) boss of one of the servers crashed. To prevent spamming, server monitoring has been stopped and will be restarted after 100 seconds.

NODE NAME : Node-6
NODE ID : 6
NODE IP : xx.xx.xx.xx
ERROR MESSAGE :None
توی لاگ xray مرزبان مستر هم هیچ اروری ندارم
ممنون میشم یه بررسی بکنید

**Comment by erfjab** [comment]
ممکن هست به خاطر منابع سرور شما باشه، بهتره از پروتکل رست استفاده کنید.
