### ISSUE TITLE
باز کردن یک پورت

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#958]
سلام و احترام
وقتی در قسمت Core Settings  پورت ها را اضافه میکنیم و چند نود داریم در تمام نودها آن پورتها را باز میکند 
( سوال اول : آیا راجی هست که مشخص کنیم این پورت در کدام نود باز باشد و در کدام نود خیر)و اگر چند پنل مرزبان داشته باشیم باعث به وجود آمدنکانفلیگ در آن پورت میشود.

وقتی در قسمت هاست پورتی را اضافه میکنیم آن پورت باز نمیشود و حتما باید در  Core Settings اضافه شده باشد.
  سوال دوم : 
چطور میتوان پورت دیفالت در Core Settings اضافه ننمود و مدیریت آن در هاست انجام شود و یا راه حلی که مشکل بالا به وجود نیاید وجود دارد ؟

![image](https://github.com/Gozargah/Marzban/assets/103871792/e84ff00e-a659-4bd9-82a4-b274ee94fa7c)

توضیح بیشتر : 

در قسمت پورت/هاست اگر پورتی که به صورت دستی اضافهمیکنیم متفاوت باشد با پورتی که در کور ستینگ وجود دارد این پورت باز نمیشود 

سپاس

**Comment by M03ED** [comment]
> سلام و احترام وقتی در قسمت Core Settings پورت ها را اضافه میکنیم و چند نود داریم در تمام نودها آن پورتها را باز میکند ( سوال اول : آیا راجی هست که مشخص کنیم این پورت در کدام نود باز باشد و در کدام نود خیر)و اگر چند پنل مرزبان داشته باشیم باعث به وجود آمدنکانفلیگ در آن پورت میشود.

ابتدا داکیومنت را مطالعه فرمایید ، این مورد قبلا توضیح داده شده
https://gozargah.github.io/marzban/fa/docs/marzban-node

> وقتی در قسمت هاست پورتی را اضافه میکنیم آن پورت باز نمیشود و حتما باید در Core Settings اضافه شده باشد. سوال دوم : چطور میتوان پورت دیفالت در Core Settings اضافه ننمود و مدیریت آن در هاست انجام شود و یا راه حلی که مشکل بالا به وجود نیاید وجود دارد ؟
> توضیح بیشتر :
> در قسمت پورت/هاست اگر پورتی که به صورت دستی اضافه میکنیم متفاوت باشد با پورتی که در کور ستینگ وجود دارد این پورت باز نمیشود

کاملا درسته و نباید باز بشه ، تغییر پورت از هاست کاربرد های متفاوتی داره و باید همینطور که الان هست بمونه
