### ISSUE TITLE
Marzban Does Not Start Properly

### ISSUE THREAD

**Issue by rlrexyz** [Gozargah/Marzban#959]
When the system starts, marzban starts automatically and when I enter the "marzban status" command, it appears as "Mazrban Up". There is no problem here, but when I try to connect from my device, the connection is not successful. If I enter the "marzban restart" command after the system restarts, I can connect.

**Machine details:**
Ubuntu 22.04.4 LTS

**Comment by M03ED** [comment]
check `marzban logs`

**Comment by rlrexyz** [comment]
> check `marzban logs`

marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade  -> 94a5cc12c0d6, init user table
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 94a5cc12c0d6 -> 3cf36a5fde73, init system table
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 3cf36a5fde73 -> 9d5a518ae432, init jwt table
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 9d5a518ae432 -> 9b60be6cd0a2, add created_at field to users table
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 9b60be6cd0a2 -> 8e849e06f131, proxy table
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 8e849e06f131 -> 671621870b02, init admin
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 671621870b02 -> e91236993f1a, inbounds table & excluded_inbounds
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e91236993f1a -> b3378dc6de01, hosts
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 671621870b02 -> d02dcfbf1517, add UserUsageResetLogs Model and data_limit_strategy field to user
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade d02dcfbf1517, b3378dc6de01 -> ece13c4c6f65, empty message
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade ece13c4c6f65 -> b15eba6e5867, add host and sni columns to hosts table
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade b15eba6e5867 -> 51e941ed9018, deactive user status
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 51e941ed9018 -> e3f0e888a563, rename deactive status to disabled
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e3f0e888a563 -> 7cbe9d91ac11, ProxyHost: security added
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 7cbe9d91ac11 -> 5b84d88804a1, fix
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 5b84d88804a1 -> a0d3d400ea75, Admin: is_sudo field
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 5b84d88804a1 -> fad8b1997c3a, case insensitive username
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade fad8b1997c3a, a0d3d400ea75 -> e410e5f15c3f, merge fad8b1997c3a & a0d3d400ea75
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e410e5f15c3f -> 97dd9311ab93, add user templates
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 97dd9311ab93 -> 37692c1c9715, nodes
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 37692c1c9715 -> e4a86bc8ec7b, node_user_usages
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e4a86bc8ec7b -> 57fda18cd9e6, add xray version
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 57fda18cd9e6 -> c106bb40c861, alpn_fingerprint_hosts
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade c106bb40c861 -> fc01b1520e72, add node usages
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade fc01b1520e72 -> 35f7f8fa9cf2, add sub_revoked_at to users
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 35f7f8fa9cf2 -> c47250b790eb, add user note
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade c47250b790eb -> 015cf1dc6eca, sub_updated_at and sub_last_user_agent
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 015cf1dc6eca -> a6e3fff39291, add notification reminders
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade a6e3fff39291 -> 025d427831dd, sub_last_user_agent length
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 025d427831dd -> 1cf7d159fdbb, add online at
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 1cf7d159fdbb -> a0715c2615f0, Add allow in secure and disable host
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade a0715c2615f0 -> 77c86a261126, Nodes coefficient
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 77c86a261126 -> 7a0dbb8a2f65, init tls table
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 7a0dbb8a2f65 -> fe7796f840a4, remove certficiate from nodes
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 77c86a261126 -> 5a4446e7b165, add password_reset_at to admins
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 5a4446e7b165, fe7796f840a4 -> 0f720f5c54dd, empty message
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 0f720f5c54dd -> 08b381fc1bc7, update_shadowsocks_method
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 08b381fc1bc7 -> 947ebbd8debe, Add on hold
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 947ebbd8debe -> 714f227201a7, Fix User Template
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 714f227201a7 -> e56f1c781e46, Fix on hold
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade e56f1c781e46 -> 470465472326, add path to hosts
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 470465472326 -> 5575fe410515, add_telegram_id_to_admin
marzban-1  | INFO  [alembic.runtime.migration] Running upgrade 5575fe410515 -> dd725e4d3628, fix_mysql_collations
marzban-1  | INFO:     Started server process [1]
marzban-1  | INFO:     Waiting for application startup.
marzban-1  | INFO:     Generating Xray core config
marzban-1  | INFO:     Xray core config generated in 0.13 seconds
marzban-1  | INFO:     Starting main Xray core
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     Starting nodes Xray core
marzban-1  | INFO:     Application startup complete.
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
marzban-1  | INFO:     78.190.196.98:5463 - "GET /login HTTP/1.1" 404 Not Found
marzban-1  | INFO:     78.190.196.98:2398 - "GET /login HTTP/1.1" 404 Not Found
marzban-1  | INFO:     78.190.196.98:2398 - "GET /locales/tr.json HTTP/1.1" 404 Not Found
marzban-1  | INFO:     78.190.196.98:2398 - "GET /favicon/favicon.ico HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2208 - "POST /api/admin/token HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2208 - "GET /api/admin HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2208 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5213 - "GET /api/inbounds HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3358 - "GET /api/nodes HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4185 - "GET /api/users?limit=30&sort=-created_at HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4185 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3635 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     ('78.190.196.98', 2569) - "WebSocket /api/core/logs?interval=1&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyaXNjIiwiYWNjZXNzIjoic3VkbyIsImlhdCI6MTcxNDMwMjQ5OCwiZXhwIjoxNzE0Mzg4ODk4fQ.mZUROh9b1byXcQa0uhUxgim4gMwPQDzSa9EwGCX-0KI" [accepted]
marzban-1  | INFO:     connection open
marzban-1  | INFO:     78.190.196.98:4500 - "GET /api/core HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3635 - "GET /api/core/config HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3635 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2407 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3836 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:1731 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:1622 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2611 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5334 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | WARNING:  Restarting Xray core...
marzban-1  | WARNING:  Xray core stopped
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     78.190.196.98:5334 - "PUT /api/core/config HTTP/1.1" 200 OK
marzban-1  | WARNING:  Restarting Xray core...
marzban-1  | WARNING:  Xray core stopped
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     78.190.196.98:4791 - "POST /api/core/restart HTTP/1.1" 200 OK
marzban-1  | INFO:     connection closed
marzban-1  | INFO:     78.190.196.98:4791 - "GET / HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4791 - "GET /assets/index.2e9c394e.js HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2290 - "GET /assets/index.59de2328.css HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5123 - "GET /assets/vendor.764109dc.js HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5123 - "GET /api/admin HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5123 - "GET /locales/tr.json HTTP/1.1" 404 Not Found
marzban-1  | INFO:     78.190.196.98:4791 - "GET /locales/en.json HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5123 - "GET /api/nodes HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2290 - "GET /api/users?limit=30&sort=-created_at HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4791 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2098 - "GET /api/inbounds HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2098 - "GET /favicon/favicon.ico HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2098 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2187 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3804 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2941 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3740 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     New user "1Mustafa" added
marzban-1  | INFO:     78.190.196.98:3358 - "POST /api/user HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3358 - "GET /api/users?limit=30&sort=-created_at HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4289 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4817 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3770 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3166 - "GET /sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxTXVzdGFmYSIsImFjY2VzcyI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTcxNDMwMjU3OH0.OV1tho19EGzZYKnijf6x-TBzJIx1I6MrBzAlz4OS-54 HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3166 - "GET /sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxTXVzdGFmYSIsImFjY2VzcyI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTcxNDMwMjU3OH0.OV1tho19EGzZYKnijf6x-TBzJIx1I6MrBzAlz4OS-54 HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4255 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3568 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3739 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2943 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4406 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2576 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4515 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3358 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4210 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     Shutting down
marzban-1  | INFO:     Waiting for application shutdown.
marzban-1  | INFO:     Stopping main Xray core
marzban-1  | WARNING:  Xray core stopped
marzban-1  | INFO:     Stopping nodes Xray core
marzban-1  | INFO:     Application shutdown complete.
marzban-1  | INFO:     Finished server process [1]
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO:     Started server process [1]
marzban-1  | INFO:     Waiting for application startup.
marzban-1  | INFO:     Generating Xray core config
marzban-1  | INFO:     Xray core config generated in 0.17 seconds
marzban-1  | INFO:     Starting main Xray core
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     Starting nodes Xray core
marzban-1  | INFO:     Application startup complete.
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
marzban-1  | INFO:     78.190.196.98:2456 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2456 - "GET /api/users?limit=30&sort=-created_at HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2456 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2742 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3413 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3490 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2733 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     Shutting down
marzban-1  | INFO:     Waiting for application shutdown.
marzban-1  | INFO:     Stopping main Xray core
marzban-1  | WARNING:  Xray core stopped
marzban-1  | INFO:     Stopping nodes Xray core
marzban-1  | INFO:     Application shutdown complete.
marzban-1  | INFO:     Finished server process [1]
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO:     Started server process [1]
marzban-1  | INFO:     Waiting for application startup.
marzban-1  | INFO:     Generating Xray core config
marzban-1  | INFO:     Xray core config generated in 0.20 seconds
marzban-1  | INFO:     Starting main Xray core
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     Starting nodes Xray core
marzban-1  | INFO:     Application startup complete.
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
marzban-1  | INFO:     78.190.196.98:4559 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     Shutting down
marzban-1  | INFO:     Waiting for application shutdown.
marzban-1  | INFO:     Stopping main Xray core
marzban-1  | WARNING:  Xray core stopped
marzban-1  | INFO:     Stopping nodes Xray core
marzban-1  | INFO:     Application shutdown complete.
marzban-1  | INFO:     Finished server process [1]
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO:     Started server process [1]
marzban-1  | INFO:     Waiting for application startup.
marzban-1  | INFO:     Generating Xray core config
marzban-1  | INFO:     Xray core config generated in 0.25 seconds
marzban-1  | INFO:     Starting main Xray core
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     Starting nodes Xray core
marzban-1  | INFO:     Application startup complete.
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
marzban-1  | INFO:     78.190.196.98:4828 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5390 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:4634 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5187 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3997 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3270 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2542 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:5495 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3073 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     Shutting down
marzban-1  | INFO:     Waiting for application shutdown.
marzban-1  | INFO:     Stopping main Xray core
marzban-1  | WARNING:  Xray core stopped
marzban-1  | INFO:     Stopping nodes Xray core
marzban-1  | INFO:     Application shutdown complete.
marzban-1  | INFO:     Finished server process [1]
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO:     Started server process [1]
marzban-1  | INFO:     Waiting for application startup.
marzban-1  | INFO:     Generating Xray core config
marzban-1  | INFO:     Xray core config generated in 0.15 seconds
marzban-1  | INFO:     Starting main Xray core
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     Starting nodes Xray core
marzban-1  | INFO:     Application startup complete.
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
marzban-1  | INFO:     Shutting down
marzban-1  | INFO:     Waiting for application shutdown.
marzban-1  | INFO:     Stopping main Xray core
marzban-1  | WARNING:  Xray core stopped
marzban-1  | INFO:     Stopping nodes Xray core
marzban-1  | INFO:     Application shutdown complete.
marzban-1  | INFO:     Finished server process [1]
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO:     Started server process [1]
marzban-1  | INFO:     Waiting for application startup.
marzban-1  | INFO:     Generating Xray core config
marzban-1  | INFO:     Xray core config generated in 0.41 seconds
marzban-1  | INFO:     Starting main Xray core
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     Starting nodes Xray core
marzban-1  | INFO:     Application startup complete.
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
marzban-1  | INFO:     78.190.196.98:1574 - "GET /sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxTXVzdGFmYSIsImFjY2VzcyI6InN1YnNjcmlwdGlvbiIsImlhdCI6MTcxNDMwMjU3OH0.OV1tho19EGzZYKnijf6x-TBzJIx1I6MrBzAlz4OS-54 HTTP/1.1" 200 OK
marzban-1  | INFO:     Shutting down
marzban-1  | INFO:     Waiting for application shutdown.
marzban-1  | INFO:     Stopping main Xray core
marzban-1  | WARNING:  Xray core stopped
marzban-1  | INFO:     Stopping nodes Xray core
marzban-1  | INFO:     Application shutdown complete.
marzban-1  | INFO:     Finished server process [1]
marzban-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
marzban-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzban-1  | INFO:     Started server process [1]
marzban-1  | INFO:     Waiting for application startup.
marzban-1  | INFO:     Generating Xray core config
marzban-1  | INFO:     Xray core config generated in 0.21 seconds
marzban-1  | INFO:     Starting main Xray core
marzban-1  | WARNING:  Xray core 1.8.8 started
marzban-1  | INFO:     Starting nodes Xray core
marzban-1  | INFO:     Application startup complete.
marzban-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
marzban-1  | INFO:     78.190.196.98:3061 - "GET / HTTP/1.1" 304 Not Modified
marzban-1  | INFO:     78.190.196.98:3188 - "GET /locales/tr.json HTTP/1.1" 404 Not Found
marzban-1  | INFO:     78.190.196.98:3061 - "GET /api/admin HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3188 - "GET /api/nodes HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:2415 - "GET /api/inbounds HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:3061 - "GET /api/system HTTP/1.1" 200 OK
marzban-1  | INFO:     78.190.196.98:1778 - "GET /api/users?limit=30&sort=-created_at HTTP/1.1" 200 OK

**Comment by M03ED** [comment]
send it when dashboard its not loading 
which version you using ?

**Comment by M03ED** [comment]
test another phone

**Comment by rlrexyz** [comment]
> test another phone

I think I solved the problem. The issue is caused by changing the IP address to default in the node settings section. If the IP address is not written there, it will not connect.

I guess this is my fault, sorry for bothering you :(

**Comment by M03ED** [comment]
> > test another phone
> 
> I think I solved the problem. The issue is caused by changing the IP address to default in the node settings section. If the IP address is not written there, it will not connect.
> 
> I guess this is my fault, sorry for bothering you :(

default ip address is main marzban address 
you need to set different ip if you using node
