### ISSUE TITLE
Marzban/Marzban Node does not work on Amazon AWS

### ISSUE THREAD

**Issue by rlrexyz** [Gozargah/Marzban#960]
As you read in the title, Marzban/Marzban Node does not work on Amazon AWS. At first, I installed Marzban Node, but when it did not work, I got suspicious and installed Marzban directly, but even though Marzban was started, I cannot access the Dashboard. Amazon AWS is probably blocking something, I would be very happy if you could help me.

**Comment by M03ED** [comment]
probably your port is closed

**Comment by rlrexyz** [comment]
> probably your port is closed

But Ufw is disabled

**Comment by M03ED** [comment]
in some datacenter they use external firewall that can be disabled from dashboard

**Comment by rlrexyz** [comment]
Thank you problem solved :)
