### ISSUE TITLE
لود نشدن سابسکریپشن در اندروید

### ISSUE THREAD

**Issue by TiamaaShah** [Gozargah/Marzban#962]
سلام
لینک ساب توی آیفون و کامپیوتر به راحتی وارد میشه ولی تو اندروید کار نمیکنه 
داخل اندروید باید لینک ها رو دستی اضافه کرد و آپدیت هم نمیشن

**Comment by M03ED** [comment]
لاگ تون رو ارسال کنید ، بدون لاگ چیزی رو نمیشه تشخیص داد

**Comment by TiamaaShah** [comment]
این لاگ برنامه V2rayng روی اندروید هستش

--------- beginning of main
05-01 17:20:02.923 D/com.v2ray.ang( 3573): https://b.***************/sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzaGFoIiwiYWNjZXNzIjoic3ViaWF0IjoxNzE0NT.ZCiHvN9a-n4gCHWqy2GxmVHtl2LFYUKesPqUpWoq7JY
05-01 17:20:04.039 W/System.err( 3573): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
05-01 17:20:04.039 W/System.err( 3573): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent(Utils.kt:358)
05-01 17:20:04.039 W/System.err( 3573): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:540)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
05-01 17:20:04.039 W/System.err( 3573): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
05-01 17:20:04.039 W/System.err( 3573): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
05-01 17:20:04.039 W/System.err( 3573): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
05-01 17:20:04.040 W/System.err( 3573): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
05-01 17:20:04.040 W/System.err( 3573): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
05-01 17:20:04.040 W/System.err( 3573): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
05-01 17:20:04.040 W/System.err( 3573): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
05-01 17:20:04.040 W/System.err( 3573): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
05-01 17:20:04.040 W/System.err( 3573): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
05-01 17:20:04.040 W/System.err( 3573): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
05-01 17:20:04.040 W/System.err( 3573): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
05-01 17:20:04.040 W/System.err( 3573): 	... 23 more
05-01 17:20:04.040 W/System.err( 3573): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-01 17:20:04.040 W/System.err( 3573): 	... 34 more

**Comment by M03ED** [comment]
لاگ مرزبان منظورم بود و نه v2rayng

**Comment by TiamaaShah** [comment]
لاگ مرزبان رو از کجا میشه پیدا کرد؟
با کامند زیر تو ترمینال رو میگید ؟
marzban logs

**Comment by TiamaaShah** [comment]
خوب مشکل رو از تو همون لاگ های v2rayng پیدا کردم.
مشکل از سرتیفیکیت acme بود.
با Certbot سرتیفیکیت گرفتم مشکل حل شد
