### ISSUE TITLE
سوال در مورد کاستوم کانفیگ در سابسکرابشن لینک

### ISSUE THREAD

**Issue by The-Erf** [Gozargah/Marzban#965]
سلام و وقت بخیر
 من چطوری میتونم با سابسکرابشن مرزبان کاستوم کانفیگ بدم؟ به طوری که کل تمپلیت xray کاربر رو من خودم بنویسم و صرفا اینباند ها را وارد کانفیگ کند (درواقع اوتباند را بسازد برای کاربر)

**Comment by The-Erf** [comment]
> در نسخه dev به صورت دیفالت کاستوم کانفیگ ارسال میشه

من الان نصبش کردم ولی json نمیده سابسکرابشنو میشه راهنمایی کنید لطفا؟

**Comment by erfan10** [comment]
سلام 
من فکر‌ میکنم دلیل اینکه json بهت نیمده هدر های درخواستت هست (Request) 


این هدر رو اضافی کنی بهت json بر میگردونه

```
Content-Type: application/json
```
