### ISSUE TITLE
Eror 404 on google websites

### ISSUE THREAD

**Issue by CIAHAT** [Gozargah/Marzban#967]
سلام.
اگرچه حدس میزنم مشکلی از سمت مرزبان نباشه، اما ایشو میزنم شاید بدرد بقیه هم بخوره.
روی بعضی از آدرس های مرتبط با گوگل مثل dl.google.com/dl/android ارور 404 میگیرم که برای اندروید استودیو هم مشکل ساز هست و پکیج های مدنظرم دانلود نمیشه برای پروژه ها.
لازم به ذکر هست که geosite گوگل کلا پشت وارپ هست و با IPv4 روتینگ شده و تست هم شده از وارپ عبور میکنن آدرس ها.
از دوستان اگر کسی روشی داره (بجز تعویض دیتاسنتر) ممنون میشم راهنمایی کنید.

**Comment by M03ED** [comment]
لطفا برای اینگونه موارد از بخش `discussions` استفاده کنید
