### ISSUE TITLE
Vless + tcp + http header request

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#970]
سلام وقت بخیر
من یه مشکلی دارم اینکه کاربرا ایفون روی برنامه streisand خیلی بهم گزارش میکنن که واتس اپ بد لود میشه واسشون
مخصوص این پروتوکل هم هست , خوب من چون اکثرا کانفیگام تانل هست این پروتوکل خوب جواب میده برای تانل برای همین از این استفاده میکنم
یه سری کاربر روی پنل x-ui دارم اونا مشکلی گزارش نکردن از این بابت ولی روی پنل مرزبان این مشکلو دارم
حالا دقیقا نمیدونم مشکل از سمت تنظیمات کور xray یا مشکل جای دیگس 
ورژن xray ام 1.8.4
اگه کسی میدونی این مشکل چطوری حل میشه لطفا راهنمایی کنه

**Comment by erfjab** [comment]
داخل تنظیمات نرم افزار باید فقط رو ipv4 بزارید تا فیکس شه.

**Comment by xmohammad1** [comment]
اینا قدیمی جیگر جان :)
