### ISSUE TITLE
انتقال آیدی سابسکریپشن های x-ui ثنایی و علیرضا به مرزبان

### ISSUE THREAD

**Issue by milad73n** [Gozargah/Marzban#972]
با عرض سلام و خسته نباشید
یه موردی که برام پیش اومده من میخوام یوزرهامو از ثنایی به مرزبان منتقل کنم ولی یه مشکل اساسی دارم. اینکه نمیتونم و نمیدونم چطوری باید سابسکریپشن های موجود رو به پنل جدید منتقل کنم. اگه راه حلی هست بفرمایید.

**Comment by azealand712-sys** [comment]
کانفینگ
