### ISSUE TITLE
Fail to detect internet connection: EOF after Modify User with API

### ISSUE THREAD

**Issue by RelaxStation** [Gozargah/Marzban#974]
وقت بخیر ، زمانی که یوزر از طریف API مادیفای میشه ، دیگه نمیتونه کانکت بشه و خطای EOF میده
کامند مادیفای:
```
{
  "proxies": {
    "vmess": {},
    "vless": {}
  },
  "inbounds": {
    "vmess": [
      "VMess TCP"
    ],
    "vless": [
      "VLESS TCP REALITY"
    ]
  },
  "expire": 1614925287,
  "data_limit": 1234567890,
  "data_limit_reset_strategy": "no_reset",
  "status": "active"
}
```
فقط با زدن آپدیت ساب اسکریپشن مشکل حل میشه حتی اگه از توی پنل هر تغییری بدم مشکل برطرف نمیشه
با المان های on hold هم تفاوتی حاصل نشد

مشکل دیگه هم که هر از گاهی پیش میاد اینه که در حالی که یوزر زمان و حجم داره اکسپایر میشه

![photo_2024-05-06_21-51-07](https://github.com/Gozargah/Marzban/assets/151868654/bd0618f5-dbd5-4ec6-bf4f-0775e22df532)

ورژن پنل 0.4.9

**Comment by M03ED** [comment]
شما دارید uuid و پسورد های مربوط به یوزر رو پاک می کنید ، اینکار باعث میشه این موارد ریست بشن و uuid قبلی دیگه معتبر نباشه
