### ISSUE TITLE
Policy

### ISSUE THREAD

**Issue by xmohammad1** [Gozargah/Marzban#975]
سلام وقت بخیر 
لطفا امکان تغییر Policy رو به قسمت xray core بیارید
https://github.com/Gozargah/Marzban/blob/master/app/xray/config.py#L70
الان توسط این فایل ساخته میشه ضاهرا

**Comment by M03ED** [comment]
> سلام وقت بخیر لطفا امکان تغییر Policy رو به قسمت xray core بیارید https://github.com/Gozargah/Marzban/blob/master/app/xray/config.py#L70 الان توسط این فایل ساخته میشه ضاهرا

تغییر اشتباه در policy میتونه باعث اختلال در مرزبان بشه 
چه نیازی به این تغییر دارید ؟

**Comment by fodhelper** [comment]
Good idea, I also like to play with handshake, connIdle and bufferSize options
