### ISSUE TITLE
creating vless users via cli

### ISSUE THREAD

**Issue by wolfheartman** [Gozargah/Marzban#976]
با توجه به اینکه بعد از نصب سایت فیلتر میشود دسترسی وب برای ایجاد کاربر نداریم با خط فرمان میشه یه کاربر تعریف کنیم که مثلا با پروتکل vless و شبکه ws وصل بشه؟اگر راهی هست ممنون میشم یه راهنمایی بکنید

**Comment by M03ED** [comment]
فیلتر شدن به خودی خود اتفاق نمی افته ، میتونید از cdn استفاده کنید

**Comment by wolfheartman** [comment]
> فیلتر شدن به خودی خود اتفاق نمی افته ، میتونید از cdn استفاده کنید

من بحثم فیلتر شدن سایت نیست راهکاریه که بتونیم از طریق محیط cli مرزبان کاربر vpn اضافه کنیم

**Comment by M03ED** [comment]
چرا باید چنین چیزی پیاده بشه ؟ اضافه کردن از طریق cli اصلا کار جالبی نیست و عقلانی هم نیست

**Comment by wolfheartman** [comment]
وقتی مرزبان را نصب میکنی مگه صفحه وب رو نباید باز کنی که توش کاربر وی پی ان اضافه کنی ؟خب اون صفحه کنترل پنل فیلتر هست برای  بردن پشت cdn  هم باید domain ثبت کنی که اونم پولی و قابل پیگیری هست زیر دامنه های trycloudflare هم که فیلتر هست فقط یه راه میمونه که از طریق online ssh بتونی به سرورت وصل بشی و کاربر ایجاد کنی دیگه

**Comment by M03ED** [comment]
نمی‌دونم چقدر سواد برنامه نویسی دارید و یا چقدر با مرزبان آشنا هستید 
ولی من با توجه به توضیحات شما ترجیح میدم این بحث رو ادامه ندم

**Comment by wolfheartman** [comment]
ربطی به سواد برنامه نویسی نداره اما برنامه نویسی بلدم، شما اصلا منظور آدم رو متوجه نمیشید و حرف خودتون رو میزنید توضیح دادن به شما بیهودست از طرز نوشتاریتون هم مشخصه

**Comment by M03ED** [comment]
اگه سواد برنامه نویسی دارید میتونید خودتون کدش رو بنویسید و pr بفرستید
