### ISSUE TITLE
Hide all configs after expiry of subscription

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#977]
When a user is expired, we can send only configs with "0.0.0.0" as address
But as many proxy users don't know how to update subscription and admins don't like them to lose their configs and ask them to do update their subscription, i think this feature must be optional and disabled by default

**Comment by xmohammad1** [comment]
well , you can add a status text also , for example when user expired show user on first config "Your Subscription Expired Contact Support to charge" something like this

**Comment by fodhelper** [comment]
ok
