### ISSUE TITLE
کرش TeleBot

### ISSUE THREAD

**Issue by hoootan** [Gozargah/Marzban#979]
سلام، بعد مدتی فعال کردن لاگ های تلگرام این ارور رو میگیرم که باعث میشه کانفیگ ها تایموت بخورن و xray به درستی کار نمیکنه.

ERROR - TeleBot: "Infinity polling exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"

این ارور در لاگ های مرزبان به صورت کرش پایتون میوفته.![image](https://github.com/Gozargah/Marzban/assets/15173179/86de6237-6357-4124-b40f-0f75d7211da7)

**Comment by M03ED** [comment]
ارور مربوط به کانکشن بین سرور و تلگرام هست ، ربطی به مرزبان نداره

**Comment by dlsborhan** [comment]
بات توکن رو عوض کردم درست شد
مرزبان رو هم ریستارت کن
