### ISSUE TITLE
مشکل باز نشدن phpmyadmin 

### ISSUE THREAD

**Issue by TIR3D4** [Gozargah/Marzban#983]
سلام وقت شما بخیر متاسفانه مشکل باز نشدن phpmyadmin رو دارم تمام مراحل رو درست انجام دادم قبلا برام باز میشد اما مدتی هست کلا باز نمیشه
با دامین http میزنم با پورت 8010 و پروکسی کلودفلر خاموش اما باز نمیشه با ایپی هم باز نمیشه هرکاری هم کردم درست نمیشه لطفا راهنمایی کنید

**Comment by milad73n** [comment]
حل شده برات؟

**Comment by iamtheted** [comment]
سلام @TIR3D4 
آیا اطمینان دارین که پورت 8010 در فایروال باز هست؟
اگر دیدین باز هست و همچنان باز نمیشه شاید آی‌پی سرورتون محدود هست و نیاز هست با اتصال VPN انجام بدین.

**Comment by erfjab** [comment]
این ایشو به خاطر در اختیار نزاشتن اطلاعات بیشتر بسته میشه. اگر مشکلتون حل نشد و بازم ادامه داشت لطفا ایشوی جدید باز کنید.
