### ISSUE TITLE
Update xray core 1.8.11

### ISSUE THREAD

**Issue by erfan10** [Gozargah/Marzban#984]
**"HttpUpgrade" has been added in the latest version of Xray Core.**

In the latest version of Xray-core, several bugs have been fixed, and a new feature named **HttpUpgrade**, as a good replacement for **WS** (web socket), has been introduced.

Therefore, I request to update xray-core in Marzban and Marzban node.

If the project manager accepts my request, I will update it as a contribution."

**Comment by M03ED** [comment]
#882 already added
