### ISSUE TITLE
The user's appearance offline

### ISSUE THREAD

**Issue by rlrexyz** [Gozargah/Marzban#990]
Hello, one day I encountered such an error while using marzban without any problems, although the user is active, it appears offline in the admin panel and the last link is written 1 minute ago, what is the reason, it has been like this for the last few days and it happened on its own... I don't want to reinstall it, do you have any solution suggestions?

https://github.com/Gozargah/Marzban/assets/81679033/23a80426-b2fd-40ef-a280-aa2805f6455f

**Comment by iamtheted** [comment]
Hi @rlrexyz 

Which image of Marzban are you using? Latest or Dev?
Also, which version is it?

Please provide more info
Thank you
