### ISSUE TITLE
وارپ با استفاده از هسته  در  Core SettingXray

### ISSUE THREAD

**Issue by yaramahmadi** [Gozargah/Marzban#991]
سلام و احترام
توی وارپ با استفاده از هسته  در  Core SettingXray

{
  "tag": "warp",
  "protocol": "wireguard",
  "settings": {
    "secretKey": "Your_Secret_Key",
    "DNS": "1.1.1.1",
    "address": ["172.16.0.2/32", "2606:4700:110:8756:9135:af04:3778:40d9/128"],
    "peers": [
      {
        "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
        "endpoint": "engage.cloudflareclient.com:2408"
      }
    ],
    "kernelMode": false
  }
}

مواردی که در فایل   wgcf-profile.conf   قرار داره
access_token    device_id     license_key     private_key 

هر کدام از آیتمهای بالا را در کدام قسمت Core SettingXray قرار دهیم

**Comment by M03ED** [comment]
لطفا قبل از ایجاد issue جدید داکیومنت رو مطالعه کنید
https://gozargah.github.io/marzban/fa/examples/warp
