### ISSUE TITLE
قطع نکردن اکانت کاربر بعد از گذر از حد مجاز

### ISSUE THREAD

**Issue by ehssanehs** [Gozargah/Marzban#999]
با سلام
دیتا بیس برنامه رو به mysql و بر روی سرور دیگری انتقال دادم و مرزبان به صورت ریموت به آن وصل می شود.
کاربران بعد از اتمام ترافیکشان هنوز متصل هستند و اشتراک فعال هست. فقط زمانی که هسته xray ریست شود بعد از راه اندازی دوباره اشتراکهای منقصی غیر فعال می گردند.
لازم به ذکر هست که در صورت اتمام تاریخ و تایم مشترک این مشکل وجود ندارد و اشتراک غیر فعال می شود.
با سپاس از زحمات تیم مرزبان

**Comment by sirvan1133** [comment]
نودهاتو اپدیت و ریستارت کن

**Comment by ehssanehs** [comment]
نود ندارم . فقط یک سرور هست و چون داخل ایران هست و امنیت نگهداری اطلاعات نداره دیتابیس رو روی یک سرور دیگه قرار دادم تا در صورت مشکل برای سرور ایران دیتابیس رو داشته باشم

**Comment by majidsadr** [comment]
Same issue with the same configuration as described here.

**Comment by arian24b** [comment]
سلام
لطفا نسخه ای که استفاده میکنید به همراه خروجی دستور زیر رو ارسال کنین: 
`docker compose logs`

**Comment by M03ED** [comment]
not enough information
